'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AATM.Libraries.EnumLocalization.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Client() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Client", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Employee() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Employee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Establishment.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Establishment() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Establishment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Others() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Others", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Supplier() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Large.
        '''</summary>
        Friend ReadOnly Property SampleEnum_Large() As String
            Get
                Return ResourceManager.GetString("SampleEnum_Large", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medium.
        '''</summary>
        Friend ReadOnly Property SampleEnum_Medium() As String
            Get
                Return ResourceManager.GetString("SampleEnum_Medium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small.
        '''</summary>
        Friend ReadOnly Property SampleEnum_Small() As String
            Get
                Return ResourceManager.GetString("SampleEnum_Small", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Very Large.
        '''</summary>
        Friend ReadOnly Property SampleEnum_VeryLarge() As String
            Get
                Return ResourceManager.GetString("SampleEnum_VeryLarge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Very Small.
        '''</summary>
        Friend ReadOnly Property SampleEnum_VerySmall() As String
            Get
                Return ResourceManager.GetString("SampleEnum_VerySmall", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
