
CREATE VIEW DailyCollectionDepartmentWise_View
 
AS
select 
	b.BranchID,
	b.Trans_Key,
	b.BillType,
	b.TransNBR,
	b.TransType,
	b.TransDateEnglish,
	b.RegistrationNo,
	c.RegistrationDate,
	c.PatientType as RegistrationType,
	case when c.PatientNameEnglish is null then 'Cash Customer' else c.PatientNameEnglish end as PatientNameEnglish,
	b.DoctorID,
	d.EmpNameEnglish as DoctorNameEnglish,
	b.InsuranceID,
	b.InsuranceNameEnglish,
	b.InsuranceGroupID,
	e.nameenglish as InsuranceTPA,
	b.ExtraDiscountPercent,
	b.ExtradiscountAmt,
	b.RoundOffAmt,
	b.Reject,
	i.underinsuranceid,
	case when b.TransType ='CA' then b.ExtraDiscountAmt else 0 end as CashExtraDiscount,
	case when b.TransType ='CR' then b.ExtraDiscountAmt else 0 end as CreditExtraDiscount,
	case when b.TransType ='CA' then b.RoundOffAmt else 0 end as CashRoundOffAmt,
	case when b.TransType ='CR' then b.RoundOffAmt else 0 end as CreditRoundOffAmt,
	sum(case when h.DepartmentGroupID = '001' then a.Qty * a.saleprice else 0 end) as GrossCON,
	sum(case when h.DepartmentGroupID = '002' or h.DepartmentGroupID is null then a.Qty * a.saleprice else 0 end) as GrossMCT,
	sum(case when h.DepartmentGroupID = '003' then a.Qty * a.saleprice else 0 end) as GrossXRY,
	sum(case when h.DepartmentGroupID = '004' then a.Qty * a.saleprice else 0 end) as GrossLAB,
	sum(case when h.DepartmentGroupID = '005' then a.Qty * a.saleprice else 0 end) as GrossDNT,
	sum(case when h.DepartmentGroupID = '006' then a.Qty * a.saleprice else 0 end) as GrossOPH,
	sum(case when h.DepartmentGroupID = '007' then a.Qty * a.saleprice else 0 end) as GrossCMD,
	sum(case when h.DepartmentGroupID = '008' then a.Qty * a.saleprice else 0 end) as GrossPHR,
	sum(case when h.DepartmentGroupID = '001' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscCON,
	sum(case when h.DepartmentGroupID = '002' or h.departmentgroupid is null then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscMCT,
	sum(case when h.DepartmentGroupID = '003' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscXRY,
	sum(case when h.DepartmentGroupID = '004' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscLAB,
	sum(case when h.DepartmentGroupID = '005' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscDNT,
	sum(case when h.DepartmentGroupID = '006' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscOPH,
	sum(case when h.DepartmentGroupID = '007' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscCMD,
	sum(case when h.DepartmentGroupID = '008' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscPHR,
	sum(case when h.DepartmentGroupID <> '008' then a.DeductibleAmt else 0 end) as CLNdedAmt,
	sum(case when h.DepartmentGroupID = '008' then a.DeductibleAmt else 0 end) as PHRdedAmt,
	'Clinic' as InvoiceType
from clinicinvoicedetails a
left outer join clinicinvoicegroup b on a.group_key = b.trans_key 
left outer join patientdetails c on b.registrationno = c.registrationno and b.registrationtype = c.patienttype
left outer join employeedetails d on b.doctorid = d.empid
left outer join insurancedetails e on e.insuranceid = b.insurancegroupid and e.insurancetype = 'TPA'
left outer join MedicalServices f on a.ServiceID = f.ServiceID
left outer join InsuranceServicePriceList g on a.serviceID = g.ServiceID and g.InsuranceID = b.InsuranceGroupID
left outer join MedicalDepartments h on h.DepartmentID = (case when f.serviceID is null then g.departmentID else f.DepartmentID end) 
left outer join insurancedetails i on i.insuranceid = b.insuranceid and i.insurancetype <> 'TPA'
where (b.Reject <> 1) AND a.ServiceID <> 'CLN-DED'
group by
	b.BranchID,
	b.Trans_Key,
	b.BillType,
	b.TransNBR,
	b.TransType, 
	b.TransDateEnglish,
	b.RegistrationNo,
	c.RegistrationDate,
	c.PatientType,
	c.PatientNameEnglish,
	b.DoctorID,
	d.EmpNameEnglish,
	b.InsuranceID,
	b.InsuranceNameEnglish,
	b.InsuranceGroupID,
	e.nameenglish,
	b.ExtraDiscountPercent,
	b.ExtradiscountAmt,
	b.RoundOffAmt,
	b.Reject,
    a.SaleStatus,
	c.PatientType,
	h.departmentgroupid,
	i.underinsuranceid
union all
Select 
	b.BranchID,
	b.Trans_Key,
	b.TransType,
	b.TransNbr,
	b.TransType, 
	b.TransDateEnglish,
	b.RegistrationNo,
	case when d.RegistrationDate is null then b.TransDateEnglish else d.RegistrationDate end as RegistrationDate,
	case when d.PatientType is null then 'Cash' else d.PatientType end as RegistrationType,
	case when d.PatientNameEnglish is null then 'Cash Customer' else d.PatientNameEnglish end as PatientNameEnglish,
	b.DoctorID,
	e.EmpNameEnglish as DoctorNameEnglish,
	b.InsuranceID,
	c.NameEnglish as InsuranceNameEnglish,
	b.InsuranceGroupID,
	f.nameenglish as InsuranceTPA,
	b.ExtraDiscountPercent,
	b.ExtraDiscountAmt,
	b.RoundOffamt,
	case when a.SaleStatus = 'SR' then 1 else 0 end as Reject,
	h.underinsuranceid,
	case when b.TransType ='CA' then b.ExtraDiscountAmt else 0 end as CashExtraDiscount,
	case when b.TransType ='CR' then b.ExtraDiscountAmt else 0 end as CreditExtraDiscount,
	case when b.TransType ='CA' then b.RoundOffAmt else 0 end as CashRoundOffAmt,
	case when b.TransType ='CR' then b.RoundOffAmt else 0 end as CreditRoundOffAmt,
	sum(case when g.DepartmentGroupID = '001' then a.Qty * a.saleprice else 0 end) as GrossCON,
	sum(case when g.DepartmentGroupID = '002' or g.departmentgroupid is null then a.Qty * a.saleprice else 0 end) as GrossMCT,
	sum(case when g.DepartmentGroupID = '003' then a.Qty * a.saleprice else 0 end) as GrossXRY,
	sum(case when g.DepartmentGroupID = '004' then a.Qty * a.saleprice else 0 end) as GrossLAB,
	sum(case when g.DepartmentGroupID = '005' then a.Qty * a.saleprice else 0 end) as GrossDNT,
	sum(case when g.DepartmentGroupID = '006' then a.Qty * a.saleprice else 0 end) as GrossOPH,
	sum(case when g.DepartmentGroupID = '007' then a.Qty * a.saleprice else 0 end) as GrossCMD,
	sum(case when g.DepartmentGroupID = '008' then a.Qty * a.saleprice else 0 end) as GrossPHR,
	sum(case when g.DepartmentGroupID = '001' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscCON,
	sum(case when g.DepartmentGroupID = '002' or g.departmentgroupid is null then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscMCT,
	sum(case when g.DepartmentGroupID = '003' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscXRY,
	sum(case when g.DepartmentGroupID = '004' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscLAB,
	sum(case when g.DepartmentGroupID = '005' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscDNT,
	sum(case when g.DepartmentGroupID = '006' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscOPH,
	sum(case when g.DepartmentGroupID = '007' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscCMD,
	sum(case when g.DepartmentGroupID = '008' then case when a.DiscountAmt = 0 then (a.qty*a.saleprice*a.DiscountPer/100) else a.DiscountAmt end else 0 end) as DiscPHR,
	sum(case when g.DepartmentGroupID <> '008' then a.DeductibleAmt else 0 end) as CLNdedAmt,
	sum(case when g.DepartmentGroupID = '008' then a.DeductibleAmt else 0 end) as PHRdedAmt,
	'Pharmacy' as InvoiceType
from pharmacyinvoicedetails a
left outer join pharmacyinvoicegroup b on a.group_key = b.trans_key
left outer join insurancedetails c on b.insuranceid = c.insuranceid
left outer join patientdetails d on b.registrationno = d.registrationno and upper(left(b.RegistrationType,2)) = d.Series
left outer join employeedetails e on b.doctorid = e.empid
left outer join insurancedetails f on f.insuranceid = c.Groupinsuranceid and f.insurancetype = 'TPA'
left outer join MedicalDepartments g on '008' = g.departmentgroupid and g.DepartmentID = 'PHR'
left outer join insurancedetails h on h.insuranceid = b.insuranceid and h.insurancetype <> 'TPA'
where (a.SaleStatus is null or a.SaleStatus = '') AND a.Item_Code <> 'PHR-DED'
group by b.BranchID,
	 b.Trans_Key,
	 b.TransType,
	 b.TransNbr,
	 b.TransType,
	 b.TransDateEnglish,
	 b.RegistrationNo,
	 d.RegistrationDate,
	 d.PatientType,
	 d.PatientNameEnglish,
	 b.DoctorID,
	 e.EmpNameEnglish,
	 b.InsuranceID,
	 c.NameEnglish,
	 b.InsuranceGroupID,
	 f.nameenglish,
	 b.ExtraDiscountPercent,
	 b.ExtraDiscountAmt,
	 b.RoundOffamt,
	 a.SaleStatus,
	 h.underinsuranceid