CREATE TABLE [dbo].[custom_att_stage_Base] (
    [emp_id]                              INT             NOT NULL,
    [att_date]                            DATE            NOT NULL,
    [date_type]                           INT             NULL,
    [present_flag]                        SMALLINT        NULL,
    [full_attendance_flag]                SMALLINT        NULL,
    [scheduled_in]                        DATETIME2 (7)   NULL,
    [scheduled_out]                       DATETIME2 (7)   NULL,
    [base_first_clock_in]                 DATETIME2 (7)   NULL,
    [base_last_clock_out]                 DATETIME2 (7)   NULL,
    [worked_minutes]                      DECIMAL (10, 2) NOT NULL,
    [payload_ot_minutes]                  DECIMAL (10, 2) NULL,
    [absence_minutes]                     DECIMAL (10, 2) NULL,
    [required_work_minutes]               DECIMAL (10, 2) NULL,
    [recomputed_worked_minutes]           DECIMAL (10, 2) NOT NULL,
    [recomputed_worked_hours]             DECIMAL (10, 2) NOT NULL,
    [use_mode]                            SMALLINT        NULL,
    [temp_duration_minutes]               INT             NOT NULL,
    [temp_work_time_duration]             INT             NOT NULL,
    [temp_break_minutes]                  INT             NOT NULL,
    [ot_eligible_flag]                    BIT             NOT NULL,
    [has_temp_schedule_base]              INT             NOT NULL,
    [has_assigned_schedule_base]          INT             NOT NULL,
    [schedule_source_base]                VARCHAR (30)    NOT NULL,
    [effective_scheduled_in]              DATETIME2 (0)   NULL,
    [effective_scheduled_out]             DATETIME2 (0)   NULL,
    [scheduled_ot_cap_minutes]            DECIMAL (38, 2) NOT NULL,
    [punch_count]                         INT             NOT NULL,
    [first_in]                            DATETIME2 (7)   NULL,
    [last_out]                            DATETIME2 (7)   NULL,
    [first_any_punch]                     DATETIME2 (7)   NULL,
    [last_any_punch]                      DATETIME2 (7)   NULL,
    [resolved_schedule_source]            VARCHAR (30)    NOT NULL,
    [effective_shift_id]                  INT             NULL,
    [effective_time_interval_id]          INT             NULL,
    [resolved_is_off_day]                 INT             NOT NULL,
    [base_is_off_day]                     INT             NOT NULL,
    [base_required_work_minutes]          INT             NOT NULL,
    [esr_base_schedule_source]            VARCHAR (30)    NOT NULL,
    [base_shift_id]                       INT             NULL,
    [base_time_interval_id]               INT             NULL,
    [esr_effective_required_work_minutes] INT             NULL
);

