'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class AccountStrings
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AATM.Accounts.AccountStrings", GetType(AccountStrings).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AP.
    '''</summary>
    Friend Shared ReadOnly Property AccountsPayableJournalPrefix() As String
        Get
            Return ResourceManager.GetString("AccountsPayableJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AR.
    '''</summary>
    Friend Shared ReadOnly Property AccountsReceivableJournalPrefix() As String
        Get
            Return ResourceManager.GetString("AccountsReceivableJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AP.
    '''</summary>
    Friend Shared ReadOnly Property ApJournalPrefix() As String
        Get
            Return ResourceManager.GetString("ApJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AR.
    '''</summary>
    Friend Shared ReadOnly Property ArJournalPrefix() As String
        Get
            Return ResourceManager.GetString("ArJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CD.
    '''</summary>
    Friend Shared ReadOnly Property CashDisbursementJournalPrefix() As String
        Get
            Return ResourceManager.GetString("CashDisbursementJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CR.
    '''</summary>
    Friend Shared ReadOnly Property CashReceiptJournalPrefix() As String
        Get
            Return ResourceManager.GetString("CashReceiptJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No open iInvoice payment entries found. Do you still want to save this entry?.
    '''</summary>
    Friend Shared ReadOnly Property CDEntry_OnBeforeSave_Empty_CkdOiItem_Ask_To_Save() As String
        Get
            Return ResourceManager.GetString("CDEntry_OnBeforeSave_Empty_CkdOiItem_Ask_To_Save", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Empty Open Invoice Payment!.
    '''</summary>
    Friend Shared ReadOnly Property CDEntry_OnBeforeSave_Empty_Journal() As String
        Get
            Return ResourceManager.GetString("CDEntry_OnBeforeSave_Empty_Journal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Child Account Found.
    '''</summary>
    Friend Shared ReadOnly Property ChartEntryTv_OnBeforeSave_Child_Account_Found() As String
        Get
            Return ResourceManager.GetString("ChartEntryTv_OnBeforeSave_Child_Account_Found", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account with child account can not be made a Detail Account. See this account .
    '''</summary>
    Friend Shared ReadOnly Property ChartEntryTv_OnBeforeSave_Child_Account_Found_Message() As String
        Get
            Return ResourceManager.GetString("ChartEntryTv_OnBeforeSave_Child_Account_Found_Message", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CK.
    '''</summary>
    Friend Shared ReadOnly Property CheckDisbursementJournalPrefix() As String
        Get
            Return ResourceManager.GetString("CheckDisbursementJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No open iInvoice payment entries found. Do you still want to save this entry?.
    '''</summary>
    Friend Shared ReadOnly Property CREntry_OnBeforeSave_Empty_CsrOiItem_Ask_To_Save() As String
        Get
            Return ResourceManager.GetString("CREntry_OnBeforeSave_Empty_CsrOiItem_Ask_To_Save", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GJ.
    '''</summary>
    Friend Shared ReadOnly Property GeneralJournalPrefix() As String
        Get
            Return ResourceManager.GetString("GeneralJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Empty GeneralJournal!.
    '''</summary>
    Friend Shared ReadOnly Property JournalEntry_OnBeforeSave_Empty_Journal() As String
        Get
            Return ResourceManager.GetString("JournalEntry_OnBeforeSave_Empty_Journal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No GeneralJournal entries found. Do you still want to save this entry?.
    '''</summary>
    Friend Shared ReadOnly Property JournalEntry_OnBeforeSave_Empty_Journal_Ask_To_Save() As String
        Get
            Return ResourceManager.GetString("JournalEntry_OnBeforeSave_Empty_Journal_Ask_To_Save", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unbalanced Entry.
    '''</summary>
    Friend Shared ReadOnly Property JournalPresenter_DataIsValid_Unbalanced_Journal_Entry_Caption() As String
        Get
            Return ResourceManager.GetString("JournalPresenter_DataIsValid_Unbalanced_Journal_Entry_Caption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unbalanced Entry, total Debits and total Credits must be equal before you can save this entry..
    '''</summary>
    Friend Shared ReadOnly Property JournalPresenter_DataIsValid_Unbalanced_Journal_Entry_Message() As String
        Get
            Return ResourceManager.GetString("JournalPresenter_DataIsValid_Unbalanced_Journal_Entry_Message", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PC.
    '''</summary>
    Friend Shared ReadOnly Property PettyCashJournalPrefix() As String
        Get
            Return ResourceManager.GetString("PettyCashJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter the Beginning date for the report!.
    '''</summary>
    Friend Shared ReadOnly Property Please_enter_the_Beginning_date_for_the_report() As String
        Get
            Return ResourceManager.GetString("Please_enter_the_Beginning_date_for_the_report", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter the Ending date for the report!.
    '''</summary>
    Friend Shared ReadOnly Property Please_enter_the_Ending_date_for_the_report() As String
        Get
            Return ResourceManager.GetString("Please_enter_the_Ending_date_for_the_report", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PJ.
    '''</summary>
    Friend Shared ReadOnly Property PurchaseJournalPrefix() As String
        Get
            Return ResourceManager.GetString("PurchaseJournalPrefix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SJ.
    '''</summary>
    Friend Shared ReadOnly Property SalesJournalPrefix() As String
        Get
            Return ResourceManager.GetString("SalesJournalPrefix", resourceCulture)
        End Get
    End Property
End Class
