Imports AATM.Accounts.BusinessLayer
Imports AATM.Accounts.PresentationLayer.Models
Imports AATM.Accounts.PresentationLayer.Views
Imports AutoMapper

Public Class MappingProfileAccounts
    Inherits Profile

    Public Sub New()
        CreateMap(Of AccountReconciliation, AccountReconciliationModel)().ReverseMap()
        CreateMap(Of AccountReconciliationItem, AccountReconciliationItemModel)().ReverseMap()
        CreateMap(Of AccountReconciliationItemModel, IAccountReconciliationItemView)().ReverseMap()
        CreateMap(Of AccountReconciliationModel, IAccountReconciliationView)().ReverseMap()
        CreateMap(Of ApJournal, ApJournalModel)().ReverseMap()
        CreateMap(Of ApJournalModel, IApJournalView)().ReverseMap()
        CreateMap(Of ApOpenInvoice, ApOpenInvoiceModel)().ReverseMap()
        'CreateMap(Of ApOpenInvoiceModel, IApOpenInvoiceView)().ReverseMap()
        CreateMap(Of ArJournal, ArJournalModel)().ReverseMap()
        CreateMap(Of ArJournalModel, IArJournalView)().ReverseMap()
        CreateMap(Of ArOpenInvoice, ArOpenInvoiceModel)().ReverseMap()
        'CreateMap(Of ArOpenInvoiceModel, IArOpenInvoiceView)().ReverseMap()
        CreateMap(Of Bank, BankModel)().ReverseMap()
        CreateMap(Of BankModel, IBankView)().ReverseMap()
        CreateMap(Of CadOiItem, CadOiItemModel)().ReverseMap()
        CreateMap(Of CadOiItemModel, ICadOiItemView)().ReverseMap()
        CreateMap(Of CashCode, CashCodeModel)().ReverseMap()
        CreateMap(Of CashCodeModel, ICashCodeView)().ReverseMap()
        CreateMap(Of CashDisbursementJournal, CashDisbursementJournalModel)().ReverseMap()
        CreateMap(Of CashDisbursementJournalModel, ICashDisbursementJournalView)().ReverseMap()
        CreateMap(Of CashReceiptJournal, CashReceiptJournalModel)().ReverseMap()
        CreateMap(Of CashReceiptJournalModel, ICashReceiptJournalView)().ReverseMap()
        CreateMap(Of Category, CategoryModel)().ReverseMap()
        CreateMap(Of CategoryModel, ICategoryView)().ReverseMap()
        CreateMap(Of Chart, ChartModel)().ReverseMap()
        CreateMap(Of ChartModel, IChartView)().ReverseMap()
        CreateMap(Of CheckDisbursementJournal, CheckDisbursementJournalModel)().ReverseMap()
        CreateMap(Of CheckDisbursementJournalModel, ICheckDisbursementJournalView)().ReverseMap()
        CreateMap(Of CkdOiItem, CkdOiItemModel)().ReverseMap()
        CreateMap(Of CkdOiItemModel, ICkdOiItemView)().ReverseMap()
        CreateMap(Of CsrOiItem, CsrOiItemModel)().ReverseMap()
        CreateMap(Of CsrOiItemModel, ICsrOiItemView)().ReverseMap()
        CreateMap(Of Customer, CustomerModel)().ReverseMap()
        CreateMap(Of CustomerModel, ICustomerView)().ReverseMap()
        CreateMap(Of Designation, DesignationModel)().ReverseMap()
        CreateMap(Of DesignationModel, IDesignationView)().ReverseMap()
        CreateMap(Of DistributionScheme, DistributionSchemeModel)().ReverseMap()
        CreateMap(Of DistributionSchemeItem, DistributionSchemeItemModel)().ReverseMap()
        CreateMap(Of DistributionSchemeItemModel, IDistributionSchemeItemView)().ReverseMap()
        CreateMap(Of DistributionSchemeModel, IDistributionSchemeView)().ReverseMap()
        CreateMap(Of Employee, EmployeeModel)().ReverseMap()
        CreateMap(Of EmployeeModel, IEmployeeView)().ReverseMap()
        CreateMap(Of GeneralJournal, GeneralJournalModel)().ReverseMap()
        CreateMap(Of GeneralJournalModel, IGeneralJournalView)().ReverseMap()
        CreateMap(Of JournalItem, JournalItemModel)().ReverseMap()
        CreateMap(Of JournalItemModel, IJournalItemView)().ReverseMap()
        CreateMap(Of PcsOiItem, PcsOiItemModel)().ReverseMap()
        CreateMap(Of PcsOiItemModel, IPcsOiItemView)().ReverseMap()
        CreateMap(Of PettyCashJournal, PettyCashJournalModel)().ReverseMap()
        CreateMap(Of PettyCashJournalModel, IPettyCashJournalView)().ReverseMap()
        CreateMap(Of PurchaseItem, PurchaseItemModel)().ReverseMap()
        CreateMap(Of PurchaseItemModel, IPurchaseItemView)().ReverseMap()
        CreateMap(Of PurchaseJournal, PurchaseJournalModel)().ReverseMap()
        CreateMap(Of PurchaseJournalModel, IPurchaseJournalView)().ReverseMap()
        CreateMap(Of SalesCashItem, SalesCashItemModel)().ReverseMap()
        CreateMap(Of SalesCashItemModel, ISalesCashItemView)().ReverseMap()
        CreateMap(Of SalesJournal, SalesJournalModel)().ReverseMap()
        CreateMap(Of SalesJournalModel, ISalesJournalView)().ReverseMap()
        CreateMap(Of Supplier, SupplierModel)().ReverseMap()
        CreateMap(Of SupplierModel, ISupplierView)().ReverseMap()

    End Sub

End Class