Imports AATM.Libraries.MessagingLibrary

Public Class OneTimeRun

    Public Shared Sub CreateAllMessages()
        Messaging.AddMessage("AskAddAnotherRecord", "Do you want to add another record?", "Please Confirm")
        Messaging.AddMessage("AskIfContinueAction", "Are you sure you want to {action} this {itemName} entry?", "Please confirm!")
        Messaging.AddMessage("AskIfDeleteRecord", "Are you sure you want to delete this record?", "Please Confirm Delete!")
        Messaging.AddMessage("AskIfSaveEmptyJournal", "Journal Entry is Empty, do you still want to save this entry?", "Empty Journal")
        Messaging.AddMessage("AskIfUserWantsToSaveOrContinueEdits", "Changes have been made to this record.  Press [Yes] to save changes, [No] to Abandon changes, or press [Cancel] to continue editing record? Save Changes?", "Please Confirm.")
        Messaging.AddMessage("AskLastRecordReachStartBeg", "This is the last matching record for the given text. Do you want to start search from the first record?", "Last Record Found.")
        Messaging.AddMessage("AskMakeExcessCollectionAdvance", "Amount not yet fully applied or no more unpaid invoices for this customer. Do you want to make the excess collection as an advance collection?", "Save Advance Collection")
        Messaging.AddMessage("AskMakeExcessPaymentAdvance", "Amount not yet fully applied or no more unpaid invoices for this supplier. Do you want to make the excess payment as an advance payment?", $"Save Advance Payment")
        Messaging.AddMessage("MsgAccountsNotAllowed", "Error on line {lineNumber}. Sorry {entryNames} accounts not allowed for this transaction!", "Invalid Entry")
        Messaging.AddMessage("MsgAlreadyPosted", "Sorry this record has already been posted!", "Disallowed operation")
        Messaging.AddMessage("MsgAppliedAmtExceedsBalance", "Error in line {lineNumber}. Applied amount and discount exceeds balance.", "Invalid Payment")
        Messaging.AddMessage("MsgBlankAccountIDNotAllowed", "Error in line <{lineNumber}>. Cannot save entries with debit/credit amounts when account ID is blank.", "Invalid Entry")
        Messaging.AddMessage("MsgBegDateMustBeLessThanEndDate", "Beginning date must be less than ending date.", "Invalid Entry")
        Messaging.AddMessage("MsgCannotPostUnreconciledEntry", "Sorry you can't post an un-reconciled entry!", "Disallowed operation")
        Messaging.AddMessage("MsgCannotSaveAnEmptyTransaction", "Sorry, cannot save an empty transaction!", "Error")
        Messaging.AddMessage("MsgCashAccountsNotAllowed", "Error on line <{lineNumber}>. Cash accounts not allowed for this transaction.", "Invalid Entry")
        Messaging.AddMessage("MsgCollectionIsOverApplied", "Collection is over applied. Either increase the amount of payment or reduce applied payments.", "Invalid Transaction")
        Messaging.AddMessage("MsgCollectionNotFullyApplied", "Collection not yet fully applied. Cannot save entry unless amount is fully applied.", "Invalid Transaction")
        Messaging.AddMessage("MsgDeleteCollEntryNotAllowed", "You can't delete this row because this entry has an existing collection and/or discount!", "Delete Error")
        Messaging.AddMessage("MsgDeletePaidEntryNotAllowed", "You can't delete this row because this entry has an existing payment and/or discount!", "Delete Error")
        Messaging.AddMessage("MsgDeleteRecordFailed", "This record was not deleted because of an error. Please try again later or ask Database Administrator for help.", "Deletion Error")
        Messaging.AddMessage("MsgDuplicateKeyValueViolation", "Cannot insert duplicate key row in object {tableName} with unique index {indexName}. The duplicate key value is {duplicateValue}!", "Unique Key Violation")
        Messaging.AddMessage("MsgDuplicateValuesNotAllowed", "A record with the value <{fieldValue}> entered in field <{fieldDescription}> already exists on file, duplicate values not allowed.", "Duplicate Value")
        Messaging.AddMessage("MsgEditingOfPostedRecordNotAllowed", $"This record has already been posted. Edits not allowed!", "Posted Entry")
        Messaging.AddMessage("MsgFirstRecordHit", "This is already the first record.", "First Record")
        Messaging.AddMessage("MsgFirstRowDeletionNotAllowed", "Deletion of the first row Is Not allowed for this transaction!", "Delete Error")
        Messaging.AddMessage("MsgFirstRowInsertionNotAllowed", "Deletion of the first row Is Not allowed for this transaction!", "Delete Error")
        Messaging.AddMessage("MsgInvalidDate", "Invalid {dateField} Date entered, value must be between {startDate} and {endDate}!", "Invalid Date")
        Messaging.AddMessage("MsgInvalidEndOfYearDate", $"Invalid year end date entry. Month must be 12 and day must be 31!", "Invalid Entry")
        Messaging.AddMessage("MsgInvalidInsertOnFirstRow", "Sorry, insertion on first row not allowed for {transactionName}.", "Invalid Insertion")
        Messaging.AddMessage("MsgInvalidPercentageRange", "Percentage value must be between <1-100>.", "Invalid Entry")
        Messaging.AddMessage("MsgInvalidUserNameOrPassword", "Invalid User Name or Password.", "Login Error")
        Messaging.AddMessage("MsgInvalidValue", "Invalid value <{fieldValue}> for field <{fieldDescription}>.", "Invalid Value")
        Messaging.AddMessage("MsgLastRecordHit", "This is already the last record.", "Last Record")
        Messaging.AddMessage("MsgMemberCannotBeAParentToItself", "Sorry a member cannot be a parent to itself.", "Invalid Parent")
        Messaging.AddMessage("MsgNoChangesMadeNothingToSave", "No changes made or changes have equivalent values as the original values, nothing to save!", "Nothing to save.")
        Messaging.AddMessage("MsgNoRecordsFound", "No records found for this table!", "Empty Table")
        Messaging.AddMessage("MsgNoSpecialAccount", "Sorry, you don't have a {specialAccountName} account. Please go to Chart of Accounts Entry and declare at least one {specialAccountName} Account!", "Error")
        Messaging.AddMessage("MsgNumeric0to255Only", "The entered value for '<{FieldName}>' must be between 0-255. Reverting to previous Value.", "Invalid Entry")
        Messaging.AddMessage("MsgOnEmptyReconChangeAccNotAllowed", "Sorry you can't change the account to reconcile when account reconciliation grid is not empty. Previous value restored.", "Account change not allowed")
        Messaging.AddMessage("MsgOnlyNumbersAllowed", "The field '<{FieldName}>' must contain numbers only.", "Invalid Entry")
        Messaging.AddMessage("MsgPasswordNotSaved", "Password not saved", "Error")
        Messaging.AddMessage("MsgPaymentCollExistChangeNotAllowed", "Sorry, this account receivable has already been partially or fully collected/discounted, changing account/customer not allowed. Value will revert to previous value.", "Modification Error")
        Messaging.AddMessage("MsgPaymentDiscExistChangeNotAllowed", "Sorry, this account payable has already been partially or fully paid/discounted, changing account/supplier not allowed. Value will revert to previous value.", "Modification Error")
        Messaging.AddMessage("MsgPaymentIsOverApplied", "Payment is over applied. Either increase the amount of payment or reduce applied payments.", "Invalid Transaction")
        Messaging.AddMessage("MsgPaymentNotFullyApplied", "Payment not yet fully applied. Cannot save entry unless amount is fully applied.", "Invalid Transaction")
        Messaging.AddMessage("MsgPostingAccountMustNotBeBlank", "Please enter the posting account for this earning.", "Required Entry")
        Messaging.AddMessage("MsgReconciliationAlreadyPosted", $"This Reconciliation entry has already been posted. Edits not allowed!", "Posted Reconciliation")
        Messaging.AddMessage("MsgRecordChangedSinceLastRetrieval", "Record Has Changed since you last retrieved the record, cannot save your modifications. Please refresh the record and try again.", "Someone changed the record!")
        Messaging.AddMessage("MsgRecordSuccessfullyDeleted", "Record was successfully deleted.", "Record Deleted")
        Messaging.AddMessage("MsgRecordSuccessfullySaved", "Record saved successfully!", "Record Saved")
        Messaging.AddMessage("MsgRowDelNotAllowedInViewMode", "Row deletion not allowed while in itemView mode. Press edit button to enable deletion.", "Error")
        Messaging.AddMessage("MsgRowInsNotAllowedInFirstRow", "Row insertion on first row not allowed for this transaction.", "Error")
        Messaging.AddMessage("MsgRowInsNotAllowedInViewMode", "Row insertion not allowed while in itemView mode. Press edit button to enable insertion.", "Error")
        Messaging.AddMessage("MsgSaveReconFirstBeforePosting", "Please save first your reconciliation before posting!", "Unsaved entries exist")
        Messaging.AddMessage("MsgSaveRecordFailed", "Something went wrong during saving, saving record failed", "Modification Error")
        Messaging.AddMessage("MsgSettingNotSet", "Sorry you have not yet setup the [{setupName}] in the [{groupSetting}] setup!", "Invalid Setup")
        Messaging.AddMessage("MsgTooManyFormsOpen", "Too many forms open. You can only open up to {maxOpenForms} forms at the same time.", "Too many forms open")
        Messaging.AddMessage("MsgTotalApMismatch", "Sorry, total header A.P. does not match total details A.P.!", "Invalid Entry")
        Messaging.AddMessage("MsgTotalArMismatch", "Sorry, total header A.R. does not match total details A.R.!", "Invalid Entry")
        Messaging.AddMessage("MsgTotalErMismatch", "Sorry, total header Employee Loans does not match total details Employee Loans!", "Invalid Entry")
        Messaging.AddMessage("MsgValidationCompareEqual", "{propertyName} must be equal to {otherPropertyName}", "Validation Error")
        Messaging.AddMessage("MsgValidationCompareNotEqual", "{propertyName} must not be equal to {otherPropertyName}", "Validation Error")
        Messaging.AddMessage("RptForTheMonth", "{reportName} for the Month of {monthName} {year}", "")
        Messaging.AddMessage("RptForTheQuarter", "{reportName} for the {quarterName} Quarter of {year}", "")
        Messaging.AddMessage("RptForTheSemester", "{reportName} for the {semesterName} Semester of {year}", "")
        Messaging.AddMessage("RptForTheYear", "{reportName} for the Year Ending {year}", "")
        Messaging.AddMessage("RptForThePeriod", "{reportName} for the period {beginningDate} to {endingDate}", "")
        Messaging.AddMessage("RptAging", "Aging of {report} as of {endingDate}", "")
        Messaging.AddMessage("MsgDatesCannotBeEmpty", "Dates cannot be empty, please enter the dates", "Invalid Entry")
        Messaging.AddMessage("MsgDeleteEntryNotAllowed", "Sorry, deletion of {description} entries not allowed!", "Delete Error")
        Messaging.AddMessage("MsgEmptyEmployeeOvertime", "Sorry, employee attendance not yet generated.  You must first generate attendance before generating payroll!", "Generate Error")
        Messaging.AddMessage("AskIfRegeneratePayroll", "Payroll has already been generated. Are you sure you want to re-generate and update previous payroll?", "Please Confirm!")
        Messaging.AddMessage("MsgPayrollGenerationCompleted", "Payroll Generation Completed!", "Finished")
        Messaging.AddMessage("MsgRateChangeNotAllowed", "Sorry, you can't change the rate field for 'fixed amount' entries. You are only allowed to change the amount field.", "Warning")
        Messaging.AddMessage("MultiplierMustNotBeZero", "Error in line <{lineNumber}> on Earning Summary Detail Tab. FactorValue must not be equal to zero.", "Invalid Entry")
        Messaging.AddMessage("MsgEmptyEmployeeAttendanceOt", "Employee attendance or overtime not yet initialized for this payroll, please initialize first before generating payroll", "Error")
        Messaging.AddMessage("MsgSysEarnDelNotAllowed", "This is a system reserved earning, deletion not allowed!", "Error")
        Messaging.AddMessage("MsgSysPayElementNotAllowed", "This is a system reserved pay element, deletion not allowed!", "Error")
        Messaging.AddMessage("MsgCannotEditReadOnly", "Sorry either this item Is read only Or you don't have the proper security credentials to change this value. Reverting to original value.", "Error")
        Messaging.AddMessage("MsgSelectedValueNotAllowed", "Sorry selected value for {field1} not allowed for selected {field2}.", "Error")
        Messaging.AddMessage("MsgNothingToFind", "Either this is a fixed field value or find not enabled for this field.", "Warning")

    End Sub

    'Public Shared Sub CreateEnums()
    '    ResourceEnumConverter.MakeResource("AccountGroupSelection", GetType(AccountGroupSelection))
    '    ResourceEnumConverter.MakeResource("AccountStatusSelection", GetType(AccountStatusSelection))
    '    ResourceEnumConverter.MakeResource("DebitCreditSelection", GetType(DebitCreditSelection))
    '    ResourceEnumConverter.MakeResource("DocumentTypeSelection", GetType(DocumentTypeSelection))
    '    ResourceEnumConverter.MakeResource("ImageTypeSelection", GetType(ImageTypeSelection))
    '    ResourceEnumConverter.MakeResource("MaleFemaleSelection", GetType(MaleFemaleSelection))
    '    ResourceEnumConverter.MakeResource("MaritalStatusSelection", GetType(MaritalStatusSelection))
    '    ResourceEnumConverter.MakeResource("PayeeTypeSelection", GetType(PayeeTypeSelection))
    '    ResourceEnumConverter.MakeResource("PaymentMethodSelection", GetType(PaymentMethodSelection))
    '    ResourceEnumConverter.MakeResource("PaymentTypeSelection", GetType(PaymentTypeSelection))
    '    ResourceEnumConverter.MakeResource("ReceiptTypeSelection", GetType(ReceiptTypeSelection))
    '    ResourceEnumConverter.MakeResource("SecurityLevelSelection", GetType(SecurityLevelSelection))
    '    ResourceEnumConverter.MakeResource("SpecialAccountSelection", GetType(SpecialAccountSelection))
    '    ResourceEnumConverter.MakeResource("TransactionTypeSelection", GetType(TransactionTypeSelection))
    '    ResourceEnumConverter.MakeResource("YearMonthDaySelection", GetType(YearMonthDaySelection))
    '    ResourceEnumConverter.MakeResource("YesNoSelection", GetType(YesNoSelection))

    'End Sub

End Class