Public Class SecurityControlModel
    Inherits Model

    Public Property IdNo As Int32
    Public Property SystemViewIdNo As Int16
    Public Property SecurityControlName As String
    Public Property SecurityControlNameAra As String
    Public Property ParentIdNo As Int32
    Public Property Notes As String
    Public Property AutoGenerated As Boolean

End Class