CREATE VIEW [dbo].[BupaEclaimSubmission_View] (
    [Trans_Key],
    [TrType],
    [BranchID],
    [InsuranceGroupID],
    [InsuranceID],
    [NameEnglish],
    [UnderInsuranceID],
    [Policy],
    [SeqNo],
    [InsCardNo],
    [RegistrationNo],
    [PatientNameEnglish],
    [TransNBR],
    [TransDateEnglish],
    [ApprovalNo],
    [ICD10],
    [Diagnosis1],
    [Diagnosis2],
    [Diagnosis3],
    [ClinicalData],
    [ClaimType],
    [ServiceID],
    [ServiceDescription],
    [ServiceDate],
    [DoctorNameEnglish],
    [DeptID],
    [Qty],
    [Amount],
    [Gross],
    [Discount],
    [Adiscount],
    [Deductible],
    [Net],
    [UserID],
    [Create_Date],
    [MachineID],
    [CoInsuranceNameEnglish],
    [ProviderCode],
    [Temprature],
    [Respiratory],
    [bp],
    [Height],
    [Weight],
    [PulseRate]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

