CREATE View BupaEclaimSubmission_View
 
as
SELECT  
		a.Trans_Key,
		a.TrType,
		a.BranchID,
		a.InsuranceGroupID,
		a.InsuranceID,
		a.NameEnglish,
		a.UnderInsuranceID,
		a.Policy,
		a.SeqNo,
		a.InsCardNo,
		a.RegistrationNo,
		a.PatientNameEnglish,
		a.TransNBR,
		a.TransDateEnglish,
		a.ApprovalNo,
		b.DX_Code1+case when b.DX_Code2='' then '' else ','+b.DX_Code2 end+case when b.DX_Code3='' then '' else ','+b.DX_Code3 end+case when b.DX_Code4='' then '' else ','+b.DX_Code4 end as ICD10,
		b.ChiefComplaint as Diagnosis1,
		b.SignificantSign as Diagnosis2,
		b.Diagnosis as Diagnosis3,
		a.ClinicalData,
		a.ClaimType,
		a.ServiceID,
		a.ServiceDescription,
		a.ServiceDate,
		a.DoctorNameEnglish,
		c.DeptID, 
		a.Qty,
		a.Amount,
		a.Gross,
		a.Discount,
		a.Adiscount,
		a.Deductible,
		a.Net,
		a.UserID,
		a.Create_Date,
		a.MachineID,
		a.CoInsuranceNameEnglish,
		a.ProviderCode,
		b.Temprature,
		b.Respiratory, 
		b.bp,
		b.Height,
		b.Weight,
		b.PulseRate
FROM InsuranceProcessedData_View a
LEFT OUTER JOIN PMRPatientGeneralInfo b on a.registrationno = b.registrationno and a.DoctorID = b.DoctorID and a.transdateenglish = b.transdateenglish AND upper(b.PatientType) = 'INSURANCE'
LEFT OUTER JOIN EmployeeDetails  c on a.DoctorID = c.EmpID 
