
CREATE VIEW 	CreditCompnayStatement_View
 
AS
select 
		branchid,
		trans_key,
		Series,
		RegistrationDate,
		RegistrationType,
		TransType,
		TransNBR,
		BillType,
		RegistrationNo,
		TransDateEnglish,
		TransDateHijri,
		DoctorID,
		InsuranceID,
		InsuranceGroupID,
		InsuranceNameEnglish,
		NormalDiscountAmt,
		PreviousBalanceAmt,
		DeductibleAmt,
		DeductibleDiscountAmt,
		ExtraDiscountPercent,
		ExtraDiscountAmt,
		RoundOffAmt,
		BillAmt,
		Remarks,
		InsSoapNo,
		InsSoapCode,
		InsCardNo,
		Reject,
		RejectDate,
		UserID,
		MachineID,
		CreditCardID,
		CreditCardNo,
		CreditCardExpiry,
		Create_Date ,
		RowNbr,
		SaleType,
		ServiceID,
		DepartmentID,
		qty,
		SalePrice,
		CostPrice,
		DiscountPer,
		DiscountAmt,
		deductiblePer,
		VATAmt,
		SaleStatus,
		CostPrice as costpriceperunit,
		PatientNameEnglish,
		age,
		AgeYMD,
		Sex,
		countryIOTA,
		ServiceNameEnglish,
		EmpNameEnglish,
		CountryNameEng ,
		IqamaNo,
		mobile,
		phoneO,
		PhoneR,
		Address1,
		Address2,
		city,
		groupName,
		groupInsuranceID,
		activeinsName,
		UnderInsuranceID,
		Co_Ins_Company,
		DepartmentNameEnglish,
		TokenNo,
		OPDFloor,
		OPDNo,
		InsServiceID,
		InsServiceNameEnglish,
		 PrintDept
from ClinicInvoice_View where reject <> 1
union all
Select 
		branchid,
		trans_key,
		'CR' as Series,
		RegistrationDate,
		RegistrationType,
		TransType,
		TransNBR,
		BillType,
		RegistrationNo,
		TransDateEnglish,
		'' as TransDateHijri,
		DoctorID,
		InsuranceID,
		InsuranceGroupID,
		InsuranceNameEnglish,
		NormalDiscountAmt,
		0 as PreviousBalanceAmt,
		DeductibleAmt,
		DeductibleDiscountAmt,
		ExtraDiscountPercent,
		ExtraDiscountAmt,
		RoundOffAmt,
		BillAmt,
		Remarks,
		'' as InsSoapNo,
		'' as InsSoapCode,
		'' as InsCardNo,
		case when BillType = 'SALE RETURN' then 1 else 0 end as Reject,
		case when BillType = 'SALE RETURN' then TransDateEnglish else '' end as RejectDate,
		UserID,
		MachineID,
		'' as CreditCardID,
		'' as CreditCardNo,
		'' as CreditCardExpiry,
		Create_Date ,
		RowNbr,
		BillType as SaleType,
		Item_Code as ServiceID,
		'PHR' as DepartmentID,
		qty,
		SalePrice,
		CostPrice,
		DiscountPer,
		DiscountAmt,
		ItemDeductiblePer as deductiblePer,
		VATAmt,
		SaleStatus,
		CostPrice as costpriceperunit,
		PatientNameEnglish,
		age,
		AgeYMD,
		Sex,
		'' as countryIOTA,
		ItemNameEnglish as ServiceNameEnglish,
		DoctorNameEnglish as EmpNameEnglish,
		CountryNameEng ,
		IqamaNo,
		'' as mobile,
		'' as phoneO,
		'' as PhoneR,
		'' as Address1,
		'' as Address2,
		'' as city,
		InsuranceGroupNameEnglish  as groupName,
		InsuranceGroupID as groupInsuranceID,
		InsuranceNameEnglish  as activeinsName,
		InsuranceID  as UnderInsuranceID,
		InsuranceID  as Co_Ins_Company,
		'Pharmacy' as DepartmentNameEnglish,
		0 as TokenNo,
		'' as OPDFloor,
		'' as OPDNo,
		'' as InsServiceID,
		'' as InsServiceNameEnglish,
		'N' PrintDept
from pharmacysales_view where BillType ='SALE INVOICE'
