CREATE VIEW [dbo].[DailyCollectionDepartmentWiseClinicCreditCard_View] (
    [BranchID],
    [Trans_Key],
    [BillType],
    [TransNBR],
    [TransDateEnglish],
    [RegistrationNo],
    [RegistrationDate],
    [RegistrationType],
    [PatientNameEnglish],
    [DoctorID],
    [DoctorNameEnglish],
    [InsuranceID],
    [InsuranceNameEnglish],
    [InsuranceGroupID],
    [InsuranceTPA],
    [ExtraDiscountPercent],
    [ExtradiscountAmt],
    [RoundOffAmt],
    [Reject],
    [UserID],
    [UserNameEnglish],
    [GrossCON],
    [GrossMCT],
    [GrossXRY],
    [GrossLAB],
    [GrossDNT],
    [GrossOPH],
    [GrossCMD],
    [GrossPHR],
    [DiscCON],
    [DiscMCT],
    [DiscXRY],
    [DiscLAB],
    [DiscDNT],
    [DiscOPH],
    [DiscCMD],
    [DiscPHR],
    [CLNdedAmt],
    [CLNdedDiscAmt],
    [CLNExtraDiscAmt],
    [PHRdedAmt],
    [PHRdedDiscAmt],
    [PHRExtraDiscAmt],
    [InvoiceType],
    [CountryIOTA],
    [CountryNameEng]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

