CREATE VIEW [dbo].[DailyCollectionDepartmentWisePharmacy_View] (
    [BranchID],
    [Trans_Key],
    [TransType],
    [TransNbr],
    [TransDateEnglish],
    [RegistrationNo],
    [RegistrationDate],
    [RegistrationType],
    [PatientNameEnglish],
    [DoctorID],
    [DoctorNameEnglish],
    [InsuranceID],
    [InsuranceNameEnglish],
    [InsuranceGroupID],
    [InsuranceTPA],
    [ExtraDiscountPercent],
    [ExtraDiscountAmt],
    [RoundOffamt],
    [Reject],
    [GrossCON],
    [GrossMCT],
    [GrossXRY],
    [GrossLAB],
    [GrossDNT],
    [GrossOPH],
    [GrossCMD],
    [GrossPHR],
    [DiscCON],
    [DiscMCT],
    [DiscXRY],
    [DiscLAB],
    [DiscDNT],
    [DiscOPH],
    [DiscCMD],
    [DiscPHR],
    [CLNdedAmt],
    [PHRdedAmt],
    [InvoiceType]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

