CREATE VIEW [dbo].[HRProcessedData_View] (
    [BranchID],
    [Trans_Key],
    [PeriodMonth],
    [PeriodYear],
    [EmpID],
    [DepartmentID],
    [Date],
    [ShiftID],
    [TimeIn1],
    [TimeOut1],
    [TimeIn2],
    [TimeOut2],
    [Status],
    [PunchNecessary],
    [TotalHrs],
    [DutyHrs],
    [OTHrs],
    [LateHRs],
    [ProcessingStatus1],
    [ProcessingStatus2],
    [ProcessingStatus3],
    [ProcessingStatus4],
    [EmpMarketing],
    [Vacation],
    [OffDay],
    [SplDuty],
    [OnLeave],
    [LeaveType],
    [Authanticate],
    [AuthReason],
    [TimeValid1],
    [TimeValid2],
    [TimeValid3],
    [TimeValid4],
    [Remark],
    [EmpNameEnglish],
    [Sex],
    [Age],
    [Department]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

