CREATE VIEW [dbo].[IBCombinedStatementSummary_ViewORIG] (
    [BranchID],
    [TransNBR],
    [TransType],
    [TransDateEnglish],
    [DoctorID],
    [EmpNameEnglish],
    [RegistrationType],
    [UserID],
    [UserNameEnglish],
    [RoundOffAmt],
    [BillType],
    [TotalVATAmt],
    [GrossAmt],
    [GrossAmtCash],
    [BillAmtCash],
    [DiscountAmtCash],
    [ExtraDiscountAmtCash],
    [RoundOffAmtCash],
    [GrossAmtCredit],
    [BillAmtCredit],
    [DiscountAmtCredit],
    [ExtraDiscountAmtCredit],
    [RoundOffAmtCredit],
    [GrossAmtIBCash],
    [BillAmtIBCash],
    [IBDiscountAmtCash],
    [IBExtraDiscountAmtCash],
    [IBRoundOffAmtCash],
    [GrossAmtIBCredit],
    [BillAmtIBCredit],
    [IBDiscountAmtCredit],
    [IBExtraDiscountAmtCredit],
    [IBRoundOffAmtCredit],
    [PharGrossAmtCash],
    [PharBillAmtCash],
    [PharDiscountAmtCash],
    [PharExtraDiscountAmtCash],
    [PharRoundOffAmtCash],
    [PharGrossAmtCredit],
    [PharBillAmtCredit],
    [PharDiscountAmtCredit],
    [PharExtraDiscountAmtCredit],
    [PharRoundAmtCredit],
    [Reject]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

