CREATE VIEW IBCombinedStatement_View
 
AS
select 
	a.BranchID,
	a.trans_key,
	a.TransType as Series,
	a.RegistrationNo,
	a.RegistrationType,
	a.PatientNameEnglish,
	a.TransNBR,
	a.TransType,
	a.TransDateEnglish,
	a.DoctorID,
	a.EmpNameEnglish,
	a.CountryIOTA,
	a.CountryNameEng,
	a.NormalDiscountAmt,
	a.PreviousBalanceAmt,
	a.DeductibleAmt,
	a.DeductibleDiscountAmt,
	a.ExtraDiscountAmt, 
	a.RoundOffAmt,
	a.VATAmt,
	a.VATExemption, 
	a.BillAmt,
	a.Remarks,
	a.InsCardNo,
	a.UserID,
	a.CreditCardID,
	a.SaleType,
	a.iqamano,
	a.groupname,
	a.groupinsuranceid,
	a.activeinsname,
	a.underinsuranceid,
	a.co_ins_company,
	sum(a.qty*a.saleprice) as GrossAmt,
	sum(case when a.discountamt = 0 then a.qty*a.saleprice*a.discountper/100 else a.DiscountAmt end)  as DiscountAmt,
	a.Reject,
	b.UserNameEnglish  
from ClinicInvoice_View a
left outer join USersBank b on a.UserID = b.UserID 
where (a.Reject is null or a.Reject = 0)
group by
	a.BranchID,
	a.trans_key,
	a.series,
	a.RegistrationNo,
	a.RegistrationType,
	a.PatientNameEnglish,
	a.TransNBR,
	a.TransType,
	a.TransDateEnglish,
	a.DoctorID,
	a.EmpNameEnglish,
	a.CountryIOTA,
	a.CountryNameEng,
	a.NormalDiscountAmt,
	a.PreviousBalanceAmt,
	a.DeductibleAmt,
	a.DeductibleDiscountAmt,
	a.ExtraDiscountAmt ,
	a.RoundOffAmt,
	a.VATAmt,
	a.VATExemption, 
	a.BillAmt,
	a.Remarks,
	a.InsCardNo,
	a.UserID,
	a.CreditCardID,
	a.SaleType,
	a.iqamano,
	a.groupname,
	a.groupinsuranceid,
	a.activeinsname,
	a.underinsuranceid,
	a.co_ins_company,
	a.Reject,
	b.UserNameEnglish  
union all
select 
	a.BranchID,
	a.trans_key,
	a.Transtype as Series,
	a.RegistrationNo,
    a.IBDiagnosisDescription as RegistrationType,
	a.PatientName as PatientNameEnglish,
	a.TransNBR,
	a.TransType,
	a.TransDateEnglish,
	a.DoctorID,
	'NONE' as EmpNameEnglish,
	a.CountryIOTA,
	a.CountryNameEnglish as CountryNameEng,
	a.DiscountAmt as NormalDiscountAmt,
	0 as PreviousBalanceAmt,
	0 as DeductibleAmt,
	0 as DeductibleDiscountAmt,
	a.ExtraDiscountAmt,
	0 as RoundOffAmt,
	a.VATAmt ,
	a.VATExemption,
	a.GrossAmt - a.DiscountAmt - a.ExtraDiscountAmt + a.VATAmt  as BillAmt,
	a.Remarks,
	'' as InsCardNo,
	a.UserID,
	'' as CreditCardID,
	'CLINIC INVOICE' AS SaleType,
	a.border_iqama as iqamano,
	a.companyname as groupname,
	a.companyid as groupinsuranceid,
	a.companyname as activeinsname,
	a.companyid as underinsuranceid,
	a.companyname as co_ins_company,
	sum(a.qty*a.price) as GrossAmt,
	sum(case when a.discountamt = 0 then a.qty*a.price*a.discper/100 else a.DiscountAmt end)  as DiscountAmt,
	a.Rejected as reject,
	b.UserNameEnglish 
from IBInvoice_View a
left outer join usersbank b on a.UserID = b.UserID  
where (a.Rejected  is null or a.Rejected  = 0)
group by
	a.BranchID,
	a.trans_key,
	a.RegistrationNo,
    a.IBDiagnosisDescription,
	a.PatientName,
	a.TransNBR,
	a.TransType,
	a.TransDateEnglish,
	a.DoctorID,
	a.CountryIOTA,
	a.CountryNameEnglish,
	a.DiscountAmt,
	a.GrossAmt,
	a.ExtraDiscountAmt ,
	a.VATAmt ,
	a.VATExemption,
	a.Remarks,
	a.UserID,
	a.border_iqama,
	a.companyname,
	a.companyid,
	a.Rejected,
	b.UserNameEnglish 
union all
select 
	BranchID,
	trans_key,
	case when registrationno = 0 then 'CA' else series end as Series,
	RegistrationNo,
	RegistrationType,
	PatientNameEnglish,
	TransNBR,
	TransType,
	TransDateEnglish,
	DoctorID,
	DoctorNameEnglish as  EmpNameEnglish,
	case when CountryIOTA is null then 'NONE' else CountryIOTA end as CountryIOTA,
	case when CountryIOTA is null then 'UNKNOWN' else CountryNameEng  end as CountryNameEng,
	NormalDiscountAmt,
	PreviousBalanceAmt,
	DeductibleAmt,
	DeductibleDiscountAmt,
	ExtraDiscountAmt, 
	RoundOffAmt,
	VatAmt, 
	0 as VATExemption,
	BillAmt,
	Remarks,
	InsuranceCardNo  as InsCardNo,
	UserID,
	CreditCardID,
	SaleType,
	case when iqamano is null then '' else IqamaNo end as IqamaNo,
	case when InsuranceGroupNameEnglish is null then '' else InsuranceGroupNameEnglish end as groupname,
	case when InsuranceGroupID is null then '' else InsuranceGroupID end as groupinsuranceid,
	case when InsuranceGroupNameEnglish is null then '' else InsuranceGroupNameEnglish end as activeinsname,
	case when underinsuranceid is null then '' else underinsuranceid end as underinsuranceid,
	case when UnderInsuranceName is null then '' else UnderInsuranceName end as  co_ins_company,
	Sum(qty*saleprice) as GrossAmt,
	sum(case when discountamt = 0 then qty*saleprice*discountper/100 else DiscountAmt end) as DiscountAmt,
	CASE WHEN BillType ='SALE RETURN' THEN 1 ELSE 0 END AS Reject,
	UserNameEnglish  
from PharmacySales_View
--where BillType <>'SALE RETURN' and (SaleStatus is null or SaleStatus ='')
group by
	BranchID,
	trans_key,
	Series,
	RegistrationNo,
	RegistrationType,
	PatientNameEnglish,
	TransNBR,
	TransType,
	TransDateEnglish,
	DoctorID,
	DoctorNameEnglish,
	CountryIOTA,
	CountryNameEng,
	NormalDiscountAmt,
	PreviousBalanceAmt,
	DeductibleAmt,
	DeductibleDiscountAmt,
	ExtraDiscountAmt, 
	RoundOffAmt,
	VatAmt ,
	BillAmt,
	Remarks,
	InsuranceCardNo,
	UserID,
	CreditCardID,
	SaleType,
	iqamano,
	InsuranceGroupNameEnglish,
	InsuranceGroupID,
	InsuranceGroupNameEnglish,
	underinsuranceid,
	UnderInsuranceName,
    BillType,
	UserNameEnglish