CREATE VIEW [dbo].[IBCreditCompnayStatement_ViewORIG] (
    [BranchID],
    [Trans_Key],
    [Series],
    [RegistrationType],
    [TransType],
    [TransNBR],
    [BillType],
    [RegistrationNo],
    [TransDateEnglish],
    [DoctorID],
    [InsuranceID],
    [InsuranceNameEnglish],
    [NormalDiscountAmt],
    [PreviousBalanceAmt],
    [ExtraDiscountPercent],
    [ExtraDiscountAmt],
    [RoundOffAmt],
    [BillAmt],
    [Remarks],
    [Reject],
    [RejectDate],
    [UserID],
    [MachineID],
    [Create_date],
    [RowNbr],
    [SaleType],
    [ServiceID],
    [DepartmentID],
    [Qty],
    [SalePrice],
    [DiscountPer],
    [DiscountAmt],
    [VATAmt],
    [VATExemption],
    [SaleStatus],
    [PatientNameEnglish],
    [Age],
    [AgeYMD],
    [Sex],
    [CountryIOTA],
    [ServiceNameEnglish],
    [EmpNameEnglish],
    [CountryNameEng],
    [IqamaNo],
    [Mobile],
    [DepartmentNameEnglish],
    [InsuranceGroupID]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

