
CREATE VIEW 	IBCreditCompnayStatement_View
 
AS
select 
		BranchID,
		Trans_Key,
		Series,
		RegistrationType,
		TransType,
		TransNBR,
		BillType,
		RegistrationNo,
		TransDateEnglish,
		DoctorID,
		InsuranceID,
		InsuranceNameEnglish,
		NormalDiscountAmt,
		PreviousBalanceAmt,
		ExtraDiscountPercent,
		ExtraDiscountAmt,
		RoundOffAmt,
		BillAmt,
		Remarks,
		Reject,
		RejectDate,
		UserID,
		MachineID,
		Create_date,
		RowNbr,
		SaleType,
		ServiceID,
		DepartmentID,
		Qty,
		SalePrice,
		DiscountPer,
		DiscountAmt,
		VATAmt,
		case when CountryIOTA = 'SAU' then VATAmt else 0 end as VATExemption,
		SaleStatus,
		PatientNameEnglish,
		Age,
		AgeYMD,
		Sex,
		CountryIOTA,
		ServiceNameEnglish,
		EmpNameEnglish,
		CountryNameEng,
		IqamaNo,
		Mobile,
		DepartmentNameEnglish,
		InsuranceGroupID
From CreditCompnayStatement_View
WHERE REJECT<> 1
UNION ALL
select 
		BranchID,
		Trans_Key,
		'IBD' as Series,
		IBDiagnosisDescription as RegistrationType,
		TransType,
		TransNBR,
		case when transtype ='Cash' then 'CA' else 'CR' end as BillType,
		RegistrationNo,
		TransDateEnglish,
		DoctorID,
		CompanyID as  InsuranceID,
		CompanyName as InsuranceNameEnglish,
		DiscountAmt as NormalDiscountAmt,
		0 as PreviousBalanceAmt,
		ExtraDiscountPer as  ExtraDiscountPercent,
		ExtraDiscountAmt,
		0 as RoundOffAmt,
		NetAmt as BillAmt,
		Remarks,
		Rejected as Reject,
		RejectedDate  as RejectDate,
		UserID,
		MachineID,
		Create_date,
		SlNo as RowNbr,
		case when Rejected = 1 then 'CLINIC RETURN' ELSE 'CLINIC INVOICE' end AS SaleType,
		ServiceID,
		DepartmentID,
		Qty,
		PRICE AS SalePrice,
		DiscPer AS DiscountPer,
		DiscAmt as DiscountAmt,
		VATAmount as VATAmt,
		case when CountryIOTA = 'SAU' then VATAmount else 0 end as VATExemption,
		case when Rejected = 1 then '' else 'SR' end as SaleStatus,
		PatientName as PatientNameEnglish,
		Age,
		AgeYMD,
		Sex,
		CountryIOTA,
		ServiceNameEnglish,
		'NONE' as EmpNameEnglish,
		CountryNameEnglish as CountryNameEng,
		Border_Iqama as IqamaNo,
		Phone as Mobile,
		'IQAMA BALADIYA' as DepartmentNameEnglish,
		CompanyID as InsuranceGroupID
From IBInvoice_View 
WHERE Rejected <> 1
