CREATE VIEW [dbo].[IBDocuments_View] (
    [Trans_Key],
    [BranchID],
    [IBType],
    [RegistrationNo],
    [PatientName],
    [TransType],
    [TransNBR],
    [TransDateEnglish],
    [TransDateHijri],
    [DeliveryDate],
    [CompanyID],
    [DoctorID],
    [Border_Iqama],
    [SponsorID],
    [Profession],
    [CountryIOTA],
    [BaladiyaExpiration],
    [Phone],
    [SponsorPhone],
    [DOB],
    [Age],
    [AgeYMD],
    [Sex],
    [LabReportNo],
    [LabReportResult],
    [LabUnfitReason],
    [XrayReportNo],
    [XrayReportResult],
    [CardStatus],
    [CardIssueDate],
    [TokenNo],
    [GrossAmt],
    [DiscountAmt],
    [TotalVATAmt],
    [NetAmt],
    [ExtraDiscountPer],
    [ExtraDiscountAmt],
    [Remarks],
    [Posted],
    [Accepted],
    [AcceptedNo],
    [Rejected],
    [RejectedDate],
    [Finishied],
    [UserID],
    [Create_Date],
    [MachineID],
    [SponsorName],
    [SalesmanID],
    [LabSeries]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

