CREATE VIEW [dbo].[InsuranceSummary_View] (
    [Trans_Key],
    [TrType],
    [BranchID],
    [InsuranceGroupID],
    [InsuranceID],
    [NameEnglish],
    [UnderInsuranceID],
    [Policy],
    [SeqNo],
    [InsCardNo],
    [RegistrationNo],
    [PatientNameEnglish],
    [TransNBR],
    [TransDateEnglish],
    [ApprovalNo],
    [ICD10],
    [Diagnosis1],
    [Diagnosis2],
    [Diagnosis3],
    [ClinicalData],
    [ClaimType],
    [ServiceID],
    [ServiceDescription],
    [ServiceDate],
    [DoctorID],
    [DoctorNameEnglish],
    [Qty],
    [Amount],
    [Gross],
    [Discount],
    [ADiscount],
    [Deductible],
    [Net],
    [UserID],
    [Create_Date],
    [MachineID],
    [InsSoapNo],
    [InsSoapCode],
    [CoInsuranceNameEnglish],
    [ProviderCode],
    [ClaimNo],
    [Logo]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

