
CREATE VIEW 	ItemPurchase_View
 
AS
SELECT  a.Trans_Key,
	a.BranchID,
	a.TransType,
	a.TransSeries,
	a.TransNo,
	a.TransDate,
	a.HijriDate,
	a.PONo,
	a.PODate,
	a.WarehouseID,
	a.PurchaseType,
	a.PurchaseFrom,
	a.SupplierID,
	a.InvoiceNo,
	a.InvoiceDate,
	a.Reference,
	a.InvoiceAmt,
	a.CurrencyCode,
	a.ConversionRate,
	a.GrossAmt,
	a.TotalExpenses,
	a.SpecialDiscountPer,
	a.SpecialDiscountAmt,
	a.SalesmanID,
	a.Remarks,
	a.PostInAccounts,
	a.PostInStock,
	a.AccountsUpdate,
	a.PurchaseGrossAmt,
	a.VATAmt as PurchaseVATAmt, 
	a.PurchaseCostAmt,
	a.PurchaseSaleAmt,
	a.PurchaseProfitPer,
	a.PurchaseProfitAmt,
	a.EnteredBy,
	a.CheckedBy,
	a.ApprovedBy,
	a.UserID,
       	a.Create_Date,
	a.MachineID,
	b.SlNo,
	b.Item_Code,
	b.pack1,
	b.pack2,
	b.pack3,
	b.Batch,
	b.Expiry,
	b.UserQty,
	b.BonusQty,
	b.Unit,
	b.TotalQty,
	b.QtyInBox,
	b.QtyInPcs,
	b.Amount,
	b.Discount,
	b.Discount2,
	b.PurchasePrice,
	b.VATPercent,
	b.VATAmt, 
	b.CostPrice,
	b.SellingPrice,
	b.ProfitPer,
	b.ProfitAmt,
	c.ItemNameEnglish,
	d.SupplierNameEnglish,
	d.VATNo,
	e.WarehouseNameEnglish
From PurchaseGroup A
LEFT OUTER JOIN PurchaseDetails B ON A.Trans_Key = B.Group_Key AND A.BranchID = B.BranchID
LEFT OUTER JOIN ItemDetails C ON B.Item_Code = C.Item_Code AND A.BranchID = C.BranchID
LEFT OUTER JOIN SupplierDetails D ON A.SupplierID = D.SupplierID 
LEFT OUTER JOIN WarehouseDetails E ON A.WarehouseID = E.WarehouseID and A.BranchID = e.BranchID
--WHERE a.TRANSTYPE = 'PUR' AND (b.PURCHASESTATUS IS NULL OR PURCHASESTATUS = 'PUR')
