CREATE VIEW [dbo].[ItemPurchaseOrder_View] (
    [Trans_Key],
    [BranchID],
    [TransType],
    [TransSeries],
    [TransNo],
    [TransDate],
    [HijriDate],
    [PurchaseFrom],
    [SupplierID],
    [CurrencyCode],
    [ConversionRate],
    [SalesmanID],
    [Remarks],
    [PostInPurchase],
    [PurchaseGrossAmt],
    [PurchaseCostAmt],
    [PurchaseSaleAmt],
    [EnteredBy],
    [CheckedBy],
    [ApprovedBy],
    [UserID],
    [Create_Date],
    [MachineID],
    [SlNo],
    [Item_Code],
    [pack1],
    [pack2],
    [pack3],
    [UserQty],
    [BonusQty],
    [Unit],
    [TotalQty],
    [QtyInBox],
    [QtyInPcs],
    [Amount],
    [Discount],
    [Discount2],
    [PurchasePrice],
    [CostPrice],
    [SellingPrice],
    [ItemNameEnglish],
    [SupplierNameEnglish],
    [fax],
    [email]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

