
CREATE VIEW 	PharmacyInovoiceView
 
AS
SELECT 
	A.Trans_Key,
	A.BranchID,
        A.WareHouseID,
	A.BillType,
	A.TransType,
	A.TransNbr,
	A.TransDateEnglish,
	A.RegistrationType,
	A.RegistrationNo,
	A.ReferenceNo,
	A.DoctorID,
	A.InsuranceID,
	A.InsuranceGroupID,
	A.InsuranceNameEnglish,
	A.DeductionCategory,
	A.InsuranceCardNo,
	A.InsurancePolicyNo,
	A.InsSoapNo,
	A.InsSoapCard,
	A.NormalDiscountAmt,
	A.PreviousBalanceAmt,
	A.DeductibleAmt,
	A.DeductibleDiscountAmt,
	A.ExtraDiscountAmt,
	A.ExtraDiscountPercent,
	A.VATAmt as TotalVATAmt, 
	A.RoundOffAmt,
	A.TenderCash,
	A.BillAmt,
	A.CostAmt,
	A.CreditCardID,
	A.CreditCardNo,
	A.CreditCardExpiry,
	A.Remarks,
	A.UserID,
	A.Create_Date,
	A.MachineID,
	B.RowNbr,
	B.Item_Code,
	B.Batch,
	B.Expiry,
	B.Qty,
	B.Unit,
	B.PcsQty,
	B.QtyInStock,
	B.Pack1,
	B.Pack2,
	B.Pack3,
	B.EANCode,
	B.SalePrice,
	B.CostPrice,
	B.costPricePerUnit,
	B.DiscountPer,
	B.DiscountAmt,
	B.VATPercent,
	b.VATAmt  
FROM PharmacyInvoiceGroup A
LEFT OUTER JOIN PharmacyInvoiceDetails B ON A.Trans_Key = B.Group_Key AND A.BranchID = B.BranchID AND A.BillType = B.SaleType
LEFT OUTER JOIN BranchDetails          C ON A.BranchID = C.BranchID
LEFT OUTER JOIN WarehouseDetails       D ON A.warehouseID = D.WarehouseID 
LEFT OUTER JOIN EmployeeDetails        E ON A.DoctorID = E.EmpID
LEFT OUTER JOIN ItemDetails	       F ON B.Item_Code = F.Item_Code
