CREATE VIEW [dbo].[PurchaseHostoryBySupplier_View] (
    [Trans_Key],
    [BranchID],
    [TransType],
    [TransSeries],
    [TransNo],
    [TransDate],
    [HijriDate],
    [PONo],
    [PODate],
    [WarehouseID],
    [PurchaseType],
    [PurchaseFrom],
    [SupplierID],
    [InvoiceNo],
    [InvoiceDate],
    [Reference],
    [InvoiceAmt],
    [CurrencyCode],
    [ConversionRate],
    [GrossAmt],
    [TotalExpenses],
    [SpecialDiscountPer],
    [SpecialDiscountAmt],
    [SalesmanID],
    [Remarks],
    [PostInAccounts],
    [PostInStock],
    [AccountsUpdate],
    [PurchaseGrossAmt],
    [PurchaseCostAmt],
    [PurchaseSaleAmt],
    [PurchaseProfitPer],
    [PurchaseProfitAmt],
    [EnteredBy],
    [CheckedBy],
    [ApprovedBy],
    [UserID],
    [Create_Date],
    [MachineID],
    [SupplierNameEnglish],
    [WarehouseNameEnglish]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

