CREATE VIEW wsl_geninfo_View
 
AS
SELECT
	F.PROVIDERCODE 		AS 	[PROVIDERID],
	'NCCI' 		AS 	[PAYERID],
	'N/A'	 		AS 	[TPAID],
	RIGHT('0000000'+RTRIM(CONVERT(varchar(7),A.REGISTRATIONNO)),6)+
        REPLACE(A.TRANSDATEENGLISH,'/','')+
        RIGHT('00'+A.DOCTORID,2)as 	[PROVCLAIMNO],
	A.INSCARDNO 		AS	[MEMBERID],
	CASE WHEN A.POLICY IS NULL THEN '' ELSE A.Policy END AS 	[POLICYNO],
	G.itemNAMEENGLISH	AS	[PLANTYPE],
	B.PATIENTNAMEENGLISH 	AS	[FULLNAME],
	'' 			AS	[FIRSTNAME],
	'' 			AS	[MIDDLENAME],
	'' 			AS	[LASTNAME],
	convert(varchar(30),A.REGISTRATIONNO) 	AS	[PATFILENO],
	a.NAMEENGLISH		AS 	[ACCCODE],
	B.DOB 			AS	[MEMBERDOB],
	B.AGE 			AS	[MEMBERAGE],
	CASE WHEN B.AGEYMD='D' THEN 'Day' ELSE CASE WHEN B.AGEYMD='M' THEN 'Month' ELSE 'Year' END END AS	[UNITAGE],
	CASE WHEN B.SEX='M' THEN 'Male' ELSE 'Female' END AS	[GENDER],
	E.COUNTRYNAMEENG 	AS	[NATIONALITY],
	A.DOCTORID 		AS	[PHYID],
	C.EMPNAMEENGLISH 	AS	[PHYNAME],
	'01' 			AS 	[PHYCATEGORY], -- Check with Doctor Master
	c.deptid 		AS	[DEPTCODE], -- DEPARTMENT
	'NEW' 			AS	[VISITTYPE], -- NEW / FOLLOW UP
	A.TRANSDATEENGLISH 	AS	[CLAIMDATE],
	'Outpatient' 		AS	[CLAIMTYPE],
	'' 			AS	[MAINCLAIMREFNO],
	'' 			AS	[ELIGREFNO],
	convert(varchar(20),A.APPROVALNO)		AS	[APPREFNO],
	NULL		 	AS	[ADMISSIONDATE],
	NULL 			AS	[ADMISSIONTIME],
	NULL		 	AS	[DISCHARGEDATE],
	NULL 			AS 	[DISCHARGETIME],
	0 			AS	[LENGTHOFSTAY],
	'' 			AS	[UNITOFSTAY],
	'' 			AS	[ROOMNO],
	'' 			AS	[BEDNO],
	convert(varchar(1000),D.CHIEFCOMPLAINT) 	AS	[MAINSYMPTOM],
	convert(varchar(200),D.SIGNIFICANTSIGN) 	AS	[SIGNIFICANTSIGN],
	convert(varchar(1000),D.OTHERCONDITION) 	AS	[OTHERCOND],
	1 			AS	[DURATIONOFILLNESS],
	'D'	 		AS	[UNITOFDURATION],
	null			AS	[TEMPERATURE],
	null 			AS 	[BLOODPRESSURE],
	null 			AS	[PULSE],
	null 			AS	[RESPIRATORYRATE],
	null 			AS	[WEIGH],
	NULL 			AS	[LASTMENSTRUATIONPERIOD],
	SUM(A.QTY*A.AMOUNT) 		AS	[TOTCLAIMGRSAMT],
	SUM(A.DISCOUNT) 		AS 	[TOTCLAIMDISC],
	SUM(A.DEDUCTIBLE) 		AS 	[TOTCLAIMPATSHARE],
	SUM((A.QTY*A.AMOUNT)-(A.DISCOUNT+A.DEDUCTIBLE)) AS	[TOTCLAIMNETAMT],
	'' 			AS	[RADIOREPORT],
	'' 			AS	[COMMREPORT],
	'' 			AS	[EXTRACTION_DATE]
FROM [INSURANCEALTEREDDATA] A
LEFT OUTER JOIN PATIENTDETAILS B ON A.REGISTRATIONNO = B.REGISTRATIONNO AND UPPER(B.PATIENTTYPE)='INSURANCE'
LEFT OUTER JOIN EMPLOYEEDETAILS C ON A.DOCTORID = C.EMPID
LEFT OUTER JOIN PMRPATIENTGENERALINFO D ON D.REGISTRATIONNO = A.REGISTRATIONNO 
					AND UPPER(D.PATIENTTYPE) = 'INSURANCE' 
					AND A.DOCTORID = D.DOCTORID 
					AND A.TRANSDATEENGLISH = D.TRANSDATEENGLISH
LEFT OUTER JOIN COUNTRYMASTER E ON B.COUNTRYIOTA = E.COUNTRYIOTA
LEFT OUTER JOIN INSURANCEDETAILS F ON A.INSURANCEID = F.INSURANCEID
LEFT OUTER JOIN DeductibleClassMaster G ON B.DEDUCTIONCATEGORY = G.itemID
GROUP BY
	A.REGISTRATIONNO,
	A.TRANSDATEENGLISH,
	A.DOCTORID,
	F.PROVIDERCODE,
	A.INSCARDNO,
	A.POLICY,
	G.itemNAMEENGLISH,
	B.PATIENTNAMEENGLISH,
	a.NAMEENGLISH,
	B.DOB,
	B.AGE,
	B.SEX,
	E.COUNTRYNAMEENG,
	A.DOCTORID,
	C.EMPNAMEENGLISH,
	c.deptid,
	A.APPROVALNO,
	AGEYMD,
	D.CHIEFCOMPLAINT,
	D.SIGNIFICANTSIGN,
	D.OTHERCONDITION
