CREATE VIEW WSL_LAB_COMPONENT_View
 
AS
SELECT 	B.INVESTIGATIONID AS LABTESTCODE,
Rtrim(convert(varchar(10),A.REGISTRATIONNO))+
	REPLACE(A.TRANSDATEENGLISH,'/','')+
	A.DOCTORID as [PROVCLAIMNO],
	B.INVESTIGATIONID AS LABCOMCODE,
	B.SLNO AS SERIAL,
	B.OBSERVATION AS LABCOMDESC,
	CASE WHEN B.RESULT1 IS NULL THEN '' ELSE B.RESULT1 END AS LABRESULT,
	'' AS LABRESULTUNIT,
	'' AS LABRESULTCOMMENT,
	C.GROUPINSURANCEID AS INSURANCEID
FROM INSURANCEALTEREDDATA A
LEFT OUTER JOIN DIAGNOSIS_REPORT_VIEW B ON A.TRANSNBR = B.INVOICENO AND A.DOCTORID = B.DOCTORID AND A.DOCTORID = B.DOCTORID
LEFT OUTER JOIN INSURANCEDETAILS C ON B.INSURANCEID = C.INSURANCEID
--WHERE A.TRANSDATEENGLISH BETWEEN '2015/05/01' AND '2015/05/31' AND C.GROUPINSURANCEID='5004'
