CREATE VIEW [dbo].[WSL_SERVICE_DETAILS_View] (
    [INSURANCEID],
    [INVOICENO],
    [SERVICECODE],
    [SERVICEDATE],
    [SERVICEDESC],
    [UNITSERVICEPRICE],
    [UNITSERVICETYPE],
    [QTY],
    [TOOTHNO],
    [TOTSERVICEGRSAMT],
    [TOTSERVICEDISC],
    [TOTSERVICEPATSHARE],
    [TOTSERVICENETAMT]
)
WITH ENCRYPTION
AS
SELECT NULL AS [NullColumn]
--The script body was encrypted and cannot be reproduced here.;

