CREATE VIEW WSL_CLAIM_ILLNESS_View
 
AS
SELECT A.TRANSDATEENGLISH,
	A.INSURANCEID,
	RIGHT('0000000'+RTRIM(CONVERT(varchar(7),A.REGISTRATIONNO)),6)+
        REPLACE(A.TRANSDATEENGLISH,'/','')+
        RIGHT('00'+A.DOCTORID,2)as 	[PROVCLAIMNO],
	CASE ILLNESSTYPE 	WHEN 1 THEN 'Regular Checkup'
				WHEN 2 THEN 'Vaccination'
				WHEN 3 THEN 'Work Related'
				WHEN 4 THEN 'Chronic'
				WHEN 5 THEN 'Psychatric'
				WHEN 6 THEN 'Infertility'
				WHEN 7 THEN 'Pregnancy'
				WHEN 8 THEN 'Congenital'
				WHEN 9 THEN 'RTA'
				ELSE 'N/A' END AS ILLNESSTYPE
FROM [INSURANCEALTEREDDATA] A
LEFT OUTER JOIN PMRPATIENTGENERALINFO B ON B.REGISTRATIONNO = A.REGISTRATIONNO 
					AND UPPER(B.PATIENTTYPE) = 'INSURANCE' 
					AND A.DOCTORID = B.DOCTORID 
					AND A.TRANSDATEENGLISH = B.TRANSDATEENGLISH
