	[Age] [numeric](3, 0) NULL,
	[AgeYMD] [char](1) NULL,
	[ApprovalNo] [varchar](20) NULL,
	[BillAmt] [numeric](12, 2) NULL,
	[BillType] [varchar](20) NULL,
	[CountryIOTA] [varchar](10) NULL,
	[CountryNameEng] [varchar](35) NULL,
	[Create_date] [datetime] NULL,
	[CreditCardID] [varchar](15) NULL,
	[DeductibleAmt] [numeric](12, 2) NULL,
	[DeductibleDiscountAmt] [numeric](12, 2) NULL,
	[deductibleper] [numeric](12, 4) NULL,
	[DepartmentID] [varchar](15) NULL,
	[DepartmentNameEnglish] [varchar](75) NULL,
	[DiscountAmt] [numeric](12, 4) NULL,
	[DiscountPer] [numeric](12, 4) NULL,
	[DoctorID] [varchar](15) NULL,
	[EmpNameEnglish] [varchar](40) NULL,
	[ExtraDiscountAmt] [numeric](12, 2) NULL,
	[ExtraDiscountPercent] [numeric](12, 2) NULL,
	[GroupInsuranceID] [varchar](15) NULL,
	[GroupName] [varchar](75) NULL,
	[InsCardNo] [varchar](30) NULL,
	[InsServiceID] [varchar](15) NULL,
	[InsServiceNameEnglish] [varchar](100) NULL,
	[InsuranceGroupID] [varchar](15) NULL,
	[InsuranceID] [varchar](15) NULL,
	[InsuranceNameEnglish] [varchar](50) NULL,
	[IqamaNo] [nvarchar](50) NULL,
	[MachineID] [varchar](30) NULL,
	[Mobile] [varchar](30) NULL,
	[NormalDiscountAmt] [numeric](12, 2) NULL,
	[OPDFloor] [varchar](15) NULL,
	[OPDNo] [varchar](5) NULL,
	[PatientNameEnglish] [varchar](50) NULL,
	[PreviousBalanceAmt] [numeric](12, 2) NULL,
	[PrintDept] [varchar](1) NULL,
	[Qty] [numeric](12, 3) NULL,
	[RegistrationDate] [varchar](10) NULL,
	[RegistrationNo] [numeric](12, 0) NULL,
	[RegistrationType] [varchar](15) NULL,
	[Remarks] [varchar](2000) NULL,
	[RoundOffAmt] [numeric](12, 2) NULL,
	[RowNbr] [numeric](3, 0) NULL,
	[SalePrice] [numeric](12, 4) NULL,
	[SaleType] [varchar](15) NULL,
[series] [varchar](2) NULL,
	[ServiceID] [varchar](50) NULL,
	[ServiceNameArabic] [varchar](100) NULL,
	[ServiceNameEnglish] [varchar](100) NULL,
	[Sex] [char](1) NULL,
	[TokenNo] [numeric](5, 0) NULL,
	[TokenPrint] [int] NULL,
	[TransDateEnglish] [varchar](10) NULL,
	[TransNBR] [numeric](10, 0) NULL,
	[TransType] [varchar](10) NULL,
	[UnderInsuranceID] [varchar](15) NULL,
	[UserID] [varchar](30) NULL,
	[VATAmt] [numeric](10, 2) NULL,
	[VatExemption] [numeric](10, 2) NULL
	[VATPercent] [numeric](5, 2) NULL,