:r c:\temp\Sql\customer.sql
:r c:\temp\Sql\supplier.sql	
:r c:\temp\Sql\ApJournal.sql
:r c:\temp\Sql\ApJournalItem.sql
:r c:\temp\Sql\ArJournal.sql
:r c:\temp\Sql\ArJournalItem.sql
:r c:\temp\Sql\ErJournal.sql
:r c:\temp\Sql\ErJournalItem.sql
:r c:\temp\Sql\GeneralJournal.sql
:r c:\temp\Sql\GeneralJournalItem.sql
:r c:\temp\Sql\GeneralJournalItem1.sql
:r c:\temp\Sql\GeneralJournalItem2.sql
:r c:\temp\Sql\GeneralJournalItem3.sql
:r c:\temp\Sql\CashDisbursementJournal.sql
:r c:\temp\Sql\CashDisbursementJournalItem.sql
:r c:\temp\Sql\CheckDisbursementJournal.sql
:r c:\temp\Sql\CheckDisbursementJournalItem.sql
:r c:\temp\Sql\CashReceiptJournal.sql
:r c:\temp\Sql\CashReceiptJournalItem.sql
:r c:\temp\Sql\CadOiItem.sql
:r c:\temp\Sql\CkdOiItem.sql
:r c:\temp\Sql\ApOpenInvoice.sql
:r c:\temp\Sql\CSROiItem.sql
:r c:\temp\Sql\AROpenInvoice.sql
:r c:\temp\Sql\ChartBalance.sql
:r c:\temp\Sql\UpdateChartBegBal.sql
