mosUSE [ISPDATA]
GO
SET IDENTITY_INSERT [dbo].[Earning] ON 
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (1, N'BPM', N'Basic Pay (Monthly)', N'Basic Pay (Monthly)', N'M', N'R', 511, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 1, 1, 0.0000, 0, N'I', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (2, N'HAM', N'Housing Allowance Monthly', N'Housing Allowance Monthly', N'M', N'R', 512, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 1, 1, 0.0000, 0, N'I', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (3, N'TAM', N'Transportation Allowance Monthly', N'Transportation Allowance Monthly', N'M', N'R', 0, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'I', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (4, N'FAM', N'Food Allowance Monthly', N'Food Allowance Monthly', N'M', N'R', 0, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'I', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (5, N'VPY', N'Vacation Pay Yearly', N'Vacation Pay Yearly', N'M', N'V', 0, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 1.0000, 0, N'D', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (6, N'OTH', N'Overtime per hour regular rate', N'Overtime per hour regular rate', N'M', N'O', 511, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'M', 0, N't')
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (7, N'OT1.5', N'Overtime per hour 1.5 times regular rate', N'Overtime per hour 1.5 times regular rate', N'M', N'O', 0, 6, N'F', CAST(0.0000 AS Decimal(10, 4)), CAST(1.5000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N' ', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (8, N'OT2', N'Overtime per hour 2 times regular rate', N'Overtime per hour 2 times regular rate', N'M', N'O', 0, 6, N'F', CAST(0.0000 AS Decimal(10, 4)), CAST(2.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N' ', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (9, N'EXP', N'Bonus', N'Bonus', N'A', N'B', 535, 0, N'X', CAST(1.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'U', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (10, N'HPD', N'Holiday Pay per Day', N'Holiday Pay per Day', N'A', N'H', 535, 1, N'F', CAST(1.0000 AS Decimal(10, 4)), CAST(3.3333 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'W', 1, N'testttess')
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (11, N'SPD', N'Sick Pay per day', N'Sick Pay per day', N'A', N'S', 433, 1, N'F', CAST(1.0000 AS Decimal(10, 4)), CAST(3.3333 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'I', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (12, N'BNE', N'Commission', N'Commission', N'A', N'C', 0, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'U', 0, NULL)
GO
INSERT [dbo].[Earning] ([IdNo], [EarningCode], [EarningName], [EarningNameAra], [Frequency], [EarningType], [AccountIdNo], [BasePaymentIdNo], [CalculationType], [DefaultQuantity], [FactorValue], [FactorType], [IncludeInEos], [IncludeInPension], [Rate], [Taxable], [Unit], [UsePayGroups], [Notes]) VALUES (13, N'OE', N'Other Earning (Monthly)', N'Other Earning (Monthly)', NULL, N'R', 0, 0, N'X', CAST(0.0000 AS Decimal(10, 4)), CAST(0.0000 AS Decimal(10, 4)), N' ', 0, 0, 0.0000, 0, N'I', 0, NULL)
GO
SET IDENTITY_INSERT [dbo].[Earning] OFF
GO