USE [ISPDATA]
GO
/****** Object:  Table [dbo].[Designation]    Script Date: 4/29/2020 12:03:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Designation](
	[IdNo] [int] IDENTITY(1,1) NOT NULL,
	[DesignationCode] [varchar](5) NOT NULL,
	[DesignationName] [varchar](50) NOT NULL,
	[DesignationNameAra] [varchar](50) NULL,
	[Description] [varchar](50) NULL,
	[DateTimeStamp] [timestamp] NULL,
	[Notes] [nvarchar](255) NULL,
 CONSTRAINT [PK_Designation] PRIMARY KEY CLUSTERED 
(
	[IdNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 4/29/2020 12:03:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[IdNo] [int] IDENTITY(1,1) NOT NULL,
	[BranchID] [int] NULL,
	[EmployeeCode] [varchar](10) NOT NULL,
	[Title] [varchar](25) NULL,
	[EmployeeName] [varchar](75) NOT NULL,
	[EmployeeNameAra] [nvarchar](75) NULL,
	[Gender] [varchar](1) NULL,
	[BirthDate] [date] NULL,
	[MaritalStatus] [char](1) NULL,
	[NationalityCode] [char](2) NULL,
	[ReligionIdNo] [smallint] NULL,
	[NationalIdNo] [varchar](10) NULL,
	[Street] [nvarchar](50) NULL,
	[District] [nvarchar](50) NULL,
	[TownCity] [nvarchar](50) NULL,
	[ProvinceState] [nvarchar](50) NULL,
	[CountryCode] [char](2) NULL,
	[PoBox] [varchar](15) NULL,
	[ZipCode] [varchar](15) NULL,
	[Phone1] [varchar](15) NULL,
	[Phone2] [varchar](15) NULL,
	[Email] [varchar](50) NULL,
	[DepartmentIdNo] [smallint] NULL,
	[DesignationIdNo] [smallint] NULL,
	[HiredDate] [date] NULL,
	[ReleasedDate] [date] NULL,
	[ArAccountIdNo] [int] NULL,
	[BankIdNo] [smallint] NULL,
	[BankAccountNo] [varchar](15) NULL,
	[IBAN] [varchar](20) NULL,
	[Notes] [varchar](300) NULL,
	[OpeningBalance] [money] NULL,
	[Balance] [money] NULL,
	[Active] [bit] NULL,
	[Create_Date] [datetime] NULL,
	[DateTimeStamp] [timestamp] NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[IdNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Designation] ON 
GO
INSERT [dbo].[Designation] ([IdNo], [DesignationCode], [DesignationName], [DesignationNameAra], [Description], [Notes]) VALUES (1, N'001', N'Staff Nurse', N'Staff Nurse', NULL, NULL)
GO
INSERT [dbo].[Designation] ([IdNo], [DesignationCode], [DesignationName], [DesignationNameAra], [Description], [Notes]) VALUES (2, N'002', N'Medical Technologist', N'Medical Technologist', NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[Designation] OFF
GO
SET IDENTITY_INSERT [dbo].[Employee] ON 
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (1, 2, N'E00107', N'Dr.', N'Essameldin Daheb', N'عصام دهب', N'M', CAST(N'1952-03-21' AS Date), N'M', N'EG', 1, N'2078505043', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-07-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-10T12:12:35.600' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (2, 2, N'E00060', N'Dr.', N'Mohamad Al-Sayed ', N'محمد السيد', N'M', CAST(N'1958-11-18' AS Date), N'M', N'EG', 1, N'2112589151', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1995-09-09' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:42:49.970' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (4, 2, N'E00205', N'Dr.', N'Mervat Abd ElSalam ', N'مرفت عبدالسلام ', N'F', CAST(N'1958-03-19' AS Date), N'M', N'EG', 1, N'2219339856', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2005-09-07' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-16T19:58:56.860' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (5, 2, N'E00021', N'Mr.', N'AbdulFattah Moustafa ', N'عبدالفتاح مصطفى', NULL, CAST(N'1954-03-15' AS Date), NULL, N'EG', 1, N'2027033451', NULL, NULL, NULL, NULL, N'YE', NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1989-01-05' AS Date), CAST(N'2019-08-20' AS Date), 208, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2019-02-28T13:51:17.067' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (6, 2, N'E00426', N'Dr.', N'Hani Ahmad Farid Zamzam', N'هانى زمزمى', N'M', CAST(N'1955-10-12' AS Date), N' ', N'EG', 1, N'2251393001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-04-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:32:26.607' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (7, 2, N'E00250', N'Dr.', N'Mohammed Sonbol', N'محمد سنبل', N'M', CAST(N'1951-10-13' AS Date), N'M', N'EG', 1, N'2028587786', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2008-05-25' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-17T10:52:01.063' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (8, 2, N'E00423', N'Dr.', N'Ibrahim Abdulsalam ', N'إبراهيم عبدالسلام ', N'M', CAST(N'1971-04-19' AS Date), N' ', N'EG', 1, N'2362233757', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-08-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:32:56.157' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (9, 2, N'E00300', N'Dr.', N'Rasha Al Refaeyxxxx', N'رشا الرفاعي', N'F', CAST(N'1971-09-02' AS Date), N'M', N'EG', 1, N'2159971528', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-01-06' AS Date), CAST(N'2020-04-08' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-14T22:33:18.470' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (11, 2, N'E00414', N'Dr.', N'Mohammad Jalal ', N'محمد جلال ', N'M', CAST(N'1972-04-22' AS Date), N'M', N'EG', 1, N'2286288556', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-02-26' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:33:52.670' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (12, 2, N'E00026', N'Mr.', N'Ali Amar ', N'علي عمار ', N'M', CAST(N'1968-05-31' AS Date), N'M', N'YE', 1, N'2044268478', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1989-08-21' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-18T10:43:47.543' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (13, 2, N'E00108', N'Ms.', N'Susan A. Britanico', N'سوزان', N'F', CAST(N'1971-01-24' AS Date), N'M', N'PH', 2, N'2157698446', NULL, NULL, NULL, NULL, NULL, NULL, N'21144', NULL, NULL, NULL, 28, NULL, CAST(N'2000-10-17' AS Date), CAST(N'2020-03-31' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-08-09T12:33:02.830' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (14, 2, N'E00136', N'Ms.', N'Joy E. Gimoro', N'جوي جيمورو', N'F', CAST(N'1972-01-29' AS Date), N'M', N'PH', 2, N'2175602933', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2001-09-24' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-15T13:14:45.893' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (15, 2, N'E00139', N'Mr.', N'AbdulRahman ElFol', N'عبدالرحمن الفل', N'M', CAST(N'1948-01-07' AS Date), N'M', N'EG', 1, N'2175603360', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2001-10-06' AS Date), CAST(N'2019-08-20' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-14T22:34:34.110' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (16, 2, N'E00001', N'Mr.', N'Marwan Fetyani', N'مروان فتياني', N'M', CAST(N'1954-03-06' AS Date), N'M', N'SA', 1, N'1016268094', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1981-01-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-09T12:27:39.037' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (17, 2, N'E00146', N'Mr.', N'Ehab Bakeer', N'إيهاب بكير', N'M', CAST(N'1969-08-14' AS Date), NULL, N'EG', 1, N'2171957927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-02-04' AS Date), CAST(N'2019-08-20' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-14T22:37:14.650' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (18, 2, N'E00040', N'Ms.', N'Subaida Sultan', N'زبيده ', N'F', CAST(N'1958-10-22' AS Date), N'M', N'PH', 1, N'2037265481', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1989-11-13' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:44:25.980' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (19, 2, N'E00006', N'Mr.', N'Muhamad Sofyan', N'محمد سفيان ', N'M', CAST(N'1959-09-15' AS Date), N'M', N'ID', 1, N'2056527043', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1988-12-03' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:35:19.347' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (20, 2, N'E00007', N'Ms.', N'Latifa Jamal  ', N'لطيفة ', N'F', CAST(N'1960-03-13' AS Date), N'M', N'ID', 1, N'2056526862', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1988-12-03' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-15T09:43:36.063' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (21, 2, N'E00064', N'Ms.', N'Fatma Al Zoghbi', N'فاطمة الزغبي', N'F', CAST(N'1965-09-17' AS Date), N'M', N'EG', 1, N'2066284510', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'1998-11-12' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-24T13:47:28.060' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (22, 2, N'E00226', N'Ms.', N'Shehana Abd Karem', N'شهينا عبدالكريم', N'F', CAST(N'1982-04-15' AS Date), N'M', N'IN', 1, N'2228116790', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2006-07-20' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-07T10:46:51.827' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (23, 2, N'E00232', N'Ms.', N'Khadijah Hamad', N'خديجة حمد', N'F', CAST(N'1981-07-03' AS Date), N'M', N'SA', 1, N'1000372779', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2007-02-22' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-03-11T13:06:34.453' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (24, 2, N'E00278', N'Ms.', N'Salwa Marwan Arkoubis', N'سلوى اركوبي', N'F', CAST(N'1968-12-20' AS Date), N'M', N'SA', 1, N'1016268102', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2011-06-01' AS Date), CAST(N'2020-03-31' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2019-01-06T17:44:22.860' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (25, 2, N'E00313', N'Mr.', N'Rolando Gatbunton', N'رولاند جاتبونتون', N'M', CAST(N'1969-10-12' AS Date), N'M', N'PH', 2, N'2179885161', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-12' AS Date), CAST(N'2020-04-08' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-15T11:01:03.150' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (26, 2, N'E00316', N'Ms.', N'Jocelyn P. Gonzales', N'جوسلين ', N'F', CAST(N'1970-10-27' AS Date), N' ', N'PH', 2, N'2231950763', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-27' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:43:40.650' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (27, 2, N'E00317', N'Ms.', N'Elmalou P. Yap', N'إلمالو ', N'F', CAST(N'1965-05-08' AS Date), N'M', N'PH', 2, N'2212350561', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-28' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-10-01T10:44:48.960' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (28, 2, N'E00318', N'Mr.', N'Villy Manalang', N'فيلي مانالانج', N'M', CAST(N'1971-11-29' AS Date), N'M', N'PH', 4, N'2181004413', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-26' AS Date), CAST(N'2020-03-10' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-08-09T12:34:12.630' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (29, 2, N'E00319', N'Ms.', N'Ma. Teresa E. Escalante', N'ماريا سكالانتي', N'F', CAST(N'1977-05-07' AS Date), N' ', N'PH', 2, N'2195328311', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-27' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-05-05T13:55:55.070' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (30, 2, N'E00321', N'Ms.', N'Marrian C. Yabut', N'ماريان كارلوس', N'F', CAST(N'1976-03-05' AS Date), N'M', N'PH', 2, N'2227433816', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-27' AS Date), CAST(N'2020-03-31' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-08-09T12:35:03.263' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (31, 2, N'E00322', N'Ms.', N'Emma Rose C. Aguilar', N'إما روس ', N'F', CAST(N'1976-08-27' AS Date), N'S', N'PH', 2, N'2212348391', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-20' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-05-05T13:55:21.323' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (32, 2, N'E00323', N'Ms.', N'Noven L. Bautista', N'نوفن باوتيستا', N'F', CAST(N'1979-11-14' AS Date), N'S', N'PH', 2, N'2212347187', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-20' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-09T12:34:43.923' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (33, 2, N'E00324', N'Mr.', N'Johnson B. Cera', N'جونسن سيرا', N'M', CAST(N'1974-05-30' AS Date), N' ', N'PH', 2, N'2208964086', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-06-27' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-09T12:34:27.903' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (34, 2, N'E00325', N'Ms.', N'Ma. LeoAnn Q Laranja', N'ماريا ليوان ', N'F', CAST(N'2016-11-27' AS Date), N'M', N'PH', 1, N'2227433709', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-11-27' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-05-05T13:56:09.293' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (35, 2, N'E00328', N'Ms.', N'Erlinda L. Ople', N'إيرلندا ', N'F', CAST(N'1948-06-29' AS Date), N'S', N'PH', 2, N'2031436294', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-10-23' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:47:56.067' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (36, 2, N'E00330', N'Ms.', N'Sittie Faida H. Taribul', N'سيتي', N'F', CAST(N'1983-08-09' AS Date), N'M', N'PH', 1, N'2234128110', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-10-25' AS Date), CAST(N'2020-04-08' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-14T22:48:17.610' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (37, 2, N'E00331', N'Mr.', N'Taramiah Anwarhossain', N'تارمياه انورحسين', N'M', CAST(N'1958-07-15' AS Date), N'M', N'BG', 1, N'2027033451', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2010-12-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-02-28T13:56:30.627' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (38, 2, N'E00340', N'Mr.', N'Shihabudeen Kunjumon ', N'شهاب الدين ', N'M', CAST(N'1983-06-30' AS Date), N'M', N'IN', 1, N'2299965950', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2011-01-20' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-13T13:17:35.900' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (39, 2, N'E00344', N'Mr.', N'Ahmed Raafat ', N'أحمد رأفت ', N'M', CAST(N'1984-10-25' AS Date), N' ', N'EG', 1, N'2300769425', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-03-10' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-10-01T13:43:59.757' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (40, 2, N'E00350', N'Dr.', N'Mohammad Fetyani', N'محمد فتياني', N'M', CAST(N'1993-06-16' AS Date), N'S', N'SA', 1, N'1091411296', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2011-06-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-06T17:54:19.843' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (41, 2, N'E00351', N'Dr.', N'Dina Fetyani', N'دينا فتياني', N'F', CAST(N'1987-11-05' AS Date), N' ', N'SA', 1, N'1049009259', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2011-06-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-24T13:58:01.910' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (42, 2, N'E00010', N'Mr.', N'Arnel A. T. Marcelo', N'أرنيل مارسيلو', N'M', CAST(N'1964-12-14' AS Date), N'M', N'PH', 2, N'2095969933', N'Kamil Azhar St.', N'AL-Rehab', N'Jeddah', N'Makkah', N'PH', N'4791', N'21412', N'0552195654', N'012-6746394', N'arnel@ibnsinajed.com', 28, NULL, CAST(N'1994-02-06' AS Date), CAST(N'2019-08-20' AS Date), NULL, 1, N'1234564890', N'81234564566666', N'System Analyst', 500.0000, 3000.0000, 1, CAST(N'2019-03-02T22:07:11.787' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (43, 2, N'E00370', N'Mr.', N'Allan G. Araya', N'ألان جي اريا', N'M', CAST(N'1974-10-27' AS Date), N'M', N'PH', 2, N'2354029049', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2012-11-03' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-09T20:34:31.483' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (44, 2, N'E00372', N'Mr.', N'Noman Imtiaz Imtiaz Ahmed', N'نعمان إمتياز', N'M', CAST(N'1989-11-06' AS Date), N'M', N'IN', 1, N'2321738466', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2012-12-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:50:44.103' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (45, 2, N'E00378', N'Mr.', N'Abdulrahman Fetyani', N'عبدالرحمن فتياني', NULL, CAST(N'1993-06-16' AS Date), NULL, N'SA', 1, N'1091411288', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2013-04-01' AS Date), CAST(N'2019-10-31' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-08-01T11:26:29.263' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (46, 2, N'E00381', N'Mr.', N'Shiyad Prayil ', N'زياد ', N'M', CAST(N'1982-05-11' AS Date), N'M', N'IN', 3, N'2345056960', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2013-05-16' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-09T12:27:00.167' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (47, 2, N'E00386', N'Ms.', N'Liyanah Al Thalabi', N'ليان ثعلبي', N'F', CAST(N'1991-02-26' AS Date), N'S', N'SA', 1, N'1085235719', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2013-06-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-11-17T12:13:03.157' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (48, 2, N'E00389', N'Mr.', N'Sultan Mousa Hassan Alharbi', N'سلطان الحربي', N'M', CAST(N'1991-05-28' AS Date), N'S', N'SA', 1, N'1073017541', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2013-06-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-14T22:53:27.063' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (49, 2, N'E00402', N'Ms.', N'Reham Zamil Jamil Arab', N'ريهام عرب', N'F', CAST(N'1997-12-30' AS Date), N'M', N'SA', 1, N'1061257570', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2014-05-10' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-03-11T13:07:37.697' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (50, 2, N'E00410', N'Ms.', N'Doaa Gobashy', N'دعاء غباش', N'F', CAST(N'1979-09-17' AS Date), N'S', N'EG', 1, N'2299050795', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-01-19' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-09T19:40:20.443' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (51, 2, N'E00411', N'Mr.', N'Muhammed Abdulnasar ', N'محمد عبدالناصر', N'M', CAST(N'1972-02-15' AS Date), N'M', N'IN', 1, N'2158029294', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-01-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-10-02T10:21:18.397' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (52, 2, N'E00412', N'Dr.', N'Rawan Bin Hammam', N'روان بن همام', N'F', CAST(N'1982-06-03' AS Date), N'M', N'YE', 1, N'2046253635', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-07-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-24T13:39:22.390' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (53, 2, N'E00427', N'Ms.', N'Doaa Basha', N'دعاء باشا', N'F', CAST(N'1989-09-15' AS Date), N'S', N'YE', 1, N'2051647879', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-11-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-07T11:28:46.300' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (54, 2, N'E00429', N'Ms.', N'Afaf Al-ghamdy', N'عفاف الغامدي', N'F', CAST(N'2016-11-24' AS Date), N' ', N'SA', 1, N'1097218471', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-11-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-06T18:04:49.550' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (55, 2, N'E00433', N'Mr.', N'Abdulellah Qasar', N'عبدالله كسار', N'M', CAST(N'1992-11-12' AS Date), NULL, N'ET', NULL, N'1079434492', N's', NULL, NULL, NULL, N'SA', NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-11-02' AS Date), CAST(N'2019-08-20' AS Date), 208, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-14T22:58:52.693' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (56, 2, N'E00436', N'Ms.', N'Sharifa Alyami', N'شريفة اليامي', N'F', CAST(N'1990-05-17' AS Date), N'S', N'SA', 1, N'1046594022', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-01-10' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-13T21:11:54.847' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (57, 2, N'E00438', N'Ms.', N'Basma Al-Harby', N'بسمة الحربي', N'F', CAST(N'1984-10-01' AS Date), N' ', N'SA', 1, N'1074136175', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-03-23' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-02-28T13:33:46.947' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (58, 2, N'E00440', N'Mr.', N'Ebrahim Ali', N'ابراهيم علي', N'M', CAST(N'1997-10-19' AS Date), N' ', N'SA', 1, N'1094058086', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-05-28' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-06T18:07:56.337' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (59, 2, N'E00441', N'Ms.', N'Hala Fetyani', N'هلا  مروان فتياني', N'F', CAST(N'2003-10-21' AS Date), N'S', N'SA', 1, N'1124158906', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-01-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-07T20:08:42.660' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (60, 2, N'E00447', N'Ms.', N'Reem Mohamad', N'ريم محمد', N'F', CAST(N'2016-11-27' AS Date), N'M', N'SA', 1, N'1115445833', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-08-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-02-28T13:42:02.973' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (61, 2, N'E00448', N'Ms.', N'Fadwa Al Jehani', N'فدوى الجهني', N'F', CAST(N'2016-11-27' AS Date), N'M', N'SA', 1, N'1061630321', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-08-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-06T20:34:50.767' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (62, 2, N'E00449', N'Mr.', N'Jamsher Mohamed', N'جمشير محمد', N'M', CAST(N'2016-11-27' AS Date), N'M', N'IN', 1, N'2396576775', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-08-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-10-01T10:54:32.663' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (63, 2, N'E00452', N'Mr.', N'Shahjan Konhi4', N'شهجاهان كوني', N'M', CAST(N'2016-11-27' AS Date), N'M', N'IN', 1, N'2415052618', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-09-01' AS Date), CAST(N'2020-04-08' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-08-07T19:24:15.863' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (64, 2, N'E00453', N'Mr.', N'Abdullah Amer', N'عبدالله عامر', N'M', CAST(N'2016-11-24' AS Date), N'S', N'SO', 1, N'2040280832', NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'22222222', NULL, NULL, 28, NULL, CAST(N'2016-09-01' AS Date), CAST(N'2019-08-20' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-10-01T11:34:41.420' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (65, 2, N'E00492', N'Dr.', N'AREEJ AHMED', N'اريج احمد', N'F', CAST(N'2018-08-29' AS Date), N'S', N'SA', 1, N'1076564176', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2018-08-01' AS Date), CAST(N'2020-03-17' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2019-01-06T18:15:10.607' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (66, 2, N'E00396', N'Mrs.', N'NAYLA MARHOUM', N'نائلة ماجارانج ', N'F', CAST(N'2018-12-11' AS Date), N'M', N'SA', 1, N'1129841845', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2018-12-11' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-03-28T11:07:27.467' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (67, 2, N'E00457', N'Ms.', N'Faten Ahmad', N'فاتن أحمد ', N'F', CAST(N'2017-06-08' AS Date), N'M', N'SA', 1, N'2040135713', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-10-30' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-03-11T13:10:52.980' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (68, 2, N'E00463', N'Ms.', N'Rana Basharaheel', N'رنا باشراحيل', N'F', CAST(N'2017-06-08' AS Date), N'S', N'SA', 1, N'1053737134', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2017-04-01' AS Date), CAST(N'2020-04-08' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2019-02-28T13:24:00.823' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (69, 2, N'E00487', N'Mr.', N'Asif Hussain', N'أسف حسين', N'M', CAST(N'1992-06-15' AS Date), N'S', N'IN', 1, N'2401434929', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2017-12-21' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-15T13:50:32.337' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (70, 2, N'E00459', N'Dr.', N'Dr. Azza Ezzat', N'عزه عزت', N'M', CAST(N'1962-03-22' AS Date), N'M', N'EG', 1, N'2316078647', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-11-24' AS Date), CAST(N'2020-03-31' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2018-07-15T13:12:16.150' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (71, 2, N'E00467', N'Ms.', N'Lina Basharaheel', N'لينا باشراحيل', N'F', CAST(N'1993-12-02' AS Date), N'S', N'SA', 1, N'1084314267', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2017-04-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-01-06T20:36:01.447' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (72, 2, N'E00466', N'Mr.', N'Muneer Hussain', N'منير حسين ', N'M', CAST(N'2018-02-22' AS Date), N'S', N'PA', 1, N'2424141766', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2018-02-22' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-10-13T20:33:00.920' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (73, 2, N'E00489', N'Mr.', N'Hassan Bukhari', N'حسان بخاري', N'M', CAST(N'2018-05-14' AS Date), N'S', N'SA', 1, N'1084553476', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2018-01-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-02-28T13:20:56.610' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (74, 2, N'E00490', N'Dr.', N'Azza Mustafa', N'عزه مصطفى', N'M', CAST(N'2018-05-14' AS Date), N'M', N'EG', 1, N'2109010252', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2018-01-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-07-15T12:51:17.590' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (75, 2, N'E00494', N'Ms.', N'HANAN AL-ARYANI', N'هنان اازياني', N'F', CAST(N'2019-01-07' AS Date), N'S', N'SA', 1, N'1055082794', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2019-01-07' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-02-28T13:24:41.297' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (76, 2, N'E00495', N'Dr.', N'MAHMOUD KHALIFA', N'محمود خليفة', N'M', CAST(N'2019-02-11' AS Date), N'M', N'EG', 1, N'2255526838', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2019-02-11' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-03-02T10:44:46.570' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (77, 2, N'E00397', N'Ms.', N'Amani Al-Sheikh', N'أماني صالح', N'F', CAST(N'2019-04-24' AS Date), N'M', N'SA', 1, N'1103234967', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2019-04-24' AS Date), CAST(N'2020-03-31' AS Date), NULL, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2019-06-26T18:57:11.920' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (78, 2, N'E00497', N'Mrs.', N'NISHMA ERIKUNNAN', N'', N'F', CAST(N'1989-07-05' AS Date), N'M', N'IN', 1, N'3040737300', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2019-06-16' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-06-26T13:16:59.997' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (79, 2, N'E00456', N'Ms.', N'Thanaa Al Jabarti', N'ثناء الجبرتي', N'M', CAST(N'2017-06-08' AS Date), N'S', N'SA', 1, N'1080364217', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2016-11-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-02-28T13:23:06.377' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (80, 2, N'E00461', N'Mr.', N'Naif Al-Harthi', N'نايف الحارثي', N'M', CAST(N'2017-06-08' AS Date), N'M', N'SA', 1, N'1005247380', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2017-03-12' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2018-08-09T13:07:49.397' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (81, 2, N'E00491', N'Mr.', N'Emad Al Zahrany', N'عماد الزهراني', N'M', CAST(N'2018-05-14' AS Date), N'S', N'SA', 1, N'1079948962', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2018-04-01' AS Date), NULL, NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, CAST(N'2019-03-26T21:11:02.690' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (82, 2, N'E00496', N'Mrs.', N'VINIBA KOONERI', N'VINIBA KOONERI', N'F', CAST(N'1995-06-27' AS Date), N'S', N'IN', 1, N'3040737318', NULL, NULL, NULL, NULL, N'NU', NULL, N'2', NULL, NULL, NULL, 28, 2, CAST(N'2019-06-16' AS Date), CAST(N'2020-04-04' AS Date), 535, 1, NULL, NULL, NULL, 0.0000, 0.0000, 0, CAST(N'2019-06-26T13:16:36.340' AS DateTime))
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (83, NULL, N'E00433', N'Mr.', N'Abdulellah Qasar 3', N'عبدالله كسار', N'M', CAST(N'1992-11-12' AS Date), NULL, NULL, NULL, N'1079434492', N's', NULL, NULL, NULL, N'SA', NULL, NULL, NULL, NULL, NULL, 28, NULL, CAST(N'2015-11-02' AS Date), CAST(N'2019-08-20' AS Date), 208, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, NULL)
GO
INSERT [dbo].[Employee] ([IdNo], [BranchID], [EmployeeCode], [Title], [EmployeeName], [EmployeeNameAra], [Gender], [BirthDate], [MaritalStatus], [NationalityCode], [ReligionIdNo], [NationalIdNo], [Street], [District], [TownCity], [ProvinceState], [CountryCode], [PoBox], [ZipCode], [Phone1], [Phone2], [Email], [DepartmentIdNo], [DesignationIdNo], [HiredDate], [ReleasedDate], [ArAccountIdNo], [BankIdNo], [BankAccountNo], [IBAN], [Notes], [OpeningBalance], [Balance], [Active], [Create_Date]) VALUES (100, NULL, N'E00450', NULL, N'Wafaa Al-Zuhairy', N'Wafaa Al-Zuhairy', NULL, CAST(N'2020-04-28' AS Date), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(N'2020-04-28' AS Date), CAST(N'2020-04-28' AS Date), 114, NULL, NULL, NULL, NULL, 0.0000, 0.0000, 0, NULL)
GO
SET IDENTITY_INSERT [dbo].[Employee] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_EmployeeName]    Script Date: 4/29/2020 12:03:20 AM ******/
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [IX_EmployeeName] UNIQUE NONCLUSTERED 
(
	[EmployeeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
