	select 
--	case when (e.DeptID = '' or e.DeptID is null) then case when n.serviceID is null then d.deptID else n.DepartmentID else e.DeptID end end as DepartmentID,
--	e.DeptID as DepartmentID	,
	c.Age				,
	c.AgeYMD			,
	a.ReferenceNo as ApprovalNo,
	a.BillAmt       		,
	a.BillType 			,
	a.BranchID         	,
	a.CreditCardExpiry,
	a.CreditCardID,
	a.CreditCardNo,
	a.DeductibleAmt 		,
	a.DeductibleDiscountAmt		,
	a.DoctorID 			,
	a.ExtraDiscountAmt    		,
	a.ExtraDiscountPercent 		,
	a.InsuranceGroupID  		,
	a.InsuranceID 			,
	a.InsuranceNameEnglish         	,
	a.MachineID	,
	a.NormalDiscountAmt 		,
	a.PreviousBalanceAmt 		,
	a.RegistrationNo       		,
	a.RegistrationType		,
	a.Reject			,
	a.RejectDate			,
	a.Remarks               	,
	a.RoundOffAmt      		,
	a.TokenNo			,
	a.trans_key    			,
	a.TransDateEnglish		,
	a.TransDateHijri		,
	a.TransNBR     			,
	a.TransType 			,
	a.UserID 			,
	a.VATAmt as TotalVATAmt,
	a.VATExemption, 
	b.CostPricePerUnit		,
	b.RowNbr			,
	b.SaleStatus			,
	b.SaleType			,
	b.ServiceID			,
	c.Address1			,
	c.Address2			,
	c.City				,
	c.InsCardNo	           	,
	c.InsSoapCode   		,
	c.InsSoapNo 			,
	c.IqamaNo			,
	c.Mobile			,
	c.PatientNameArabic	,
	c.PatientNameEnglish	,
	c.PhoneO			,
	c.PhoneR			,
	c.RegistrationDate		,
	c.series			,
	c.Sex				,
	case when (d.DepartmentID = 'INJ' and a.InsuranceID = '') or (d.DepartmentID = 'VAC' and a.insuranceID = '') then 'Y' else 'N' end as PrintDept,
	case when (n.serviceID is null or d.ServiceNameArabic is null or d.ServiceNameArabic = '') then d.ServiceNameEnglish else d.ServiceNameArabic  end as ServiceNameArabic,
	case when b.CostPrice is null then 0 else b.costPrice end as CostPrice,
	case when b.deductibleper is null then 0 else b.DeductiblePer end as DeductiblePer,
	case when b.DiscountAmt	is null then 0 else b.DiscountAmt end as DiscountAmt,
	case when b.DiscountPer is null then 0 else b.DiscountPer end as DiscountPer,
	case when b.qty is null then 1 else b.Qty	end as Qty,
	case when b.SalePrice is null then 0 else b.SalePrice end as SalePrice,
	case when b.VATAmt   is null then 0 else b.VATAmt  end as VATAmt,
	case when b.VATPercent  is null then 0 else b.VATPercent  end as VATPercent,
	case when n.serviceID is null then d.ServiceNameEnglish else n.ServiceNameEnglish end as ServiceNameEnglish	,
	CONVERT(datetime,a.Create_Date) as Create_date,
    d.DepartmentID,
	DBO.currency_conversion(a.BillAmt) as AmtWordArabic
	e.EmpNameArabic 		,
	e.EmpNameEnglish		,
	e.OPDFloor			,
	e.OPDNo				,
	f.CountryNameArabic 	,
	f.CountryNameEng		,
	g.DepartmentNameEnglish		,
	h.GroupInsuranceID		,
	h.NameArabic         	,
	h.UnderInsuranceID		,
	k.NameEnglish as GroupName      ,
	l.NameEnglish as activeInsName	,
	m.NameEnglish as co_ins_company ,
	n.ServiceID	as insServiceID	,
	n.ServiceNameEnglish as InsServiceNameEnglish,