update arjournal set approved = 1 where year(transactiondate) < 2021
update arjournal set approved = 0 where year(transactiondate) = 2021
update apjournal set approved = 1 where year(transactiondate) < 2021
update apjournal set approved = 0 where year(transactiondate) = 2021
update ckjournal set approved = 1 where year(transactiondate) < 2021
update ckjournal set approved = 0 where year(transactiondate) = 2021
update cashreceiptjournal set approved = 1 where year(transactiondate) < 2021
update cashreceiptjournal set approved = 0 where year(transactiondate) = 2021
update cdjournal set approved = 1 where year(transactiondate) < 2021
update cdjournal set approved = 0 where year(transactiondate) = 2021
update cdjournal set approved = 1 where year(transactiondate) < 2021
update cdjournal set approved = 0 where year(transactiondate) = 2021
update pcjournal set approved = 1 where year(transactiondate) < 2021
update pcjournal set approved = 0 where year(transactiondate) = 2021
update cdjournal set approved = 1 where year(transactiondate) < 2021
update cdjournal set approved = 0 where year(transactiondate) = 2021
update purchaseJournal set approved = 1 where year(transactiondate) < 2021
update purchaseJournal set approved = 0 where year(transactiondate) = 2021
update salesjournal set approved = 1 where year(transactiondate) < 2021
update salesjournal set approved = 0 where year(transactiondate) = 2021
update generaljournal set approved = 1 where year(transactiondate) < 2021
update generaljournal set approved = 0 where year(transactiondate) = 2021
