CREATE VIEW InsuranceReport_View
 
AS
select
	a.BranchID,
	a.SeqNo,
	a.InsCardNo,
	a.RegistrationNo,
	a.PatientNameEnglish,
	a.TransNBR,
	a.TransDAteEnglish,
	a.ApprovalNo,
	a.ICD10,
	a.Diagnosis1,
	a.Diagnosis2,
	a.Diagnosis3,
	a.ClinicalData,
	a.ClaimType,
	case when g.AltServiceID is null then a.ServiceID else g.AltServiceID end as ServiceID,
	case when g.AltServiceID is null then a.ServiceDescription else g.AltServiceNameEnglish end as ServiceDescription,
	a.Qty,
	a.Amount,
	a.Qty * a.Amount as Gross,
	a.Discount,
	(a.Qty * a.Amount) - a.Discount as ADiscount,
	0 as DeductiblePer,
	a.Deductible,
	(a.Qty * a.Amount) - (a.Discount+a.Deductible) as net,
	a.DoctorID,
	a.DoctorNameEnglish,
	a.Policy,
	a.InsCoCode,
	a.InsuranceID,
	a.UnderInsCoCode,
	a.TrType,
	b.DepartmentID,
	c.NameEnglish
From InsuranceAlteredData a
left outer join InsuranceServicePriceList b on a.ServiceID = b.ServiceID and a.InsuranceID = b.InsuranceID
left outer join InsuranceDetails c on a.InsCoCode = c.InsuranceID
left outer join InsuranceAltServicePriceList g on g.ServiceID = a.ServiceID and g.InsuranceID = a.InsuranceID
where TrType = 'Clinic'
union All
select
	a.BranchID,
	a.SeqNo,
	a.InsCardNo,
	a.RegistrationNo,
	a.PatientNameEnglish,
	a.TransNBR,
	a.TransDAteEnglish,
	a.ApprovalNo,
	a.ICD10,
	a.Diagnosis1,
	a.Diagnosis2,
	a.Diagnosis3,
	a.ClinicalData,
	a.ClaimType,
	'MED' as ServiceID,
	'Pharmacy Bill' as ServiceNameEnglish,
	1 as Qty,
	0 as Amount,
	sum(a.qty * a.Amount)  as Gross,
	sum(a.Discount) as Discount,
	sum((a.Qty*a.Amount) - a.Discount) as ADiscount,
	0 as DeductiblePer,
	sum(a.Deductible) as Deductible,
	sum((a.Qty*a.Amount) - (a.Discount + a.Deductible)) as net,
	a.DoctorID,
	a.DoctorNameEnglish,
	a.Policy,
	a.InsCoCode,
	a.InsuranceID,
	a.UnderInsCoCode,
	a.TrType,
	'PHR' as DepartmentID,
	c.NameEnglish
From InsuranceAlteredData a
left outer join InsuranceDetails c on a.InsCoCode = c.InsuranceID 
where TrType = 'Pharmacy'
Group By
	a.BranchID,
	a.SeqNo,
	a.InsCardNo,
	a.RegistrationNo,
	a.PatientNameEnglish,
	a.TransNBR,
	a.TransDAteEnglish,
	a.ApprovalNo,
	a.ICD10,
	a.Diagnosis1,
	a.Diagnosis2,
	a.Diagnosis3,
	a.ClinicalData,
	a.ClaimType,
	a.DoctorID,
	a.DoctorNameEnglish,
	a.Policy,
	a.InsCoCode,
	a.InsuranceID,
	a.UnderInsCoCode,
	a.TrType,
	c.NameEnglish,
	a.amount