
CREATE VIEW PMRPatientProfile_View
 
AS
	SELECT a.Trans_key,
	'1' as appearanceorder,
	a.TransType,
	a.transdateenglish,
	a.PatientType,
	a.BillType,
	a.Series,
	a.RegistrationNo,
	e.PatientNameEnglish as PatientName,
	e.Age,
	e.Sex,
	e.AgeYMD,
	e.IqamaNo as ID_No,
	a.TokenNo,
	a.InsuranceID,
	a.InsuranceGroupID,
	a.DoctorID,
	f.EmpNameEnglish as DoctorNameEnglish,
	f.DeptID  as DepartmentID,
	h.DepartmentNameEnglish  as DepartmentNameEnglish,
	a.bp,
	a.breathing,
	a.Temprature,
	a.PulseRate,
	a.respiratory,
	a.VisitNo,
	a.VisitType,
	a.durationofillness,
	a.DurationYMD,
	a.admissiontype,
	a.fixedalergies,
	a.drugalergies,
	a.otheralergies,
	a.chiefcomplaint,
	a.notealergies,
	a.DoctorRemark as notespl,
	'' as noteother,
	a.significantsign,
	a.othercondition,
	a.diagnosis,
	a.dx_code1,
	a.dx_code2,
	a.dx_code3,
	a.dx_code4,
	'10' as icd_type,
	a.medicationnote,
	a.illnesstype,
	a.lmp,
	a.cmf,
	a.cmfNote,
	a.los,
	a.eda,
	a.userid,
	host_name() as machineid,
	a.create_date,
	b.rownbr,
	b.Altitem_code as Item_Code,
	b.qty,
	b.unit,
	b.saleprice,
	b.discountper,
	b.discountamt,
	b.billamt as netamt,
	b.AltItemNameEnglish as ItemNameEnglish,
	b.AltItemNameArabic as ItemNameArabic,
	'' as DosageEnglish,
	'' as DosageArabic,
	'0' as duration,
	e.countryiota,
	g.countrynameeng,
	c.DocumentInfo as DocumentInfo1,
	d.DocumentInfo as DocumentInfo2,
	i.NameEnglish as InsuranceNameEnglish,
	a.DoctorRemark  
from 		PMRPatientGeneralInfo 			a	
left outer join PMRInvestigationTreatment_View 	b on a.trans_key=b.trans_key 
left outer join PatientImagesDatabase..PatientScannedDocuments c on a.PatientType  collate database_default = c.PatientType  collate database_default AND a.RegistrationNo = c.RegistrationNo AND c.DocumentID = '002'
left outer join PatientImagesDatabase..PatientScannedDocuments d on a.PatientType  collate database_default = d.PatientType  collate database_default AND a.RegistrationNo = d.RegistrationNo AND d.DocumentID = '001'
left outer join PatientDetails e on a.RegistrationNo = e.RegistrationNo and a.Series = e.Series 
left outer join EmployeeDetails f on a.DoctorID = f.EMPID
left outer join CountryMaster g on e.countryiota = g.countryiota
left outer join MedicalDepartments h on f.DeptID = h.DepartmentID 
left outer join InsuranceDetails i on e.InsCoCode = i.InsuranceID 
union all
	SELECT a.Trans_key,
	'2' as appearanceorder,
	a.TransType,
	a.transdateenglish,
	a.PatientType,
	a.BillType,
	a.Series,
	a.RegistrationNo,
	e.PatientNameEnglish as PatientName,
	e.Age,
	e.Sex,
	e.AgeYMD,
	e.IqamaNo as ID_No,
	a.TokenNo,
	a.InsuranceID,
	a.InsuranceGroupID,
	a.DoctorID,
	f.EmpNameEnglish as DoctorNameEnglish,
	f.DeptID  as DepartmentID,
	h.DepartmentNameEnglish  as DepartmentNameEnglish,
	a.bp,
	a.breathing,
	a.Temprature,
	a.PulseRate,
	a.respiratory,
	a.VisitNo,
	a.VisitType,
	a.durationofillness,
	a.DurationYMD,
	a.admissiontype,
	a.fixedalergies,
	a.drugalergies,
	a.otheralergies,
	a.chiefcomplaint,
	a.notealergies,
	a.DoctorRemark as notespl,
	'' as noteother,
	a.significantsign,
	a.othercondition,
	a.diagnosis,
	a.dx_code1,
	a.dx_code2,
	a.dx_code3,
	a.dx_code4,
	'10' as icd_type,
	a.medicationnote,
	a.illnesstype,
	a.lmp,
	a.cmf,
	a.cmfNote,
	a.los,
	a.eda,
	a.userid,
	host_name() as machineid,
	a.create_date,
	b.rownbr,
	b.item_code,
	b.qty,
	b.unit,
	b.saleprice,
	b.discountper,
	b.discountamt,
	b.billamt as netamt,
	b.ItemNameEnglish,
	b.ItemNameArabic,
	'' as DosageEnglish,
	'' as DosageArabic,
	b.duration as duration,
	e.countryiota,
	g.countrynameeng,
	c.DocumentInfo as DocumentInfo1,
	d.DocumentInfo as DocumentInfo2,
	i.NameEnglish as InsuranceNameEnglish ,
	a.DoctorRemark  
from 	PMRPatientGeneralInfo 		a	
left outer join PMRMedicineDetails_View 	b on a.trans_key=b.trans_key 
left outer join PatientImagesDatabase..PatientScannedDocuments c on a.PatientType collate database_default = c.PatientType  collate database_default AND a.RegistrationNo = c.RegistrationNo AND c.DocumentID = '002'
left outer join PatientImagesDatabase..PatientScannedDocuments d on a.PatientType  collate database_default = d.PatientType  collate database_default AND a.RegistrationNo = d.RegistrationNo AND d.DocumentID = '001'
left outer join PatientDetails e on a.RegistrationNo = e.RegistrationNo and a.Series = e.Series 
left outer join EmployeeDetails f on a.DoctorID = f.EMPID
left outer join CountryMaster g on e.countryiota = g.countryiota
left outer join MedicalDepartments h on f.DeptID = h.DepartmentID 
left outer join InsuranceDetails i on e.InsCoCode = i.InsuranceID 
union all
	SELECT a.Trans_key,
	'3' as appearanceorder,
	a.TransType,
	a.transdateenglish,
	a.PatientType,
	a.BillType,
	a.Series,
	a.RegistrationNo,
	e.PatientNameEnglish as PatientName,
	e.Age,
	e.Sex,
	e.AgeYMD,
	e.IqamaNo as ID_No,
	a.TokenNo,
	a.InsuranceID,
	a.InsuranceGroupID,
	a.DoctorID,
	f.EmpNameEnglish as DoctorNameEnglish,
	f.DeptID  as DepartmentID,
	h.DepartmentNameEnglish  as DepartmentNameEnglish,
	a.bp,
	a.breathing,
	a.Temprature,
	a.PulseRate,
	a.respiratory,
	a.VisitNo,
	a.VisitType,
	a.durationofillness,
	a.DurationYMD,
	a.admissiontype,
	a.fixedalergies,
	a.drugalergies,
	a.otheralergies,
	a.chiefcomplaint,
	a.notealergies,
	a.DoctorRemark as notespl,
	'' as noteother,
	a.significantsign,
	a.othercondition,
	a.diagnosis,
	a.dx_code1,
	a.dx_code2,
	a.dx_code3,
	a.dx_code4,
	'10' as icd_type,
	a.medicationnote,
	a.illnesstype,
	a.lmp,
	a.cmf,
	a.cmfNote,
	a.los,
	a.eda,
	a.userid,
	host_name() as machineid,
	a.create_date,
	b.RowNBR,
	'Tooth # '+b.ToothNBR as item_code,
	1 as qty,
	'' as unit,
	0 as saleprice,
	0 as discountper,
	0 as discountamt,
	0 as netamt,
	'Surface :'+b.ToothSurface  as ItemNameEnglish,
	'' as ItemNameArabic,
	'' as DosageEnglish,
	'' as DosageArabic,
	'' as duration,
	e.countryiota,
	g.countrynameeng,
	c.DocumentInfo as DocumentInfo1,
	d.DocumentInfo as DocumnetInfo2,
	i.NameEnglish as InsuranceNameEnglish ,
	a.DoctorRemark  
from 	PMRPatientGeneralInfo 		a	
left outer join PMRDentalTeethDescription 	b on a.trans_key=b.trans_key 
left outer join PatientImagesDatabase..PatientScannedDocuments c on a.PatientType  collate database_default = c.PatientType  collate database_default AND a.RegistrationNo = c.RegistrationNo AND c.DocumentID = '002'
left outer join PatientImagesDatabase..PatientScannedDocuments d on a.PatientType  collate database_default = d.PatientType  collate database_default AND a.RegistrationNo = d.RegistrationNo AND d.DocumentID = '001'
left outer join PatientDetails e on a.RegistrationNo = e.RegistrationNo and a.Series = e.Series 
left outer join EmployeeDetails f on a.DoctorID = f.EMPID
left outer join CountryMaster g on e.countryiota = g.countryiota
left outer join MedicalDepartments h on f.DeptID = h.DepartmentID 
left outer join InsuranceDetails i on e.InsCoCode = i.InsuranceID