
CREATE VIEW 	PurchaseHostoryBySupplier_View
 
AS
SELECT  a.Trans_Key,
	a.BranchID,
	a.TransType,
	a.TransSeries,
	a.TransNo,
	a.TransDate,
	a.HijriDate,
	a.PONo,
	a.PODate,
	a.WarehouseID,
	a.PurchaseType,
	a.PurchaseFrom,
	a.SupplierID,
	a.InvoiceNo,
	a.InvoiceDate,
	a.Reference,
	a.InvoiceAmt,
	a.CurrencyCode,
	a.ConversionRate,
	a.GrossAmt,
	a.TotalExpenses,
	a.SpecialDiscountPer,
	a.SpecialDiscountAmt,
	a.SalesmanID,
	a.Remarks,
	a.PostInAccounts,
	a.PostInStock,
	a.AccountsUpdate,
	a.PurchaseGrossAmt,
	a.PurchaseCostAmt,
	a.PurchaseSaleAmt,
	a.PurchaseProfitPer,
	a.PurchaseProfitAmt,
	a.EnteredBy,
	a.CheckedBy,
	a.ApprovedBy,
	a.UserID,
       	a.Create_Date,
	a.MachineID,
	d.SupplierNameEnglish,
	e.WarehouseNameEnglish
From PurchaseGroup A
LEFT OUTER JOIN SupplierDetails D ON A.SupplierID = D.SupplierID 
LEFT OUTER JOIN WarehouseDetails E ON A.WarehouseID = E.WarehouseID and A.BranchID = e.BranchID