CREATE VIEW WSL_CLAIM_DIAGNOSIS_View
 
AS
SELECT 
	A.TRANSDATEENGLISH,
	A.INSURANCEID,
	A.TRANSNBR,
	RIGHT('0000000'+RTRIM(CONVERT(varchar(7),A.REGISTRATIONNO)),6)+
        REPLACE(A.TRANSDATEENGLISH,'/','')+
        RIGHT('00'+A.DOCTORID,2)as 	[PROVCLAIMNO],
	A.ICD10 AS DIAGNOSISCODE,
	B.ICD_DESCRIPTION AS DIAGNOSISDESC
FROM [INSURANCEALTEREDDATA] A
LEFT OUTER JOIN ICD10_MASTER B ON A.ICD10 = B.ICD_CODE