CREATE VIEW WSL_SERVICE_DETAILS_View
 
AS
SELECT 	A.INSURANCEID,
	A.TRANSNBR AS INVOICENO,
	A.SERVICEID AS SERVICECODE,
	A.TRANSDATEENGLISH AS SERVICEDATE,
	A.SERVICEDESCRIPTION AS SERVICEDESC,
	A.AMOUNT AS UNITSERVICEPRICE,
	'N/A' AS UNITSERVICETYPE,
	A.QTY,
	'' AS TOOTHNO,
	A.QTY*A.AMOUNT AS TOTSERVICEGRSAMT,
	A.DISCOUNT AS TOTSERVICEDISC,
	A.DEDUCTIBLE AS TOTSERVICEPATSHARE,
	(A.QTY*A.AMOUNT)- (A.DISCOUNT+A.DEDUCTIBLE) AS TOTSERVICENETAMT
FROM INSURANCEALTEREDDATA A
--LEFT OUTER JOIN SHEET1$ B ON A.TRANSNBR = B.[INVOICE NO]
--WHERE TRANSDATEENGLISH BETWEEN '2015/05/01' AND '2015/05/31' AND INSURANCEID='5004'