<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net48;net8.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Deterministic>true</Deterministic>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<!-- Use Microsoft.Data.SqlClient everywhere -->
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" Condition="'$(TargetFramework)'=='netstandard2.0' or '$(TargetFramework)'=='net8.0'" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" Condition="'$(TargetFramework)'=='net48'" />
		<!-- SNI native dependency is only needed on .NET Framework -->
		<PackageReference Include="Microsoft.Data.SqlClient.SNI" Version="6.0.2" Condition="'$(TargetFramework)'=='net48'" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0-rc.1.25451.107" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Contracts\AATM.Contracts\AATM.Contracts.csproj" />
		<ProjectReference Include="..\AATM.DataAccess\AATM.DataAccess.csproj" />
	</ItemGroup>
</Project>