CREATE TABLE [dbo].[accnew1] (
    [BranchID]              VARCHAR (15)   NULL,
    [ReportID]              VARCHAR (5)    NOT NULL,
    [ReportNo]              NUMERIC (5)    NOT NULL,
    [ReportOrder]           NUMERIC (5)    NULL,
    [ReportFileName]        VARCHAR (75)   NULL,
    [ReportTitleEnglish]    VARCHAR (100)  NULL,
    [ReportTitleArabic]     NVARCHAR (100) NULL,
    [ReportHeadingEnglish1] VARCHAR (75)   NOT NULL,
    [ReportHeadingEnglish2] VARCHAR (75)   NULL,
    [ReportHeadingArabic1]  NVARCHAR (75)  NOT NULL,
    [ReportHeadingArabic2]  NVARCHAR (75)  NULL,
    [QueryColumns]          VARCHAR (1000) NULL,
    [QueryFrom]             VARCHAR (500)  NULL,
    [SQLWhereClause]        VARCHAR (500)  NULL,
    [SQLGroupClause]        VARCHAR (500)  NULL,
    [QueryParameters]       VARCHAR (250)  NULL,
    [SQLOrderByClause]      VARCHAR (250)  NULL,
    [ReportUsedFunction]    VARCHAR (50)   NULL,
    [ReportDescription]     VARCHAR (300)  NULL,
    [ReportTxtParameters]   VARCHAR (500)  NULL,
    [UnionParameters]       VARCHAR (15)   NULL,
    [OtherParameters]       VARCHAR (300)  NULL,
    [doc_type]              CHAR (1)       NULL,
    [UserID]                VARCHAR (15)   NULL,
    [Create_Date]           DATETIME       NULL,
    [MachineID]             VARCHAR (20)   NULL,
    [Active]                CHAR (1)       NULL
);

