CREATE TABLE [dbo].[ChartOfAccounts] (
    [BranchID]         VARCHAR (15)    NOT NULL,
    [AccountID]        VARCHAR (10)    NOT NULL,
    [AcNameEnglish]    VARCHAR (50)    NOT NULL,
    [LedgerNameArabic] NVARCHAR (50)   NULL,
    [ParentID]         VARCHAR (10)    NOT NULL,
    [PrimaryGroupID]   VARCHAR (10)    NULL,
    [LedgerStatus]     BIT             NULL,
    [OpeningBalance]   NUMERIC (12, 2) NULL,
    [ClosingBalance]   NUMERIC (12, 2) NULL,
    [BalanceAmt]       NUMERIC (12, 2) NULL,
    [CreditAmt]        NUMERIC (12, 2) NULL,
    [DebitAmt]         NUMERIC (12, 2) NULL,
    [ThisYearBalance]  NUMERIC (12, 2) NULL,
    [PrevYearBalance]  NUMERIC (12, 2) NULL,
    [ThisQtrBalance]   NUMERIC (12, 2) NULL,
    [PrevQtrBalance]   NUMERIC (12, 2) NULL,
    [LedgerNature]     NUMERIC (1)     NULL,
    [CostCentres]      VARCHAR (15)    NULL,
    [Address]          NTEXT           NULL,
    [City]             VARCHAR (30)    NULL,
    [Phone_Mobile]     VARCHAR (40)    NULL,
    [ContactPerson]    NVARCHAR (40)   NULL,
    [eMail]            VARCHAR (30)    NULL,
    [Remark]           VARCHAR (300)   NULL,
    [UserID]           VARCHAR (15)    NULL,
    [Create_Date]      DATETIME        NULL,
    [MachineID]        VARCHAR (20)    NULL
);

