CREATE TABLE [dbo].[EmployeeNew] (
    [IdNo]            INT           NOT NULL,
    [BranchID]        INT           NULL,
    [EmployeeCode]    VARCHAR (10)  NULL,
    [Title]           VARCHAR (25)  NULL,
    [EmployeeName]    VARCHAR (75)  NOT NULL,
    [EmployeeNameAra] NVARCHAR (75) NULL,
    [Gender]          VARCHAR (1)   NULL,
    [BirthDate]       DATE          NULL,
    [MaritalStatus]   CHAR (1)      NULL,
    [NationalityCode] CHAR (2)      NULL,
    [NationalityId]   VARCHAR (15)  NULL,
    [ReligionIdNo]    INT           NULL,
    [ReligionId]      VARCHAR (15)  NULL,
    [NationalIdNo]    VARCHAR (10)  NULL,
    [Street]          NVARCHAR (50) NULL,
    [District]        NVARCHAR (50) NULL,
    [TownCity]        NVARCHAR (50) NULL,
    [ProvinceState]   NVARCHAR (50) NULL,
    [CountryCode]     CHAR (2)      NULL,
    [PoBox]           VARCHAR (15)  NULL,
    [ZipCode]         VARCHAR (15)  NULL,
    [Phone1]          VARCHAR (15)  NULL,
    [Phone2]          VARCHAR (15)  NULL,
    [Email]           VARCHAR (50)  NULL,
    [DepartmentIdNo]  VARCHAR (15)  NULL,
    [DesignationIdNo] VARCHAR (15)  NULL,
    [HiredDate]       DATE          NULL,
    [ReleasedDate]    DATE          NULL,
    [ArAccountIdNo]   INT           NULL,
    [BankIdNo]        INT           NULL,
    [BankAccountNo]   VARCHAR (15)  NULL,
    [IBAN]            VARCHAR (20)  NULL,
    [Notes]           VARCHAR (300) NULL,
    [OpeningBalance]  MONEY         NULL,
    [Balance]         MONEY         NULL,
    [Active]          BIT           NULL,
    [Create_Date]     DATETIME      NULL,
    [DateTimeStamp]   ROWVERSION    NULL
);

