CREATE TABLE [dbo].[HRAttendenceDescription] (
    [BranchID]    VARCHAR (15) NULL,
    [PeriodMonth] VARCHAR (20) NULL,
    [PeriodYear]  VARCHAR (10) NULL,
    [EmpID]       VARCHAR (15) NULL,
    [TotalDays]   NUMERIC (2)  NULL,
    [WorkingDays] NUMERIC (2)  NULL,
    [OffDays]     NUMERIC (2)  NULL,
    [Day1]        INT          NULL,
    [Day2]        INT          NULL,
    [Day3]        INT          NULL,
    [Day4]        INT          NULL,
    [Day5]        INT          NULL,
    [Day6]        INT          NULL,
    [Day7]        INT          NULL,
    [Day8]        INT          NULL,
    [Day9]        INT          NULL,
    [Day10]       INT          NULL,
    [Day11]       INT          NULL,
    [Day12]       INT          NULL,
    [Day13]       INT          NULL,
    [Day14]       INT          NULL,
    [Day15]       INT          NULL,
    [Day16]       INT          NULL,
    [Day17]       INT          NULL,
    [Day18]       INT          NULL,
    [Day19]       INT          NULL,
    [Day20]       INT          NULL,
    [Day21]       INT          NULL,
    [Day22]       INT          NULL,
    [Day23]       INT          NULL,
    [Day24]       INT          NULL,
    [Day25]       INT          NULL,
    [Day26]       INT          NULL,
    [Day27]       INT          NULL,
    [Day28]       INT          NULL,
    [Day29]       INT          NULL,
    [Day30]       INT          NULL,
    [Day31]       INT          NULL
);

