CREATE TABLE [dbo].[InsuranceAlteredData] (
    [Trans_Key]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [TrType]             VARCHAR (10)    NOT NULL,
    [BranchID]           VARCHAR (15)    NOT NULL,
    [InsuranceID]        VARCHAR (15)    NOT NULL,
    [InsCoCode]          VARCHAR (15)    NOT NULL,
    [NameEnglish]        VARCHAR (75)    NOT NULL,
    [UnderInsCoCode]     VARCHAR (15)    NOT NULL,
    [Policy]             VARCHAR (50)    NULL,
    [SeqNo]              BIGINT          NOT NULL,
    [InsCardNo]          VARCHAR (30)    NULL,
    [RegistrationNo]     NUMERIC (12)    NOT NULL,
    [PatientNameEnglish] NVARCHAR (50)   NULL,
    [TransNbr]           NUMERIC (12)    NOT NULL,
    [TransDateEnglish]   VARCHAR (10)    NULL,
    [ApprovalNo]         VARCHAR (30)    NULL,
    [ICD10]              VARCHAR (30)    NULL,
    [Diagnosis1]         VARCHAR (50)    NULL,
    [Diagnosis2]         VARCHAR (50)    NULL,
    [Diagnosis3]         VARCHAR (50)    NULL,
    [ClinicalData]       VARCHAR (300)   NULL,
    [ClaimType]          CHAR (1)        DEFAULT ('O') NULL,
    [ServiceID]          VARCHAR (15)    NULL,
    [ServiceDescription] VARCHAR (75)    NULL,
    [ServiceDate]        VARCHAR (10)    NULL,
    [DoctorID]           VARCHAR (15)    NULL,
    [DoctorNameEnglish]  VARCHAR (50)    NULL,
    [Qty]                INT             DEFAULT (1) NULL,
    [Amount]             NUMERIC (8, 2)  NULL,
    [Gross]              NUMERIC (10, 2) NULL,
    [Discount]           NUMERIC (10, 2) NULL,
    [ADiscount]          NUMERIC (10, 2) NULL,
    [Deductible]         NUMERIC (10, 2) NULL,
    [Net]                NUMERIC (10, 2) NULL,
    [Updated]            INT             DEFAULT (0) NULL,
    [PrintStatus]        INT             DEFAULT (0) NULL,
    [UserID]             VARCHAR (15)    NULL,
    [Create_Date]        DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]          VARCHAR (20)    DEFAULT (host_name()) NULL,
    [Lock]               INT             DEFAULT (0) NULL,
    [LockMachine]        VARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([Trans_Key] ASC)
);

