CREATE TABLE [dbo].[ItemDetailsNew] (
    [BranchID]                VARCHAR (15)   NULL,
    [Item_Code]               VARCHAR (15)   NOT NULL,
    [RegistrationNo]          NVARCHAR (50)  NULL,
    [Content1]                NVARCHAR (150) NULL,
    [ItemNameEnglish]         VARCHAR (50)   NULL,
    [ItemGroup]               VARCHAR (5)    NULL,
    [Pack1]                   NUMERIC (2)    NULL,
    [Pack2]                   NUMERIC (3)    NULL,
    [Pack3]                   NUMERIC (4)    NULL,
    [Strength value]          NVARCHAR (50)  NULL,
    [SaleStrip]               CHAR (1)       NULL,
    [SalePcs]                 CHAR (1)       NULL,
    [Credit_Patient_Allow]    CHAR (1)       NULL,
    [Item_Blocked]            CHAR (1)       NULL,
    [Created_By_Branch]       VARCHAR (15)   NULL,
    [Unit of strength]        NVARCHAR (30)  NULL,
    [Dosage Form]             NVARCHAR (75)  NULL,
    [Route of Administration] NVARCHAR (150) NULL,
    [ATC Code 1]              NVARCHAR (50)  NULL,
    [ATC Code 2]              NVARCHAR (50)  NULL,
    [float]                   FLOAT (53)     NULL,
    [Unit of volume]          NVARCHAR (50)  NULL,
    [Package type]            NVARCHAR (50)  NULL,
    [Package size]            FLOAT (53)     NULL,
    [Legal status]            NVARCHAR (20)  NULL,
    [Product control]         NVARCHAR (30)  NULL,
    [Public price (SAR)]      FLOAT (53)     NULL,
    [Shelf-life (mon)]        FLOAT (53)     NULL,
    [Storage conditions]      NVARCHAR (50)  NULL,
    [Manufacturer name]       NVARCHAR (255) NULL,
    [Country of Manufacturer] NVARCHAR (50)  NULL,
    [Marketing Company]       NVARCHAR (150) NULL,
    [Nationality]             NVARCHAR (50)  NULL,
    [MAH (Agent name)]        NVARCHAR (150) NULL,
    [Authorization status]    NVARCHAR (15)  NULL,
    [Marketing status]        NVARCHAR (20)  NULL,
    [Remarks]                 NVARCHAR (255) NULL,
    [Color]                   NVARCHAR (50)  NULL,
    [Shape]                   NVARCHAR (50)  NULL,
    [DrugIdentification]      NVARCHAR (50)  NULL
);

