CREATE TABLE [dbo].[PatientDetails] (
    [BranchID]            VARCHAR (15)    NOT NULL,
    [Series]              VARCHAR (2)     NOT NULL,
    [RegistrationNo]      NUMERIC (12)    NOT NULL,
    [GroupNo]             NUMERIC (12)    NULL,
    [RegistrationDate]    VARCHAR (10)    NULL,
    [PatientType]         VARCHAR (15)    NULL,
    [BillType]            VARCHAR (2)     NOT NULL,
    [Courtesy]            VARCHAR (10)    NULL,
    [PatientNameEnglish]  VARCHAR (50)    NOT NULL,
    [PatientNameArabic]   NVARCHAR (50)   NULL,
    [Address1]            VARCHAR (50)    NULL,
    [Address2]            VARCHAR (50)    NULL,
    [Street]              VARCHAR (50)    NULL,
    [City]                VARCHAR (30)    NULL,
    [IqamaNo]             NVARCHAR (50)   NULL,
    [PassportNo]          NVARCHAR (50)   NULL,
    [PhoneR]              VARCHAR (30)    NULL,
    [PhoneO]              VARCHAR (30)    NULL,
    [Mobile]              VARCHAR (30)    NULL,
    [eMail]               VARCHAR (30)    NULL,
    [Alert]               CHAR (1)        NULL,
    [DOB]                 VARCHAR (10)    NULL,
    [Age]                 NUMERIC (3)     NULL,
    [AgeYMD]              CHAR (1)        NULL,
    [Sex]                 CHAR (1)        NULL,
    [CountryIOTA]         VARCHAR (15)    NOT NULL,
    [CountryPhone]        VARCHAR (30)    NULL,
    [InsCoCode]           VARCHAR (15)    NULL,
    [DeductionCategory]   VARCHAR (15)    NULL,
    [SplConsultationDays] NUMERIC (10)    NULL,
    [LastConsDate]        VARCHAR (10)    NULL,
    [InsCardNo]           VARCHAR (30)    NULL,
    [InsCardExpiry]       VARCHAR (10)    NULL,
    [InsCardStatus]       CHAR (1)        NULL,
    [InsSoapNo]           VARCHAR (30)    NULL,
    [InsSoapCode]         VARCHAR (30)    NULL,
    [InsPolicy]           VARCHAR (30)    NULL,
    [SalesmanCode]        VARCHAR (10)    NULL,
    [Limit]               NUMERIC (12, 2) NULL,
    [BalanceAmt]          NUMERIC (12, 2) NULL,
    [Restricted]          VARCHAR (1)     NULL,
    [AC_Code]             VARCHAR (15)    NULL,
    [DoctorCode]          VARCHAR (10)    NULL,
    [FingureScan]         VARCHAR (1)     NULL,
    [FingureScanned]      VARCHAR (1)     NULL,
    [FaceScan]            VARCHAR (1)     NULL,
    [FaceScanned]         VARCHAR (1)     NULL,
    [Remarks]             VARCHAR (300)   NULL,
    [UserID]              VARCHAR (15)    NULL,
    [Create_Date]         DATETIME        NULL,
    [MachineID]           VARCHAR (20)    NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDX_PatientDetails]
    ON [dbo].[PatientDetails]([BranchID] ASC, [RegistrationNo] ASC, [PatientType] ASC);

