CREATE TABLE [dbo].[PensionProvider] (
    [IdNo]                   INT            IDENTITY (1, 1) NOT NULL,
    [PensionProviderCode]    VARCHAR (15)   NOT NULL,
    [PensionProviderName]    VARCHAR (50)   NOT NULL,
    [PensionProviderNameAra] NVARCHAR (50)  NOT NULL,
    [ContactPerson]          NVARCHAR (50)  NULL,
    [ContactDesignation]     NVARCHAR (50)  NULL,
    [Street]                 NVARCHAR (50)  NULL,
    [District]               NVARCHAR (35)  NULL,
    [TownCity]               NVARCHAR (35)  NULL,
    [ProvinceState]          NVARCHAR (35)  NULL,
    [CountryCode]            CHAR (2)       NULL,
    [POBox]                  VARCHAR (10)   NULL,
    [ZipCode]                VARCHAR (10)   NULL,
    [Phone1]                 VARCHAR (15)   NULL,
    [Phone2]                 VARCHAR (15)   NULL,
    [Mobile]                 VARCHAR (15)   NULL,
    [Fax]                    VARCHAR (15)   NULL,
    [Email]                  VARCHAR (254)  NULL,
    [Website]                VARCHAR (254)  NULL,
    [AccountIdNo]            SMALLINT       NOT NULL,
    [BankAccountNo]          VARCHAR (20)   NULL,
    [BankIdNo]               SMALLINT       NULL,
    [IBAN]                   VARCHAR (35)   NULL,
    [PaymentMethod]          CHAR (2)       NULL,
    [Notes]                  NVARCHAR (255) NULL,
    [Active]                 BIT            NULL,
    [DateTimeStamp]          ROWVERSION     NULL,
    CONSTRAINT [PK_PensionProviderDetailsIDNo] PRIMARY KEY CLUSTERED ([IdNo] ASC),
    CONSTRAINT [IX_PensionProviderName] UNIQUE NONCLUSTERED ([IdNo] ASC),
    CONSTRAINT [IX_PensionProviderNameAra] UNIQUE NONCLUSTERED ([IdNo] ASC)
);

