CREATE TABLE [dbo].[pharmacyinvoicedetails9] (
    [Group_Key]        INT             NOT NULL,
    [InvoiceType]      VARCHAR (2)     NOT NULL,
    [SaleType]         VARCHAR (15)    NULL,
    [BranchID]         VARCHAR (15)    NOT NULL,
    [RowNbr]           DECIMAL (3)     NOT NULL,
    [Item_Code]        VARCHAR (15)    NOT NULL,
    [Batch]            VARCHAR (15)    NULL,
    [Expiry]           VARCHAR (10)    NULL,
    [Qty]              DECIMAL (12, 3) NULL,
    [Unit]             VARCHAR (10)    NULL,
    [PcsQty]           DECIMAL (4)     NULL,
    [QtyInStock]       DECIMAL (10)    NULL,
    [Pack1]            DECIMAL (8)     NULL,
    [Pack2]            DECIMAL (8)     NULL,
    [Pack3]            DECIMAL (8)     NULL,
    [EANCode]          VARCHAR (15)    NULL,
    [SalePrice]        DECIMAL (12, 4) NULL,
    [CostPrice]        DECIMAL (12, 4) NULL,
    [costPricePerUnit] DECIMAL (12, 4) NULL,
    [DiscountPer]      DECIMAL (12, 4) NULL,
    [DiscountAmt]      DECIMAL (12, 4) NULL,
    [DeductiblePer]    DECIMAL (12, 4) NULL,
    [DeductibleAmt]    DECIMAL (12, 4) NULL,
    [AgentCommPer]     DECIMAL (12, 2) NULL,
    [SalesManCommPer]  DECIMAL (12, 2) NULL,
    [Stock_Status]     CHAR (1)        NULL,
    [SBT_Status]       CHAR (1)        NULL,
    [Packed_Stock]     DECIMAL (7, 3)  NULL,
    [DosageID]         VARCHAR (15)    NULL,
    [SaleStatus]       VARCHAR (2)     NULL,
    [VATPercent]       DECIMAL (5, 2)  NULL,
    [VATAmt]           DECIMAL (10, 2) NULL
);

