CREATE TABLE [dbo].[pharmacyinvoicegroup9] (
    [Trans_Key]             INT             NOT NULL,
    [BranchID]              VARCHAR (15)    NOT NULL,
    [WareHouseID]           VARCHAR (5)     NULL,
    [BillType]              VARCHAR (20)    NOT NULL,
    [TransType]             VARCHAR (10)    NULL,
    [TransNbr]              DECIMAL (10)    NOT NULL,
    [TransDateEnglish]      VARCHAR (10)    NOT NULL,
    [TransDateHijri]        VARCHAR (10)    NULL,
    [RegistrationType]      VARCHAR (10)    NOT NULL,
    [RegistrationNo]        DECIMAL (12)    NOT NULL,
    [RegistrationDate]      VARCHAR (10)    NULL,
    [ReferenceNo]           VARCHAR (20)    NULL,
    [DoctorID]              VARCHAR (15)    NULL,
    [InsuranceID]           VARCHAR (15)    NULL,
    [InsuranceGroupID]      VARCHAR (50)    NULL,
    [InsuranceNameEnglish]  VARCHAR (75)    NULL,
    [DeductionCategory]     VARCHAR (30)    NULL,
    [InsuranceCardNo]       VARCHAR (50)    NULL,
    [InsurancePolicyNo]     VARCHAR (20)    NULL,
    [InsSoapNo]             VARCHAR (30)    NULL,
    [InsSoapCard]           VARCHAR (30)    NULL,
    [SalesmanID]            VARCHAR (15)    NULL,
    [AgentID]               VARCHAR (15)    NULL,
    [NormalDiscountAmt]     DECIMAL (12, 2) NULL,
    [PreviousBalanceAmt]    DECIMAL (12, 2) NULL,
    [DeductibleAmt]         DECIMAL (12, 2) NULL,
    [DeductibleDiscountAmt] DECIMAL (12, 2) NULL,
    [ExtraDiscountAmt]      DECIMAL (12, 2) NULL,
    [ExtraDiscountPercent]  DECIMAL (12, 2) NULL,
    [RoundOffAmt]           DECIMAL (12, 2) NULL,
    [TenderCash]            DECIMAL (12, 2) NULL,
    [BillAmt]               DECIMAL (12, 2) NULL,
    [CostAmt]               DECIMAL (12, 2) NULL,
    [CommissionAmt]         DECIMAL (12, 2) NULL,
    [CreditCardID]          VARCHAR (15)    NULL,
    [CreditCardNo]          VARCHAR (20)    NULL,
    [CreditCardExpiry]      VARCHAR (10)    NULL,
    [remarks]               VARCHAR (300)   NULL,
    [DeductibleInvoiceNbr]  DECIMAL (12)    NULL,
    [UserID]                VARCHAR (30)    NULL,
    [Create_Date]           SMALLDATETIME   NULL,
    [MachineID]             VARCHAR (30)    NULL,
    [VATAmt]                DECIMAL (10, 2) NULL
);

