CREATE TABLE [dbo].[PharmacyInvoicePrint] (
    [Group_Key]            NUMERIC (10)    NOT NULL,
    [BranchID]             VARCHAR (15)    NOT NULL,
    [RegistrationType]     VARCHAR (2)     NOT NULL,
    [TransType]            VARCHAR (10)    NULL,
    [BillType]             VARCHAR (2)     NOT NULL,
    [TransNBR]             NUMERIC (10)    NOT NULL,
    [RegistrationNBR]      NUMERIC (12)    NOT NULL,
    [ReferenceNo]          VARCHAR (20)    NULL,
    [TransDateEnglish]     VARCHAR (10)    NOT NULL,
    [TransDateHijiri]      VARCHAR (10)    NULL,
    [DoctorID]             VARCHAR (5)     NULL,
    [InsuranceID]          VARCHAR (10)    NULL,
    [InsuranceGroupID]     VARCHAR (15)    NULL,
    [InsuranecName]        VARCHAR (50)    NULL,
    [InsSoapNo]            VARCHAR (30)    NULL,
    [InsSoapCard]          VARCHAR (30)    NULL,
    [InsuranceCardNo]      VARCHAR (30)    NULL,
    [DeductionCategory]    VARCHAR (20)    NULL,
    [SalesmanID]           VARCHAR (5)     NULL,
    [AgentID]              VARCHAR (5)     NULL,
    [NormalDiscountAmt]    NUMERIC (12, 2) NULL,
    [PreviousBalanceAmt]   NUMERIC (12, 2) NULL,
    [DeductibleAmt]        NUMERIC (12, 2) NULL,
    [DiscountOnDeductible] NUMERIC (12, 2) NULL,
    [ExtraDiscountPer]     NUMERIC (12, 2) NULL,
    [ExtraDiscountAmt]     NUMERIC (12, 2) NULL,
    [RoundOffAmt]          NUMERIC (12, 2) NULL,
    [TenderCashAmt]        NUMERIC (12, 2) NULL,
    [BillAmt]              NUMERIC (12, 2) NULL,
    [CostAmt]              NUMERIC (12, 2) DEFAULT (0) NULL,
    [CommissionAmt]        NUMERIC (12, 2) NULL,
    [RowNbr]               NUMERIC (3)     NOT NULL,
    [Item_Code]            VARCHAR (15)    NOT NULL,
    [BatchNo]              VARCHAR (15)    NULL,
    [ExpiryDate]           VARCHAR (10)    NULL,
    [Qty]                  NUMERIC (12, 3) NULL,
    [Qty_Unit]             VARCHAR (10)    NULL,
    [Qty_In_Pcs]           NUMERIC (4)     NULL,
    [Pack1]                NUMERIC (8)     DEFAULT (1) NULL,
    [Pack2]                NUMERIC (8)     DEFAULT (1) NULL,
    [Pack3]                NUMERIC (8)     DEFAULT (1) NULL,
    [Price]                NUMERIC (12, 4) DEFAULT (0) NULL,
    [Cost_Price]           NUMERIC (12, 2) DEFAULT (0) NULL,
    [cost_In_Pcs]          NUMERIC (12, 2) DEFAULT (0) NULL,
    [DiscountPer]          NUMERIC (12, 2) DEFAULT (0) NULL,
    [DiscountAmt]          NUMERIC (12, 2) DEFAULT (0) NULL,
    [ItemDeductiblePer]    NUMERIC (12, 2) DEFAULT (0) NULL,
    [ItemDeductibleAmt]    NUMERIC (12, 2) DEFAULT (0) NULL,
    [AgentCommPer]         NUMERIC (12, 2) DEFAULT (0) NULL,
    [SalesManCommPer]      NUMERIC (12, 2) DEFAULT (0) NULL,
    [Stock_Status]         CHAR (1)        NULL,
    [SBT_Status]           CHAR (1)        NULL,
    [remarks]              VARCHAR (300)   NULL,
    [UserID]               VARCHAR (30)    NULL,
    [Create_Date]          DATETIME        DEFAULT (getdate()) NULL,
    [machineID]            VARCHAR (30)    NULL,
    [VATPercent]           NUMERIC (5, 2)  NULL,
    [VATAmt]               NUMERIC (10, 2) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_PharmacyInvoicePrint]
    ON [dbo].[PharmacyInvoicePrint]([BranchID] ASC, [Group_Key] ASC, [UserID] ASC, [machineID] ASC);

