CREATE TABLE [dbo].[PMRPatientSickLeave] (
    [Trans_Key]            INT            IDENTITY (1, 1) NOT NULL,
    [TransNBR]             NUMERIC (10)   NOT NULL,
    [TransDate]            VARCHAR (10)   NOT NULL,
    [Series]               VARCHAR (2)    NOT NULL,
    [RegistrationNo]       NUMERIC (12)   NOT NULL,
    [RegistrationDate]     VARCHAR (10)   NULL,
    [PatientType]          VARCHAR (15)   NULL,
    [PatientNameEnglish]   NVARCHAR (75)  NULL,
    [PatientNameArabic]    NVARCHAR (75)  NULL,
    [Occupation]           NVARCHAR (50)  NULL,
    [PlaceOfWork]          NVARCHAR (50)  NULL,
    [ID_No]                NVARCHAR (50)  NULL,
    [Passport]             NVARCHAR (50)  NULL,
    [Phone]                NVARCHAR (30)  NULL,
    [Mobile]               NVARCHAR (30)  NULL,
    [Email]                NVARCHAR (30)  NULL,
    [DOB]                  VARCHAR (10)   NULL,
    [DOBHijri]             VARCHAR (10)   NULL,
    [Age]                  NUMERIC (3)    NULL,
    [AgeYMD]               CHAR (1)       NULL,
    [Sex]                  CHAR (1)       NULL,
    [CountryIOTA]          VARCHAR (15)   NULL,
    [CountryName]          NVARCHAR (50)  NULL,
    [InsuranceID]          VARCHAR (15)   NULL,
    [CategoryID]           VARCHAR (15)   NULL,
    [TPAID]                VARCHAR (15)   NULL,
    [InsuranceCardNo]      VARCHAR (30)   NULL,
    [InsCardExpiry]        VARCHAR (10)   NULL,
    [DoctorID]             VARCHAR (15)   NULL,
    [DoctorName]           NVARCHAR (75)  NULL,
    [Complaint]            NVARCHAR (200) NULL,
    [Diagnosis]            NVARCHAR (200) NULL,
    [VisitingDate]         VARCHAR (10)   NULL,
    [DateOfVisitHijri]     VARCHAR (10)   NULL,
    [SickOneDay]           CHAR (1)       DEFAULT ('1') NULL,
    [Days]                 NUMERIC (2)    DEFAULT (1) NULL,
    [DateFrom]             VARCHAR (10)   NULL,
    [DateOfAdmissionHijri] VARCHAR (10)   NULL,
    [DateUpto]             VARCHAR (10)   NULL,
    [DateOfDischargeHijri] VARCHAR (10)   NULL,
    [Remarks]              NVARCHAR (500) NULL,
    [FollowUp]             INT            DEFAULT (0) NULL,
    [Referral]             INT            DEFAULT (0) NULL,
    [Approval]             INT            DEFAULT (0) NULL,
    [Facility]             INT            DEFAULT (0) NULL,
    [Disability]           INT            DEFAULT (0) NULL,
    [Other]                NVARCHAR (150) NULL,
    [ReferenceNo]          VARCHAR (20)   NULL,
    [Review]               NVARCHAR (100) NULL,
    [Director]             NVARCHAR (50)  NULL,
    [History]              NVARCHAR (200) NULL,
    [Language]             CHAR (1)       NULL,
    [UserID]               VARCHAR (15)   NULL,
    [Create_Date]          DATETIME       DEFAULT (getdate()) NULL,
    [MachineID]            VARCHAR (20)   DEFAULT (host_name()) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDX_PMRPatientSickLeave]
    ON [dbo].[PMRPatientSickLeave]([TransNBR] ASC);

