CREATE TABLE [dbo].[purchasegroup9] (
    [Trans_Key]          INT             NOT NULL,
    [BranchID]           VARCHAR (15)    NOT NULL,
    [TransType]          VARCHAR (5)     NOT NULL,
    [TransSeries]        CHAR (10)       NOT NULL,
    [TransNo]            DECIMAL (10)    NOT NULL,
    [TransDate]          VARCHAR (10)    NOT NULL,
    [HijriDate]          VARCHAR (10)    NULL,
    [PONo]               DECIMAL (10)    NULL,
    [PODate]             VARCHAR (10)    NULL,
    [WarehouseID]        VARCHAR (15)    NOT NULL,
    [PurchaseType]       CHAR (10)       NULL,
    [PurchaseFrom]       CHAR (10)       NULL,
    [SupplierID]         VARCHAR (10)    NOT NULL,
    [InvoiceNo]          VARCHAR (20)    NULL,
    [InvoiceDate]        VARCHAR (10)    NULL,
    [Reference]          VARCHAR (20)    NULL,
    [InvoiceAmt]         DECIMAL (12, 2) NULL,
    [CurrencyCode]       VARCHAR (5)     NOT NULL,
    [ConversionRate]     DECIMAL (10, 5) NULL,
    [GrossAmt]           DECIMAL (12, 2) NULL,
    [TotalExpenses]      DECIMAL (12, 2) NULL,
    [SpecialDiscountPer] DECIMAL (7, 3)  NULL,
    [SpecialDiscountAmt] DECIMAL (12, 2) NULL,
    [SalesmanID]         VARCHAR (15)    NULL,
    [Remarks]            VARCHAR (300)   NULL,
    [PostInAccounts]     CHAR (1)        NULL,
    [PostInStock]        CHAR (1)        NULL,
    [AccountsUpdate]     VARCHAR (10)    NULL,
    [PurchaseGrossAmt]   DECIMAL (12, 2) NULL,
    [PurchaseCostAmt]    DECIMAL (12, 2) NULL,
    [PurchaseSaleAmt]    DECIMAL (12, 2) NULL,
    [PurchaseProfitPer]  DECIMAL (12, 2) NULL,
    [PurchaseProfitAmt]  DECIMAL (12, 2) NULL,
    [EnteredBy]          VARCHAR (15)    NULL,
    [CheckedBy]          VARCHAR (15)    NULL,
    [ApprovedBy]         VARCHAR (15)    NULL,
    [UserID]             VARCHAR (15)    NULL,
    [Create_Date]        SMALLDATETIME   NULL,
    [MachineID]          VARCHAR (20)    NULL,
    [VATAmt]             DECIMAL (10, 2) NULL,
    [VATIncludingInCost] INT             NULL
);



