CREATE TABLE [dbo].[SystemSettings] (
    [DefaultBranchID]               VARCHAR (15)    DEFAULT ('02') NULL,
    [DefaultCurrency]               VARCHAR (10)    DEFAULT ('SAR') NULL,
    [DefaultYear]                   NUMERIC (4)     DEFAULT (2013) NULL,
    [DefaultDateFormat]             VARCHAR (10)    DEFAULT ('mm/DD/yyyy') NULL,
    [CashBillSeriesPrefix]          VARCHAR (10)    DEFAULT ('Cash') NULL,
    [CreditBillSeriesPrefix]        VARCHAR (10)    DEFAULT ('Credit') NULL,
    [DCRBillSeriesPrefix]           VARCHAR (10)    DEFAULT ('DCR') NULL,
    [DDRBillSeriesPrefix]           VARCHAR (10)    DEFAULT ('DDR') NULL,
    [DebitAdviceSeriesPrefix]       VARCHAR (10)    DEFAULT ('DA') NULL,
    [MaxLengthOfIDs]                NUMERIC (2)     DEFAULT (15) NULL,
    [MaxLengthOfPhone]              NUMERIC (2)     DEFAULT (21) NULL,
    [DefaultWarehouseID]            VARCHAR (15)    DEFAULT ('WH01') NULL,
    [BatchLength]                   NUMERIC (2)     DEFAULT (4) NULL,
    [MaxLengthofItemCode]           NUMERIC (2)     DEFAULT (5) NULL,
    [EANCodeReadable]               CHAR (1)        DEFAULT ('Y') NULL,
    [DefaultPatientRecognizedBy]    CHAR (15)       DEFAULT ('RegistrationNo') NULL,
    [DayClosingType]                CHAR (1)        DEFAULT ('A') NULL,
    [InvoiceEditReject]             CHAR (1)        DEFAULT ('Y') NULL,
    [AccountsLinked]                CHAR (1)        DEFAULT ('N') NULL,
    [CaseSheetPrint]                CHAR (1)        DEFAULT ('Y') NULL,
    [FileRoomInvoiceCopyPrint]      CHAR (1)        DEFAULT ('N') NULL,
    [FamilyFileUsed]                CHAR (1)        DEFAULT ('N') NULL,
    [PatientDiscountApplicable]     CHAR (1)        DEFAULT ('N') NULL,
    [InvoiceCreateForAdvDate]       CHAR (1)        DEFAULT ('N') NULL,
    [ConvertCashPatientToCredit]    CHAR (1)        DEFAULT ('Y') NULL,
    [PatientUpperLimitAdjustment]   CHAR (1)        DEFAULT ('N') NULL,
    [TVDisplay]                     CHAR (1)        DEFAULT ('N') NULL,
    [TokenPrint]                    CHAR (1)        DEFAULT ('Y') NULL,
    [BarCodePrinterInstalled]       CHAR (1)        DEFAULT ('Y') NULL,
    [SmallBarCodeUsed]              CHAR (1)        DEFAULT ('Y') NULL,
    [CashBillPrinting]              CHAR (5)        DEFAULT ('Big') NULL,
    [CreditBillPrinting]            CHAR (5)        DEFAULT ('Big') NULL,
    [ACSalesAndPurchasePostingAuto] CHAR (1)        DEFAULT ('Y') NULL,
    [ReportPath]                    VARCHAR (30)    NOT NULL,
    [BackupPath]                    VARCHAR (30)    NOT NULL,
    [CostValidation]                CHAR (1)        DEFAULT ('Y') NULL,
    [PharmacyCalculation]           CHAR (1)        DEFAULT ('N') NULL,
    [PatientHoldActive]             CHAR (1)        DEFAULT ('Y') NULL,
    [MaxLocalNoOfNode]              NUMERIC (2)     DEFAULT (5) NULL,
    [MaxTotalNoOfNode]              NUMERIC (3)     DEFAULT (10) NULL,
    [MultiLanguageActivated]        CHAR (1)        DEFAULT ('N') NULL,
    [PharmacyInvPrintWithoutSaving] CHAR (1)        DEFAULT ('N') NULL,
    [DayClosingTime]                VARCHAR (11)    NULL,
    [LastStockTakingDate]           VARCHAR (10)    NULL,
    [ApplicationType]               VARCHAR (15)    DEFAULT ('Pro') NULL,
    [ApplicationExpiredOn]          VARCHAR (10)    DEFAULT (getdate() + 120) NULL,
    [DefaultLanguage]               VARCHAR (15)    DEFAULT ('English') NULL,
    [ExpiryShowInLookupDays]        NUMERIC (3)     DEFAULT (15) NULL,
    [FollowUp]                      VARCHAR (15)    DEFAULT ('FOL001') NULL,
    [DeductibleCountOneDay]         INT             DEFAULT (0) NULL,
    [PharmacyBillPrint]             VARCHAR (10)    DEFAULT ('BIG') NULL,
    [ClinicBillPrint]               VARCHAR (10)    DEFAULT ('BIG') NULL,
    [InvoiceFlag]                   INT             DEFAULT (1) NULL,
    [IndividualServicePriceApply]   INT             NULL,
    [UserID]                        VARCHAR (15)    DEFAULT ('Admin') NULL,
    [Create_Date]                   DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]                     VARCHAR (20)    DEFAULT (host_name()) NULL,
    [CashCollectionID]              VARCHAR (15)    NULL,
    [ScannedDocPath]                VARCHAR (100)   NULL,
    [PrintDosage]                   CHAR (1)        NULL,
    [DummyPharmacy]                 CHAR (1)        NULL,
    [DeletePharmacyInvoice]         CHAR (1)        NULL,
    [RoundOffAmt]                   INT             NULL,
    [RefundDed]                     INT             NULL,
    [BankCollectionID]              VARCHAR (15)    NULL,
    [OutPatientDoctorBlock]         CHAR (1)        NULL,
    [PMRPharmacyStock]              CHAR (1)        NULL,
    [BarCode9]                      INT             NULL,
    [IBDDoctor]                     VARCHAR (15)    NULL,
    [IBDTokenGenerate]              INT             NULL,
    [IBDDepartmentID]               VARCHAR (15)    NULL,
    [PrintIBForm]                   INT             NULL,
    [PhoneDigits]                   INT             DEFAULT ((0)) NULL,
    [AttachIBD]                     CHAR (1)        NULL,
    [MultipleDeptSave]              CHAR (1)        NULL,
    [EditClinicPrice]               CHAR (1)        NULL,
    [DefaultCreditType]             VARCHAR (20)    NULL,
    [LabDeptID]                     VARCHAR (15)    NULL,
    [AttachedWithDC]                CHAR (1)        NULL,
    [PharmacyDiscountAmt]           NUMERIC (5, 2)  NULL,
    [BlankFileLeave]                INT             NULL,
    [OpenDiscount]                  INT             DEFAULT ((0)) NULL,
    [ComPort4Drawer]                INT             NULL,
    [attachedLABServices]           INT             NULL,
    [WithoutStockItemBatch]         VARCHAR (3)     NULL,
    [HRDataBaseType]                VARCHAR (20)    NULL,
    [HRDataBasePath]                VARCHAR (100)   NULL,
    [PHRCashCollectionID]           VARCHAR (15)    NULL,
    [PHRBankCollectionID]           VARCHAR (15)    NULL,
    [IBCashCollectionID]            VARCHAR (15)    NULL,
    [IBBankCollectionID]            VARCHAR (15)    NULL,
    [PatientNameUpdate]             CHAR (1)        DEFAULT ('N') NULL,
    [DefaultPatientType]            VARCHAR (20)    NULL,
    [PatientDocumentFolder]         VARCHAR (50)    NULL,
    [PMRSaveOldDate]                INT             NULL,
    [ICD104Cash]                    CHAR (1)        NULL,
    [VATApplicable]                 INT             DEFAULT ((0)) NULL,
    [VATPercent]                    NUMERIC (5, 2)  DEFAULT ((0)) NULL,
    [VATOnGross]                    INT             DEFAULT ((0)) NULL,
    [VATExemption]                  INT             NULL,
    [splPriceDiscNewPatient]        INT             NULL,
    [ChangePatientType]             INT             NULL,
    [LABDefaultResults]             CHAR (1)        NULL,
    [PreStockEntry]                 CHAR (1)        NULL,
    [LABStatusMaintain]             INT             NULL,
    [TakeRoundOffAmt]               INT             NULL,
    [DiscAmt]                       NUMERIC (10, 2) NULL
);

