CREATE TABLE [dbo].[VatInvoice4Qtr2018] (
    [InvSource]              VARCHAR (16)     NOT NULL,
    [Group_Key]              NUMERIC (10)     NOT NULL,
    [TransType]              VARCHAR (15)     NULL,
    [SaleType]               VARCHAR (12)     NOT NULL,
    [BranchID]               VARCHAR (15)     NULL,
    [RowNbr]                 NUMERIC (10)     NOT NULL,
    [ItemCode]               VARCHAR (15)     NOT NULL,
    [Qty]                    NUMERIC (13, 3)  NULL,
    [Unit]                   VARCHAR (10)     NULL,
    [PcsQty]                 NUMERIC (4)      NULL,
    [SalePrice]              NUMERIC (12, 4)  NULL,
    [ItemGrossPrice]         NUMERIC (26, 7)  NULL,
    [ItemDiscountAmt]        NUMERIC (38, 10) NULL,
    [ItemNetAmount]          NUMERIC (38, 9)  NULL,
    [AdjItemNetAmount]       NUMERIC (38, 6)  NULL,
    [VATPercent]             NUMERIC (5, 2)   NOT NULL,
    [VATAmt]                 NUMERIC (10, 2)  NOT NULL,
    [TransNbr]               NUMERIC (10)     NULL,
    [TransDateEnglish]       VARCHAR (10)     NULL,
    [InvNormalDiscount]      NUMERIC (12, 2)  NULL,
    [InvExtraDiscount]       NUMERIC (12, 2)  NULL,
    [InvRoundoffAmt]         NUMERIC (12, 2)  NULL,
    [InvVatAmt]              NUMERIC (10, 2)  NOT NULL,
    [InvVatExemption]        NUMERIC (10, 2)  NOT NULL,
    [BillAmt]                NUMERIC (12, 2)  NULL,
    [TInvNormalDiscount]     NUMERIC (12, 2)  NULL,
    [TInvExtraDiscount]      NUMERIC (12, 2)  NULL,
    [TInvRoundoffAmt]        NUMERIC (12, 2)  NULL,
    [TInvVatAmt]             NUMERIC (10, 2)  NOT NULL,
    [TInvVatExemption]       NUMERIC (10, 2)  NOT NULL,
    [TBillAmt]               NUMERIC (12, 2)  NULL,
    [Rejected]               INT              NULL,
    [CostCenter]             VARCHAR (30)     NULL,
    [UserID]                 VARCHAR (30)     NULL,
    [DoctorID]               VARCHAR (15)     NULL,
    [RegistrationNo]         NUMERIC (12)     NULL,
    [RegistrationType]       VARCHAR (15)     NULL,
    [PatientNameEnglish]     NVARCHAR (75)    NULL,
    [InsuranceID]            VARCHAR (15)     NULL,
    [NameEnglish]            VARCHAR (75)     NULL,
    [ServiceNameEnglish]     VARCHAR (100)    NULL,
    [InsuranceGroupID]       VARCHAR (15)     NULL,
    [AdjInvExtraDisc]        NUMERIC (13, 2)  NULL,
    [InvGrossAmt]            NUMERIC (17, 2)  NULL,
    [Series]                 VARCHAR (2)      NULL,
    [AdditionalItemDiscount] NUMERIC (38, 6)  NULL,
    [AdjItemDiscount]        NUMERIC (38, 6)  NULL,
    [AdjExtPlusVat]          NUMERIC (38, 6)  NULL,
    [AdjItemVat]             NUMERIC (38, 6)  NULL,
    [AdjItemVatExemption]    NUMERIC (38, 6)  NULL,
    [AdjExtAmt]              NUMERIC (38, 6)  NULL,
    [IqamaNo]                NVARCHAR (50)    NULL,
    [CountryName]            VARCHAR (35)     NULL,
    [VAdjDiscount]           NUMERIC (38, 6)  NULL,
    [VAdjNetAmt]             NUMERIC (38, 6)  NULL,
    [VAdjExtAmt]             NUMERIC (38, 6)  NULL,
    [VAdjustedVatAmt]        NUMERIC (38, 6)  NULL,
    [VAdjVatExemption]       NUMERIC (38, 6)  NULL
);

