CREATE VIEW WSL_INVOICES_View
 
AS
SELECT 	A.INSURANCEID,
	A.TRANSNBR AS INVOICENO,
	RIGHT('0000000'+RTRIM(CONVERT(varchar(7),A.REGISTRATIONNO)),6)+
        REPLACE(A.TRANSDATEENGLISH,'/','')+
        RIGHT('00'+A.DOCTORID,2)as 	[PROVCLAIMNO],
	A.TRANSDATEENGLISH AS INVOICEDATE,
	LEFT(C.DEPARTMENTNAMEENGLISH,20) AS INVOICEDEPT,
	SUM(A.QTY*A.AMOUNT) AS TOTINVGRSAMT,
	SUM(A.DISCOUNT) AS TOTINVDISC,
	SUM(A.DEDUCTIBLE) AS TOTINVPATSHARE,
	SUM((A.QTY*A.AMOUNT)-(A.DISCOUNT+A.DEDUCTIBLE)) AS TOTINVNETAMT
FROM INSURANCEALTEREDDATA A
LEFT OUTER JOIN EMPLOYEEDETAILS B ON A.DOCTORID = B.EMPID
LEFT OUTER JOIN MEDICALDEPARTMENTS C ON B.DEPTID = C.DEPARTMENTID
--WHERE TRANSDATEENGLISH BETWEEN '2015/05/01' AND '2015/05/31' AND INSURANCEID='5004'
GROUP BY
	A.INSURANCEID,
	A.TRANSNBR,
	A.REGISTRATIONNO,
	A.TRANSDATEENGLISH,
	A.DOCTORID,
	C.DEPARTMENTNAMEENGLISH