<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AATM.UI.Controls</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\FilteringComboBoxWithProgress.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Controls\FilteringComboBoxWithProgress.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataAccess\AATM.DataAccess.Sql\AATM.DataAccess.Sql.csproj" />
    <ProjectReference Include="..\..\DataAccess\AATM.DataAccess\AATM.DataAccess.csproj" />
  </ItemGroup>

</Project>
