CREATE 	PROCEDURE uSpWSL_SERVICE_DETAILS 
        ( 
          @DateFrom as varchar(10),
          @DateUpto as varchar(10),
          @TPA as varchar(15) 
        )
 
AS 
DECLARE @SQLString varchar(8000) 
SET @SQLString = 'INSERT INTO WASEELDB..WSL_SERVICE_DETAILS 
SELECT INVOICENO,SERVICECODE,SERVICEDATE,LEFT(SERVICEDESC,20) AS SERVICEDESC,UNITSERVICEPRICE,UNITSERVICETYPE,QTY,TOOTHNO,TOTSERVICEGRSAMT,TOTSERVICEDISC,TOTSERVICEPATSHARE,TOTSERVICENETAMT 
FROM WSL_SERVICE_DETAILS_View
WHERE [INSURANCEID] = "' + @TPA +'" AND [SERVICEDATE] Between "' + @DateFrom +'" AND "'+ @DateUpto + '" '
EXECUTE(@SQLString)
SET QUOTED_IDENTIFIER ON
SET NOCOUNT OFF