CREATE TABLE [dbo].[auth_user] (
    [id]                  INT            IDENTITY (1, 1) NOT NULL,
    [username]            NVARCHAR (30)  NOT NULL,
    [password]            NVARCHAR (128) NOT NULL,
    [update_time]         DATETIME2 (7)  NULL,
    [first_name]          NVARCHAR (30)  NOT NULL,
    [last_name]           NVARCHAR (30)  NOT NULL,
    [emp_pin]             NVARCHAR (30)  NULL,
    [email]               NVARCHAR (254) NOT NULL,
    [tele_phone]          NVARCHAR (30)  NULL,
    [auth_time_dept]      INT            NULL,
    [login_id]            INT            NULL,
    [login_type]          INT            NULL,
    [login_count]         INT            NULL,
    [is_staff]            BIT            NOT NULL,
    [is_active]           BIT            NOT NULL,
    [is_superuser]        BIT            NOT NULL,
    [is_public]           BIT            NOT NULL,
    [can_manage_all_dept] BIT            NOT NULL,
    [del_flag]            INT            NULL,
    [date_joined]         DATETIME2 (7)  NOT NULL,
    [last_login]          DATETIME2 (7)  NULL,
    [session_key]         NVARCHAR (32)  NULL,
    [login_ip]            NVARCHAR (32)  NULL,
    [photo]               NVARCHAR (200) NULL,
    [assign_company]      INT            NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    UNIQUE NONCLUSTERED ([username] ASC)
);

