CREATE TABLE [dbo].[custom_att_stage_DailyAttendance] (
    [emp_id]                    INT             NOT NULL,
    [att_date]                  DATE            NOT NULL,
    [year_no]                   INT             NOT NULL,
    [month_no]                  INT             NOT NULL,
    [daily_status]              VARCHAR (50)    NULL,
    [business_day_type]         VARCHAR (50)    NULL,
    [attendance_status]         VARCHAR (50)    NULL,
    [anomaly_flag]              VARCHAR (100)   NULL,
    [anomaly_group]             VARCHAR (50)    NULL,
    [needs_payroll_review]      BIT             NULL,
    [first_clock_in]            DATETIME        NULL,
    [last_clock_out]            DATETIME        NULL,
    [recomputed_worked_minutes] DECIMAL (10, 2) NULL,
    [ot_minutes]                DECIMAL (10, 2) NULL,
    [required_scheduled_hours]  DECIMAL (10, 2) NULL,
    [worked_hours]              DECIMAL (10, 2) NULL,
    [ot_hours]                  DECIMAL (10, 2) NULL,
    [punch_status]              VARCHAR (50)    NULL,
    [schedule_label]            VARCHAR (100)   NULL,
    [late_minutes]              DECIMAL (10, 2) NULL,
    [early_out_minutes]         DECIMAL (10, 2) NULL,
    [recomputed_absence_hours]  DECIMAL (10, 2) NULL,
    [work_completion_pct]       DECIMAL (10, 2) NULL,
    [date_type]                 INT             NULL,
    [comp_leave_eligible_flag]  INT             NULL,
    [comp_leave_minutes]        DECIMAL (10, 2) NULL,
    [comp_leave_hours]          DECIMAL (10, 2) NULL
);

