CREATE TABLE [dbo].[custom_att_stage_DailyMetrics] (
    [emp_id]                          INT             NOT NULL,
    [att_date]                        DATE            NOT NULL,
    [date_type]                       INT             NULL,
    [base_date_type]                  INT             NOT NULL,
    [base_is_off_day]                 INT             NOT NULL,
    [present_flag]                    SMALLINT        NULL,
    [full_attendance_flag]            SMALLINT        NULL,
    [scheduled_in]                    DATETIME2 (0)   NULL,
    [scheduled_out]                   DATETIME2 (0)   NULL,
    [first_clock_in]                  DATETIME2 (7)   NULL,
    [last_clock_out]                  DATETIME2 (7)   NULL,
    [punch_count]                     INT             NOT NULL,
    [scheduled_ot_cap_minutes]        DECIMAL (38, 2) NOT NULL,
    [worked_minutes]                  DECIMAL (10, 2) NOT NULL,
    [payload_ot_minutes]              DECIMAL (10, 2) NOT NULL,
    [absence_minutes]                 DECIMAL (10, 2) NOT NULL,
    [required_work_minutes]           DECIMAL (10, 2) NOT NULL,
    [recomputed_worked_minutes]       DECIMAL (10, 2) NOT NULL,
    [recomputed_worked_hours]         DECIMAL (10, 2) NOT NULL,
    [use_mode]                        SMALLINT        NULL,
    [temp_duration_minutes]           INT             NOT NULL,
    [temp_work_time_duration]         INT             NOT NULL,
    [temp_break_minutes]              INT             NOT NULL,
    [ot_eligible_flag]                BIT             NOT NULL,
    [has_temp_schedule]               INT             NOT NULL,
    [has_assigned_schedule]           INT             NOT NULL,
    [schedule_source]                 VARCHAR (30)    NOT NULL,
    [base_schedule_source]            VARCHAR (30)    NOT NULL,
    [base_shift_id]                   INT             NULL,
    [base_time_interval_id]           INT             NULL,
    [base_required_work_minutes]      INT             NOT NULL,
    [effective_required_work_minutes] DECIMAL (12, 2) NOT NULL,
    [WorkCompletionToleranceMinutes]  INT             NOT NULL,
    [resolved_schedule_source]        VARCHAR (30)    NOT NULL,
    [effective_shift_id]              INT             NULL,
    [effective_time_interval_id]      INT             NULL,
    [resolved_is_off_day]             INT             NOT NULL,
    [schedule_type]                   VARCHAR (12)    NOT NULL,
    [effective_ot_eligible]           INT             NOT NULL,
    [scheduled_payable_minutes]       DECIMAL (12, 2) NOT NULL,
    [scheduled_payable_hours]         DECIMAL (10, 2) NULL,
    [regular_required_minutes]        DECIMAL (13, 2) NULL,
    [regular_required_hours]          DECIMAL (10, 2) NULL,
    [regular_paid_minutes]            DECIMAL (13, 2) NULL,
    [regular_paid_hours]              DECIMAL (10, 2) NULL,
    [ot_minutes]                      DECIMAL (14, 2) NULL,
    [ot_hours]                        DECIMAL (10, 2) NULL,
    [total_paid_minutes]              DECIMAL (15, 2) NULL,
    [total_paid_hours]                DECIMAL (10, 2) NULL,
    [unpaid_excess_minutes]           DECIMAL (13, 2) NULL,
    [unpaid_excess_hours]             DECIMAL (10, 2) NULL,
    [worked_hours]                    DECIMAL (10, 2) NULL,
    [absence_hours]                   DECIMAL (10, 2) NULL,
    [required_work_hours]             DECIMAL (10, 2) NULL,
    [required_scheduled_hours]        DECIMAL (10, 2) NULL,
    [recomputed_absence_hours]        DECIMAL (10, 2) NULL,
    [work_balance_hours]              DECIMAL (10, 2) NULL,
    [recomputed_excess_minutes]       DECIMAL (14, 2) NULL,
    [recomputed_excess_hours]         DECIMAL (10, 2) NULL,
    [excess_work_minutes]             DECIMAL (13, 2) NULL,
    [excess_work_hours]               DECIMAL (10, 2) NULL,
    [late_minutes]                    INT             NULL,
    [early_out_minutes]               DECIMAL (14, 2) NULL,
    [work_completion_pct]             DECIMAL (10, 2) NULL,
    [attendance_status]               VARCHAR (22)    NOT NULL,
    [anomaly_flag]                    VARCHAR (26)    NOT NULL,
    [needs_payroll_review]            INT             NOT NULL,
    [comp_leave_eligible_flag]        INT             NOT NULL,
    [comp_leave_minutes]              DECIMAL (10, 2) NULL,
    [comp_leave_hours]                DECIMAL (10, 2) NULL,
    [att_year]                        INT             NULL,
    [att_month]                       INT             NULL,
    [att_day]                         INT             NULL,
    [weekday_name]                    NVARCHAR (30)   NULL
);

