<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\AATM.Contracts\AATM.Contracts.csproj" />
    <ProjectReference Include="..\..\DataAccess\AATM.WpfDataAccess\AATM.WpfDataAccess.csproj" />
  </ItemGroup>

</Project>
