CREATE TABLE [dbo].[EmployeeDetails] (
    [Primary_Key]                  INT           IDENTITY (1, 1) NOT NULL,
    [BranchID]                     VARCHAR (15)  DEFAULT ('PH001') NULL,
    [EmpID]                        VARCHAR (15)  NOT NULL,
    [EmpNameEnglish]               VARCHAR (40)  NOT NULL,
    [EmpNameArabic]                NVARCHAR (40) NULL,
    [EmpDegree]                    VARCHAR (30)  NULL,
    [EmpDegreePlace]               VARCHAR (40)  NULL,
    [DOB]                          VARCHAR (10)  NULL,
    [DOJ]                          VARCHAR (10)  NULL,
    [DOR]                          VARCHAR (10)  NULL,
    [Contract_From]                VARCHAR (10)  NULL,
    [Contract_Upto]                VARCHAR (10)  NULL,
    [Sex]                          CHAR (1)      DEFAULT ('M') NULL,
    [Age]                          NUMERIC (2)   NULL,
    [BloodGroup]                   VARCHAR (5)   NULL,
    [MeritalStatus]                VARCHAR (10)  NULL,
    [FatherSpouseNameEng]          VARCHAR (40)  NULL,
    [FatherSpouseNameArabic]       NVARCHAR (40) NULL,
    [NationalID]                   VARCHAR (3)   NULL,
    [ReligionID]                   VARCHAR (3)   NULL,
    [GOSI]                         VARCHAR (20)  NULL,
    [FileNo]                       VARCHAR (20)  NULL,
    [pAddress1]                    VARCHAR (40)  NULL,
    [pAddress2]                    VARCHAR (40)  NULL,
    [pStreet]                      VARCHAR (40)  NULL,
    [pCity]                        VARCHAR (40)  NULL,
    [pCountry]                     VARCHAR (30)  NULL,
    [pPOBox]                       VARCHAR (20)  NULL,
    [pZIP]                         VARCHAR (20)  NULL,
    [pPhone]                       VARCHAR (25)  NULL,
    [pFax]                         VARCHAR (25)  NULL,
    [pMailID]                      VARCHAR (40)  NULL,
    [pWeb]                         VARCHAR (40)  NULL,
    [mAddress1]                    VARCHAR (40)  NULL,
    [mAddress2]                    VARCHAR (40)  NULL,
    [mStreet]                      VARCHAR (40)  NULL,
    [mCity]                        VARCHAR (40)  NULL,
    [mCountry]                     VARCHAR (30)  NULL,
    [mPOBox]                       VARCHAR (20)  NULL,
    [mZIP]                         VARCHAR (20)  NULL,
    [mPhone]                       VARCHAR (25)  NULL,
    [mFax]                         VARCHAR (25)  NULL,
    [mMailID]                      VARCHAR (40)  NULL,
    [mWeb]                         VARCHAR (40)  NULL,
    [DeptID]                       VARCHAR (15)  NULL,
    [DesignationID]                VARCHAR (15)  NULL,
    [SponserNameEnglish]           VARCHAR (40)  NULL,
    [SponserNameArabic]            NVARCHAR (40) NULL,
    [UnderCoSponsorship]           CHAR (1)      NULL,
    [MedicalLicenseNo]             VARCHAR (20)  NULL,
    [MedicalIssueDate]             VARCHAR (10)  NULL,
    [MedicalRenewalDate]           VARCHAR (10)  NULL,
    [MedicalPlace]                 VARCHAR (30)  NULL,
    [PassportNo]                   VARCHAR (20)  NULL,
    [PassportIssueDate]            VARCHAR (10)  NULL,
    [PassportRenewalDate]          VARCHAR (10)  NULL,
    [PassportIssuePlace]           VARCHAR (30)  NULL,
    [PassportIssueCountryID]       VARCHAR (3)   NULL,
    [VisaNo]                       VARCHAR (20)  NULL,
    [VisaIssueDate]                VARCHAR (10)  NULL,
    [VisaRenewalDate]              VARCHAR (10)  NULL,
    [VisaIssueCountryID]           VARCHAR (3)   NULL,
    [IQAMANo]                      VARCHAR (20)  NULL,
    [IQAMAIssueDate]               VARCHAR (10)  NULL,
    [IQAMARenewalDate]             VARCHAR (10)  NULL,
    [IQAMAIssuePlace]              VARCHAR (30)  NULL,
    [IQAMAIssueCountryID]          VARCHAR (3)   NULL,
    [DrivingLicenseNo]             VARCHAR (20)  NULL,
    [DrivingLicenseIssueDate]      VARCHAR (10)  NULL,
    [DrivingLicenseRenewalDate]    VARCHAR (10)  NULL,
    [DrivingLicenseIssuePlace]     VARCHAR (30)  NULL,
    [DrivingLicenseIssueCountryID] VARCHAR (3)   NULL,
    [ServiceID]                    VARCHAR (15)  NULL,
    [OPDFloor]                     VARCHAR (15)  DEFAULT ('GROUND FLOOR') NULL,
    [OPDNo]                        VARCHAR (5)   NOT NULL,
    [ConsultationTime]             NUMERIC (2)   DEFAULT (10) NULL,
    [ConsultationAvgTime]          NUMERIC (2)   DEFAULT (10) NULL,
    [ReconsultationDays]           NUMERIC (2)   DEFAULT (15) NULL,
    [Discontinue]                  CHAR (1)      DEFAULT ('N') NULL,
    [GenerateToken]                INT           DEFAULT (1) NULL,
    [UserID]                       VARCHAR (15)  DEFAULT ('Admin') NULL,
    [Create_Date]                  DATETIME      DEFAULT (getdate()) NULL,
    [MachineID]                    VARCHAR (20)  DEFAULT (host_name()) NULL,
    [COSTCENTRE]                   VARCHAR (15)  NULL,
    [ShortName]                    VARCHAR (15)  NULL,
    PRIMARY KEY CLUSTERED ([Primary_Key] ASC)
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_EmployeeDetails]
    ON [dbo].[EmployeeDetails]([BranchID] ASC, [EmpID] ASC);

