CREATE TABLE [dbo].[HREmployeeDetails] (
    [BranchID]           VARCHAR (15)  NOT NULL,
    [Courtesy]           VARCHAR (25)  NULL,
    [EmpID]              VARCHAR (15)  NOT NULL,
    [AttendenceID]       VARCHAR (15)  NULL,
    [EmpNameEnglish]     VARCHAR (75)  NOT NULL,
    [EmpNameArabic]      NVARCHAR (75) NULL,
    [NationalID]         VARCHAR (15)  NULL,
    [ReligionID]         VARCHAR (15)  NULL,
    [DepartmentID]       VARCHAR (15)  NULL,
    [DesignationID]      VARCHAR (15)  NULL,
    [CategoryID]         VARCHAR (15)  NULL,
    [JobID]              VARCHAR (15)  NULL,
    [JoinDate]           VARCHAR (10)  NULL,
    [DOB]                VARCHAR (10)  NULL,
    [ContractFrom]       VARCHAR (10)  NULL,
    [ContractUpTo]       VARCHAR (10)  NULL,
    [Sex]                VARCHAR (1)   NULL,
    [Age]                NUMERIC (3)   NULL,
    [MeritalStatus]      VARCHAR (30)  NULL,
    [DutyHrs]            NUMERIC (2)   NULL,
    [ServiceStatus]      INT           NULL,
    [Degree]             VARCHAR (100) NULL,
    [Experience]         VARCHAR (200) NULL,
    [Address1]           VARCHAR (100) NULL,
    [Address2]           VARCHAR (100) NULL,
    [Street]             VARCHAR (50)  NULL,
    [City]               VARCHAR (50)  NULL,
    [Country]            VARCHAR (50)  NULL,
    [POBox]              VARCHAR (30)  NULL,
    [ZIP]                VARCHAR (30)  NULL,
    [Phone]              VARCHAR (30)  NULL,
    [Mobile]             VARCHAR (30)  NULL,
    [eMail]              VARCHAR (100) NULL,
    [PassportNo]         VARCHAR (50)  NULL,
    [IQAMANo]            VARCHAR (50)  NULL,
    [InsuranceNo]        VARCHAR (50)  NULL,
    [DrvLicense]         VARCHAR (50)  NULL,
    [PassportExpiry]     VARCHAR (10)  NULL,
    [IQAMAExpiry]        VARCHAR (10)  NULL,
    [InsuranceExpiry]    VARCHAR (10)  NULL,
    [DrvLicenseExpiry]   VARCHAR (10)  NULL,
    [FileNo]             VARCHAR (50)  NULL,
    [GOSI]               VARCHAR (50)  NULL,
    [SponserNameEnglish] VARCHAR (75)  NULL,
    [SponserNameArabic]  VARCHAR (75)  NULL,
    [Remark]             VARCHAR (300) NULL,
    [UserID]             VARCHAR (15)  NULL,
    [Create_Date]        DATETIME      NULL,
    [MachineID]          VARCHAR (20)  NULL,
    [SundayOff]          INT           NULL,
    [MondayOff]          INT           NULL,
    [TuesdayOff]         INT           NULL,
    [WednesdayOff]       INT           NULL,
    [ThursdayOff]        INT           NULL,
    [FridayOff]          INT           NULL,
    [SaturdayOff]        INT           NULL,
    [empmarketing]       INT           NULL,
    [PunchNecessary]     INT           NULL,
    [AlternativeFriday]  INT           NULL,
    [Friday135]          INT           NULL,
    [Friday24]           INT           NULL,
    [HSaturday]          INT           NULL,
    [HSunday]            INT           NULL,
    [HMonday]            INT           NULL,
    [HTuesday]           INT           NULL,
    [HWednesday]         INT           NULL,
    [HThursday]          INT           NULL,
    [HFriday]            INT           NULL,
    [SplDayApplicable]   INT           NULL,
    [SplDay]             INT           NULL,
    [FridayDutyHrs]      INT           NULL,
    [primary_key]        INT           IDENTITY (1, 1) NOT NULL,
    [LedgerID]           VARCHAR (15)  NULL,
    [EmpCode]            VARCHAR (15)  NULL
);



