CREATE TABLE [dbo].[PMRScannerSettings] (
    [ScannerID]                 TINYINT         DEFAULT (1) NULL,
    [Image_Source]              VARCHAR (50)    NOT NULL,
    [Show_Twain]                TINYINT         DEFAULT (0) NULL,
    [Clear_Image_Buffer]        TINYINT         DEFAULT (0) NULL,
    [Enable_feeder]             TINYINT         DEFAULT (0) NULL,
    [Enable_duplex]             TINYINT         DEFAULT (0) NULL,
    [Pixel_type]                VARCHAR (40)    NULL,
    [DPI]                       VARCHAR (40)    NULL,
    [OCR_Recognize_mode]        TINYINT         DEFAULT (0) NULL,
    [OCR_Chracter_filter]       TINYINT         DEFAULT (0) NULL,
    [OCR_Language]              TINYINT         DEFAULT (0) NULL,
    [Compression_type]          TINYINT         DEFAULT (0) NULL,
    [PDF_settings]              TINYINT         DEFAULT (0) NULL,
    [JPEG_Compression]          TINYINT         DEFAULT (1) NULL,
    [Quality]                   NUMERIC (5)     DEFAULT (80) NULL,
    [Brightness_Value]          NUMERIC (10, 2) DEFAULT (0) NULL,
    [Contrast_Value]            NUMERIC (10, 2) DEFAULT (1) NULL,
    [Saturation_Value]          NUMERIC (10, 2) DEFAULT (1) NULL,
    [Hue_Value]                 NUMERIC (10, 2) DEFAULT (0) NULL,
    [Gamma_Value]               NUMERIC (10, 2) DEFAULT (1) NULL,
    [High_Quality]              TINYINT         DEFAULT (0) NULL,
    [Border]                    TINYINT         DEFAULT (0) NULL,
    [Image_Display]             TINYINT         DEFAULT (0) NULL,
    [CAP_User_Defined]          TINYINT         DEFAULT (0) NULL,
    [CAP_Left]                  NUMERIC (10, 2) DEFAULT (0) NULL,
    [CAP_Top]                   NUMERIC (10, 2) DEFAULT (0) NULL,
    [CAP_Height]                NUMERIC (10, 2) DEFAULT (11.5) NULL,
    [CAP_Width]                 NUMERIC (10, 2) DEFAULT (8.23) NULL,
    [Background_Color]          VARCHAR (40)    NULL,
    [Text_Font_Name]            VARCHAR (40)    NULL,
    [Text_Font_Size]            NUMERIC (5)     DEFAULT (10) NULL,
    [Text_Font_Style]           VARCHAR (40)    NULL,
    [Text_Left]                 NUMERIC (5)     DEFAULT (0) NULL,
    [Text_Top]                  NUMERIC (5)     DEFAULT (0) NULL,
    [Text1]                     NVARCHAR (40)   NULL,
    [Text2]                     NVARCHAR (40)   NULL,
    [Text_Show]                 TINYINT         DEFAULT (0) NULL,
    [Text_Style]                VARCHAR (40)    NULL,
    [Text_Color]                VARCHAR (40)    NULL,
    [Text_Outline_Border_Color] VARCHAR (40)    NULL,
    [Text_Outline_Back_Color]   VARCHAR (40)    NULL,
    [Text_Hash_Brush]           VARCHAR (40)    NULL,
    [Text_Hash_Fore_Color]      VARCHAR (40)    NULL,
    [Text_Hash_Back_Color]      VARCHAR (40)    NULL,
    [UserID]                    VARCHAR (15)    NULL,
    [Create_Date]               DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]                 VARCHAR (20)    DEFAULT (host_name()) NULL
);

