CREATE TABLE [dbo].[CashDuplicatePatients] (
    [branchid]            VARCHAR (15)    NOT NULL,
    [series]              VARCHAR (2)     NOT NULL,
    [registrationno]      NUMERIC (12)    NOT NULL,
    [groupno]             NUMERIC (12)    NULL,
    [registrationdate]    VARCHAR (10)    NULL,
    [PatientType]         VARCHAR (15)    NULL,
    [billtype]            VARCHAR (2)     NOT NULL,
    [Courtesy]            VARCHAR (10)    NULL,
    [patientnameenglish]  VARCHAR (50)    NOT NULL,
    [patientnamearabic]   NVARCHAR (50)   NULL,
    [address1]            VARCHAR (50)    NULL,
    [address2]            VARCHAR (50)    NULL,
    [street]              VARCHAR (50)    NULL,
    [city]                VARCHAR (30)    NULL,
    [IqamaNo]             NVARCHAR (50)   NULL,
    [PassportNo]          NVARCHAR (50)   NULL,
    [PhoneR]              VARCHAR (30)    NULL,
    [PhoneO]              VARCHAR (30)    NULL,
    [mobile]              VARCHAR (30)    NULL,
    [eMail]               VARCHAR (30)    NULL,
    [Alert]               CHAR (1)        NULL,
    [DOB]                 VARCHAR (10)    NULL,
    [age]                 NUMERIC (3)     NULL,
    [AgeYMD]              CHAR (1)        NULL,
    [sex]                 CHAR (1)        NULL,
    [CountryIOTA]         VARCHAR (15)    NOT NULL,
    [CountryPhone]        VARCHAR (30)    NULL,
    [InsCoCode]           VARCHAR (15)    NULL,
    [DeductionCategory]   VARCHAR (15)    NULL,
    [SplConsultationDays] NUMERIC (10)    NULL,
    [LastConsDate]        VARCHAR (10)    NULL,
    [InsCardNo]           VARCHAR (30)    NULL,
    [InsCardExpiry]       VARCHAR (10)    NULL,
    [InsCardStatus]       CHAR (1)        NULL,
    [InsSoapNo]           VARCHAR (30)    NULL,
    [InsSoapCode]         VARCHAR (30)    NULL,
    [InsPolicy]           VARCHAR (30)    NULL,
    [SalesmanCode]        VARCHAR (10)    NULL,
    [Limit]               NUMERIC (12, 2) NULL,
    [BalanceAmt]          NUMERIC (12, 2) NULL,
    [Restricted]          VARCHAR (1)     NULL,
    [AC_Code]             VARCHAR (15)    NULL,
    [DoctorCode]          VARCHAR (10)    NULL,
    [FingureScan]         VARCHAR (1)     NULL,
    [FingureScanned]      VARCHAR (1)     NULL,
    [FaceScan]            VARCHAR (1)     NULL,
    [FaceScanned]         VARCHAR (1)     NULL,
    [Remarks]             VARCHAR (300)   NULL,
    [UserID]              VARCHAR (15)    NULL,
    [Create_Date]         DATETIME        NULL,
    [MachineID]           VARCHAR (20)    NULL
);

