CREATE TABLE [dbo].[CBCReference] (
    [IdNo]                 INT             IDENTITY (1, 1) NOT NULL,
    [PatientName]          NVARCHAR (50)   NULL,
    [SampleId]             INT             NULL,
    [MRN]                  INT             NULL,
    [Gender]               CHAR (1)        NULL,
    [Age]                  SMALLINT        NULL,
    [AgeYMD]               CHAR (1)        NULL,
    [WBC]                  DECIMAL (10, 2) NULL,
    [WBCUnit]              VARCHAR (20)    NULL,
    [WBCReference]         VARCHAR (50)    NULL,
    [Neutrophils]          DECIMAL (10, 2) NULL,
    [NeutrophilsUnit]      VARCHAR (20)    NULL,
    [NeutrophilsReference] VARCHAR (50)    NULL,
    [Lymphocytes]          DECIMAL (10, 2) NULL,
    [LymphocytesUnit]      VARCHAR (20)    NULL,
    [LymphocytesReference] VARCHAR (50)    NULL,
    [Monocytes]            DECIMAL (10, 2) NULL,
    [MonocytesUnit]        VARCHAR (20)    NULL,
    [MonocytesReference]   VARCHAR (50)    NULL,
    [RBC]                  DECIMAL (10, 2) NULL,
    [RBCUnit]              VARCHAR (20)    NULL,
    [RBCReference]         VARCHAR (50)    NULL,
    [Hemoglobin]           DECIMAL (10, 2) NULL,
    [HemoglobinUnit]       VARCHAR (20)    NULL,
    [HemoglobinReference]  VARCHAR (50)    NULL,
    [Hematocrit]           DECIMAL (10, 2) NULL,
    [HematocritUnit]       VARCHAR (20)    NULL,
    [HematocritReference]  VARCHAR (50)    NULL,
    [MCV]                  DECIMAL (10, 2) NULL,
    [MCVUnit]              VARCHAR (20)    NULL,
    [MCVReference]         VARCHAR (50)    NULL,
    [MCH]                  DECIMAL (10, 2) NULL,
    [MCHUnit]              VARCHAR (20)    NULL,
    [MCHReference]         VARCHAR (50)    NULL,
    [RDWCV]                DECIMAL (10, 2) NULL,
    [RDWCVUnit]            VARCHAR (20)    NULL,
    [RDWCVReference]       VARCHAR (50)    NULL,
    [RDWSD]                DECIMAL (10, 2) NULL,
    [RDWSDUnit]            VARCHAR (20)    NULL,
    [RDWSDReference]       VARCHAR (50)    NULL,
    [Platelets]            DECIMAL (10, 2) NULL,
    [PlateletsUnit]        VARCHAR (20)    NULL,
    [PlateletsReference]   VARCHAR (50)    NULL,
    [PCT]                  DECIMAL (10, 2) NULL,
    [PCTUnit]              VARCHAR (20)    NULL,
    [PCTReference]         VARCHAR (50)    NULL,
    [MPV]                  DECIMAL (10, 2) NULL,
    [MPVUnit]              VARCHAR (20)    NULL,
    [MPVReference]         VARCHAR (50)    NULL,
    [PDW]                  DECIMAL (10, 2) NULL,
    [PDWUnit]              VARCHAR (20)    NULL,
    [PDWReference]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_CBCReference] PRIMARY KEY CLUSTERED ([IdNo] ASC)
);

