<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\AATM.Services\AATM.Services.csproj" />
    <ProjectReference Include="..\..\Wpf\AATM.Contracts\AATM.Contracts.csproj" />
  </ItemGroup>

</Project>
