CREATE TABLE [dbo].[A1_Vendor] (
    [ID]         INT            IDENTITY (1, 1) NOT NULL,
    [Name]       NVARCHAR (50)  NULL,
    [DefualtBox] NVARCHAR (50)  NULL,
    [Mobile]     NVARCHAR (50)  NULL,
    [specialty]  NVARCHAR (50)  NULL,
    [Salary]     INT            NULL,
    [BdlHome]    INT            NULL,
    [BdlDrive]   INT            NULL,
    [BdlTravale] INT            NULL,
    [BdlOther]   INT            NULL,
    [Per1]       INT            NULL,
    [Per2]       INT            NULL,
    [Per3]       INT            NULL,
    [Per4]       INT            NULL,
    [Per5]       INT            NULL,
    [Per6]       INT            NULL,
    [Per7]       INT            NULL,
    [Lim1]       INT            NULL,
    [Lim2]       INT            NULL,
    [Lim3]       INT            NULL,
    [Lim4]       INT            NULL,
    [Lim5]       INT            NULL,
    [Lim6]       INT            NULL,
    [Lim7]       INT            NULL,
    [Note]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_A1_Vendor] PRIMARY KEY CLUSTERED ([ID] ASC)
);

