CREATE TABLE [dbo].[CBCResults] (
    [IdNo]               INT            IDENTITY (1, 1) NOT NULL,
    [PatientName]        VARCHAR (50)   NULL,
    [InvoiceNo]          NUMERIC (10)   NULL,
    [SampleId]           NUMERIC (10)   NULL,
    [MachineIDNo]        TINYINT        NULL,
    [DateTimeTransmtted] SMALLDATETIME  CONSTRAINT [DF_CBCResults_DateTimeTransmtted] DEFAULT (getdate()) NULL,
    [MRN]                VARCHAR (10)   NULL,
    [Gender]             VARCHAR (6)    NULL,
    [Age]                NUMERIC (6)    NULL,
    [AgeYMD]             VARCHAR (6)    NULL,
    [WBC]                DECIMAL (7, 2) NULL,
    [Neutrophils]        DECIMAL (5, 2) NULL,
    [Lymphocytes]        DECIMAL (5, 2) NULL,
    [Monocytes]          DECIMAL (5, 2) NULL,
    [RBC]                DECIMAL (5, 2) NULL,
    [Hemoglobin]         DECIMAL (5, 2) NULL,
    [Hematocrit]         DECIMAL (5, 2) NULL,
    [MCV]                DECIMAL (6, 2) NULL,
    [MCH]                DECIMAL (6, 2) NULL,
    [RDWCV]              DECIMAL (5, 2) NULL,
    [RDWSD]              DECIMAL (6, 2) NULL,
    [Platelets]          DECIMAL (6, 2) NULL,
    [PCT]                DECIMAL (6, 3) NULL,
    [MPV]                DECIMAL (6, 2) NULL,
    [PDW]                DECIMAL (6, 2) NULL,
    [EOS]                DECIMAL (6, 2) NULL,
    [BAS]                DECIMAL (6, 2) NULL,
    [IMG]                DECIMAL (6, 2) NULL,
    [MCHC]               DECIMAL (6, 2) NULL,
    [WBCF]               CHAR (1)       NULL,
    CONSTRAINT [PK_CBCResults] PRIMARY KEY CLUSTERED ([IdNo] ASC)
);

