CREATE TABLE [dbo].[InsuranceInvoiceReturn] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [InsuranceCompanyID]       INT             NOT NULL,
    [InvoiceNumber]            NVARCHAR (255)  NULL,
    [InvoiceIssueDate]         DATETIME        NULL,
    [Note]                     NVARCHAR (MAX)  NULL,
    [VatPer]                   DECIMAL (18, 2) NULL,
    [BuyerCRNumber]            NVARCHAR (255)  NULL,
    [BuyerFullName]            NVARCHAR (255)  NULL,
    [BuyerVATNumber]           NVARCHAR (255)  NULL,
    [BuyerStreet]              NVARCHAR (255)  NULL,
    [BuyerBuildingNumber]      NVARCHAR (255)  NULL,
    [BuyerAdditionalNumber]    NVARCHAR (255)  NULL,
    [BuyerCity]                NVARCHAR (255)  NULL,
    [BuyerPostalCode]          NVARCHAR (255)  NULL,
    [BuyerState]               NVARCHAR (255)  NULL,
    [BuyerNeighborhood]        NVARCHAR (255)  NULL,
    [BuyerCountryCode]         NVARCHAR (255)  NULL,
    [ProviderCRNumber]         NVARCHAR (255)  NULL,
    [ProviderCode]             NVARCHAR (255)  NULL,
    [ProviderName]             NVARCHAR (255)  NULL,
    [ProviderVATNumber]        NVARCHAR (255)  NULL,
    [ProviderStreet]           NVARCHAR (255)  NULL,
    [ProviderBuildingNumber]   NVARCHAR (255)  NULL,
    [ProviderAdditionalNumber] NVARCHAR (255)  NULL,
    [ProviderCity]             NVARCHAR (255)  NULL,
    [ProviderPostalCode]       NVARCHAR (255)  NULL,
    [ProviderState]            NVARCHAR (255)  NULL,
    [ProviderNeighborhood]     NVARCHAR (255)  NULL,
    [JZ_CompanyId]             INT             NULL,
    [Status]                   INT             NULL,
    [ENumber]                  NVARCHAR (127)  NULL,
    [EId]                      INT             NULL,
    CONSTRAINT [PK_InsuranceInvoiceReturn] PRIMARY KEY CLUSTERED ([ID] ASC)
);

