CREATE TABLE [dbo].[Insurance_DCAF] (
    [ID]                       INT            IDENTITY (1, 1) NOT NULL,
    [illness]                  NVARCHAR (MAX) NULL,
    [Complaint]                NVARCHAR (MAX) NULL,
    [Diagnosis]                NVARCHAR (MAX) NULL,
    [DiagnosisOther]           NVARCHAR (MAX) NULL,
    [Significant]              NVARCHAR (MAX) NULL,
    [Code1]                    NVARCHAR (MAX) NULL,
    [Code2]                    NVARCHAR (MAX) NULL,
    [Code3]                    NVARCHAR (MAX) NULL,
    [Code4]                    NVARCHAR (MAX) NULL,
    [CBOrthodontics]           BIT            NULL,
    [CBCheckUp]                BIT            NULL,
    [CBRTA]                    BIT            NULL,
    [CBWorkRelated]            BIT            NULL,
    [CBDevelopmental]          BIT            NULL,
    [CBCleaning]               BIT            NULL,
    [CBSportsRelated]          BIT            NULL,
    [Date1]                    DATE           NULL,
    [Date2]                    DATE           NULL,
    [Date3]                    DATE           NULL,
    [Date4]                    DATE           NULL,
    [NameRelationship]         NVARCHAR (MAX) NULL,
    [CompleteCodeBy]           NVARCHAR (MAX) NULL,
    [Teeth]                    NVARCHAR (MAX) NULL,
    [CustID]                   INT            NULL,
    [UserName]                 NVARCHAR (MAX) NULL,
    [Date]                     DATE           NULL,
    [Time]                     TIME (0)       NULL,
    [Status]                   TINYINT        NULL,
    [DrName]                   NVARCHAR (255) NULL,
    [HowValue]                 NVARCHAR (255) NULL,
    [WhenValue]                NVARCHAR (255) NULL,
    [WhereValue]               NVARCHAR (255) NULL,
    [Other]                    NVARCHAR (255) NULL,
    [Version]                  NVARCHAR (50)  NULL,
    [CBRegularDentalTreatment] BIT            NULL,
    [CBPlanType]               BIT            NULL,
    [CBNewVisit]               BIT            NULL,
    [CBFollowUp]               BIT            NULL,
    [Approval]                 NVARCHAR (255) NULL,
    [Age]                      NVARCHAR (255) NULL,
    [XRayInput1]               NVARCHAR (MAX) NULL,
    [XRayInput2]               NVARCHAR (MAX) NULL,
    [XRayInput3]               NVARCHAR (MAX) NULL,
    [XRayInput4]               NVARCHAR (MAX) NULL,
    [CBInpatient]              BIT            NULL,
    [CBOutpatient]             BIT            NULL,
    [InsuranceCompnay]         NVARCHAR (100) NULL,
    [InsuranceClass]           NVARCHAR (100) NULL,
    [InsurancePolicy]          NVARCHAR (100) NULL,
    [InsuranceMainCompnay]     NVARCHAR (100) NULL,
    [InsuranceMembership]      NVARCHAR (MAX) NULL,
    [AllowExceedApprovalLimit] BIT            NULL,
    [RelatedID]                INT            NULL,
    [OperationCodes]           NVARCHAR (255) NULL,
    [IllnessUnit]              NVARCHAR (255) NULL,
    [CustomField1]             NVARCHAR (255) NULL,
    [CustomField2]             NVARCHAR (255) NULL,
    [CustomField3]             NVARCHAR (255) NULL,
    [CustomField4]             NVARCHAR (255) NULL,
    [CustomField5]             NVARCHAR (255) NULL,
    [InsuranceRelation]        NVARCHAR (50)  NULL,
    [InsuranceExpiredDate]     DATE           NULL,
    [CustomerBirthday]         DATE           NULL,
    [TreatmentPlan]            NVARCHAR (MAX) NULL,
    [PatientHistory]           NVARCHAR (MAX) NULL,
    [PhysicalExamination]      NVARCHAR (MAX) NULL,
    [HistoryOfPresentIllness]  NVARCHAR (MAX) NULL,
    [InvestigationResult]      NVARCHAR (50)  NULL,
    [PharmacyApproval]         NVARCHAR (255) NULL,
    CONSTRAINT [PK_Insurance_DCAF] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_Insurance_DCAF_AppWait]
    ON [dbo].[Insurance_DCAF]([CustID] ASC, [Date] ASC, [Time] ASC, [DrName] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Insurance_DCAF_Insurance]
    ON [dbo].[Insurance_DCAF]([InsurancePolicy] ASC, [InsuranceClass] ASC, [InsuranceCompnay] ASC);

