CREATE TABLE [dbo].[InsuranceInvoice] (
    [ID]                                                       INT             IDENTITY (1, 1) NOT NULL,
    [InsuranceCompanyID]                                       INT             NOT NULL,
    [InvoiceNumber]                                            NVARCHAR (255)  NULL,
    [InvoiceIssueDate]                                         DATETIME        NULL,
    [SupplyPeriodStartDate]                                    DATETIME        NULL,
    [SupplyPeriodEndDate]                                      DATETIME        NULL,
    [Attention]                                                NVARCHAR (255)  NULL,
    [Comment]                                                  NVARCHAR (255)  NULL,
    [Description]                                              NVARCHAR (255)  NULL,
    [BuyerCRNumber]                                            NVARCHAR (255)  NULL,
    [BuyerFullName]                                            NVARCHAR (255)  NULL,
    [BuyerVATNumber]                                           NVARCHAR (255)  NULL,
    [BuyerStreet]                                              NVARCHAR (255)  NULL,
    [BuyerBuildingNumber]                                      NVARCHAR (255)  NULL,
    [BuyerAdditionalNumber]                                    NVARCHAR (255)  NULL,
    [BuyerCity]                                                NVARCHAR (255)  NULL,
    [BuyerPostalCode]                                          NVARCHAR (255)  NULL,
    [BuyerState]                                               NVARCHAR (255)  NULL,
    [BuyerNeighborhood]                                        NVARCHAR (255)  NULL,
    [BuyerCountryCode]                                         NVARCHAR (255)  NULL,
    [ProviderCRNumber]                                         NVARCHAR (255)  NULL,
    [ProviderCode]                                             NVARCHAR (255)  NULL,
    [ProviderName]                                             NVARCHAR (255)  NULL,
    [ProviderVATNumber]                                        NVARCHAR (255)  NULL,
    [ProviderStreet]                                           NVARCHAR (255)  NULL,
    [ProviderBuildingNumber]                                   NVARCHAR (255)  NULL,
    [ProviderAdditionalNumber]                                 NVARCHAR (255)  NULL,
    [ProviderCity]                                             NVARCHAR (255)  NULL,
    [ProviderPostalCode]                                       NVARCHAR (255)  NULL,
    [ProviderState]                                            NVARCHAR (255)  NULL,
    [ProviderNeighborhood]                                     NVARCHAR (255)  NULL,
    [ClaimsCount]                                              INT             NULL,
    [ReportItemsCount]                                         INT             NULL,
    [TotalWorksBeforeDiscount]                                 DECIMAL (18, 2) NULL,
    [TotalDiscount]                                            DECIMAL (18, 2) NULL,
    [TotalWorksAfterDiscountWithoutVAT]                        DECIMAL (18, 2) NULL,
    [TotalPatientCarryWithoutVAT]                              DECIMAL (18, 2) NULL,
    [TotalPatientCarryFromAmountIncludeVAT]                    DECIMAL (18, 2) NULL,
    [TotalPatientCarryFromAmountNotIncludeVAT]                 DECIMAL (18, 2) NULL,
    [TotalPatientVATValue]                                     DECIMAL (18, 2) NULL,
    [TotalPatientCarryWithVAT]                                 DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryWithoutVAT]                            DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryFromAmountIncludeVAT]                  DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryFromAmountNotIncludeVAT]               DECIMAL (18, 2) NULL,
    [TotalInsuranceVATValue]                                   DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryWithVAT]                               DECIMAL (18, 2) NULL,
    [VatPer]                                                   DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryWithoutVATBeforeDiscount]              DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryFromAmountIncludeVATBeforeDiscount]    DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryFromAmountNotIncludeVATBeforeDiscount] DECIMAL (18, 2) NULL,
    [TotalInsuranceVATValueBeforeDiscount]                     DECIMAL (18, 2) NULL,
    [TotalInsuranceCarryWithVATBeforeDiscount]                 DECIMAL (18, 2) NULL,
    [JZ_CompanyId]                                             INT             NULL,
    [Status]                                                   INT             NULL,
    [SeperateDetailsType]                                      INT             NULL,
    [ENumber]                                                  NVARCHAR (127)  NULL,
    [EId]                                                      INT             NULL,
    [VATNote]                                                  NVARCHAR (MAX)  NULL,
    [IgnoreZatca]                                              BIT             NULL,
    CONSTRAINT [PK_InsuranceInvoice] PRIMARY KEY CLUSTERED ([ID] ASC)
);

