CREATE TABLE [dbo].[KS_CustomerTemp] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [FileDate]    DATE           NULL,
    [FileTime]    TIME (0)       NULL,
    [Name1]       NVARCHAR (MAX) NULL,
    [Name2]       NVARCHAR (MAX) NULL,
    [Name3]       NVARCHAR (MAX) NULL,
    [Job]         NVARCHAR (MAX) NULL,
    [Gender]      NVARCHAR (MAX) NULL,
    [Nat]         NVARCHAR (MAX) NULL,
    [Address]     NVARCHAR (MAX) NULL,
    [Mobile1]     NVARCHAR (MAX) NULL,
    [Mobile2]     NVARCHAR (MAX) NULL,
    [Phone1]      NVARCHAR (MAX) NULL,
    [Phone2]      NVARCHAR (MAX) NULL,
    [Mail1]       NVARCHAR (MAX) NULL,
    [Mail2]       NVARCHAR (MAX) NULL,
    [WattsUp]     NVARCHAR (MAX) NULL,
    [Facbook]     NVARCHAR (MAX) NULL,
    [Birthday]    DATE           NULL,
    [CIDentity]   NVARCHAR (MAX) NULL,
    [Marital]     NVARCHAR (MAX) NULL,
    [SmsBlocked]  BIT            NULL,
    [Resource]    NVARCHAR (MAX) NULL,
    [LevelStatue] NVARCHAR (MAX) NULL,
    [WebSite]     NVARCHAR (MAX) NULL,
    [Comment]     NVARCHAR (MAX) NULL,
    [City]        NVARCHAR (MAX) NULL,
    [Country]     NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_KS_CustomerTemp] PRIMARY KEY CLUSTERED ([ID] ASC)
);

