CREATE TABLE [dbo].[MedicRep] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [PatID]                INT            NULL,
    [PatName]              NVARCHAR (255) NULL,
    [Date]                 DATE           NULL,
    [time]                 TIME (0)       NULL,
    [User]                 NVARCHAR (255) NULL,
    [Destination]          NVARCHAR (255) NULL,
    [Descryption]          NVARCHAR (MAX) NULL,
    [Needed]               NVARCHAR (MAX) NULL,
    [Dr]                   NVARCHAR (255) NULL,
    [ManagDr]              NVARCHAR (255) NULL,
    [FinalAproval]         NVARCHAR (MAX) NULL,
    [Gender]               NVARCHAR (255) NULL,
    [Nat]                  NVARCHAR (255) NULL,
    [Birthday]             DATE           NULL,
    [Job]                  NVARCHAR (255) NULL,
    [JobSource]            NVARCHAR (255) NULL,
    [VisitDate]            DATE           NULL,
    [EntreDate]            DATE           NULL,
    [ExitDate]             DATE           NULL,
    [CB1]                  BIT            NULL,
    [CB2]                  BIT            NULL,
    [CB3]                  BIT            NULL,
    [CB4]                  BIT            NULL,
    [CB5]                  BIT            NULL,
    [CB6]                  BIT            NULL,
    [CB7]                  BIT            NULL,
    [CB8]                  BIT            NULL,
    [CB9]                  BIT            NULL,
    [CB10]                 BIT            NULL,
    [CB11]                 BIT            NULL,
    [CB12]                 BIT            NULL,
    [VecationSDate]        DATE           NULL,
    [VecationEDate]        DATE           NULL,
    [VecationDurationW]    NVARCHAR (255) NULL,
    [VecationDurationN]    NCHAR (10)     NULL,
    [FinalRepDate]         DATE           NULL,
    [FinalRepUser]         NVARCHAR (255) NULL,
    [FinalRepManager]      NVARCHAR (255) NULL,
    [Txt1]                 NVARCHAR (255) NULL,
    [Txt2]                 NVARCHAR (255) NULL,
    [Txt3]                 NVARCHAR (255) NULL,
    [Txt4]                 NVARCHAR (255) NULL,
    [Txt5]                 NVARCHAR (255) NULL,
    [Txt6]                 NVARCHAR (MAX) NULL,
    [Txt7]                 NVARCHAR (MAX) NULL,
    [Txt8]                 NVARCHAR (MAX) NULL,
    [Txt9]                 NVARCHAR (MAX) NULL,
    [Txt10]                NVARCHAR (MAX) NULL,
    [ReferralNo]           NVARCHAR (255) NULL,
    [ReferralDate]         DATE           NULL,
    [D1]                   DATE           NULL,
    [D2]                   DATE           NULL,
    [D3]                   DATE           NULL,
    [D4]                   DATE           NULL,
    [D5]                   DATE           NULL,
    [ISWrittenFinal]       BIT            NULL,
    [OnlineEnb]            BIT            NULL,
    [OnlineUploadDone]     BIT            NULL,
    [OnlineUploadUserId]   INT            NULL,
    [OnlineUploadUserName] NVARCHAR (255) NULL,
    [OnlineUploadDateTime] DATETIME       NULL,
    CONSTRAINT [PK_MedicRep] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_MedicRep_AppWait]
    ON [dbo].[MedicRep]([PatID] ASC, [Date] ASC, [time] ASC, [Dr] ASC);

