CREATE TABLE [dbo].[A1_QuotationWroks] (
    [ID]                           INT             IDENTITY (1, 1) NOT NULL,
    [OrderID]                      INT             NULL,
    [Category]                     NVARCHAR (255)  NULL,
    [Name]                         NVARCHAR (MAX)  NULL,
    [Price]                        FLOAT (53)      NULL,
    [Count]                        FLOAT (53)      NULL,
    [Total]                        FLOAT (53)      NULL,
    [Disc]                         DECIMAL (19, 4) NULL,
    [DiscType]                     NVARCHAR (50)   NULL,
    [DiscNet]                      DECIMAL (18, 2) NULL,
    [Net]                          DECIMAL (18, 2) NULL,
    [Note]                         NVARCHAR (MAX)  NULL,
    [UserName]                     NVARCHAR (255)  NULL,
    [Date]                         DATE            NULL,
    [Time]                         TIME (0)        NULL,
    [Unit]                         NVARCHAR (50)   NULL,
    [WorkID]                       NVARCHAR (255)  NULL,
    [MaxPrice]                     FLOAT (53)      NULL,
    [MinPrice]                     FLOAT (53)      NULL,
    [IsService]                    BIT             NULL,
    [PrushID]                      INT             NULL,
    [Cost]                         FLOAT (53)      NULL,
    [TotalCost]                    FLOAT (53)      NULL,
    [SourceBarCode]                NVARCHAR (255)  NULL,
    [InsuranceTahamal]             DECIMAL (18, 2) NULL,
    [PatientTahamalPer]            DECIMAL (18, 2) NULL,
    [IsInsurance]                  BIT             NULL,
    [InuranceCode]                 NVARCHAR (255)  NULL,
    [InuranceName]                 NVARCHAR (255)  NULL,
    [InsuranceTahamalStatic]       DECIMAL (18, 2) NULL,
    [InsuranceTahamalChangedCause] NVARCHAR (MAX)  NULL,
    [InternalNotes]                NVARCHAR (MAX)  NULL,
    [VATPer]                       DECIMAL (18, 2) NULL,
    [VatValue]                     DECIMAL (18, 2) NULL,
    [TotalNoVAT]                   DECIMAL (18, 2) NULL,
    [VatExemption]                 DECIMAL (18, 2) NULL,
    [InsuranceTahamalVATPer]       DECIMAL (18, 2) NULL,
    [InsuranceTahamalVATValue]     DECIMAL (18, 2) NULL,
    [InsuranceTahamalAfterVAT]     DECIMAL (18, 2) NULL,
    [ICD10]                        NVARCHAR (555)  NULL,
    [DrugDose]                     NVARCHAR (MAX)  NULL,
    [DrugInfo]                     NVARCHAR (MAX)  NULL,
    [Type]                         INT             NULL,
    [OfferID]                      INT             NULL,
    [Teeth]                        NVARCHAR (255)  NULL,
    CONSTRAINT [PK_A1_QuotationWroks] PRIMARY KEY CLUSTERED ([ID] ASC)
);

