CREATE TABLE [dbo].[A1_Quotation] (
    [ID]                    INT             IDENTITY (1, 1) NOT NULL,
    [Date]                  DATETIME        NULL,
    [CustID]                NVARCHAR (255)  NULL,
    [CustName]              NVARCHAR (255)  NULL,
    [Type]                  NVARCHAR (255)  NULL,
    [Total]                 INT             NULL,
    [Mdfo3]                 INT             NULL,
    [Bake]                  INT             NULL,
    [Comment]               NVARCHAR (MAX)  NULL,
    [Time]                  TIME (0)        NULL,
    [UserName]              NVARCHAR (255)  NULL,
    [UserID]                INT             NULL,
    [GeneralCust]           BIT             NULL,
    [Store]                 INT             NULL,
    [Box]                   NVARCHAR (255)  NULL,
    [DrName]                NVARCHAR (255)  NULL,
    [DrID]                  INT             NULL,
    [SourceType]            NVARCHAR (50)   NULL,
    [SourceID]              INT             NULL,
    [MailPayDate]           DATETIME        NULL,
    [MailPayData]           NVARCHAR (MAX)  NULL,
    [MailPayNote]           NVARCHAR (MAX)  NULL,
    [AssignedTo]            INT             NULL,
    [OrderID]               INT             NULL,
    [IsSchedule]            BIT             NULL,
    [scheduleValue]         INT             NULL,
    [MeritDate]             DATE            NULL,
    [IsInsurance]           BIT             NULL,
    [InsuranceCompany]      NVARCHAR (255)  NULL,
    [InsurancePolicy]       NVARCHAR (255)  NULL,
    [InsuranceClass]        NVARCHAR (255)  NULL,
    [InsuranceMemberNo]     NVARCHAR (255)  NULL,
    [InsuranceApprovalNo]   NVARCHAR (255)  NULL,
    [InsuranceLimitCustDay] DECIMAL (18, 2) NULL,
    [InsuranceUpToPer]      DECIMAL (18, 2) NULL,
    [InsuranceUpToMoney]    DECIMAL (18, 2) NULL,
    [LimitCustVisit]        DECIMAL (18, 2) NULL,
    [CustIdentity]          NVARCHAR (255)  NULL,
    [CustNat]               NVARCHAR (255)  NULL,
    [Clinic]                NVARCHAR (255)  NULL,
    [IsFavorite]            BIT             NULL,
    [FavoriteNote]          NVARCHAR (255)  NULL,
    [SpecialtieID]          INT             NULL,
    CONSTRAINT [PK_A1_Quotation_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);

