CREATE TABLE [dbo].[A1_Suppliers] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [Name]             NVARCHAR (MAX) NULL,
    [Date]             DATE           NULL,
    [time]             TIME (0)       NULL,
    [Adress]           NVARCHAR (MAX) NULL,
    [Phone]            NVARCHAR (50)  NULL,
    [Mobile]           NVARCHAR (50)  NULL,
    [Fax]              NVARCHAR (50)  NULL,
    [Nat]              NVARCHAR (50)  NULL,
    [PersonalIdentity] NVARCHAR (MAX) NULL,
    [Email]            NVARCHAR (255) NULL,
    [Note]             NVARCHAR (MAX) NULL,
    [User]             NVARCHAR (50)  NULL,
    [City]             NVARCHAR (50)  NULL,
    [Phone2]           NVARCHAR (MAX) NULL,
    [Mobile2]          NVARCHAR (MAX) NULL,
    [Email2]           NVARCHAR (MAX) NULL,
    [Job]              NVARCHAR (MAX) NULL,
    [CompanyLocation]  NVARCHAR (MAX) NULL,
    [MandobName]       NVARCHAR (MAX) NULL,
    [SupplieType]      NVARCHAR (MAX) NULL,
    [ForeignName]      NVARCHAR (MAX) NULL,
    [VATNumber]        NVARCHAR (MAX) NULL,
    [Parent]           NVARCHAR (255) NULL,
    [IsDisabled]       BIT            NULL,
    [GLN]              NVARCHAR (255) NULL,
    CONSTRAINT [PK_Suppliers] PRIMARY KEY CLUSTERED ([ID] ASC)
);

