CREATE TABLE [dbo].[Customers] (
    [CustName]                   NVARCHAR (MAX)  NULL,
    [CustDadName]                NVARCHAR (255)  NULL,
    [CustMamName]                NVARCHAR (255)  NULL,
    [CustJob]                    NVARCHAR (255)  NULL,
    [CustGender]                 NVARCHAR (255)  NULL,
    [CustNat]                    NVARCHAR (255)  NULL,
    [CustAddress]                NVARCHAR (MAX)  NULL,
    [CustMobile1]                NVARCHAR (255)  NULL,
    [CustMobile2]                NVARCHAR (255)  NULL,
    [CustPhone1]                 NVARCHAR (255)  NULL,
    [CustPhone2]                 NVARCHAR (255)  NULL,
    [CustMail1]                  NVARCHAR (255)  NULL,
    [CustMail2]                  NVARCHAR (255)  NULL,
    [CustWattsUp]                NVARCHAR (255)  NULL,
    [CustFacbook]                NVARCHAR (255)  NULL,
    [CustBirthday]               DATE            NULL,
    [CutIDentity]                NVARCHAR (255)  NULL,
    [CustMarital]                NVARCHAR (255)  NULL,
    [CustFileDate]               DATE            NULL,
    [CustDr]                     INT             NULL,
    [CustSmsEnabled]             BIT             NULL,
    [CustBlockedNote]            NVARCHAR (MAX)  NULL,
    [CustResource]               NVARCHAR (MAX)  NULL,
    [CustLevelStatue]            NVARCHAR (MAX)  NULL,
    [CustWebSite]                NVARCHAR (MAX)  NULL,
    [CustDrName]                 NVARCHAR (255)  NULL,
    [CustAge]                    NVARCHAR (255)  NULL,
    [CustResourceDetals]         NVARCHAR (MAX)  NULL,
    [CustComment]                NVARCHAR (MAX)  NULL,
    [CustCity]                   NVARCHAR (255)  NULL,
    [CustID]                     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CustDrsName]                NVARCHAR (MAX)  NULL,
    [CustUserName]               NVARCHAR (255)  NULL,
    [CustOldID]                  NVARCHAR (MAX)  NULL,
    [CustAppBlocked]             BIT             NULL,
    [CustAppBlockedNote]         NVARCHAR (MAX)  NULL,
    [PersonalImage]              IMAGE           NULL,
    [IdentityImage]              IMAGE           NULL,
    [Insurance]                  IMAGE           NULL,
    [Medicalhistorycard]         IMAGE           NULL,
    [HealthStatuDetails]         NVARCHAR (MAX)  NULL,
    [HealthStatuNote]            NVARCHAR (MAX)  NULL,
    [Somker]                     BIT             NULL,
    [BloodG]                     NVARCHAR (255)  NULL,
    [ChildNo]                    INT             NULL,
    [InsuranceCoName]            NVARCHAR (100)  NULL,
    [InsuranceAproNo]            NVARCHAR (55)   NULL,
    [InsurancePlic]              NVARCHAR (100)  NULL,
    [InsuranceClass]             NVARCHAR (55)   NULL,
    [PrevSickPseronal]           NVARCHAR (MAX)  NULL,
    [PrevSickFamily]             NVARCHAR (MAX)  NULL,
    [PrevSickConsoltion]         NVARCHAR (MAX)  NULL,
    [PrevSickMedicneThss]        NVARCHAR (MAX)  NULL,
    [PrevSickSpicalDo]           NVARCHAR (MAX)  NULL,
    [LastMofiyDate]              DATETIME        NULL,
    [LastModifyUser]             NVARCHAR (255)  NULL,
    [CustFileTime]               TIME (0)        NULL,
    [IsESignature]               BIT             NULL,
    [DadID]                      NVARCHAR (MAX)  NULL,
    [MamID]                      NVARCHAR (MAX)  NULL,
    [JobSource]                  NVARCHAR (255)  NULL,
    [Qualification]              NVARCHAR (255)  NULL,
    [MotherIdentity]             NVARCHAR (255)  NULL,
    [FatherIdentity]             NVARCHAR (255)  NULL,
    [OtherIdentity]              NVARCHAR (255)  NULL,
    [LastEditUser]               NVARCHAR (255)  NULL,
    [DefaultDiscount]            DECIMAL (18, 2) NULL,
    [SuretyName]                 NVARCHAR (255)  NULL,
    [SuretyID]                   NVARCHAR (255)  NULL,
    [SuretyAddress]              NVARCHAR (MAX)  NULL,
    [PassportNo]                 NVARCHAR (255)  NULL,
    [CustInvoiceBlockedEnb]      BIT             NULL,
    [CustInvoiceBlockedTxt]      NVARCHAR (MAX)  NULL,
    [CustAllBlockedEnb]          BIT             NULL,
    [CustAllBlockedTxt]          NVARCHAR (MAX)  NULL,
    [CustBlocked]                BIT             NULL,
    [RelativeName]               NVARCHAR (MAX)  NULL,
    [RelativePhone]              NVARCHAR (MAX)  NULL,
    [FileTypeID]                 INT             NULL,
    [FileTypeNo]                 NVARCHAR (10)   NULL,
    [FileTypeName]               NVARCHAR (255)  NULL,
    [IdentityType]               NVARCHAR (10)   NULL,
    [DefaultDiscountExpiredDate] DATE            NULL,
    [Weight]                     DECIMAL (5, 2)  NULL,
    [InsuranceExpiredDate]       DATE            NULL,
    [VATNumber]                  NVARCHAR (50)   NULL,
    [BaldiNo]                    NVARCHAR (50)   NULL,
    [InsuranceRelation]          NVARCHAR (50)   NULL,
    [GLN]                        NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([CustID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_Customers_CustNat]
    ON [dbo].[Customers]([CustNat] ASC);

