CREATE TABLE [dbo].[Drs] (
    [DrID]                         INT             IDENTITY (1, 1) NOT NULL,
    [DrNmae]                       NVARCHAR (MAX)  NULL,
    [DrNmaeLatin]                  NVARCHAR (MAX)  NULL,
    [DrJob]                        NVARCHAR (MAX)  NULL,
    [DrPhone]                      NVARCHAR (MAX)  NULL,
    [DrAddress]                    NVARCHAR (MAX)  NULL,
    [DrGender]                     NVARCHAR (MAX)  NULL,
    [DrNat]                        NVARCHAR (MAX)  NULL,
    [DrFacbook]                    NVARCHAR (MAX)  NULL,
    [DrMail]                       NVARCHAR (MAX)  NULL,
    [DrBirthDay]                   DATE            NULL,
    [DrIDentity]                   NVARCHAR (MAX)  NULL,
    [DrSalary]                     DECIMAL (18, 2) NULL,
    [DrMonthlyRevenue1]            DECIMAL (18, 2) NULL,
    [DrMonthlyRevenue2]            DECIMAL (18, 2) NULL,
    [DrMonthlyRevenuePrecent1]     DECIMAL (18, 2) NULL,
    [DrMonthlyRevenuePrecent2]     DECIMAL (18, 2) NULL,
    [DrAnalysisRevenue]            DECIMAL (18, 2) NULL,
    [DrAnalysisPercent]            DECIMAL (18, 2) NULL,
    [DrClinicNum]                  NVARCHAR (MAX)  NULL,
    [DrComment]                    NVARCHAR (MAX)  NULL,
    [AImage]                       IMAGE           NULL,
    [BigImage]                     IMAGE           NULL,
    [AColor]                       INT             NULL,
    [ASharedID]                    NVARCHAR (MAX)  NULL,
    [ADefultDateEnab]              BIT             NULL,
    [ADefultTime]                  DATETIME        NULL,
    [MedicalManager]               BIT             NULL,
    [FileStatus]                   INT             NULL,
    [Specialization]               NVARCHAR (MAX)  NULL,
    [IsLAbManager]                 BIT             NULL,
    [ConsultCodes]                 NVARCHAR (255)  NULL,
    [ConsultDays]                  INT             NULL,
    [ConsultLimitNumbers]          INT             NULL,
    [IsDisableAppointment]         BIT             NULL,
    [WaitingMinutes]               INT             NULL,
    [Order1]                       INT             NULL,
    [IsXrayManager]                BIT             NULL,
    [ReciveAppSMSReminder]         BIT             NULL,
    [SpecialtieID]                 INT             NULL,
    [EmpID]                        INT             NULL,
    [ReciveAppSMSConf]             BIT             NULL,
    [SCHSNumber]                   NVARCHAR (400)  NULL,
    [AllowedAppointmentUsers]      NVARCHAR (MAX)  NULL,
    [IsDentist]                    BIT             NULL,
    [MinAppDurationMinute]         INT             NULL,
    [Stamp]                        IMAGE           NULL,
    [ReviewCodes]                  NVARCHAR (255)  NULL,
    [CustomField1]                 NVARCHAR (255)  NULL,
    [CustomField2]                 NVARCHAR (255)  NULL,
    [CustomField3]                 NVARCHAR (255)  NULL,
    [CustomField4]                 NVARCHAR (255)  NULL,
    [CustomField5]                 NVARCHAR (255)  NULL,
    [IsEmergency]                  BIT             NULL,
    [DisableSMS]                   BIT             NULL,
    [DefaultInvoiceSource]         INT             NULL,
    [MovingClinic]                 BIT             NULL,
    [CCHISpeciality]               NVARCHAR (255)  NULL,
    [AppointmentWithSessionForced] BIT             NULL,
    CONSTRAINT [PK_Drs] PRIMARY KEY CLUSTERED ([DrID] ASC)
);

