CREATE TABLE [dbo].[Employee] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [AddedDateTime]        DATETIME       NULL,
    [NameAr]               NVARCHAR (255) NULL,
    [NameEn]               NVARCHAR (255) NULL,
    [IdentityNumber]       NVARCHAR (MAX) NULL,
    [IdenetyType]          NVARCHAR (255) NULL,
    [IdentityIsEndedDate]  BIT            NULL,
    [[Identity]]EndedDate] DATE           NULL,
    [Mobile1]              NVARCHAR (255) NULL,
    [Mobile2]              NVARCHAR (255) NULL,
    [Phone1]               NVARCHAR (255) NULL,
    [Phone2]               NVARCHAR (255) NULL,
    [Nationality]          NVARCHAR (255) NULL,
    [SourceCityPhone]      NVARCHAR (255) NULL,
    [Salary]               INT            NULL,
    [BdlScan]              INT            NULL,
    [BdlMoalsat]           INT            NULL,
    [OtherBld]             INT            NULL,
    [Image]                IMAGE          NULL,
    [PassPortImage]        IMAGE          NULL,
    [IdentityImage]        IMAGE          NULL,
    [ContractImage]        IMAGE          NULL,
    [AcademicQuali]        NVARCHAR (MAX) NULL,
    [MateralStatu]         NVARCHAR (255) NULL,
    [LocalAdress]          NVARCHAR (255) NULL,
    [MailBoxLocal]         NVARCHAR (255) NULL,
    [MailCodeLocal]        NVARCHAR (255) NULL,
    [RevrencedInfo]        NVARCHAR (MAX) NULL,
    [Mail1]                NVARCHAR (255) NULL,
    [Mail2]                NVARCHAR (255) NULL,
    [FixedAdress]          NVARCHAR (MAX) NULL,
    [MailBoxFixed]         NVARCHAR (255) NULL,
    [MailCodeFixed]        NVARCHAR (255) NULL,
    [Religion]             NVARCHAR (255) NULL,
    [OtherImage1]          IMAGE          NULL,
    [OtherImage2]          IMAGE          NULL,
    [Disable]              BIT            NULL,
    [Job]                  NVARCHAR (255) NULL,
    [JobSpical]            NVARCHAR (255) NULL,
    [Birthday]             DATE           NULL,
    [BdlTotal]             INT            NULL,
    [StartContract]        DATE           NULL,
    [EndContract]          DATE           NULL,
    [PassportID]           NVARCHAR (MAX) NULL,
    [PassPortEndDate]      DATE           NULL,
    [Note1]                NVARCHAR (MAX) NULL,
    [Note2]                NVARCHAR (MAX) NULL,
    [Note3]                NVARCHAR (MAX) NULL,
    [Note4]                NVARCHAR (MAX) NULL,
    [Note5]                NVARCHAR (MAX) NULL,
    [Gender]               NVARCHAR (255) NULL,
    [City]                 NVARCHAR (255) NULL,
    [BorderNumber]         NVARCHAR (255) NULL,
    [BorderEnterDate]      DATE           NULL,
    [BorderEndDate]        DATE           NULL,
    [BorderEndDay]         INT            NULL,
    [CurrentCity]          NVARCHAR (255) NULL,
    [JobNumber]            NVARCHAR (255) NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([ID] ASC)
);

