CREATE TABLE [dbo].[Glasses] (
    [ID]         INT            IDENTITY (1, 1) NOT NULL,
    [SphereLN]   NVARCHAR (255) NULL,
    [SphereRN]   NVARCHAR (255) NULL,
    [CylindreLN] NVARCHAR (255) NULL,
    [CylindreRN] NVARCHAR (255) NULL,
    [AxisLN]     NVARCHAR (255) NULL,
    [AxisRN]     NVARCHAR (255) NULL,
    [SphereLF]   NVARCHAR (255) NULL,
    [SphereRF]   NVARCHAR (255) NULL,
    [CylindreLF] NVARCHAR (255) NULL,
    [CylindreRF] NVARCHAR (255) NULL,
    [AxisLF]     NVARCHAR (255) NULL,
    [AxisRF]     NVARCHAR (255) NULL,
    [IPDN]       NVARCHAR (255) NULL,
    [IPDF]       NVARCHAR (255) NULL,
    [Note]       NVARCHAR (MAX) NULL,
    [DateTime]   DATETIME       NULL,
    [UserName]   NVARCHAR (255) NULL,
    [DrName]     NVARCHAR (255) NULL,
    [PatID]      INT            NULL,
    [VACCLN]     NVARCHAR (255) NULL,
    [VACCRN]     NVARCHAR (255) NULL,
    [VACCLF]     NVARCHAR (255) NULL,
    [VACCRF]     NVARCHAR (255) NULL,
    [VACSLN]     NVARCHAR (255) NULL,
    [VACSRN]     NVARCHAR (255) NULL,
    [VACSLF]     NVARCHAR (255) NULL,
    [VACSRF]     NVARCHAR (255) NULL,
    CONSTRAINT [PK_Glasses] PRIMARY KEY CLUSTERED ([ID] ASC)
);

