CREATE TABLE [dbo].[Insurance_OCAF] (
    [ID]                            INT            IDENTITY (1, 1) NOT NULL,
    [CustID]                        INT            NULL,
    [UserName]                      NVARCHAR (MAX) NULL,
    [Date]                          DATE           NULL,
    [Time]                          TIME (0)       NULL,
    [Complaint]                     NVARCHAR (MAX) NULL,
    [Significant]                   NVARCHAR (MAX) NULL,
    [DiagnosisOther]                NVARCHAR (MAX) NULL,
    [CBManagementForm]              BIT            NULL,
    [ManagementLine]                NVARCHAR (MAX) NULL,
    [EstimatedDays]                 NVARCHAR (MAX) NULL,
    [EstimatedExpectedDate]         DATE           NULL,
    [Date1]                         DATE           NULL,
    [Date2]                         DATE           NULL,
    [Date3]                         DATE           NULL,
    [Date4]                         DATE           NULL,
    [NameRelationship]              NVARCHAR (MAX) NULL,
    [CompleteCodeBy]                NVARCHAR (MAX) NULL,
    [AllocateCost]                  NVARCHAR (MAX) NULL,
    [Status]                        TINYINT        NULL,
    [Diagnosis]                     NVARCHAR (MAX) NULL,
    [DrName]                        NVARCHAR (255) NULL,
    [Version]                       NVARCHAR (50)  NULL,
    [CBPlanType]                    BIT            NULL,
    [CBNewVisit]                    BIT            NULL,
    [CBFollowUp]                    BIT            NULL,
    [CBRefill]                      BIT            NULL,
    [CBWalkIn]                      BIT            NULL,
    [CBReferral]                    BIT            NULL,
    [Approval]                      NVARCHAR (255) NULL,
    [Age]                           NVARCHAR (255) NULL,
    [SphereLN]                      NVARCHAR (255) NULL,
    [SphereRN]                      NVARCHAR (255) NULL,
    [CylindreLN]                    NVARCHAR (255) NULL,
    [CylindreRN]                    NVARCHAR (255) NULL,
    [AxisLN]                        NVARCHAR (255) NULL,
    [AxisRN]                        NVARCHAR (255) NULL,
    [SphereLF]                      NVARCHAR (255) NULL,
    [SphereRF]                      NVARCHAR (255) NULL,
    [CylindreLF]                    NVARCHAR (255) NULL,
    [CylindreRF]                    NVARCHAR (255) NULL,
    [AxisLF]                        NVARCHAR (255) NULL,
    [AxisRF]                        NVARCHAR (255) NULL,
    [VALN]                          NVARCHAR (255) NULL,
    [VARN]                          NVARCHAR (255) NULL,
    [VALF]                          NVARCHAR (255) NULL,
    [VARF]                          NVARCHAR (255) NULL,
    [PQN]                           NVARCHAR (255) NULL,
    [PQF]                           NVARCHAR (255) NULL,
    [BifocalR]                      NVARCHAR (255) NULL,
    [BifocalL]                      NVARCHAR (255) NULL,
    [Vertex]                        NVARCHAR (255) NULL,
    [PriamLN]                       NVARCHAR (255) NULL,
    [PriamRN]                       NVARCHAR (255) NULL,
    [PriamLF]                       NVARCHAR (255) NULL,
    [PriamRF]                       NVARCHAR (255) NULL,
    [illness]                       NVARCHAR (MAX) NULL,
    [CBInpatient]                   BIT            NULL,
    [CBOutpatient]                  BIT            NULL,
    [InsuranceCompnay]              NVARCHAR (100) NULL,
    [InsuranceClass]                NVARCHAR (100) NULL,
    [InsurancePolicy]               NVARCHAR (100) NULL,
    [InsuranceMainCompnay]          NVARCHAR (100) NULL,
    [InsuranceMembership]           NVARCHAR (MAX) NULL,
    [AllowExceedApprovalLimit]      BIT            NULL,
    [RelatedID]                     INT            NULL,
    [OperationCodes]                NVARCHAR (255) NULL,
    [IllnessUnit]                   NVARCHAR (255) NULL,
    [CustomField1]                  NVARCHAR (255) NULL,
    [CustomField2]                  NVARCHAR (255) NULL,
    [CustomField3]                  NVARCHAR (255) NULL,
    [CustomField4]                  NVARCHAR (255) NULL,
    [CustomField5]                  NVARCHAR (255) NULL,
    [Code1]                         NVARCHAR (MAX) NULL,
    [Code2]                         NVARCHAR (MAX) NULL,
    [Code3]                         NVARCHAR (MAX) NULL,
    [Code4]                         NVARCHAR (MAX) NULL,
    [InsuranceRelation]             NVARCHAR (50)  NULL,
    [InsuranceExpiredDate]          DATE           NULL,
    [CustomerBirthday]              DATE           NULL,
    [XRayInput1]                    NVARCHAR (MAX) NULL,
    [XRayInput2]                    NVARCHAR (MAX) NULL,
    [XRayInput3]                    NVARCHAR (MAX) NULL,
    [XRayInput4]                    NVARCHAR (MAX) NULL,
    [TreatmentPlan]                 NVARCHAR (MAX) NULL,
    [PatientHistory]                NVARCHAR (MAX) NULL,
    [PhysicalExamination]           NVARCHAR (MAX) NULL,
    [HistoryOfPresentIllness]       NVARCHAR (MAX) NULL,
    [InvestigationResult]           NVARCHAR (50)  NULL,
    [PharmacyApproval]              NVARCHAR (255) NULL,
    [ChiefComplaintCodeValue]       NVARCHAR (30)  NULL,
    [ChiefComplaintCodeDescription] NVARCHAR (255) NULL,
    [ReferralName]                  NVARCHAR (255) NULL,
    [ICD10ErrorsNote]               NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Insurance_OCAF] PRIMARY KEY CLUSTERED ([ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_Insurance_OCAF_AppWait]
    ON [dbo].[Insurance_OCAF]([CustID] ASC, [Date] ASC, [Time] ASC, [DrName] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Insurance_OCAF_Insurance]
    ON [dbo].[Insurance_OCAF]([InsurancePolicy] ASC, [InsuranceClass] ASC, [InsuranceCompnay] ASC);

