CREATE TABLE [dbo].[Insurance_UCAF_DCAF_Works] (
    [ID]                             INT             IDENTITY (1, 1) NOT NULL,
    [Code]                           NVARCHAR (255)  NULL,
    [Name]                           NVARCHAR (255)  NULL,
    [ScientificName]                 NVARCHAR (MAX)  NULL,
    [Type]                           NVARCHAR (255)  NULL,
    [Cost]                           NVARCHAR (255)  NULL,
    [Price]                          DECIMAL (18, 2) NULL,
    [Quantity]                       DECIMAL (18, 2) NULL,
    [Total]                          DECIMAL (18, 2) NULL,
    [Source]                         NVARCHAR (255)  NULL,
    [SourceID]                       INT             NULL,
    [SourceCode]                     NVARCHAR (255)  NULL,
    [CustomName]                     NVARCHAR (255)  NULL,
    [CustomCode]                     NVARCHAR (255)  NULL,
    [Status]                         INT             NULL,
    [IsMedicine]                     BIT             NULL,
    [ToothNo]                        NVARCHAR (255)  NULL,
    [InsuranceApprovedNumber]        NVARCHAR (MAX)  NULL,
    [InternalNote]                   NVARCHAR (MAX)  NULL,
    [Note]                           NVARCHAR (MAX)  NULL,
    [Dose]                           NVARCHAR (255)  NULL,
    [Duration]                       NVARCHAR (255)  NULL,
    [Unit]                           NVARCHAR (50)   NULL,
    [Frequency]                      NVARCHAR (50)   NULL,
    [CCHICode]                       NVARCHAR (255)  NULL,
    [CCHIName]                       NVARCHAR (255)  NULL,
    [InsuranceApprovedAmountWithVat] DECIMAL (18, 2) NULL,
    [ToothSurface]                   NVARCHAR (255)  NULL,
    [GTIN]                           NVARCHAR (255)  NULL,
    [ScientificCode]                 NVARCHAR (255)  NULL,
    [ICD10]                          NVARCHAR (50)   NULL,
    [DrugSelectionReason]            NVARCHAR (255)  NULL,
    CONSTRAINT [PK_Insurance_UCAF_DCAF_Works] PRIMARY KEY CLUSTERED ([ID] ASC)
);

