CREATE TABLE [dbo].[Insurance_UCAF] (
    [ID]                            INT            IDENTITY (1, 1) NOT NULL,
    [CustID]                        INT            NULL,
    [UserName]                      NVARCHAR (MAX) NULL,
    [Date]                          DATE           NULL,
    [Time]                          TIME (0)       NULL,
    [BP]                            NVARCHAR (MAX) NULL,
    [Plus]                          NVARCHAR (MAX) NULL,
    [Temp]                          NVARCHAR (MAX) NULL,
    [illness]                       NVARCHAR (MAX) NULL,
    [CBInpatient]                   BIT            NULL,
    [CBOutpatient]                  BIT            NULL,
    [CBEmergencyCase]               BIT            NULL,
    [Complaint]                     NVARCHAR (MAX) NULL,
    [Significant]                   NVARCHAR (MAX) NULL,
    [DiagnosisOther]                NVARCHAR (MAX) NULL,
    [Code1]                         NVARCHAR (MAX) NULL,
    [Code2]                         NVARCHAR (MAX) NULL,
    [Code3]                         NVARCHAR (MAX) NULL,
    [Code4]                         NVARCHAR (MAX) NULL,
    [CBChronic]                     BIT            NULL,
    [CBCongenital]                  BIT            NULL,
    [CBRTA]                         BIT            NULL,
    [CBWorkRelated]                 BIT            NULL,
    [CBVaccination]                 BIT            NULL,
    [CBCheckUp]                     BIT            NULL,
    [CBPsychiatric]                 BIT            NULL,
    [CBInfertility]                 BIT            NULL,
    [CBpregnancy]                   BIT            NULL,
    [lmp]                           NVARCHAR (MAX) NULL,
    [CBManagementForm]              BIT            NULL,
    [ManagementLine]                NVARCHAR (MAX) NULL,
    [EstimatedDays]                 NVARCHAR (MAX) NULL,
    [EstimatedExpectedDate]         DATE           NULL,
    [Date1]                         DATE           NULL,
    [Date2]                         DATE           NULL,
    [Date3]                         DATE           NULL,
    [Date4]                         DATE           NULL,
    [NameRelationship]              NVARCHAR (MAX) NULL,
    [CompleteCodeBy]                NVARCHAR (MAX) NULL,
    [AllocateCost]                  NVARCHAR (MAX) NULL,
    [Status]                        TINYINT        NULL,
    [Diagnosis]                     NVARCHAR (MAX) NULL,
    [DrName]                        NVARCHAR (255) NULL,
    [Weight]                        NVARCHAR (255) NULL,
    [Height]                        NVARCHAR (255) NULL,
    [RR]                            NVARCHAR (255) NULL,
    [EmergencyCaseLevel]            NVARCHAR (255) NULL,
    [Version]                       NVARCHAR (50)  NULL,
    [CBPlanType]                    BIT            NULL,
    [CBNewVisit]                    BIT            NULL,
    [CBFollowUp]                    BIT            NULL,
    [CBRefill]                      BIT            NULL,
    [CBWalkIn]                      BIT            NULL,
    [CBReferral]                    BIT            NULL,
    [Approval]                      NVARCHAR (255) NULL,
    [Age]                           NVARCHAR (255) NULL,
    [XRayInput1]                    NVARCHAR (MAX) NULL,
    [XRayInput2]                    NVARCHAR (MAX) NULL,
    [XRayInput3]                    NVARCHAR (MAX) NULL,
    [XRayInput4]                    NVARCHAR (MAX) NULL,
    [InsuranceCompnay]              NVARCHAR (100) NULL,
    [InsuranceClass]                NVARCHAR (100) NULL,
    [InsurancePolicy]               NVARCHAR (100) NULL,
    [InsuranceMainCompnay]          NVARCHAR (100) NULL,
    [InsuranceMembership]           NVARCHAR (MAX) NULL,
    [AllowExceedApprovalLimit]      BIT            NULL,
    [RelatedID]                     INT            NULL,
    [OperationCodes]                NVARCHAR (255) NULL,
    [IllnessUnit]                   NVARCHAR (255) NULL,
    [CustomField1]                  NVARCHAR (255) NULL,
    [CustomField2]                  NVARCHAR (255) NULL,
    [CustomField3]                  NVARCHAR (255) NULL,
    [CustomField4]                  NVARCHAR (255) NULL,
    [CustomField5]                  NVARCHAR (255) NULL,
    [InsuranceRelation]             NVARCHAR (50)  NULL,
    [InsuranceExpiredDate]          DATE           NULL,
    [CustomerBirthday]              DATE           NULL,
    [TreatmentPlan]                 NVARCHAR (MAX) NULL,
    [PatientHistory]                NVARCHAR (MAX) NULL,
    [PhysicalExamination]           NVARCHAR (MAX) NULL,
    [HistoryOfPresentIllness]       NVARCHAR (MAX) NULL,
    [InvestigationResult]           NVARCHAR (50)  NULL,
    [PharmacyApproval]              NVARCHAR (255) NULL,
    [ChiefComplaintCodeValue]       NVARCHAR (30)  NULL,
    [ChiefComplaintCodeDescription] NVARCHAR (255) NULL,
    [ReferralName]                  NVARCHAR (255) NULL,
    [ICD10ErrorsNote]               NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Insurance_UCAF] PRIMARY KEY CLUSTERED ([ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_Insurance_UCAF_AppWait]
    ON [dbo].[Insurance_UCAF]([CustID] ASC, [Date] ASC, [Time] ASC, [DrName] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Insurance_UCAF_Insurance]
    ON [dbo].[Insurance_UCAF]([InsurancePolicy] ASC, [InsuranceClass] ASC, [InsuranceCompnay] ASC);

