CREATE TABLE [dbo].[Users] (
    [UserID]           INT            IDENTITY (1, 1) NOT NULL,
    [UserName]         NVARCHAR (255) NULL,
    [UserPass]         NVARCHAR (255) NULL,
    [UserSysName]      NVARCHAR (255) NULL,
    [UserLevel]        NVARCHAR (255) NULL,
    [UserControl]      NVARCHAR (255) NULL,
    [UserLoginLang]    NVARCHAR (255) NULL,
    [UserAllCust]      BIT            NULL,
    [UserRoles]        NVARCHAR (MAX) NULL,
    [UserPhone]        NVARCHAR (255) NULL,
    [UserSection]      NVARCHAR (MAX) NULL,
    [UserFavorite]     NVARCHAR (MAX) NULL,
    [UserEnabled]      BIT            NULL,
    [UserNote]         NVARCHAR (MAX) NULL,
    [UserAddedDate]    DATE           NULL,
    [UserNew]          NVARCHAR (MAX) NULL,
    [UserDesktTop]     NVARCHAR (MAX) NULL,
    [UserStart]        NVARCHAR (MAX) NULL,
    [UserRolesOthers]  NVARCHAR (MAX) NULL,
    [LSettings]        NVARCHAR (MAX) NULL,
    [LastSeen]         DATETIME       NULL,
    [Image]            IMAGE          NULL,
    [LastWrintingDate] DATETIME       NULL,
    [LastWrintingID]   INT            NULL,
    [StarrtUpService]  NVARCHAR (MAX) NULL,
    [Email]            NVARCHAR (MAX) NULL,
    [Gender]           NVARCHAR (255) NULL,
    [PermissionType]   NVARCHAR (MAX) NULL,
    [AllRoles]         BIT            NULL,
    [WorkingTime]      NVARCHAR (MAX) NULL,
    [WorkingTimeEnb]   BIT            NULL,
    [WorkingTimeNote]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserID] ASC)
);

