'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class Messages
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AATM.Libraries.Languages.Messages", GetType(Messages).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction Aborted.
    '''</summary>
    Public Shared ReadOnly Property BfDataEntry_InitiateSave_Transaction_Aborted() As String
        Get
            Return ResourceManager.GetString("BfDataEntry_InitiateSave_Transaction_Aborted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Connection String Error!.
    '''</summary>
    Public Shared ReadOnly Property ConnectionStringError() As String
        Get
            Return ResourceManager.GetString("ConnectionStringError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date can&apos;t be greater than today&apos;s date!.
    '''</summary>
    Public Shared ReadOnly Property DateCanTBeGreaterThanTodaySDate() As String
        Get
            Return ResourceManager.GetString("DateCanTBeGreaterThanTodaySDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date can&apos;t be less than .
    '''</summary>
    Public Shared ReadOnly Property DateCanTBeLessThan() As String
        Get
            Return ResourceManager.GetString("DateCanTBeLessThan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete {0} translation for [&apos;{1}&apos;] ?.
    '''</summary>
    Public Shared ReadOnly Property Delete0TranslationFor1() As String
        Get
            Return ResourceManager.GetString("Delete0TranslationFor1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Following fields are mandatory,.
    '''</summary>
    Public Shared ReadOnly Property FollowingFieldsAreMandatory() As String
        Get
            Return ResourceManager.GetString("FollowingFieldsAreMandatory", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to  Help is not implemented... .
    '''</summary>
    Public Shared ReadOnly Property HelpIsNotImplemented() As String
        Get
            Return ResourceManager.GetString("HelpIsNotImplemented", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid Connection String, specified connection string doesn&apos;t exist..
    '''</summary>
    Public Shared ReadOnly Property InvalidConnectionStringSpecifiedConnectionStringDoesnTExist() As String
        Get
            Return ResourceManager.GetString("InvalidConnectionStringSpecifiedConnectionStringDoesnTExist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Missing Information.
    '''</summary>
    Public Shared ReadOnly Property MissingInformation() As String
        Get
            Return ResourceManager.GetString("MissingInformation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No data found.
    '''</summary>
    Public Shared ReadOnly Property NoDataFound() As String
        Get
            Return ResourceManager.GetString("NoDataFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nothing to delete.
    '''</summary>
    Public Shared ReadOnly Property NothingToDelete() As String
        Get
            Return ResourceManager.GetString("NothingToDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password was not encrypted!.
    '''</summary>
    Public Shared ReadOnly Property PasswordWasNotEncrypted() As String
        Get
            Return ResourceManager.GetString("PasswordWasNotEncrypted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter desired Year of_Report!.
    '''</summary>
    Public Shared ReadOnly Property PleaseEnterDesiredYearOf_Report() As String
        Get
            Return ResourceManager.GetString("PleaseEnterDesiredYearOf_Report", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter the Beginning date for the report!.
    '''</summary>
    Public Shared ReadOnly Property PleaseEnterTheBeginningDateForTheReport() As String
        Get
            Return ResourceManager.GetString("PleaseEnterTheBeginningDateForTheReport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter the Ending date for the report!.
    '''</summary>
    Public Shared ReadOnly Property PleaseEnterTheEndingDateForTheReport() As String
        Get
            Return ResourceManager.GetString("PleaseEnterTheEndingDateForTheReport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, a member cannot be a parent to itself. Sorry, [rest of string was truncated]&quot;;.
    '''</summary>
    Public Shared ReadOnly Property SorryAMemberCannotBeAParentToItself() As String
        Get
            Return ResourceManager.GetString("SorryAMemberCannotBeAParentToItself", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sorry Beginning Date can&apos;t be later than Ending Date.
    '''</summary>
    Public Shared ReadOnly Property SorryBeginningDateCanTBeLaterThanEndingDate() As String
        Get
            Return ResourceManager.GetString("SorryBeginningDateCanTBeLaterThanEndingDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unsuccessful Login.
    '''</summary>
    Public Shared ReadOnly Property UnsuccessfulLogin() As String
        Get
            Return ResourceManager.GetString("UnsuccessfulLogin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Year can&apos;t be greater than today&apos;s year!.
    '''</summary>
    Public Shared ReadOnly Property YearCanTBeGreaterThanTodaySYear() As String
        Get
            Return ResourceManager.GetString("YearCanTBeGreaterThanTodaySYear", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Year can&apos;t be less than.
    '''</summary>
    Public Shared ReadOnly Property YearCanTBeLessThan() As String
        Get
            Return ResourceManager.GetString("YearCanTBeLessThan", resourceCulture)
        End Get
    End Property
End Class
