'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class StringWords
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AATM.Libraries.Languages.StringWords", GetType(StringWords).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancelled.
    '''</summary>
    Public Shared ReadOnly Property Cancelled() As String
        Get
            Return ResourceManager.GetString("Cancelled", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 2018.
    '''</summary>
    Public Shared ReadOnly Property Constant_LastPostingYearForAccountingData() As String
        Get
            Return ResourceManager.GetString("Constant_LastPostingYearForAccountingData", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date can&apos;t be less than.
    '''</summary>
    Public Shared ReadOnly Property DateCanTBeLessThan() As String
        Get
            Return ResourceManager.GetString("DateCanTBeLessThan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete {0} for all languages?.
    '''</summary>
    Public Shared ReadOnly Property Delete0ForAllLanguages() As String
        Get
            Return ResourceManager.GetString("Delete0ForAllLanguages", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Done!.
    '''</summary>
    Public Shared ReadOnly Property Done() As String
        Get
            Return ResourceManager.GetString("Done", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Help.
    '''</summary>
    Public Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No data found.
    '''</summary>
    Public Shared ReadOnly Property NoDataFound() As String
        Get
            Return ResourceManager.GetString("NoDataFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Permanent.
    '''</summary>
    Public Shared ReadOnly Property Permanent() As String
        Get
            Return ResourceManager.GetString("Permanent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to [Error].
    '''</summary>
    Public Shared ReadOnly Property ShowErrorMessage_Error() As String
        Get
            Return ResourceManager.GetString("ShowErrorMessage_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction Aborted.
    '''</summary>
    Public Shared ReadOnly Property Transaction_Aborted() As String
        Get
            Return ResourceManager.GetString("Transaction_Aborted", resourceCulture)
        End Get
    End Property
End Class
