CREATE PROCEDURE dbo.SaveCdJournalAtomic
 @TransactionDate date,@ReferenceNo varchar(15)=NULL,@Amount money,@AccountIdNo smallint,@PaymentType char(1)=NULL,@PayType char(1)=NULL,@PayeeIdNo int=NULL,@PayeeName nvarchar(100)=NULL,@CheckNumber varchar(10)=NULL,@CheckDate date=NULL,@ORNumber varchar(15)=NULL,@DiscountTaken money=NULL,@DiscountAccountIdNo int=NULL,@Applied money=NULL,@UnApplied money=NULL,@VatNumber varchar(15)=NULL,@VatAmount money=NULL,@Notes nvarchar(300)=NULL,@PcClosed bit=0,@Approved bit=0,@Posted bit=0,@Cancelled bit=0,@Items dbo.JournalItemInsert READONLY,@OiItems dbo.CdOiItemInsert READONLY,@JournalIdNo int OUTPUT
AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON;
 IF @TransactionDate>='20260101' AND (NOT EXISTS(SELECT 1 FROM @Items) OR ABS((SELECT COALESCE(SUM(Debit),0) FROM @Items)-(SELECT COALESCE(SUM(Credit),0) FROM @Items))>.01) THROW 51210,'Cash disbursement details are not balanced.',1;
 BEGIN TRAN; BEGIN TRY
  INSERT dbo.CdJournal(TransactionDate,ReferenceNo,Amount,AccountIdNo,PaymentType,PayType,PayeeIdNo,PayeeName,CheckNumber,CheckDate,ORNumber,DiscountTaken,DiscountAccountIdNo,Applied,UnApplied,VatNumber,VatAmount,Notes,PcClosed,Approved,Posted,Cancelled) VALUES(@TransactionDate,@ReferenceNo,@Amount,@AccountIdNo,@PaymentType,@PayType,@PayeeIdNo,@PayeeName,@CheckNumber,@CheckDate,@ORNumber,@DiscountTaken,@DiscountAccountIdNo,@Applied,@UnApplied,@VatNumber,@VatAmount,@Notes,@PcClosed,@Approved,@Posted,@Cancelled);
  SET @JournalIdNo=CONVERT(int,SCOPE_IDENTITY());
  INSERT dbo.CdJournalItem(AccountIdNo,Credit,Debit,JournalIdNo,Notes,PayIdNo,RevCostCenterIdNo,Sequence) SELECT AccountIdNo,Credit,Debit,@JournalIdNo,Notes,PayIdNo,RevCostCenterIdNo,Sequence FROM @Items;
  INSERT dbo.CdOiItem(Amount,ApOpenInvoiceIdNo,DiscountTaken,DjIdNo,Sequence) SELECT Amount,ApOpenInvoiceIdNo,DiscountTaken,@JournalIdNo,Sequence FROM @OiItems;
  DECLARE @s varchar(20)='GL'+CONVERT(varchar(4),YEAR(@TransactionDate))+RIGHT('0'+CONVERT(varchar(2),MONTH(@TransactionDate)),2),@p varchar(10),@m int,@v int; SELECT @v=Value,@p=Prefix,@m=MaxLength FROM dbo.Series WITH(UPDLOCK,HOLDLOCK) WHERE SeriesName=@s; IF @p IS NULL BEGIN SET @p=RIGHT('0'+CONVERT(varchar(2),MONTH(@TransactionDate)),2)+'-';SET @m=3;SET @v=0;INSERT dbo.Series(SeriesName,Value,MaxLength,Prefix,Description) VALUES(@s,0,@m,@p,'GL Series for '+@s);END; SET @v=@v+1;UPDATE dbo.Series SET Value=@v WHERE SeriesName=@s;UPDATE dbo.CdJournal SET ReferenceNo=@p+RIGHT(REPLICATE('0',@m)+CONVERT(varchar(20),@v),@m) WHERE IdNo=@JournalIdNo; COMMIT;
 END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;SET @JournalIdNo=0;THROW;END CATCH END;
GO
