CREATE PROCEDURE dbo.UpdateErJournalAtomic
 @JournalIdNo int,@EmployeeIdNo int,@TransactionDate date,@ReferenceNo varchar(15)=NULL,@TransactionType char(1)=NULL,@Amount money,@AccountIdNo smallint,@Notes nvarchar(255),@Approved bit=0,@Posted bit=0,@Cancelled bit=0,@Items dbo.JournalItemInsert READONLY
AS BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;
 IF NOT EXISTS(SELECT 1 FROM dbo.ErJournal WHERE IdNo=@JournalIdNo) THROW 51320,'Employee reimbursement was not found.',1;
  IF EXISTS(SELECT 1 FROM dbo.ErJournal WHERE IdNo=@JournalIdNo AND Posted=1) THROW 51321,'Posted employee reimbursements cannot be edited.',1;
  IF EXISTS(SELECT 1 FROM dbo.ErJournalItem i JOIN dbo.Reconciled r ON r.JournalCode='ER' AND r.JournalItemIdNo=i.IdNo WHERE i.JournalIdNo=@JournalIdNo) THROW 51322,'Reconciled employee reimbursements cannot be edited.',1;
  IF EXISTS(SELECT 1 FROM dbo.ErOpenInvoice o WHERE (o.JournalIdNo=@JournalIdNo OR EXISTS(SELECT 1 FROM dbo.ErJournalItem i WHERE i.JournalIdNo=@JournalIdNo AND i.IdNo=o.JournalItemIdNo)) AND (o.PaidAmount<>0 OR o.DiscountTaken<>0)) THROW 51326,'Employee reimbursements with settled open-invoice markers cannot be edited.',1;
  IF EXISTS(SELECT 1 FROM dbo.ArOpenInvoice o JOIN dbo.CsrOiItem c ON c.ArOpenInvoiceIdNo=o.IdNo WHERE o.JournalCode='ER' AND o.JournalIdNo=@JournalIdNo) OR EXISTS(SELECT 1 FROM dbo.ApOpenInvoice o JOIN dbo.CdOiItem c ON c.ApOpenInvoiceIdNo=o.IdNo WHERE o.JournalCode='ER' AND o.JournalIdNo=@JournalIdNo) OR EXISTS(SELECT 1 FROM dbo.ApOpenInvoice o JOIN dbo.PcOiItem p ON p.ApOpenInvoiceIdNo=o.IdNo WHERE o.JournalCode='ER' AND o.JournalIdNo=@JournalIdNo) OR EXISTS(SELECT 1 FROM dbo.ApOpenInvoice o JOIN dbo.CkOiItem k ON k.ApOpenInvoiceIdNo=o.IdNo WHERE o.JournalCode='ER' AND o.JournalIdNo=@JournalIdNo) THROW 51335,'Employee reimbursement open invoices with allocations cannot be edited.',1;
  EXEC dbo.AssertJournalNotReconciliationLocked @JournalCode='ER', @JournalIdNo=@JournalIdNo;
 IF @TransactionDate>='20260101' AND EXISTS(SELECT 1 FROM @Items WHERE Debit<0 OR Credit<0 OR (Debit<>0 AND Credit<>0)) THROW 51324,'Employee reimbursement detail lines contain invalid debit/credit values.',1;
 IF @TransactionDate>='20260101' AND EXISTS(SELECT 1 FROM @Items WHERE AccountIdNo=0 AND (Debit<>0 OR Credit<>0)) THROW 51325,'Employee reimbursement detail lines require an account.',1;
 IF @TransactionDate>='20260101' AND (NOT EXISTS(SELECT 1 FROM @Items) OR ABS((SELECT COALESCE(SUM(Debit),0) FROM @Items)-(SELECT COALESCE(SUM(Credit),0) FROM @Items)) > 0.00005) THROW 51323,'Employee reimbursement details are not balanced.',1;
 IF @Cancelled=0 AND EXISTS(SELECT 1 FROM @Items i JOIN dbo.Account a ON a.IdNo=i.AccountIdNo WHERE a.SpecialAccount='AR' AND (i.Debit<>0 OR i.Credit<>0) AND dbo.FnResolveOpenInvoiceParty(i.PayIdNo,'C',NULL) IS NULL) THROW 51336,'An AR employee reimbursement line requires a customer contact.',1;
 IF @Cancelled=0 AND EXISTS(SELECT 1 FROM @Items i JOIN dbo.Account a ON a.IdNo=i.AccountIdNo WHERE a.SpecialAccount='AP' AND (i.Debit<>0 OR i.Credit<>0) AND dbo.FnResolveOpenInvoiceParty(i.PayIdNo,'S',NULL) IS NULL) THROW 51337,'An AP employee reimbursement line requires a supplier contact.',1;
  BEGIN TRAN;BEGIN TRY DELETE o FROM dbo.ErOpenInvoice o WHERE o.JournalIdNo=@JournalIdNo OR EXISTS(SELECT 1 FROM dbo.ErJournalItem i WHERE i.JournalIdNo=@JournalIdNo AND i.IdNo=o.JournalItemIdNo);DELETE FROM dbo.ArOpenInvoice WHERE JournalCode='ER' AND JournalIdNo=@JournalIdNo;DELETE FROM dbo.ApOpenInvoice WHERE JournalCode='ER' AND JournalIdNo=@JournalIdNo;DELETE FROM dbo.ErJournalItem WHERE JournalIdNo=@JournalIdNo;UPDATE dbo.ErJournal SET EmployeeIdNo=@EmployeeIdNo,TransactionDate=@TransactionDate,ReferenceNo=@ReferenceNo,TransactionType=@TransactionType,Amount=@Amount,AccountIdNo=@AccountIdNo,Notes=@Notes,Approved=@Approved,Posted=@Posted,Cancelled=@Cancelled WHERE IdNo=@JournalIdNo;INSERT dbo.ErJournalItem(AccountIdNo,Credit,Debit,JournalIdNo,Notes,PayIdNo,RevCostCenterIdNo,Sequence) SELECT AccountIdNo,Credit,Debit,@JournalIdNo,Notes,PayIdNo,RevCostCenterIdNo,Sequence FROM @Items;INSERT dbo.ArOpenInvoice(JournalCode,JournalIdNo,JournalItemIdNo) SELECT 'ER',@JournalIdNo,i.IdNo FROM dbo.ErJournalItem i JOIN dbo.Account a ON a.IdNo=i.AccountIdNo WHERE i.JournalIdNo=@JournalIdNo AND @Cancelled=0 AND a.SpecialAccount='AR' AND (i.Debit<>0 OR i.Credit<>0);INSERT dbo.ApOpenInvoice(JournalCode,JournalIdNo,JournalItemIdNo) SELECT 'ER',@JournalIdNo,i.IdNo FROM dbo.ErJournalItem i JOIN dbo.Account a ON a.IdNo=i.AccountIdNo WHERE i.JournalIdNo=@JournalIdNo AND @Cancelled=0 AND a.SpecialAccount='AP' AND (i.Debit<>0 OR i.Credit<>0);COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH END;
GO
