//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if !NETFRAMEWORK
using Microsoft.Extensions.Configuration;
#endif

namespace AATM.Data.Sql.My
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings
#if NETFRAMEWORK
        : global::System.Configuration.ApplicationSettingsBase
#endif
    {
#if NETFRAMEWORK
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
#else
        private static readonly System.Lazy<Settings> defaultInstance = new(() => new Settings());
        public static Settings Default => defaultInstance.Value;

        private readonly IConfigurationRoot _configuration;

        private Settings()
        {
            var basePath = GetBasePath();
            var env = GetEnvironmentName();

            var builder = new ConfigurationBuilder()
                .SetBasePath(basePath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env}.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables();

            _configuration = builder.Build();
        }

        private static string GetBasePath()
        {
            try
            {
                var entry = System.Reflection.Assembly.GetEntryAssembly();
                if (entry != null)
                {
                    var dir = System.IO.Path.GetDirectoryName(entry.Location);
                    if (!string.IsNullOrEmpty(dir)) return dir!;
                }
            }
            catch
            {
                // ignore and fall back
            }
            return System.AppContext.BaseDirectory;
        }

        private static string GetEnvironmentName()
        {
            return System.Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")
                   ?? System.Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")
                   ?? "Production";
        }

        public IConfiguration Configuration => _configuration;

        public string? this[string key] => _configuration[key];

        public T GetValue<T>(string key, T defaultValue = default!)
        {
            return _configuration.GetValue<T>(key, defaultValue);
        }

        public T BindSection<T>(string sectionName) where T : new()
        {
            var instance = new T();
            _configuration.GetSection(sectionName).Bind(instance);
            return instance;
        }
#endif
    }
}
