Imports System.ComponentModel
Imports System.Drawing
Imports System.Windows.Forms
Imports AATM.Libraries.BaseControlsLibrary
Imports AATM.Libraries.GlobalFuncNSub

Public Class CTextBox
    Inherits BTextBox
    Implements IEntryControl

    Private _defaultVal As String
    Private _isNumeric As Boolean
    Private _isMandatory As Boolean
    Private _displayOnly As Boolean
    Private _textToSearch As String
    Private _searchAnywhere As Boolean
    Private _oldValue As String
    Private _editingMode As Boolean
    Private _viewable As Boolean
    Private _selectable As Boolean
    Private _editable As Boolean
    Private _isUnique As Boolean = False
    Private WithEvents _contextMenuStrip1 As New ContextMenuStrip
    Private _autoGeneratedValue As Boolean

    Public Sub New()
        MyBase.New()
        Dim myfont As New Font("Sans Serif", 10.0!, FontStyle.Regular)
        DataBoundControl = True
        BorderStyle = BorderStyle.FixedSingle
        ContextMenuStrip = _contextMenuStrip1
        AcceptsTab = False
        AcceptsReturn = False
        Margin = New Padding(1)
        Font = myfont
    End Sub

    Public Property EditingMode As Boolean Implements IEntryControl.EditingMode
        Get
            Return _editingMode
        End Get
        Set(value As Boolean)
            'If Me.Name.ToLower() = "txtprofitcentercode" Then
            '    Debugger.Break()
            'End If
            _editingMode = value
            If value Or DisplayOnly Then
                ForeColor = GlobalVariables.DefaultFormControlReadOnlyForegroundColor
                BackColor = GlobalVariables.DefaultFormControlReadOnlyBackgroundColor
                Me.ReadOnly = True
                Me.Refresh()
            Else
                ForeColor = GlobalVariables.DefaultFormControlForegroundColor
                BackColor = GlobalVariables.DefaultFormControlBackgroundColor
                Me.ReadOnly = False
            End If
        End Set
    End Property

    Public ReadOnly Property Translatable As Boolean Implements IEntryControl.Translatable
        Get
            Return False
        End Get
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control value will be shown but masked by <*> .")>
    <Browsable(True)>
    Public Property Viewable As Boolean
        Get
            Return _viewable
        End Get
        Set
            _viewable = Value
            If Not Value Then
                If PasswordChar = vbNullChar Or PasswordChar = "" Then
                    PasswordChar = Convert.ToChar(" ")
                End If
            End If
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Specify here the custom format for the textbox")>
    <Browsable(True)>
    Public Property CustomFormat As String

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control can be selected.")>
    <Browsable(True)>
    Public Property Selectable As Boolean
        Get
            Return _selectable
        End Get
        Set
            _selectable = Value
            Enabled = Value
            Refresh()
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control can be edited.")>
    <Browsable(True)>
    Public Property Editable As Boolean
        Get
            Return _editable
        End Get
        Set
            _editable = Value
            DisplayOnly = Value
        End Set
    End Property

    'Public Sub MakeEditable(editableControl As Boolean) Implements IEntryControl.MakeEditable
    '    Me.ReadOnly = Not editableControl
    'End Sub

    'Public Sub MakeSelectable(selectable As Boolean) Implements IEntryControl.MakeSelectable
    '    Enabled = selectable
    'End Sub

    'Public Sub MakeVisible(visibleControl As Boolean) Implements IEntryControl.MakeVisible
    '    Me.Visible = visibleControl
    'End Sub

    'Public Sub MakeViewable(Viewable As Boolean) Implements IEntryControl.MakeViewable
    '    If Viewable Then
    '        PasswordChar = Convert.ToChar("*")
    '    End If
    'End Sub

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control will only accept numeric values.")>
    <Browsable(True)>
    Public Property ValueIsNumeric As Boolean
        Get
            Return _isNumeric
        End Get
        Set
            _isNumeric = Value
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control has a unique key constraint.")>
    <Browsable(True)>
    Public Property ValueIsUnique As Boolean
        Get
            Return _isUnique
        End Get
        Set
            _isUnique = Value
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control is Read Only .")>
    <Browsable(True)>
    Public Property DisplayOnly As Boolean
        Get
            Return _displayOnly
        End Get
        Set(value As Boolean)
            _displayOnly = value
            If value Then
                _editingMode = True
            End If
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control is mandatory.")>
    <Browsable(True)>
    Public Property ValueIsMandatory As Boolean
        Get
            Return _isMandatory
        End Get
        Set
            _isMandatory = Value
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that null check will not be done for this control.")>
    <Browsable(True)>
    Public Property IgnoreNullCheck As Boolean = False

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control will accept null values.")>
    Public Property ValueIsNullable As Boolean

    <Category("Custom Properties")>
    <DefaultValue(CType(Nothing, String))>
    <Description("The Default Value that this control will have if initialized or cleared.")>
    <Browsable(True)>
    Public Property DefaultValue As String

    <Category("Custom Properties")>
    <Description("Select the label to which this control is linked.")>
    <Browsable(True)>
    Public Property LinkedLabel As CLabel

    <Category("Custom Properties")>
    <Description("Change to true if this is a computed value. When true this will not be auto validated for empty values.")>
    <Browsable(True)>
    Public Property ComputedValue As Boolean

    Public Property OldValue() As String
        Get
            Return _oldValue
        End Get
        Set(ByVal value As String)
            _oldValue = value
        End Set
    End Property

    Public Sub EnterHandler(sender As Object, e As EventArgs) Handles MyBase.Enter
        _oldValue = Text
        If Not (EditingMode Or DisplayOnly) Then
            ForeColor = GlobalVariables.DefaultFormControlEditingForegroundColor
            BackColor = GlobalVariables.DefaultFormControlEditingBackgroundColor
        End If
    End Sub

    Public Sub LeaveHandler(sender As Object, e As EventArgs) Handles MyBase.Leave
        If Not (EditingMode Or DisplayOnly) Then
            ForeColor = GlobalVariables.DefaultFormControlForegroundColor
            BackColor = GlobalVariables.DefaultFormControlBackgroundColor
        End If
    End Sub

    'Public Sub DisableHandler(sender As Object, e As EventArgs) Handles MyBase.EnabledChanged
    '    ForeColor = CType(IIf(Enabled, Color.Black, SystemColors.ControlLightLight), Color)
    '    BackColor = CType(IIf(Enabled, Color.White, SystemColors.ControlLight), Color)
    'End Sub

    Public Sub CTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Me.Validating
        'Dim errorMsg As String
        'If ValueIsNumeric Then
        '    If Not IsNumeric(Text) Then
        '        If ValueIsNullable And Text.Trim() = "" Then
        '            Text = Nothing
        '            '' nothing to do
        '            ' blank values allowed for nullable fields
        '        Else
        '            e.Cancel = True
        '            errorMsg = "Sorry, only numeric values allowed for this field! The value <" + Text +
        '                       "> is Not allowed. Reverting to previous value."
        '            MessageBox.Show(errorMsg)
        '            Undo()
        '            'MyErrorProvider.ShowErrorMessage(ErrorMsg)
        '        End If
        '    End If
        'End If
    End Sub

#Region "Constant Declarations#"

    ' Text Menu Captions
    Const TextFind = "Find on this field"

    Const TextUndo = "Undo Last Cut/Paste/Delete"
    Const TextCut = "Cut Selected Text"
    Const TextCopy = "Copy Selected Text"
    Const TextPaste = "Paste Text"
    Const TextDelete = "Delete Selected Text"
    Const TextSelectAll = "Select All Text"

#End Region

    Private Sub TextBox1_MouseUp(sender As Object, e As MouseEventArgs) Handles Me.MouseUp
        HandleMouseUp(sender, e)
    End Sub

    Private Sub HandleMouseUp(control As Object, e As MouseEventArgs)

        ' Checking the Mouse right Button
        If e.Button = MouseButtons.Right Then
            control.ContextMenuStrip.Show(control, New Point(e.X, e.Y))
        End If
    End Sub

    Private Sub HandlePopup(sender As Object, e As EventArgs) Handles _contextMenuStrip1.Opening
        ContextHandler(sender, e)
    End Sub

    Protected Sub ContextHandler(sender As Object, e As EventArgs)

        Const separator = "-"

        _contextMenuStrip1.Items.Clear()

        Dim menuItemFind As New ToolStripMenuItem With {
                .Text = TextFind
                }
        _contextMenuStrip1.Items.Add(menuItemFind)
        menuItemFind.ShortcutKeys = Keys.Control Or Keys.F
        menuItemFind.ShortcutKeyDisplayString = "Ctrl-F"
        AddHandler menuItemFind.Click, AddressOf MenuItemFind_Click

        Dim menuItemUndo As New ToolStripMenuItem With {
                .Text = TextUndo
                }
        _contextMenuStrip1.Items.Add(menuItemUndo)
        menuItemUndo.ShortcutKeys = Keys.Control Or Keys.Z
        menuItemUndo.ShortcutKeyDisplayString = "Ctrl-Z"
        'menuItemUndo.Enabled = (IIf(SampleTextBox.CanUndo, True, False))
        AddHandler menuItemUndo.Click, AddressOf MenuItemUndo_Click

        _contextMenuStrip1.Items.Add(separator)

        Dim menuItemCut As New ToolStripMenuItem With {
                .Text = TextCut
                }
        _contextMenuStrip1.Items.Add(menuItemCut)
        ' menuItemCut.Enabled = (IIf(SampleTextBox.SelectionLength = 0, False, True))
        menuItemCut.ShortcutKeys = Keys.Control Or Keys.X
        menuItemCut.ShortcutKeyDisplayString = "Ctrl-X"
        AddHandler menuItemCut.Click, AddressOf MenuItemCut_Click

        Dim menuItemCopy As New ToolStripMenuItem With {
                .Text = TextCopy
                }
        _contextMenuStrip1.Items.Add(menuItemCopy)
        menuItemCopy.ShortcutKeys = Keys.Control Or Keys.C
        menuItemCopy.ShortcutKeyDisplayString = "Ctrl-C"
        'menuItemCopy.Enabled = (IIf(SampleTextBox.SelectionLength = 0, False, True))
        AddHandler menuItemCopy.Click, AddressOf MenuItemCopy_Click

        Dim menuItemPaste As New ToolStripMenuItem With {
                .Text = TextPaste
                }
        _contextMenuStrip1.Items.Add(menuItemPaste)
        menuItemPaste.ShortcutKeys = Keys.Control Or Keys.V
        menuItemPaste.ShortcutKeyDisplayString = "Ctrl-V"
        'menuItemPaste.Enabled = (IIf(My.Computer.Clipboard.GetText() = "", False, True))
        AddHandler menuItemPaste.Click, AddressOf MenuItemPaste_Click

        Dim menuItemDelete As New ToolStripMenuItem With {
                .Text = TextDelete
                }
        _contextMenuStrip1.Items.Add(menuItemDelete)
        menuItemDelete.ShortcutKeys = Keys.Delete
        menuItemDelete.ShortcutKeyDisplayString = "Delete"
        'menuItemDelete.Enabled = (IIf(SampleTextBox.SelectionLength = 0, False, True))
        AddHandler menuItemDelete.Click, AddressOf MenuItemDelete_Click

        _contextMenuStrip1.Items.Add(separator)

        Dim menuItemSelectAll As New ToolStripMenuItem With {
                .Text = TextSelectAll
                }
        _contextMenuStrip1.Items.Add(menuItemSelectAll)
        menuItemSelectAll.ShortcutKeys = Keys.Control Or Keys.A
        menuItemSelectAll.ShortcutKeyDisplayString = "Ctrl-A"
        'menuItemSelectAll.Enabled = (IIf(SampleTextBox.SelectionLength = SampleTextBox.Text.Length Or SampleTextBox.SelectionLength = SampleTextBox.Text.Trim.Length, False, True))
        AddHandler menuItemSelectAll.Click, AddressOf MenuItemSelectAll_Click

        _contextMenuStrip1.Items.Add(separator)

        'End If
    End Sub

    Private Sub MenuItemFind_Click()
        Dim myForm = FindForm()
        Dim pnt As Point
        Dim searchForm = New CFindForm
        Dim screenRectangle As Rectangle
        Dim formLocation As Point
        screenRectangle = Screen.PrimaryScreen.WorkingArea
        searchForm.StartPosition = FormStartPosition.Manual
        pnt = myForm.PointToScreen(Location)
        'If System.ComponentModel.LicenseManager.UsageMode <> System.ComponentModel.LicenseUsageMode.Designtime Then
        '    If GlobalVariables.RightToLeftLayout Then
        '        formLocation = New Point(pnt.X - Width - SearchForm.Width, pnt.Y)
        '        If formLocation.X < 0 Then
        '            formLocation.X = pnt.X - Width
        '            formLocation.Y += Height
        '        End If
        '    Else
        '        formLocation = New Point(pnt.X + Width, pnt.Y)
        '        If formLocation.X + SearchForm.Width > screenRectangle.Width Then
        '            formLocation.X = pnt.X - SearchForm.Width
        '            If Not GlobalVariables.RightToLeftLayout Then
        '                ' this will cover the label so add controls height to display the caption
        '                formLocation.Y += Height
        '            End If
        '        End If
        '    End If
        'End If
        If formLocation.Y + searchForm.Height > screenRectangle.Height Then
            formLocation.Y = pnt.Y - searchForm.Height + Height
        End If
        searchForm.Location = formLocation
        'If System.ComponentModel.LicenseManager.UsageMode <> System.ComponentModel.LicenseUsageMode.Designtime Then
        '    SearchForm.RightToLeftLayout = myForm.RightToLeftLayout
        '    SearchForm.RightToLeft = myForm.RightToLeft
        'End If
        searchForm.ShowDialog()
        _textToSearch = searchForm.TextToSearch
        _searchAnywhere = Convert.ToBoolean(searchForm.GetSearchAnywhere)
        searchForm.Dispose()
        If _textToSearch <> "" Then

            CallByName(myForm, "FindField", CallType.Method, Me)

        End If
    End Sub

    Public Function GetTextToSearch() As String
        Return _textToSearch
    End Function

    Public Function GetSearchAnywhere() As Boolean
        Return _searchAnywhere
    End Function

    Private Sub MenuItemCut_Click()
        Cut()
    End Sub

    Private Sub MenuItemCopy_Click()
        Copy()
    End Sub

    Private Sub MenuItemPaste_Click()
        Paste()
    End Sub

    Private Sub MenuItemSelectAll_Click()
        SelectAll()
    End Sub

    Private Sub MenuItemUndo_Click()
        Undo()
    End Sub

    Private Sub MenuItemDelete_Click()
        Dim clipBoardText As String
        clipBoardText = Clipboard.GetText()
        Cut()
        If clipBoardText <> "" Then
            Clipboard.SetText(clipBoardText)
        End If
    End Sub

    Private Sub CTextBox_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.Enter Then
            e.SuppressKeyPress = True
            e.Handled = True
            'Me.SelectNextControl(Me, True, True, true, true)
            SendKeys.Send("{TAB}")
            'SendWait("{TAB}")
        ElseIf ValueIsNumeric Then
            If ((e.KeyCode >= Keys.D0 And e.KeyCode <= Keys.D9) Or
                (e.KeyCode >= Keys.NumPad0 And e.KeyCode <= Keys.NumPad9) Or
                (e.KeyCode >= Keys.F1 And e.KeyCode <= Keys.F24) Or
                e.KeyCode = Keys.Decimal Or e.KeyCode = Keys.Subtract Or e.KeyCode = Keys.Delete Or
                e.KeyCode = Keys.Insert Or e.KeyCode = Keys.Back Or e.KeyCode = Keys.OemPeriod Or e.KeyCode = Keys.OemMinus Or
                e.KeyCode = Keys.Up Or e.KeyCode = Keys.Down Or e.KeyCode = Keys.Left Or e.KeyCode = Keys.Right) Then
            Else
                e.SuppressKeyPress = True
                e.Handled = True
                Beep()
            End If

        End If
    End Sub

    Private Sub CTextBox_LostFocus(ByVal sender As Object,
        ByVal e As System.EventArgs) Handles MyBase.LostFocus
        If Me.CustomFormat IsNot Nothing Then
            Text = String.Format("{0:" + Me.CustomFormat + "}", Convert.ToDecimal(NumParser(Of Decimal)(Text)))
        End If
    End Sub

    Private Sub CTextBox_GotFocus(ByVal sender As Object, ByVal e As System.EventArgs) Handles MyBase.GotFocus
        'Debugger.Break()
    End Sub

    'Private Sub CTextBox_KeyUp(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
    '    Try
    '        Dim iKeep As Integer = SelectionStart - 1
    '        For i As Integer = iKeep To 0 + 1
    '            If Text(i) = ","c Then iKeep -= 1
    '        Next
    '        Text = String.Format("{0:N2}", Convert.ToInt32(Text.Replace(",", "")))
    '        For i As Integer = 0 To iKeep - 1
    '            If Text(i) = ","c Then iKeep += 1
    '        Next
    '        SelectionStart = iKeep + 1
    '    Catch
    '    End Try
    'End Sub

    Public Function ValueChanged()
        If Text = _oldValue Then
            Return False
        End If
        Return True
    End Function

End Class