Imports System.ComponentModel
Imports System.Drawing
Imports System.Windows.Forms
Imports AATM.Libraries.AatmInterfaces
Imports AATM.Libraries.BaseControlsLibrary
Imports AATM.Libraries.GlobalFuncNSub
Imports AATM.Libraries.Messaging

Public Class CTextBox
    Inherits BTextBox
    Implements IEntryControl, IFindableControl, ILinkedLabel

    Private _defaultVal As String
    Private _oldValue As String
    Private _editingMode As Boolean = True
    Private _translatable As Boolean = False
    Private _controlName As String

    'Private _viewable As Boolean
    'Private _selectable As Boolean
    Private _editable As Boolean

    Private WithEvents _contextMenuStrip1 As New ContextMenuStrip
    Private _autoGeneratedValue As Boolean
    Private _contextHandlerOn As Boolean = False
    Private _displayOnly As Boolean

    Public Sub New()
        MyBase.New()
        Dim myFont As New Font("Sans Serif", 10.0!, FontStyle.Regular)
        DataBoundControl = True
        BorderStyle = BorderStyle.FixedSingle
        ContextMenuStrip = _contextMenuStrip1
        ShortcutsEnabled = True
        AcceptsTab = False
        AcceptsReturn = False
        Margin = New Padding(1)
        Font = myFont
    End Sub

    Public Property EditingMode As Boolean Implements IEntryControl.EditingMode
        Get
            Return _editingMode
        End Get
        Set(value As Boolean)
            If Not AlwaysEditable Then
                _editingMode = value
                UpdateDisplayOnlyControl()
            End If
        End Set
    End Property

    Public Sub UpdateDisplayOnlyControl()
        If _editingMode And Not DisplayOnly Then
            [ReadOnly] = False
            ForeColor = GlobalVariables.DefaultFormControlForegroundColor
            BackColor = GlobalVariables.DefaultFormControlBackgroundColor
        Else
            [ReadOnly] = False
            ForeColor = GlobalVariables.DefaultFormControlReadOnlyForegroundColor
            BackColor = GlobalVariables.DefaultFormControlReadOnlyBackgroundColor
            [ReadOnly] = True
        End If
    End Sub

    Public Property Translatable As Boolean Implements IEntryControl.Translatable
        Get
            Return False
        End Get
        Set(value As Boolean)
            _translatable = value
        End Set
    End Property

    '<Category("Custom Properties")>
    '<DefaultValue(False)>
    '<Description("Set to True to specify that this control value will be shown but masked by <*> .")>
    '<Browsable(True)>
    'Public Property Viewable As Boolean
    '    Get
    '        Return _viewable
    '    End Get
    '    Set
    '        _viewable = Value
    '        If Not Value Then
    '            If PasswordChar = vbNullChar Or PasswordChar = "" Then
    '                PasswordChar = Convert.ToChar(" ")
    '            End If
    '        End If
    '    End Set
    'End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Specify here the custom format for the textbox")>
    <Browsable(True)>
    Public Property CustomFormat As String

    '<Category("Custom Properties")>
    '<DefaultValue(False)>
    '<Description("Set to True to specify that this control can be selected.")>
    '<Browsable(True)>
    'Public Property Selectable As Boolean
    '    Get
    '        Return _selectable
    '    End Get
    '    Set
    '        _selectable = Value
    '        Enabled = Value
    '        Refresh()
    '    End Set
    'End Property


    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control is always editable.")>
    Public Property AlwaysEditable As Boolean = False

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control can be edited.")>
    Public Property Editable As Boolean
        Get
            Return _editable
        End Get
        Set
            _editable = Value
            'DisplayOnly = Value
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control doesn't change alignment.")>
    <Browsable(True)>
    Public Property FixedAlignment As Boolean

    <Category("Custom Properties")>
    <Description("Set to the lowest allowed value for this control")>
    <Browsable(True)>
    Public Property MinimumValue As Decimal? = Nothing

    <Category("Custom Properties")>
    <Description("Set to the highest allowed value for this control")>
    <Browsable(True)>
    Public Property MaximumValue As Decimal? = Nothing

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Specify here the temporary 'maxlength' value for data entry (useful to override default 'MaxLength' property).")>
    <Browsable(True)>
    Public Property OverrideMaxLength As Integer = 0

    'Public Sub MakeEditable(editableControl As Boolean) Implements IEntryControl.MakeEditable
    '    Me.ReadOnly = Not editableControl
    'End Sub

    'Public Sub MakeSelectable(selectable As Boolean) Implements IEntryControl.MakeSelectable
    '    Enabled = selectable
    'End Sub

    'Public Sub MakeVisible(visibleControl As Boolean) Implements IEntryControl.MakeVisible
    '    Me.Visible = visibleControl
    'End Sub

    'Public Sub MakeViewable(Viewable As Boolean) Implements IEntryControl.MakeViewable
    '    If Viewable Then
    '        PasswordChar = Convert.ToChar("*")
    '    End If
    'End Sub

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control will only accept numeric values.")>
    <Browsable(True)>
    Public Property ValueIsNumeric As Boolean

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control has a unique key constraint.")>
    <Browsable(True)>
    Public Property ValueIsUnique As Boolean = False

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control must be unique, however blanks allowed.")>
    <Browsable(True)>
    Public Property ValueIsUniqueBlanksAllowed As Boolean

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control is Read Only .")>
    <Browsable(True)>
    Public Property DisplayOnly As Boolean
        Get
            Return _displayOnly
        End Get
        Set(value As Boolean)
            If Not AlwaysEditable Then
                If _displayOnly = value Then Exit Property
                _displayOnly = value
                If value Then
                    [ReadOnly] = True
                    ForeColor = GlobalVariables.DefaultFormControlReadOnlyForegroundColor
                    BackColor = GlobalVariables.DefaultFormControlReadOnlyBackgroundColor
                Else
                    [ReadOnly] = False
                    ForeColor = GlobalVariables.DefaultFormControlForegroundColor
                    BackColor = GlobalVariables.DefaultFormControlBackgroundColor
                End If
            Else
                _displayOnly = False
                Me.ReadOnly = False
            End If
        End Set
    End Property

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control is mandatory.")>
    <Browsable(True)>
    Public Property ValueIsMandatory As Boolean

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that null check will not be done for this control.")>
    <Browsable(True)>
    Public Property IgnoreNullCheck As Boolean = False

    <Category("Custom Properties")>
    <DefaultValue(False)>
    <Description("Set to True to specify that this control will accept null values.")>
    Public Property ValueIsNullable As Boolean

    <Category("Custom Properties")>
    <DefaultValue(CType(Nothing, String))>
    <Description("The Default Value that this control will have if initialized or cleared.")>
    <Browsable(True)>
    Public Property DefaultValue As String

    <Category("Custom Properties")>
    <Description("Select the label to which this control is linked.")>
    <Browsable(True)>
    Public Property LinkedLabel As CLabel Implements ILinkedLabel.LinkedLabel

    Public Function GetControlDescription(Optional defaultDescription As String = Nothing) Implements ILinkedLabel.GetControlDescription
        Dim description As String
        If LinkedLabel Is Nothing OrElse LinkedLabel.Text Is Nothing OrElse LinkedLabel.Text = "" Then
            description = If(defaultDescription Is Nothing OrElse defaultDescription = "", Name, defaultDescription)
        Else
            description = LinkedLabel.Text
        End If
        Return description
    End Function

    <Category("Custom Properties")>
    <Description("Change to true if this is a computed value. When true this will not be auto validated for empty values.")>
    <Browsable(True)>
    Public Property ComputedValue As Boolean

    Public Property OldValue() As String
        Get
            Return _oldValue
        End Get
        Set(ByVal value As String)
            _oldValue = value
        End Set
    End Property

    Public Sub SetValue(ByRef value)
        If value Is DBNull.Value OrElse value Is Nothing Then
            Text = Nothing
        Else
            Text = value
        End If
    End Sub

    Public Function GetValue(Of T)() As Object
        If Text Is Nothing Then
            Return Nothing
        End If
        Dim objType As Type = GetType(T)
        Return CalculateValue(objType)
        'Dim objUnderlyingType As Type = Nullable.GetUnderlyingType(objType)
        'If objUnderlyingType <> Nothing Then
        '    Return CalculateValue(objUnderlyingType)
        'Else
        '    Return CalculateValue(objType)
        'End If
        'Return Text
    End Function

    Public Function CalculateValue(objDataType)
        Select Case objDataType
            Case GetType(String)
                Return Text
            Case GetType(Short), GetType(Short?) 'Int16
                Return NumParser(Of Short)(Text)
            Case GetType(Integer), GetType(Integer?) 'Int32
                Return NumParser(Of Integer)(Text)
            Case GetType(Decimal), GetType(Decimal?)
                Return NumParser(Of Decimal)(Text)
            Case GetType(Boolean), GetType(Boolean?)
                Return BoolParser(Of Boolean)(Text)
            Case GetType(DateTime), GetType(DateTime?)
                Return DateParser(Of DateTime)(Text)
            Case GetType(Date), GetType(Date?)
                Return DateParser(Of Date)(Text)
            Case GetType(Single), GetType(Single?)
                Return NumParser(Of Single)(Text)
            Case GetType(Double), GetType(Double?)
                Return NumParser(Of Double)(Text)
            Case GetType(Byte), GetType(Byte?)
                Return NumParser(Of Byte)(Text)
            Case GetType(SByte), GetType(SByte?)
                Return NumParser(Of SByte)(Text)
            Case GetType(Char), GetType(Char?)
                Return Text
            Case GetType(UInteger), GetType(UInteger?)
                Return NumParser(Of Double)(Text)
            Case GetType(ULong), GetType(ULong)
                Return NumParser(Of ULong)(Text)
            Case GetType(UShort), GetType(UShort)
                Return NumParser(Of UShort)(Text)
        End Select
        Return Text
    End Function

#Region "FindableControl"

    <Category("Custom Properties")>
    <Description("Set to True to enable find on this field.")>
    <DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)>
    Public Property FindEnabled As Boolean Implements IFindableControl.FindEnabled

    Public ReadOnly Property SearchMode As IFindableControl.SearchModeEnum Implements IFindableControl.SearchMode
        Get
            Return IFindableControl.SearchModeEnum.TextBox
        End Get
    End Property

    Public ReadOnly Property FindDataSource As Object Implements IFindableControl.FindDataSource
        Get
            Return Nothing
        End Get
    End Property

    Public ReadOnly Property FindDisplayMember As String Implements IFindableControl.FindDisplayMember
        Get
            Return Nothing
        End Get
    End Property

    Public ReadOnly Property FindValueMember As String Implements IFindableControl.FindValueMember
        Get
            Return Nothing
        End Get
    End Property

    Private Property IgnoreCase As Boolean Implements IFindableControl.IgnoreCase

    Public Property SearchPlace As IFindableControl.SearchPlaceEnum Implements IFindableControl.SearchPlace

    Public Property BegFindValue As Object Implements IFindableControl.BegFindValue

    Public Property EndFindValue As Object Implements IFindableControl.EndFindValue

    Public Property FieldName As String Implements IFindableControl.FieldName

    Public Property FindDataType As IFindableControl.DataTypeEnum Implements IFindableControl.FindDataType

    Public Property FieldDescription As String Implements IFindableControl.FieldDescription

#End Region

    'Private Function GetDataType() As IFindableControl.DataTypeEnum
    '    If TypeOf Text Is String Then
    '        Return IFindableControl.DataTypeEnum.String
    '    Else
    '        Return IFindableControl.DataTypeEnum.Date
    '    End If
    'End Function

    Public Sub EnterHandler(sender As Object, e As EventArgs) Handles MyBase.Enter
        _oldValue = Text
        'for editing
        'If EditingMode And Not DisplayOnly Then
        '    ForeColor = GlobalVariables.DefaultFormControlEditingForegroundColor
        '    BackColor = GlobalVariables.DefaultFormControlEditingBackgroundColor
        'Else
        '    ForeColor = GlobalVariables.DefaultFormControlReadOnlyForegroundColor
        '    BackColor = GlobalVariables.DefaultFormControlReadOnlyBackgroundColor
        'End If
    End Sub

    Public Sub LeaveHandler(sender As Object, e As EventArgs) Handles MyBase.Leave
        If EditingMode And Not DisplayOnly Then
            ForeColor = GlobalVariables.DefaultFormControlForegroundColor
            BackColor = GlobalVariables.DefaultFormControlBackgroundColor
        Else
            If Not AlwaysEditable Then
                ForeColor = GlobalVariables.DefaultFormControlReadOnlyForegroundColor
                BackColor = GlobalVariables.DefaultFormControlReadOnlyBackgroundColor
            Else
                ForeColor = GlobalVariables.DefaultFormForegroundColor
                BackColor = GlobalVariables.DefaultFormBackgroundColor
            End If
        End If
    End Sub

    'Public Sub DisableHandler(sender As Object, e As EventArgs) Handles MyBase.EnabledChanged
    '    ForeColor = CType(IIf(Enabled, Color.Black, SystemColors.ControlLightLight), Color)
    '    BackColor = CType(IIf(Enabled, Color.White, SystemColors.ControlLight), Color)
    'End Sub

    'Public Sub CTextBox_Validating(sender As Object, e As CancelEventArgs) Handles Me.Validating
    '    'Dim errorMsg As String
    '    'If ValueIsNumeric Then
    '    '    If Not IsNumeric(Text) Then
    '    '        If ValueIsNullable And Text.Trim() = "" Then
    '    '            Text = Nothing
    '    '            '' nothing to do
    '    '            ' blank values allowed for nullable fields
    '    '        Else
    '    '            e.Cancel = True
    '    '            errorMsg = "Sorry, only numeric values allowed for this field! The value <" + Text +
    '    '                       "> is Not allowed. Reverting to previous value."
    '    '            MessageBox.Show(errorMsg)
    '    '            Undo()
    '    '            'MyErrorProvider.ShowErrorMessage(ErrorMsg)
    '    '        End If
    '    '    End If
    '    'End If
    'End Sub

#Region "Declarations#"

    ' Text Menu Captions
    Private Shared ReadOnly _textFind = MessagingService.TranslateCaption("Find on this field")

    Private Shared ReadOnly _textCut = MessagingService.TranslateCaption("Cut Selected Text")
    Private Shared ReadOnly _textCopy = MessagingService.TranslateCaption("Copy Selected Text")
    Private Shared ReadOnly _textPaste = MessagingService.TranslateCaption("Paste Text")
    Private Shared ReadOnly _textUndo = MessagingService.TranslateCaption("Undo Last Action")
    Private Shared ReadOnly _textDelete = MessagingService.TranslateCaption("Delete Selected Text")
    Private Shared ReadOnly _textSelectAll = MessagingService.TranslateCaption("Select All Text")

#End Region

    'Private Sub TextBox1_MouseUp(sender As Object, e As MouseEventArgs) Handles Me.MouseUp
    '    HandleMouseUp(sender, e)
    'End Sub

    'Private Sub HandleMouseUp(control As Object, e As MouseEventArgs)

    '    ' Checking the Mouse right Button
    '    If e.Button = MouseButtons.Right Then
    '        control.ContextMenuStrip.Show(control, New Point(e.X, e.Y))
    '    End If
    'End Sub

    Private Sub HandlePopup(sender As Object, e As EventArgs) Handles _contextMenuStrip1.Opening
        ContextHandler(sender, e)
    End Sub

    Protected Sub ContextHandler(sender As Object, e As EventArgs)

        Const separator = "-"

        _contextMenuStrip1.Items.Clear()

        Dim menuItemFind As New ToolStripMenuItem With {
                .Text = _textFind
                }
        _contextMenuStrip1.Items.Add(menuItemFind)
        menuItemFind.ShortcutKeys = Keys.Control Or Keys.F
        menuItemFind.ShortcutKeyDisplayString = $"Ctrl-F"
        AddHandler menuItemFind.Click, AddressOf MenuItemFind_Click

        Dim menuItemUndo As New ToolStripMenuItem With {
                .Text = _textUndo
                }
        _contextMenuStrip1.Items.Add(menuItemUndo)
        menuItemUndo.ShortcutKeys = Keys.Control Or Keys.Z
        menuItemUndo.ShortcutKeyDisplayString = $"Ctrl-Z"
        'menuItemUndo.Enabled = (IIf(SampleTextBox.CanUndo, True, False))
        AddHandler menuItemUndo.Click, AddressOf MenuItemUndo_Click

        _contextMenuStrip1.Items.Add(separator)

        Dim menuItemCut As New ToolStripMenuItem With {
                .Text = _textCut
                }
        _contextMenuStrip1.Items.Add(menuItemCut)
        menuItemCut.Enabled = (SelectionLength <> 0)
        menuItemCut.ShortcutKeys = Keys.Control Or Keys.X
        menuItemCut.ShortcutKeyDisplayString = $"Ctrl-X"
        AddHandler menuItemCut.Click, AddressOf MenuItemCut_Click

        Dim menuItemCopy As New ToolStripMenuItem With {
                .Text = _textCopy
                }
        _contextMenuStrip1.Items.Add(menuItemCopy)
        menuItemCopy.ShortcutKeys = Keys.Control Or Keys.C
        menuItemCopy.ShortcutKeyDisplayString = $"Ctrl-C"
        menuItemCopy.Enabled = (SelectionLength <> 0)
        AddHandler menuItemCopy.Click, AddressOf MenuItemCopy_Click

        Dim menuItemPaste As New ToolStripMenuItem With {
                .Text = _textPaste
                }
        _contextMenuStrip1.Items.Add(menuItemPaste)
        menuItemPaste.ShortcutKeys = Keys.Control Or Keys.V
        menuItemPaste.ShortcutKeyDisplayString = $"Ctrl-V"
        menuItemPaste.Enabled = (My.Computer.Clipboard.GetText() <> "")
        AddHandler menuItemPaste.Click, AddressOf MenuItemPaste_Click

        Dim menuItemDelete As New ToolStripMenuItem With {
                .Text = _textDelete
                }
        _contextMenuStrip1.Items.Add(menuItemDelete)
        menuItemDelete.ShortcutKeys = Keys.Delete
        menuItemDelete.ShortcutKeyDisplayString = $"Delete"
        menuItemDelete.Enabled = (SelectionLength <> 0)
        AddHandler menuItemDelete.Click, AddressOf MenuItemDelete_Click

        _contextMenuStrip1.Items.Add(separator)

        Dim menuItemSelectAll As New ToolStripMenuItem With {
                .Text = _textSelectAll
                }
        _contextMenuStrip1.Items.Add(menuItemSelectAll)
        menuItemSelectAll.ShortcutKeys = Keys.Control Or Keys.A
        menuItemSelectAll.ShortcutKeyDisplayString = $"Ctrl-A"
        menuItemSelectAll.Enabled = (Not (SelectionLength = Text.Length Or SelectionLength = Text.Trim.Length))
        AddHandler menuItemSelectAll.Click, AddressOf MenuItemSelectAll_Click

        _contextMenuStrip1.Items.Add(separator)

    End Sub

    Private Sub MenuItemFind_Click()
        If FindEnabled Then
            Dim myForm = FindForm()
            Dim pnt As Point
            Dim searchForm = New CFindForm(Me)
            Dim screenRectangle As Rectangle
            Dim formLocation As Point
            screenRectangle = Screen.PrimaryScreen.WorkingArea
            searchForm.StartPosition = FormStartPosition.Manual
            pnt = myForm.PointToScreen(Location)
            If formLocation.Y + searchForm.Height > screenRectangle.Height Then
                formLocation.Y = pnt.Y - searchForm.Height + Height
            End If
            FieldName = Name.Substring(3)
            searchForm.Location = formLocation
            Dim x = Invoker.InvokeFunction(myForm, "GetFieldType", {FieldName})
            FindDataType = GetObjectDataType(x)
            searchForm.SetFieldDescription(GetControlDescription(FieldName))
            searchForm.ShowDialog()
            searchForm.Dispose()
            Invoker.InvokeFunction(myForm, "FindFieldNew", {Me})
        Else
            AATM.Libraries.Messaging.MessagingService.Show(True, "MsgNothingToFind")
        End If
    End Sub

    Private Sub MenuItemCut_Click()
        If EditingMode Then
            Cut()
        Else
            MessagingService.Show(True, "MsgOperationNotAvailableInViewMode")
        End If
    End Sub

    Private Sub MenuItemCopy_Click()
        Copy()
    End Sub

    Private Sub MenuItemPaste_Click()
        If EditingMode Then
            Paste()
        Else
            MessagingService.Show(True, "MsgOperationNotAvailableInViewMode")
        End If
    End Sub

    Private Sub MenuItemSelectAll_Click()
        SelectAll()
    End Sub

    Private Sub MenuItemUndo_Click()
        If EditingMode Then
            Undo()
        Else
            MessagingService.Show(True, "MsgOperationNotAvailableInViewMode")
        End If
    End Sub

    Private Sub MenuItemDelete_Click()
        If EditingMode Then
            Dim clipBoardText As String
            clipBoardText = Clipboard.GetText()
            Cut()
            If clipBoardText <> "" Then
                Clipboard.SetText(clipBoardText)
            End If
        Else
            MessagingService.Show(True, "MsgOperationNotAvailableInViewMode")
        End If
    End Sub

    Private Sub CTextBox_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.Enter Then
            If Not AcceptsReturn Then
                SendKeys.Send("{TAB}")
                e.Handled = True
                e.SuppressKeyPress = True
            End If
        End If
    End Sub

    Public Function ValueChanged()
        If Text = _oldValue Then
            Return False
        End If
        Return True
    End Function

    Public Function GetDecimalValue() As Decimal
        If Text <> "" Then
            Return Convert.ToDecimal(Text)
        Else
            Return 0D
        End If
    End Function

End Class