CREATE TABLE [dbo].[att_paycode] (
    [id]             INT            IDENTITY (1, 1) NOT NULL,
    [create_time]    DATETIME2 (7)  NULL,
    [create_user]    NVARCHAR (150) NULL,
    [change_time]    DATETIME2 (7)  NULL,
    [change_user]    NVARCHAR (150) NULL,
    [status]         SMALLINT       NOT NULL,
    [code]           NVARCHAR (20)  NOT NULL,
    [name]           NVARCHAR (50)  NOT NULL,
    [code_type]      SMALLINT       NOT NULL,
    [tag]            SMALLINT       NULL,
    [fixed_code]     SMALLINT       NULL,
    [is_work]        BIT            NOT NULL,
    [fixed_hours]    NUMERIC (8, 2) NOT NULL,
    [is_paid]        BIT            NOT NULL,
    [is_benefit]     BIT            NOT NULL,
    [round_off]      SMALLINT       NOT NULL,
    [min_val]        NUMERIC (4, 1) NOT NULL,
    [display_format] SMALLINT       NOT NULL,
    [symbol]         NVARCHAR (20)  NULL,
    [display_order]  SMALLINT       NOT NULL,
    [desc]           NVARCHAR (MAX) NULL,
    [is_display]     BIT            NOT NULL,
    [is_default]     BIT            NOT NULL,
    [color_setting]  NVARCHAR (30)  NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    UNIQUE NONCLUSTERED ([code] ASC),
    UNIQUE NONCLUSTERED ([name] ASC)
);

