CREATE TABLE [dbo].[backup_iclock_transaction_testrows_20260408] (
    [id]             INT            IDENTITY (1, 1) NOT NULL,
    [company_code]   NVARCHAR (50)  NULL,
    [emp_code]       NVARCHAR (20)  NOT NULL,
    [punch_time]     DATETIME2 (7)  NOT NULL,
    [punch_state]    NVARCHAR (5)   NOT NULL,
    [verify_type]    INT            NOT NULL,
    [work_code]      NVARCHAR (20)  NULL,
    [terminal_sn]    NVARCHAR (50)  NULL,
    [terminal_alias] NVARCHAR (50)  NULL,
    [area_alias]     NVARCHAR (100) NULL,
    [longitude]      FLOAT (53)     NULL,
    [latitude]       FLOAT (53)     NULL,
    [gps_location]   NVARCHAR (MAX) NULL,
    [mobile]         NVARCHAR (50)  NULL,
    [source]         SMALLINT       NULL,
    [purpose]        SMALLINT       NULL,
    [crc]            NVARCHAR (100) NULL,
    [is_attendance]  SMALLINT       NULL,
    [reserved]       NVARCHAR (100) NULL,
    [upload_time]    DATETIME2 (7)  NULL,
    [sync_status]    SMALLINT       NULL,
    [sync_time]      DATETIME2 (7)  NULL,
    [is_mask]        SMALLINT       NULL,
    [temperature]    NUMERIC (4, 1) NULL,
    [emp_id]         INT            NULL,
    [terminal_id]    INT            NULL
);

