CREATE TABLE [dbo].[iclock_devicemoduleconfig] (
    [id]                              INT            IDENTITY (1, 1) NOT NULL,
    [create_time]                     DATETIME2 (7)  NULL,
    [create_user]                     NVARCHAR (150) NULL,
    [change_time]                     DATETIME2 (7)  NULL,
    [change_user]                     NVARCHAR (150) NULL,
    [status]                          SMALLINT       NOT NULL,
    [enable_registration]             BIT            NOT NULL,
    [enable_resigned_filter]          BIT            NOT NULL,
    [enable_auto_add]                 BIT            NOT NULL,
    [enable_name_upload]              BIT            NOT NULL,
    [enable_name_download]            BIT            NOT NULL,
    [enable_card_upload]              BIT            NOT NULL,
    [encryption]                      BIT            NOT NULL,
    [timezone]                        SMALLINT       NOT NULL,
    [global_setup]                    BIT            NOT NULL,
    [heartbeat]                       INT            NOT NULL,
    [transfer_mode]                   SMALLINT       NOT NULL,
    [transfer_interval]               INT            NOT NULL,
    [transfer_time]                   NVARCHAR (100) NOT NULL,
    [sync_mode]                       SMALLINT       NOT NULL,
    [sync_time]                       NVARCHAR (100) NOT NULL,
    [transaction_retention]           INT            NOT NULL,
    [command_retention]               INT            NOT NULL,
    [dev_log_retention]               INT            NOT NULL,
    [upload_log_retention]            INT            NOT NULL,
    [user_notification_log_retention] INT            NOT NULL,
    [report_log_retention]            INT            NOT NULL,
    [edit_policy]                     SMALLINT       NOT NULL,
    [import_policy]                   SMALLINT       NOT NULL,
    [mobile_policy]                   SMALLINT       NOT NULL,
    [device_policy]                   SMALLINT       NOT NULL,
    [api_policy]                      SMALLINT       NOT NULL,
    [visitor_policy]                  SMALLINT       NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

