CREATE TABLE [dbo].[iclock_terminal] (
    [id]                INT            IDENTITY (1, 1) NOT NULL,
    [create_time]       DATETIME2 (7)  NULL,
    [create_user]       NVARCHAR (150) NULL,
    [change_time]       DATETIME2 (7)  NULL,
    [change_user]       NVARCHAR (150) NULL,
    [status]            SMALLINT       NOT NULL,
    [ip_address]        NVARCHAR (39)  NOT NULL,
    [terminal_tz]       SMALLINT       NOT NULL,
    [heartbeat]         INT            NOT NULL,
    [transfer_mode]     SMALLINT       NOT NULL,
    [transfer_interval] INT            NOT NULL,
    [transfer_time]     NVARCHAR (100) NOT NULL,
    [fw_ver]            NVARCHAR (100) NULL,
    [push_protocol]     NVARCHAR (50)  NOT NULL,
    [push_ver]          NVARCHAR (50)  NULL,
    [language]          INT            NULL,
    [terminal_name]     NVARCHAR (30)  NULL,
    [platform]          NVARCHAR (30)  NULL,
    [oem_vendor]        NVARCHAR (50)  NULL,
    [user_count]        INT            NULL,
    [transaction_count] INT            NULL,
    [fp_count]          INT            NULL,
    [fp_alg_ver]        NVARCHAR (10)  NULL,
    [face_count]        INT            NULL,
    [face_alg_ver]      NVARCHAR (10)  NULL,
    [fv_count]          INT            NULL,
    [fv_alg_ver]        NVARCHAR (10)  NULL,
    [palm_count]        INT            NULL,
    [palm_alg_ver]      NVARCHAR (10)  NULL,
    [lock_func]         SMALLINT       NOT NULL,
    [log_stamp]         NVARCHAR (30)  NULL,
    [op_log_stamp]      NVARCHAR (30)  NULL,
    [capture_stamp]     NVARCHAR (30)  NULL,
    [sn]                NVARCHAR (50)  NOT NULL,
    [alias]             NVARCHAR (50)  NOT NULL,
    [real_ip]           NVARCHAR (39)  NULL,
    [state]             INT            NOT NULL,
    [product_type]      SMALLINT       NULL,
    [is_attendance]     SMALLINT       NOT NULL,
    [is_registration]   SMALLINT       NOT NULL,
    [purpose]           SMALLINT       NULL,
    [controller_type]   SMALLINT       NULL,
    [authentication]    SMALLINT       NOT NULL,
    [style]             NVARCHAR (20)  NULL,
    [upload_flag]       NVARCHAR (10)  NULL,
    [is_tft]            BIT            NOT NULL,
    [last_activity]     DATETIME2 (7)  NULL,
    [upload_time]       DATETIME2 (7)  NULL,
    [push_time]         DATETIME2 (7)  NULL,
    [is_access]         SMALLINT       NOT NULL,
    [area_id]           INT            NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [iclock_terminal_area_id_c019c6f0_fk_personnel_area_id] FOREIGN KEY ([area_id]) REFERENCES [dbo].[personnel_area] ([id]),
    UNIQUE NONCLUSTERED ([sn] ASC)
);


GO
CREATE NONCLUSTERED INDEX [iclock_terminal_area_id_c019c6f0]
    ON [dbo].[iclock_terminal]([area_id] ASC);

