CREATE 	PROCEDURE uSpWSL_INVOICES 
        ( 
          @DateFrom as varchar(10),
          @DateUpto as varchar(10),
          @TPA as varchar(15) 
        )
 
AS 
DECLARE @SQLString varchar(8000) 
SET @SQLString = 'INSERT INTO WASEELDB..WSL_INVOICES 
SELECT INVOICENO,PROVCLAIMNO,INVOICEDATE,INVOICEDEPT,TOTINVGRSAMT,TOTINVDISC,TOTINVPATSHARE,TOTINVNETAMT
FROM WSL_INVOICES_View
WHERE [INSURANCEID] = "' + @TPA +'" AND [INVOICEDATE] Between "' + @DateFrom +'" AND "'+ @DateUpto + '" '
EXECUTE(@SQLString)
SET QUOTED_IDENTIFIER ON
SET NOCOUNT OFF