CREATE 	PROCEDURE uSpWSL_CLAIM_DIAGNOSIS 
        ( 
          @DateFrom as varchar(10),
          @DateUpto as varchar(10),
          @TPA as varchar(15) 
        )
 
AS 
DECLARE @SQLString varchar(8000) 
SET @SQLString = 'INSERT INTO WASEELDB..WSL_CLAIM_DIAGNOSIS 
SELECT PROVCLAIMNO,DIAGNOSISCODE,DIAGNOSISDESC 
FROM WSL_CLAIM_DIAGNOSIS_View
WHERE [INSURANCEID] = "' + @TPA +'" AND [TRANSDATEENGLISH] Between "' + @DateFrom +'" AND "'+ @DateUpto + '" '
EXECUTE(@SQLString)
SET QUOTED_IDENTIFIER ON
SET NOCOUNT OFF
