CREATE TABLE [dbo].[EmployeeOld] (
    [IDNo]            INT          IDENTITY (1, 1) NOT NULL,
    [BranchID]        VARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF__Employee__Branch__5B438874] DEFAULT ('0001') NULL,
    [EmployeeID]      VARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [FirstName]       VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MiddleName]      VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ThirdName]       VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LastName]        VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [FirstNameAra]    VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MiddleNameAra]   VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ThirdNameAra]    VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LastNameAra]     VARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [NationalityID]   INT          NULL,
    [BirthDate]       DATE         NULL,
    [DateJoined]      VARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DateReleased]    VARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Gender]          CHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF__Employee__Gender__5C37ACAD] DEFAULT ('M') NULL,
    [Age]             NUMERIC (2)  NULL,
    [AgeYMD]          CHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BloodGroup]      VARCHAR (5)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MaritalStatus]   CHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NationalID]      VARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ReligionID]      INT          NULL,
    [FileNo]          VARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DepartmentIDNo]  INT          NULL,
    [DesignationIDNo] INT          NULL,
    [PayGroupIDNo]    INT          NULL,
    [PayRank]         INT          NULL,
    [UserID]          VARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF__Employee__UserID__5D2BD0E6] DEFAULT ('Admin') NULL,
    [MainTelephone]   VARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CompanyEmail]    VARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmployeeTypeID]  INT          NULL,
    [PassportNo]      VARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmergencyName]   VARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmergencyPhone]  VARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Photograph]      IMAGE        NULL,
    [DateTimeStamp]   ROWVERSION   NOT NULL,
    [CreateDate]      DATETIME     NOT NULL,
    CONSTRAINT [PK__Employee__B87DC9ABAA40C497] PRIMARY KEY CLUSTERED ([IDNo] ASC)
);

