CREATE TABLE [dbo].[MedicalFitnessReport] (
    [IdNo]                     INT            IDENTITY (1, 1) NOT NULL,
    [InvoiceNo]                INT            NOT NULL,
    [InvoiceDate]              DATETIME       NULL,
    [FileNo]                   INT            NULL,
    [PatientName]              NVARCHAR (255) NULL,
    [Gender]                   NVARCHAR (50)  NULL,
    [Age]                      NVARCHAR (50)  NULL,
    [Nationality]              NVARCHAR (255) NULL,
    [IdentityNo]               NVARCHAR (255) NULL,
    [DoctorName]               NVARCHAR (255) NULL,
    [BloodType]                NVARCHAR (10)  NULL,
    [FinalResultStatus]        CHAR (1)       NULL,
    [Remarks]                  NVARCHAR (MAX) NULL,
    [UserID]                   VARCHAR (15)   CONSTRAINT [DF_MedicalFitnessReport_UserID] DEFAULT ('Admin') NULL,
    [DateCreated]              DATETIME       CONSTRAINT [DF_MedicalFitnessReport_DateCreated] DEFAULT (getdate()) NULL,
    [MachineID]                VARCHAR (20)   CONSTRAINT [DF_MedicalFitnessReport_MachineID] DEFAULT (host_name()) NULL,
    [ExamTemperature]          NVARCHAR (255) NULL,
    [ExamBloodPressure]        NVARCHAR (255) NULL,
    [ExamPulse]                NVARCHAR (255) NULL,
    [ExamRespiratorySystem]    NVARCHAR (255) NULL,
    [ExamCardiovascularSystem] NVARCHAR (255) NULL,
    [ExamNervousSystem]        NVARCHAR (255) NULL,
    [ExamAbdomen]              NVARCHAR (255) NULL,
    [ExamWeight]               NVARCHAR (255) NULL,
    [ExamHeight]               NVARCHAR (255) NULL,
    [ExamExtremities]          NVARCHAR (255) NULL,
    [ExamChestXRay]            NVARCHAR (255) NULL,
    [ExamRightEye]             NVARCHAR (255) NULL,
    [ExamLeftEye]              NVARCHAR (255) NULL,
    [ExamRightEar]             NVARCHAR (255) NULL,
    [ExamLeftEar]              NVARCHAR (255) NULL,
    [CompanyName]              NVARCHAR (255) NULL,
    [PassportNo]               NVARCHAR (100) NULL,
    CONSTRAINT [CK_MedicalFitnessReport_FinalResultStatus] CHECK ([FinalResultStatus] IS NULL OR ([FinalResultStatus]='U' OR [FinalResultStatus]='F'))
);


GO

