CREATE TABLE [dbo].[Patient] (
    [IdNo]                INT             IDENTITY (1, 1) NOT NULL,
    [BranchID]            VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Series]              VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [RegistrationNo]      NUMERIC (12)    NOT NULL,
    [GroupNo]             NUMERIC (12)    NULL,
    [RegistrationDate]    VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PatientType]         VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BillType]            VARCHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Courtesy]            VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PatientName]         VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PatientNameAra]      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Address1]            VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Address2]            VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Street]              VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [City]                VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IqamaNo]             NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PassportNo]          NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PhoneR]              VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PhoneO]              VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Mobile]              VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [eMail]               VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Alert]               CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DOB]                 VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Age]                 NUMERIC (3)     NULL,
    [AgeYMD]              CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sex]                 CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CountryIOTA]         VARCHAR (3)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CountryPhone]        VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsCoCode]           VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DeductionCategory]   VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SplConsultationDays] NUMERIC (10)    NULL,
    [LastConsDate]        VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsCardNo]           VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsCardExpiry]       VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsCardStatus]       CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsSoapNo]           VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsSoapCode]         VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [InsPolicy]           VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SalesmanCode]        VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Limit]               NUMERIC (12, 2) NULL,
    [BalanceAmt]          NUMERIC (12, 2) NULL,
    [Restricted]          VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AC_Code]             VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DoctorCode]          VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FingureScan]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FingureScanned]      VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FaceScan]            VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FaceScanned]         VARCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Remarks]             VARCHAR (300)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UserID]              VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Create_Date]         DATETIME        NULL,
    [MachineID]           VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DateTimeStamp]       ROWVERSION      NULL,
    CONSTRAINT [PK_PatientDetails] PRIMARY KEY CLUSTERED ([IdNo] ASC)
);

