param([Parameter(Mandatory = $true)][string]$BinaryDirectory)

$ErrorActionPreference = 'Stop'
$testRoot = Split-Path -Parent $PSScriptRoot
$testBin = (Resolve-Path -LiteralPath $BinaryDirectory).Path
$testName = 'MedicalFitnessSaveTest_' + [Guid]::NewGuid().ToString('N')
$testDirectory = Join-Path $testRoot ('.tmp\' + $testName)
[void](New-Item -ItemType Directory -Path $testDirectory)
$testExe = Join-Path $testBin 'MedicalFitnessSaveChecks.exe'
$testReferences = @('Accounts.exe', 'BusinessLayer.dll', 'Common.dll', 'DataLayer.dll') |
    ForEach-Object { Join-Path $testBin $_ }
$testReferences += @('System.dll', 'System.Core.dll', 'System.Data.dll', 'System.Xml.dll', 'System.Configuration.dll')
$testCompiler = New-Object Microsoft.CSharp.CSharpCodeProvider
$testOptions = New-Object System.CodeDom.Compiler.CompilerParameters
$testOptions.GenerateExecutable = $true
$testOptions.OutputAssembly = $testExe
$testOptions.ReferencedAssemblies.AddRange([string[]]$testReferences)
try {
    $compiled = $testCompiler.CompileAssemblyFromFile($testOptions, (Join-Path $PSScriptRoot 'MedicalFitnessSaveChecks.cs'))
    if ($compiled.Errors.HasErrors) { throw (($compiled.Errors | ForEach-Object ToString) -join [Environment]::NewLine) }
} finally { $testCompiler.Dispose() }

# These connections are local, integrated-authentication and synthetic only.
# Never copy the application's production configuration into the test runner.
$testBuilder = New-Object System.Data.SqlClient.SqlConnectionStringBuilder
$testBuilder['Data Source'] = '(localdb)\MSSQLLocalDB'
$testBuilder['Integrated Security'] = $true
$testBuilder['Initial Catalog'] = $testName
$testConfig = New-Object System.Xml.XmlDocument
$testConfig.LoadXml('<configuration><connectionStrings /></configuration>')
foreach ($connectionName in @('ISPDATA', 'Kizen')) {
    $node = $testConfig.CreateElement('add')
    $node.SetAttribute('name', $connectionName)
    $node.SetAttribute('connectionString', $testBuilder.ConnectionString)
    [void]$testConfig.SelectSingleNode('/configuration/connectionStrings').AppendChild($node)
}
$testConfig.Save($testExe + '.config')
$testBuilder['Initial Catalog'] = 'master'
$master = New-Object System.Data.SqlClient.SqlConnection($testBuilder.ConnectionString)
$created = $false
try {
    $master.Open()
    $create = $master.CreateCommand()
    $dataPath = (Join-Path $testDirectory 'test.mdf').Replace("'", "''")
    $logPath = (Join-Path $testDirectory 'test_log.ldf').Replace("'", "''")
    $create.CommandText = "CREATE DATABASE [$testName] ON PRIMARY (NAME=N'$testName',FILENAME=N'$dataPath') LOG ON (NAME=N'${testName}_log',FILENAME=N'$logPath');"
    [void]$create.ExecuteNonQuery()
    $created = $true
    & $testExe $testRoot
    if ($LASTEXITCODE -ne 0) { throw 'Medical fitness save regression checks failed.' }
} finally {
    if ($created) {
        # Only the database generated by this invocation may be removed.
        if ($testName -notmatch '^MedicalFitnessSaveTest_[a-f0-9]{32}$') { throw 'Unsafe test database name.' }
        $drop = $master.CreateCommand()
        $drop.CommandText = "ALTER DATABASE [$testName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$testName];"
        [void]$drop.ExecuteNonQuery()
    }
    $master.Dispose()
}
