CREATE TABLE [dbo].[ClinicInvoicePrint] (
    [series]                VARCHAR (2)     NULL,
    [RegistrationDate]      VARCHAR (10)    NULL,
    [RegistrationType]      VARCHAR (15)    NULL,
    [TransType]             VARCHAR (10)    NULL,
    [TransNBR]              NUMERIC (10)    NULL,
    [BillType]              VARCHAR (20)    NULL,
    [RegistrationNo]        NUMERIC (12)    NULL,
    [TransDateEnglish]      VARCHAR (10)    NULL,
    [DoctorID]              VARCHAR (15)    NULL,
    [InsuranceID]           VARCHAR (15)    NULL,
    [InsuranceGroupID]      VARCHAR (15)    NULL,
    [InsuranceNameEnglish]  VARCHAR (50)    NULL,
    [NormalDiscountAmt]     NUMERIC (12, 2) NULL,
    [PreviousBalanceAmt]    NUMERIC (12, 2) NULL,
    [DeductibleAmt]         NUMERIC (12, 2) NULL,
    [DeductibleDiscountAmt] NUMERIC (12, 2) NULL,
    [ExtraDiscountPercent]  NUMERIC (12, 2) NULL,
    [ExtraDiscountAmt]      NUMERIC (12, 2) NULL,
    [RoundOffAmt]           NUMERIC (12, 2) NULL,
    [BillAmt]               NUMERIC (12, 2) NULL,
    [Remarks]               VARCHAR (2000)  NULL,
    [InsCardNo]             VARCHAR (30)    NULL,
    [CreditCardID]          VARCHAR (15)    NULL,
    [RowNbr]                NUMERIC (3)     NULL,
    [SaleType]              VARCHAR (15)    NULL,
    [ServiceID]             VARCHAR (50)    NULL,
    [InsServiceID]          VARCHAR (15)    NULL,
    [DepartmentID]          VARCHAR (15)    NULL,
    [Qty]                   NUMERIC (12, 3) NULL,
    [SalePrice]             NUMERIC (12, 4) NULL,
    [DiscountPer]           NUMERIC (12, 4) NULL,
    [DiscountAmt]           NUMERIC (12, 4) NULL,
    [deductibleper]         NUMERIC (12, 4) NULL,
    [PatientNameEnglish]    VARCHAR (50)    NULL,
    [Age]                   NUMERIC (3)     NULL,
    [AgeYMD]                CHAR (1)        NULL,
    [Sex]                   CHAR (1)        NULL,
    [CountryIOTA]           VARCHAR (10)    NULL,
    [ServiceNameEnglish]    VARCHAR (100)   NULL,
    [ServiceNameArabic]     VARCHAR (100)   NULL,
    [InsServiceNameEnglish] VARCHAR (100)   NULL,
    [EmpNameEnglish]        VARCHAR (40)    NULL,
    [CountryNameEng]        VARCHAR (35)    NULL,
    [IqamaNo]               NVARCHAR (50)   NULL,
    [Mobile]                VARCHAR (30)    NULL,
    [GroupName]             VARCHAR (75)    NULL,
    [GroupInsuranceID]      VARCHAR (15)    NULL,
    [UnderInsuranceID]      VARCHAR (15)    NULL,
    [DepartmentNameEnglish] VARCHAR (75)    NULL,
    [TokenNo]               NUMERIC (5)     NULL,
    [TokenPrint]            INT             DEFAULT ((0)) NULL,
    [OPDFloor]              VARCHAR (15)    NULL,
    [OPDNo]                 VARCHAR (5)     NULL,
    [PrintDept]             VARCHAR (1)     NULL,
    [UserID]                VARCHAR (30)    NULL,
    [MachineID]             VARCHAR (30)    NULL,
    [Create_date]           DATETIME        NULL,
    [ApprovalNo]            VARCHAR (20)    NULL,
    [VATPercent]            NUMERIC (5, 2)  NULL,
    [VATAmt]                NUMERIC (10, 2) NULL,
    [VatExemption]          NUMERIC (10, 2) NULL,
    [IBType]                VARCHAR (4)     NULL,
    [InvSource]             VARCHAR (16)    NULL,
    [SponsorId]             VARCHAR (20)    NULL,
    [Copy]                  VARCHAR (9)     NULL
);

