'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AATM.Accounts.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_Asset() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_Asset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Equity.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_Equity() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_Equity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expenses.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_Expense() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_Expense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liability.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_Liability() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_Liability", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_None() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Revenue.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_Revenue() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_Revenue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RevExpSummary.
        '''</summary>
        Friend ReadOnly Property AccountGroupSelection_RevExpSummary() As String
            Get
                Return ResourceManager.GetString("AccountGroupSelection_RevExpSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CashOnly.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_CashOnly() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_CashOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExceededCreditLimit.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_ExceededCreditLimit() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_ExceededCreditLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NewAccount.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_NewAccount() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_NewAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OnHold.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_OnHold() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_OnHold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_Open() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prospect.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_Prospect() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_Prospect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SeeNote.
        '''</summary>
        Friend ReadOnly Property AccountStatusSelection_SeeNote() As String
            Get
                Return ResourceManager.GetString("AccountStatusSelection_SeeNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit.
        '''</summary>
        Friend ReadOnly Property DebitCreditSelection_Credit() As String
            Get
                Return ResourceManager.GetString("DebitCreditSelection_Credit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debit.
        '''</summary>
        Friend ReadOnly Property DebitCreditSelection_Debit() As String
            Get
                Return ResourceManager.GetString("DebitCreditSelection_Debit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property DebitCreditSelection_None() As String
            Get
                Return ResourceManager.GetString("DebitCreditSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Client() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Client", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Employee() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Employee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Establishment.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Establishment() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Establishment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Others() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Others", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Patient() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Patient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend ReadOnly Property DocumentTypeSelection_Supplier() As String
            Get
                Return ResourceManager.GetString("DocumentTypeSelection_Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bmp.
        '''</summary>
        Friend ReadOnly Property ImageTypeSelection_Bmp() As String
            Get
                Return ResourceManager.GetString("ImageTypeSelection_Bmp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jpg.
        '''</summary>
        Friend ReadOnly Property ImageTypeSelection_Jpg() As String
            Get
                Return ResourceManager.GetString("ImageTypeSelection_Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property ImageTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("ImageTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pdf.
        '''</summary>
        Friend ReadOnly Property ImageTypeSelection_Pdf() As String
            Get
                Return ResourceManager.GetString("ImageTypeSelection_Pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Female.
        '''</summary>
        Friend ReadOnly Property MaleFemaleSelection_Female() As String
            Get
                Return ResourceManager.GetString("MaleFemaleSelection_Female", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Male.
        '''</summary>
        Friend ReadOnly Property MaleFemaleSelection_Male() As String
            Get
                Return ResourceManager.GetString("MaleFemaleSelection_Male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property MaleFemaleSelection_None() As String
            Get
                Return ResourceManager.GetString("MaleFemaleSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Divorced.
        '''</summary>
        Friend ReadOnly Property MaritalStatusSelection_Divorced() As String
            Get
                Return ResourceManager.GetString("MaritalStatusSelection_Divorced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Married.
        '''</summary>
        Friend ReadOnly Property MaritalStatusSelection_Married() As String
            Get
                Return ResourceManager.GetString("MaritalStatusSelection_Married", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property MaritalStatusSelection_None() As String
            Get
                Return ResourceManager.GetString("MaritalStatusSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single.
        '''</summary>
        Friend ReadOnly Property MaritalStatusSelection_Single() As String
            Get
                Return ResourceManager.GetString("MaritalStatusSelection_Single", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Widowed.
        '''</summary>
        Friend ReadOnly Property MaritalStatusSelection_Widowed() As String
            Get
                Return ResourceManager.GetString("MaritalStatusSelection_Widowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer.
        '''</summary>
        Friend ReadOnly Property PayeeTypeSelection_Customer() As String
            Get
                Return ResourceManager.GetString("PayeeTypeSelection_Customer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee.
        '''</summary>
        Friend ReadOnly Property PayeeTypeSelection_Employee() As String
            Get
                Return ResourceManager.GetString("PayeeTypeSelection_Employee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property PayeeTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("PayeeTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend ReadOnly Property PayeeTypeSelection_Others() As String
            Get
                Return ResourceManager.GetString("PayeeTypeSelection_Others", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend ReadOnly Property PayeeTypeSelection_Supplier() As String
            Get
                Return ResourceManager.GetString("PayeeTypeSelection_Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BankTransfer.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_BankTransfer() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_BankTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BitCoin.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_BitCoin() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_BitCoin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cash.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_Cash() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_Cash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_Check() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_Check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreditCard.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_CreditCard() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_CreditCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DebitCard.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_DebitCard() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_DebitCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mixed.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_Mixed() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_Mixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MobileTransfer.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_MobileTransfer() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_MobileTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_None() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_Others() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_Others", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paypal.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_Paypal() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_Paypal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WireTransfer.
        '''</summary>
        Friend ReadOnly Property PaymentMethodSelection_WireTransfer() As String
            Get
                Return ResourceManager.GetString("PaymentMethodSelection_WireTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AccountsPayable.
        '''</summary>
        Friend ReadOnly Property PaymentTypeSelection_AccountsPayable() As String
            Get
                Return ResourceManager.GetString("PaymentTypeSelection_AccountsPayable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CustomerRefund.
        '''</summary>
        Friend ReadOnly Property PaymentTypeSelection_CustomerRefund() As String
            Get
                Return ResourceManager.GetString("PaymentTypeSelection_CustomerRefund", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee.
        '''</summary>
        Friend ReadOnly Property PaymentTypeSelection_Employee() As String
            Get
                Return ResourceManager.GetString("PaymentTypeSelection_Employee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property PaymentTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("PaymentTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend ReadOnly Property PaymentTypeSelection_Others() As String
            Get
                Return ResourceManager.GetString("PaymentTypeSelection_Others", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend ReadOnly Property PaymentTypeSelection_Supplier() As String
            Get
                Return ResourceManager.GetString("PaymentTypeSelection_Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AccountsReceivable.
        '''</summary>
        Friend ReadOnly Property ReceiptTypeSelection_AccountsReceivable() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeSelection_AccountsReceivable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer.
        '''</summary>
        Friend ReadOnly Property ReceiptTypeSelection_Customer() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeSelection_Customer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee.
        '''</summary>
        Friend ReadOnly Property ReceiptTypeSelection_Employee() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeSelection_Employee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property ReceiptTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend ReadOnly Property ReceiptTypeSelection_Others() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeSelection_Others", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SupplierRefund.
        '''</summary>
        Friend ReadOnly Property ReceiptTypeSelection_SupplierRefund() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeSelection_SupplierRefund", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direct.
        '''</summary>
        Friend ReadOnly Property RevCostCenterTypeSelection_Direct() As String
            Get
                Return ResourceManager.GetString("RevCostCenterTypeSelection_Direct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shared.
        '''</summary>
        Friend ReadOnly Property RevCostCenterTypeSelection_Shared() As String
            Get
                Return ResourceManager.GetString("RevCostCenterTypeSelection_Shared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrator1.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Administrator1() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Administrator1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrator2.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Administrator2() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Administrator2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrator3.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Administrator3() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Administrator3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guest.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Guest() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Guest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manager1.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Manager1() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Manager1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manager2.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Manager2() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Manager2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manager3.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_Manager3() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_Manager3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_None() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User1.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_User1() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_User1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User2.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_User2() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_User2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User3.
        '''</summary>
        Friend ReadOnly Property SecurityLevelSelection_User3() As String
            Get
                Return ResourceManager.GetString("SecurityLevelSelection_User3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AccountsPayable.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_AccountsPayable() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_AccountsPayable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AccountsPayableDiscount.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_AccountsPayableDiscount() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_AccountsPayableDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AccountsReceivable.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_AccountsReceivable() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_AccountsReceivable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AccountsReceivableDiscount.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_AccountsReceivableDiscount() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_AccountsReceivableDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdvancesToSupplier.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_AdvancesToSupplier() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_AdvancesToSupplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_Bank() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_Bank", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cash.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_Cash() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_Cash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CheckingAccount.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_CheckingAccount() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_CheckingAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CustomerAdvances.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_CustomerAdvances() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_CustomerAdvances", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EmployeeLoan.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_EmployeeLoan() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_EmployeeLoan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_None() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PettyCashAccount.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_PettyCashAccount() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_PettyCashAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sales.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_Sales() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_Sales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VatInput.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_VatInput() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_VatInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VatOutput.
        '''</summary>
        Friend ReadOnly Property SpecialAccountSelection_VatOutput() As String
            Get
                Return ResourceManager.GetString("SpecialAccountSelection_VatOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit.
        '''</summary>
        Friend ReadOnly Property TransactionTypeSelection_Credit() As String
            Get
                Return ResourceManager.GetString("TransactionTypeSelection_Credit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debit.
        '''</summary>
        Friend ReadOnly Property TransactionTypeSelection_Debit() As String
            Get
                Return ResourceManager.GetString("TransactionTypeSelection_Debit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invoice.
        '''</summary>
        Friend ReadOnly Property TransactionTypeSelection_Invoice() As String
            Get
                Return ResourceManager.GetString("TransactionTypeSelection_Invoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property TransactionTypeSelection_None() As String
            Get
                Return ResourceManager.GetString("TransactionTypeSelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day.
        '''</summary>
        Friend ReadOnly Property YearMonthDaySelection_Day() As String
            Get
                Return ResourceManager.GetString("YearMonthDaySelection_Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month.
        '''</summary>
        Friend ReadOnly Property YearMonthDaySelection_Month() As String
            Get
                Return ResourceManager.GetString("YearMonthDaySelection_Month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property YearMonthDaySelection_None() As String
            Get
                Return ResourceManager.GetString("YearMonthDaySelection_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend ReadOnly Property YearMonthDaySelection_Year() As String
            Get
                Return ResourceManager.GetString("YearMonthDaySelection_Year", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowGradientBackgroundLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowGradientBackgroundLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowGradientBackgroundLarge1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowGradientBackgroundLarge1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowGradientBackgroundLarge2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowGradientBackgroundLarge2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
