CREATE TABLE [dbo].[accountscutoffdateopb] (
    [Trans_Key]         NUMERIC (10)    NULL,
    [BranchID]          VARCHAR (15)    NULL,
    [FinYear]           VARCHAR (9)     NULL,
    [TransNo]           NUMERIC (10)    NULL,
    [VDate]             VARCHAR (10)    NULL,
    [VType]             VARCHAR (3)     NULL,
    [RefType]           VARCHAR (10)    NULL,
    [RefNo]             NUMERIC (10)    NULL,
    [CostCentreID]      VARCHAR (5)     NOT NULL,
    [SlNo]              NUMERIC (4)     NOT NULL,
    [DrCr]              VARCHAR (1)     NULL,
    [LedgerID]          VARCHAR (20)    NOT NULL,
    [LedgerNameEnglish] VARCHAR (50)    NULL,
    [ParentID]          VARCHAR (10)    NULL,
    [GroupNameEnglish]  VARCHAR (50)    NULL,
    [DrAmt]             NUMERIC (15, 2) NULL,
    [CrAmt]             NUMERIC (15, 2) NULL,
    [EntryDescription]  NVARCHAR (500)  NULL,
    [VDescription]      NTEXT           NULL,
    [UserID]            VARCHAR (15)    NULL,
    [Create_date]       DATETIME        NULL,
    [MachineID]         VARCHAR (20)    NULL,
    [CCNameEnglish]     VARCHAR (50)    NULL,
    [LedgerNameArabic]  NVARCHAR (50)   NULL,
    [Status]            INT             NULL,
    [groupnamearabic]   NVARCHAR (50)   NULL
);

