CREATE TABLE [dbo].[AccountsAutoLinked] (
    [BranchID]                 VARCHAR (15) NOT NULL,
    [CashInHand]               VARCHAR (15) NULL,
    [BankAccount]              VARCHAR (15) NULL,
    [CostOfGoods]              VARCHAR (15) NULL,
    [SalesCash]                VARCHAR (15) NULL,
    [SalesCashCash]            VARCHAR (15) NULL,
    [SalesCashCreditCard]      VARCHAR (15) NULL,
    [PharmacySales]            VARCHAR (15) NULL,
    [PharmacySalesCash]        VARCHAR (15) NULL,
    [PharmacySalesCreditCards] VARCHAR (15) NULL,
    [ClinicSales]              VARCHAR (15) NULL,
    [ClinicSalesCash]          VARCHAR (15) NULL,
    [ClinicSalesCreditCards]   VARCHAR (15) NULL,
    [PharmacyInventory]        VARCHAR (15) NULL,
    [ClinicInventory]          VARCHAR (15) NULL,
    [CashSales]                VARCHAR (15) NULL,
    [CashSalesCash]            VARCHAR (15) NULL,
    [CashSalesCreditCards]     VARCHAR (15) NULL,
    [CreditSales]              VARCHAR (15) NULL,
    [ApplyCostCentre]          INT          NULL,
    [UserID]                   VARCHAR (5)  NOT NULL,
    [Create_Date]              DATETIME     NULL,
    [MachineID]                VARCHAR (20) NOT NULL
);

