CREATE TABLE [dbo].[BookingShiftSchedulesss] (
    [Trans_Key]     INT          NULL,
    [BranchId]      VARCHAR (5)  NULL,
    [DoctorId]      VARCHAR (5)  NULL,
    [ShiftId]       INT          NULL,
    [SunOff]        CHAR (1)     NULL,
    [MonOff]        CHAR (1)     NULL,
    [TueOff]        CHAR (1)     NULL,
    [WedOff]        CHAR (1)     NULL,
    [ThrOff]        CHAR (1)     NULL,
    [FriOff]        CHAR (1)     NULL,
    [SatOff]        CHAR (1)     NULL,
    [SunApplicable] CHAR (1)     NULL,
    [MonApplicable] CHAR (1)     NULL,
    [TueApplicable] CHAR (1)     NULL,
    [WedApplicable] CHAR (1)     NULL,
    [ThrApplicable] CHAR (1)     NULL,
    [FriApplicable] CHAR (1)     NULL,
    [SatApplicable] CHAR (1)     NULL,
    [Description]   VARCHAR (50) NULL,
    [DIrectShift]   CHAR (10)    NULL,
    [ShiftStart]    TIME (7)     NULL,
    [shiftEnd]      TIME (7)     NULL,
    [LunchStart]    TIME (7)     NULL,
    [LunchEnd]      TIME (7)     NULL,
    [Activate]      CHAR (1)     NULL,
    [UserId]        VARCHAR (30) NULL,
    [Create_date]   DATETIME     NULL,
    [MachineId]     VARCHAR (30) NULL
);

