CREATE TABLE [dbo].[ClinicInvoiceGroupHold] (
    [Trans_Key]             INT             NULL,
    [BranchID]              VARCHAR (15)    NOT NULL,
    [WareHouseID]           VARCHAR (5)     DEFAULT ('01') NULL,
    [BillType]              VARCHAR (20)    NOT NULL,
    [TransType]             VARCHAR (10)    NULL,
    [TransNbr]              NUMERIC (10)    NOT NULL,
    [TransDateEnglish]      VARCHAR (10)    NOT NULL,
    [TransDateHijri]        VARCHAR (10)    NULL,
    [RegistrationType]      VARCHAR (10)    NOT NULL,
    [RegistrationNo]        NUMERIC (12)    NOT NULL,
    [RegistrationDate]      VARCHAR (10)    NULL,
    [PatientName]           NVARCHAR (50)   NULL,
    [PatientNameArabic]     NVARCHAR (50)   NULL,
    [Age]                   NUMERIC (3)     NULL,
    [AgeYMD]                CHAR (1)        NULL,
    [DOB]                   VARCHAR (10)    NULL,
    [Sex]                   CHAR (1)        NULL,
    [IqamaNo]               VARCHAR (50)    NULL,
    [GroupFileNo]           NUMERIC (12)    NULL,
    [Mobile]                VARCHAR (30)    NULL,
    [CountryIOTA]           VARCHAR (10)    NULL,
    [ReferenceNo]           VARCHAR (20)    NULL,
    [DoctorID]              VARCHAR (15)    NULL,
    [InsuranceID]           VARCHAR (15)    NULL,
    [InsuranceGroupID]      VARCHAR (15)    NULL,
    [InsuranceNameEnglish]  VARCHAR (50)    NULL,
    [DeductionCategory]     VARCHAR (20)    NULL,
    [InsuranceCardNo]       VARCHAR (20)    NULL,
    [InsurancePolicyNo]     VARCHAR (20)    NULL,
    [InsSoapNo]             VARCHAR (30)    NULL,
    [InsSoapCard]           VARCHAR (30)    NULL,
    [SalesmanID]            VARCHAR (15)    NULL,
    [AgentID]               VARCHAR (15)    NULL,
    [NormalDiscountAmt]     NUMERIC (12, 2) DEFAULT (0) NULL,
    [PreviousBalanceAmt]    NUMERIC (12, 2) DEFAULT (0) NULL,
    [DeductibleAmt]         NUMERIC (12, 2) DEFAULT (0) NULL,
    [DeductibleDiscountAmt] NUMERIC (12, 2) DEFAULT (0) NULL,
    [ExtraDiscountAmt]      NUMERIC (12, 2) DEFAULT (0) NULL,
    [ExtraDiscountPercent]  NUMERIC (12, 2) DEFAULT (0) NULL,
    [RoundOffAmt]           NUMERIC (12, 2) DEFAULT (0) NULL,
    [TenderCash]            NUMERIC (12, 2) DEFAULT (0) NULL,
    [BillAmt]               NUMERIC (12, 2) DEFAULT (0) NULL,
    [CostAmt]               NUMERIC (12, 2) DEFAULT (0) NULL,
    [CommissionAmt]         NUMERIC (12, 2) DEFAULT (0) NULL,
    [CreditCardID]          VARCHAR (15)    NULL,
    [CreditCardNo]          VARCHAR (20)    NULL,
    [CreditCardExpiry]      VARCHAR (10)    NULL,
    [remarks]               VARCHAR (300)   NULL,
    [UserID]                VARCHAR (30)    DEFAULT ('Admin') NULL,
    [Create_Date]           DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]             VARCHAR (30)    DEFAULT (host_name()) NULL,
    [VATAmt]                NUMERIC (10, 2) NULL
);

