CREATE TABLE [dbo].[DoctorWiseTimeFrameReport] (
    [DoctorID]   VARCHAR (15)    NULL,
    [DoctorName] VARCHAR (50)    NULL,
    [HR1Pt]      INT             NULL,
    [HR1Amt]     NUMERIC (10, 2) NULL,
    [HR2Pt]      INT             NULL,
    [HR2Amt]     NUMERIC (10, 2) NULL,
    [HR3Pt]      INT             NULL,
    [HR3Amt]     NUMERIC (10, 2) NULL,
    [HR4Pt]      INT             NULL,
    [HR4Amt]     NUMERIC (10, 2) NULL,
    [HR5Pt]      INT             NULL,
    [HR5Amt]     NUMERIC (10, 2) NULL,
    [HR6Pt]      INT             NULL,
    [HR6Amt]     NUMERIC (10, 2) NULL,
    [HR7Pt]      INT             NULL,
    [HR7Amt]     NUMERIC (10, 2) NULL,
    [HR8pt]      INT             NULL,
    [HR8Amt]     NUMERIC (10, 2) NULL,
    [HR9Pt]      INT             NULL,
    [HR9Amt]     NUMERIC (10, 2) NULL,
    [HR10Pt]     INT             NULL,
    [HR10Amt]    NUMERIC (10, 2) NULL,
    [HR11Pt]     INT             NULL,
    [HR11Amt]    NUMERIC (10, 2) NULL,
    [HR12Pt]     INT             NULL,
    [HR12Amt]    NUMERIC (10, 2) NULL,
    [HR13Pt]     INT             NULL,
    [HR13Amt]    NUMERIC (10, 2) NULL,
    [HR14Pt]     INT             NULL,
    [HR14Amt]    NUMERIC (10, 2) NULL,
    [HR15Pt]     INT             NULL,
    [HR15Amt]    NUMERIC (10, 2) NULL,
    [HR16Pt]     INT             NULL,
    [HR16Amt]    NUMERIC (10, 2) NULL,
    [HR17Pt]     INT             NULL,
    [HR17Amt]    NUMERIC (10, 2) NULL,
    [HR18Pt]     INT             NULL,
    [HR18Amt]    NUMERIC (10, 2) NULL,
    [HR19Pt]     INT             NULL,
    [HR19Amt]    NUMERIC (10, 2) NULL,
    [HR20Pt]     INT             NULL,
    [HR20Amt]    NUMERIC (10, 2) NULL,
    [HR21Pt]     INT             NULL,
    [HR21Amt]    NUMERIC (10, 2) NULL,
    [HR22Pt]     INT             NULL,
    [HR22Amt]    NUMERIC (10, 2) NULL,
    [HR23Pt]     INT             NULL,
    [HR23Amt]    NUMERIC (10, 2) NULL,
    [HR24Pt]     INT             NULL,
    [HR24Amt]    NUMERIC (10, 2) NULL,
    [MachineID]  VARCHAR (20)    NULL
);

