CREATE TABLE [dbo].[DrugListx] (
    [registrationno]          NVARCHAR (50)  NULL,
    [Generic name]            NVARCHAR (150) NULL,
    [trade name]              NVARCHAR (150) NULL,
    [strength value]          FLOAT (53)     NULL,
    [unit of strength]        NVARCHAR (30)  NULL,
    [dosage form]             NVARCHAR (75)  NULL,
    [Route of Administration] NVARCHAR (150) NULL,
    [ATC Code 1]              NVARCHAR (50)  NULL,
    [ATC Code 2]              NVARCHAR (50)  NULL,
    [Volume]                  FLOAT (53)     NULL,
    [Unit of Volume]          NVARCHAR (50)  NULL,
    [Package type]            NVARCHAR (50)  NULL,
    [Package size]            FLOAT (53)     NULL,
    [Legal Status]            NVARCHAR (20)  NULL,
    [Product Control]         NVARCHAR (30)  NULL,
    [Public price (SAR)]      FLOAT (53)     NULL,
    [Shelf-life (mon)]        FLOAT (53)     NULL,
    [Storage conditions]      NVARCHAR (50)  NULL,
    [Manufacturer name]       NVARCHAR (150) NULL,
    [Country of Manufacturer] NVARCHAR (50)  NULL,
    [Marketing Company]       NVARCHAR (150) NULL,
    [Nationality]             NVARCHAR (50)  NULL,
    [MAH (Agent Name)]        NVARCHAR (150) NULL,
    [Authorization status]    NVARCHAR (15)  NULL,
    [Marketing status]        NVARCHAR (20)  NULL,
    [Remarks]                 NVARCHAR (255) NULL
);

