CREATE TABLE [dbo].[HRAttendenceDetails] (
    [BranchID]         VARCHAR (15)   NOT NULL,
    [Serial_No]        BIGINT         NULL,
    [EmpID]            VARCHAR (15)   NOT NULL,
    [Date]             VARCHAR (10)   NOT NULL,
    [ShiftID]          VARCHAR (15)   NOT NULL,
    [AttendenceID]     VARCHAR (15)   NOT NULL,
    [DepartmentID]     VARCHAR (15)   NULL,
    [TimeIn1]          VARCHAR (30)   NULL,
    [TimeOut1]         VARCHAR (30)   NULL,
    [TimeIn2]          VARCHAR (30)   NULL,
    [TimeOut2]         VARCHAR (30)   NULL,
    [Status]           INT            NULL,
    [SplDuty]          INT            NULL,
    [OffDay]           INT            NULL,
    [OnLeave]          INT            NULL,
    [LeaveType]        VARCHAR (15)   NULL,
    [PunchNecessary]   INT            NULL,
    [TotalHRS]         NUMERIC (2)    NULL,
    [DutyHRS]          NUMERIC (2)    NULL,
    [OTHrs]            NUMERIC (7, 2) NULL,
    [LateHrs]          NUMERIC (7, 2) NULL,
    [ProcessingStatus] INT            NULL,
    [Authanticate]     INT            NULL,
    [AuthReason]       VARCHAR (30)   NULL,
    [UserID]           VARCHAR (15)   NULL,
    [Create_Date]      DATETIME       NULL,
    [MachineID]        VARCHAR (20)   NULL
);

