CREATE TABLE [dbo].[HREmployeeSalaryMaster] (
    [BranchID]               VARCHAR (15)    NOT NULL,
    [EmpID]                  VARCHAR (15)    NOT NULL,
    [Basic]                  NUMERIC (10, 2) NOT NULL,
    [HRA]                    NUMERIC (10, 2) NULL,
    [Food]                   NUMERIC (10, 2) NULL,
    [Transport]              NUMERIC (10, 2) NULL,
    [Uniform]                NUMERIC (10, 2) NULL,
    [Washing]                NUMERIC (10, 2) NULL,
    [Education]              NUMERIC (10, 2) NULL,
    [YearlyBonus]            NUMERIC (10, 2) NULL,
    [MedicalApply]           INT             NULL,
    [Medical]                NUMERIC (10, 2) NULL,
    [OTApply]                INT             NULL,
    [OTRate]                 NUMERIC (10, 2) NULL,
    [ServiceBenefitsApply]   INT             NULL,
    [ServiceBenefits]        NUMERIC (10, 2) NULL,
    [Others]                 NUMERIC (10, 2) NULL,
    [PaymentMode]            VARCHAR (20)    NULL,
    [BankName]               VARCHAR (50)    NULL,
    [BankAC]                 VARCHAR (30)    NULL,
    [VacationTicketProvided] INT             NULL,
    [NoOfTickets]            INT             NULL,
    [VacationDays]           INT             NULL,
    [VacationSalary]         NUMERIC (10, 2) NULL,
    [Remark]                 VARCHAR (300)   NULL,
    [gosi]                   NUMERIC (10, 2) NULL
);

