CREATE TABLE [dbo].[HRMonthlyProcessedAttendence] (
    [BranchID]          VARCHAR (15)   NULL,
    [Trans_Key]         BIGINT         NOT NULL,
    [PeriodMonth]       VARCHAR (20)   NOT NULL,
    [PeriodYear]        VARCHAR (10)   NOT NULL,
    [EmpID]             VARCHAR (15)   NOT NULL,
    [DepartmentID]      VARCHAR (15)   NULL,
    [Date]              VARCHAR (10)   NULL,
    [ShiftID]           VARCHAR (15)   NULL,
    [TimeIn1]           VARCHAR (30)   NULL,
    [TimeOut1]          VARCHAR (30)   NULL,
    [TimeIn2]           VARCHAR (30)   NULL,
    [TimeOut2]          VARCHAR (30)   NULL,
    [Status]            INT            NULL,
    [PunchNecessary]    INT            NULL,
    [TotalHrs]          NUMERIC (5, 2) NULL,
    [DutyHrs]           NUMERIC (5, 2) NULL,
    [OTHrs]             NUMERIC (5, 2) NULL,
    [LateHRs]           NUMERIC (5, 2) NULL,
    [ProcessingStatus1] INT            NULL,
    [ProcessingStatus2] INT            NULL,
    [ProcessingStatus3] INT            NULL,
    [ProcessingStatus4] INT            NULL,
    [EmpMarketing]      INT            NULL,
    [Vacation]          INT            NULL,
    [OffDay]            INT            NULL,
    [SplDuty]           INT            NULL,
    [OnLeave]           INT            NULL,
    [LeaveType]         VARCHAR (15)   NULL,
    [Authanticate]      INT            NULL,
    [AuthReason]        VARCHAR (50)   NULL,
    [TimeValid1]        INT            NULL,
    [TimeValid2]        INT            NULL,
    [TimeValid3]        INT            NULL,
    [TimeValid4]        INT            NULL,
    [Remark]            VARCHAR (100)  NULL
);

