CREATE TABLE [dbo].[HRPayrollDetails] (
    [BranchID]               VARCHAR (15)    NOT NULL,
    [Group_Key]              NUMERIC (10)    NOT NULL,
    [PeriodMonth]            VARCHAR (30)    NOT NULL,
    [PeriodYear]             VARCHAR (30)    NOT NULL,
    [EmpID]                  VARCHAR (15)    NOT NULL,
    [Basic]                  NUMERIC (10, 2) NULL,
    [MonthDays]              NUMERIC (2)     NOT NULL,
    [Absence]                NUMERIC (2)     NULL,
    [Presence]               NUMERIC (2)     NULL,
    [Salary]                 NUMERIC (10, 2) NULL,
    [OTHrs]                  NUMERIC (10, 2) NULL,
    [OTRate]                 NUMERIC (10, 2) NULL,
    [OTAmt]                  NUMERIC (10, 2) NULL,
    [HRA]                    NUMERIC (10, 2) NULL,
    [Food]                   NUMERIC (10, 2) NULL,
    [Transport]              NUMERIC (10, 2) NULL,
    [Uniform]                NUMERIC (10, 2) NULL,
    [Washing]                NUMERIC (10, 2) NULL,
    [Education]              NUMERIC (10, 2) NULL,
    [YearlyBonus]            NUMERIC (10, 2) NULL,
    [Medical]                NUMERIC (10, 2) NULL,
    [ServiceBenefits]        NUMERIC (10, 2) NULL,
    [ServiceBenefitsReserve] NUMERIC (10, 2) NULL,
    [Vacation]               NUMERIC (10, 2) NULL,
    [Others]                 NUMERIC (10, 2) NULL,
    [SalaryAdvance]          NUMERIC (10, 2) NULL,
    [LoanAmt]                NUMERIC (10, 2) NULL,
    [InterestRate]           NUMERIC (10, 2) NULL,
    [GOSI]                   NUMERIC (10, 2) NULL,
    [OthersLess]             NUMERIC (10, 2) NULL
);

