CREATE TABLE [dbo].[IBInvoiceGroup] (
    [Trans_Key]          NUMERIC (10)    NOT NULL,
    [BranchID]           VARCHAR (15)    NOT NULL,
    [IBType]             VARCHAR (4)     NOT NULL,
    [RegistrationNo]     NUMERIC (10)    NOT NULL,
    [PatientName]        NVARCHAR (75)   NOT NULL,
    [TransType]          VARCHAR (15)    NOT NULL,
    [TransNBR]           NUMERIC (10)    NOT NULL,
    [TransDateEnglish]   VARCHAR (10)    NOT NULL,
    [TransDateHijri]     VARCHAR (10)    NULL,
    [DeliveryDate]       VARCHAR (10)    NULL,
    [CompanyID]          VARCHAR (15)    NULL,
    [DoctorID]           VARCHAR (15)    NOT NULL,
    [Border_Iqama]       VARCHAR (15)    NULL,
    [SponsorID]          VARCHAR (20)    NULL,
    [Profession]         VARCHAR (50)    NULL,
    [CountryIOTA]        VARCHAR (15)    NOT NULL,
    [BaladiyaExpiration] VARCHAR (10)    NULL,
    [Phone]              VARCHAR (20)    NULL,
    [SponsorPhone]       VARCHAR (20)    NULL,
    [DOB]                VARCHAR (10)    NULL,
    [Age]                INT             NULL,
    [AgeYMD]             CHAR (1)        DEFAULT ('Y') NULL,
    [Sex]                CHAR (1)        DEFAULT ('M') NULL,
    [LabReportNo]        VARCHAR (15)    NULL,
    [LabReportResult]    VARCHAR (25)    NULL,
    [LabUnfitReason]     VARCHAR (40)    NULL,
    [XrayReportNo]       VARCHAR (15)    NULL,
    [XrayReportResult]   VARCHAR (25)    NULL,
    [CardStatus]         CHAR (1)        DEFAULT ('N') NULL,
    [CardIssueDate]      VARCHAR (10)    NULL,
    [TokenNo]            INT             NULL,
    [GrossAmt]           NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [DiscountAmt]        NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [NetAmt]             NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [ExtraDiscountPer]   NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [ExtraDiscountAmt]   NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [Remarks]            VARCHAR (100)   NULL,
    [Posted]             INT             DEFAULT ((0)) NULL,
    [Accepted]           INT             DEFAULT ((0)) NULL,
    [AcceptedNo]         VARCHAR (10)    NULL,
    [Rejected]           INT             DEFAULT ((0)) NULL,
    [RejectedDate]       VARCHAR (10)    NULL,
    [Finishied]          CHAR (1)        DEFAULT ('N') NULL,
    [UserID]             VARCHAR (15)    NULL,
    [Create_Date]        DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]          VARCHAR (20)    DEFAULT (host_name()) NULL,
    [SponsorName]        NVARCHAR (75)   NULL,
    [SalesmanID]         VARCHAR (15)    NULL,
    [LabSeries]          NUMERIC (10)    NULL,
    [VATAmt]             NUMERIC (10, 2) DEFAULT ((0)) NULL,
    [VATExemption]       NUMERIC (10, 2) DEFAULT ((0)) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDX_IBInvoiceGroup]
    ON [dbo].[IBInvoiceGroup]([Trans_Key] ASC, [RegistrationNo] ASC, [TransNBR] ASC);

