CREATE TABLE [dbo].[nonpostedpurchase] (
    [Trans_Key]          INT             NOT NULL,
    [BranchID]           VARCHAR (15)    NOT NULL,
    [TransType]          VARCHAR (5)     NOT NULL,
    [TransSeries]        CHAR (10)       NOT NULL,
    [TransNo]            NUMERIC (10)    NOT NULL,
    [TransDate]          VARCHAR (10)    NOT NULL,
    [HijriDate]          VARCHAR (10)    NULL,
    [PONo]               NUMERIC (10)    NULL,
    [PODate]             VARCHAR (10)    NULL,
    [WarehouseID]        VARCHAR (15)    NOT NULL,
    [PurchaseType]       CHAR (10)       NULL,
    [PurchaseFrom]       CHAR (10)       NULL,
    [SupplierID]         VARCHAR (10)    NOT NULL,
    [InvoiceNo]          VARCHAR (20)    NULL,
    [InvoiceDate]        VARCHAR (10)    NULL,
    [Reference]          VARCHAR (20)    NULL,
    [InvoiceAmt]         NUMERIC (12, 2) NULL,
    [CurrencyCode]       VARCHAR (5)     NOT NULL,
    [ConversionRate]     NUMERIC (10, 5) NULL,
    [GrossAmt]           NUMERIC (12, 2) NULL,
    [TotalExpenses]      NUMERIC (12, 2) NULL,
    [SpecialDiscountPer] NUMERIC (7, 3)  NULL,
    [SpecialDiscountAmt] NUMERIC (12, 2) NULL,
    [SalesmanID]         VARCHAR (15)    NULL,
    [Remarks]            VARCHAR (300)   NULL,
    [PostInAccounts]     CHAR (1)        NULL,
    [PostInStock]        CHAR (1)        NULL,
    [AccountsUpdate]     VARCHAR (10)    NULL,
    [PurchaseGrossAmt]   NUMERIC (12, 2) NULL,
    [PurchaseCostAmt]    NUMERIC (12, 2) NULL,
    [PurchaseSaleAmt]    NUMERIC (12, 2) NULL,
    [PurchaseProfitPer]  NUMERIC (7, 2)  NULL,
    [PurchaseProfitAmt]  NUMERIC (12, 2) NULL,
    [EnteredBy]          VARCHAR (15)    NULL,
    [CheckedBy]          VARCHAR (15)    NULL,
    [ApprovedBy]         VARCHAR (15)    NULL,
    [UserID]             VARCHAR (15)    NULL,
    [Create_Date]        DATETIME        NULL,
    [MachineID]          VARCHAR (20)    NULL
);

