CREATE TABLE [dbo].[outpatientfile] (
    [branchid]            VARCHAR (2)  NOT NULL,
    [series]              VARCHAR (2)  NOT NULL,
    [registrationno]      NUMERIC (12) NOT NULL,
    [groupno]             NUMERIC (12) NOT NULL,
    [RegistrationDate]    VARCHAR (10) NULL,
    [patienttype]         VARCHAR (11) NOT NULL,
    [billtype]            VARCHAR (2)  NOT NULL,
    [courtesy]            VARCHAR (1)  NOT NULL,
    [PatientNameEnglish]  VARCHAR (50) NULL,
    [PatientNameArabic]   VARCHAR (1)  NOT NULL,
    [Address1]            VARCHAR (1)  NOT NULL,
    [Address2]            VARCHAR (1)  NOT NULL,
    [Street]              VARCHAR (1)  NOT NULL,
    [City]                VARCHAR (6)  NOT NULL,
    [iqamano]             VARCHAR (1)  NOT NULL,
    [passportno]          VARCHAR (1)  NOT NULL,
    [phoner]              VARCHAR (1)  NOT NULL,
    [phoneo]              VARCHAR (1)  NOT NULL,
    [mobile]              VARCHAR (1)  NOT NULL,
    [email]               VARCHAR (1)  NOT NULL,
    [alert]               VARCHAR (1)  NOT NULL,
    [dob]                 VARCHAR (1)  NOT NULL,
    [age]                 INT          NOT NULL,
    [ageymd]              VARCHAR (1)  NOT NULL,
    [Sex]                 VARCHAR (1)  NOT NULL,
    [countryiota]         VARCHAR (3)  NOT NULL,
    [countryphone]        VARCHAR (1)  NOT NULL,
    [inscocode]           VARCHAR (1)  NOT NULL,
    [deductioncategory]   VARCHAR (1)  NOT NULL,
    [splconsultationdays] INT          NOT NULL,
    [lastconsdate]        VARCHAR (1)  NOT NULL,
    [inscardno]           VARCHAR (1)  NOT NULL,
    [inscardexpiry]       VARCHAR (1)  NOT NULL,
    [inscardstatus]       VARCHAR (1)  NOT NULL,
    [inssoapno]           VARCHAR (1)  NOT NULL,
    [inssoapcode]         VARCHAR (1)  NOT NULL,
    [inspolicy]           VARCHAR (1)  NOT NULL,
    [salesmancode]        VARCHAR (1)  NOT NULL,
    [limit]               INT          NOT NULL,
    [balanceamt]          INT          NOT NULL,
    [restricted]          VARCHAR (1)  NOT NULL,
    [ac_code]             VARCHAR (1)  NOT NULL,
    [doctorcode]          VARCHAR (3)  NOT NULL,
    [fingurescan]         VARCHAR (1)  NOT NULL,
    [fingurescanned]      VARCHAR (1)  NOT NULL,
    [facescan]            VARCHAR (1)  NOT NULL,
    [facescanned]         VARCHAR (1)  NOT NULL,
    [remarks]             VARCHAR (1)  NOT NULL,
    [userid]              VARCHAR (5)  NOT NULL,
    [create_date]         DATETIME     NOT NULL,
    [MAchineID]           VARCHAR (6)  NOT NULL
);

