CREATE TABLE [dbo].[PharmacyInvoiceDetails] (
    [Group_Key]        INT             NOT NULL,
    [InvoiceType]      VARCHAR (2)     NOT NULL,
    [SaleType]         VARCHAR (15)    DEFAULT ('SALE') NULL,
    [BranchID]         VARCHAR (15)    NOT NULL,
    [RowNbr]           NUMERIC (3)     NOT NULL,
    [Item_Code]        VARCHAR (15)    NOT NULL,
    [Batch]            VARCHAR (15)    NULL,
    [Expiry]           VARCHAR (10)    NULL,
    [Qty]              NUMERIC (12, 3) NULL,
    [Unit]             VARCHAR (10)    NULL,
    [PcsQty]           NUMERIC (4)     NULL,
    [QtyInStock]       NUMERIC (10)    DEFAULT (0) NULL,
    [Pack1]            NUMERIC (8)     DEFAULT (1) NULL,
    [Pack2]            NUMERIC (8)     DEFAULT (1) NULL,
    [Pack3]            NUMERIC (8)     DEFAULT (1) NULL,
    [EANCode]          VARCHAR (15)    NULL,
    [SalePrice]        NUMERIC (12, 4) DEFAULT (0) NULL,
    [CostPrice]        NUMERIC (12, 4) DEFAULT (0) NULL,
    [costPricePerUnit] NUMERIC (12, 4) DEFAULT (0) NULL,
    [DiscountPer]      NUMERIC (12, 4) DEFAULT (0) NULL,
    [DiscountAmt]      NUMERIC (12, 4) DEFAULT (0) NULL,
    [DeductiblePer]    NUMERIC (12, 4) DEFAULT (0) NULL,
    [DeductibleAmt]    NUMERIC (12, 4) DEFAULT (0) NULL,
    [AgentCommPer]     NUMERIC (12, 2) DEFAULT (0) NULL,
    [SalesManCommPer]  NUMERIC (12, 2) DEFAULT (0) NULL,
    [Stock_Status]     CHAR (1)        NULL,
    [SBT_Status]       CHAR (1)        NULL,
    [Packed_Stock]     NUMERIC (7, 3)  NULL,
    [DosageID]         VARCHAR (15)    NULL,
    [SaleStatus]       VARCHAR (2)     DEFAULT (null) NULL,
    [VATPercent]       NUMERIC (5, 2)  DEFAULT ((0)) NULL,
    [VATAmt]           NUMERIC (10, 2) DEFAULT ((0)) NULL
);

