CREATE TABLE [dbo].[PMRDentalDetails] (
    [Trans_Key]           BIGINT       NOT NULL,
    [TransDateEnglish]    VARCHAR (10) DEFAULT (getdate()) NULL,
    [PatientType]         VARCHAR (15) DEFAULT ('Insurance') NULL,
    [BillType]            CHAR (2)     DEFAULT ('CR') NULL,
    [Series]              VARCHAR (2)  NOT NULL,
    [RegistrationNO]      NUMERIC (10) NOT NULL,
    [TokenNo]             NUMERIC (10) DEFAULT (0) NULL,
    [InsuranceID]         VARCHAR (15) NULL,
    [InsuranceGroupID]    VARCHAR (15) NULL,
    [DoctorID]            VARCHAR (15) NULL,
    [Visit_No]            NUMERIC (10) DEFAULT (1) NULL,
    [Visit_Type]          VARCHAR (15) NULL,
    [Duration_of_illness] NUMERIC (5)  DEFAULT (1) NULL,
    [Chief_complaint]     NTEXT        NULL,
    [Other_condition]     NTEXT        NULL,
    [Diagnosis]           NTEXT        NULL,
    [DX_Code1]            VARCHAR (15) NULL,
    [DX_Code2]            VARCHAR (15) NULL,
    [DX_Code3]            VARCHAR (15) NULL,
    [DX_Code4]            VARCHAR (15) NULL,
    [MedicationNote]      NTEXT        NULL,
    [IllnessType]         NUMERIC (5)  DEFAULT (0) NULL,
    [Img_Dental]          IMAGE        NULL,
    [UserID]              VARCHAR (15) NULL,
    [Create_Date]         DATETIME     DEFAULT (getdate()) NULL,
    [MachineID]           VARCHAR (20) DEFAULT (host_name()) NULL
);

