CREATE TABLE [dbo].[PMROpthalDetails] (
    [Trans_key]        BIGINT          NOT NULL,
    [TransDateEnglish] VARCHAR (10)    NOT NULL,
    [PatientType]      VARCHAR (15)    NOT NULL,
    [Series]           VARCHAR (2)     NOT NULL,
    [RegistrationNo]   NUMERIC (10)    NOT NULL,
    [DoctorID]         VARCHAR (15)    NULL,
    [Dist_SP_R]        VARCHAR (5)     NULL,
    [Dist_CY_R]        VARCHAR (5)     NULL,
    [Dist_AX_R]        VARCHAR (5)     NULL,
    [Dist_PR_R]        VARCHAR (5)     NULL,
    [Dist_VA_R]        VARCHAR (5)     NULL,
    [Dist_PD_R]        VARCHAR (5)     NULL,
    [Dist_SP_N]        VARCHAR (5)     NULL,
    [Dist_CY_N]        VARCHAR (5)     NULL,
    [Dist_AX_N]        VARCHAR (5)     NULL,
    [Dist_PR_N]        VARCHAR (5)     NULL,
    [Dist_VA_N]        VARCHAR (5)     NULL,
    [Dist_PD_N]        VARCHAR (5)     NULL,
    [Near_SP_L]        VARCHAR (5)     NULL,
    [Near_CY_L]        VARCHAR (5)     NULL,
    [Near_AX_L]        VARCHAR (5)     NULL,
    [Near_PR_L]        VARCHAR (5)     NULL,
    [Near_VA_L]        VARCHAR (5)     NULL,
    [Near_PD_L]        VARCHAR (5)     NULL,
    [Near_SP_N]        VARCHAR (5)     NULL,
    [Near_CY_N]        VARCHAR (5)     NULL,
    [Near_AX_N]        VARCHAR (5)     NULL,
    [Near_PR_N]        VARCHAR (5)     NULL,
    [Near_VA_N]        VARCHAR (5)     NULL,
    [Near_PD_N]        VARCHAR (5)     NULL,
    [Bifocal1]         VARCHAR (15)    NULL,
    [Vertex]           VARCHAR (15)    NULL,
    [Bifocal2]         VARCHAR (15)    NULL,
    [RegularLenseType] CHAR (1)        DEFAULT ('0') NULL,
    [Multicoated]      CHAR (1)        DEFAULT ('0') NULL,
    [Varilux]          CHAR (1)        DEFAULT ('0') NULL,
    [Light]            CHAR (1)        DEFAULT ('0') NULL,
    [Aspheric]         CHAR (1)        DEFAULT ('0') NULL,
    [Bifocal]          CHAR (1)        DEFAULT ('0') NULL,
    [Medium]           CHAR (1)        DEFAULT ('0') NULL,
    [Lenticular]       CHAR (1)        DEFAULT ('0') NULL,
    [SingleVision]     CHAR (1)        DEFAULT ('0') NULL,
    [Dark]             CHAR (1)        DEFAULT ('0') NULL,
    [SafetyThickness]  CHAR (1)        DEFAULT ('0') NULL,
    [AntiReflecting]   CHAR (1)        DEFAULT ('0') NULL,
    [Photosensitive]   CHAR (1)        DEFAULT ('0') NULL,
    [HighIndex]        CHAR (1)        DEFAULT ('0') NULL,
    [Colored]          CHAR (1)        DEFAULT ('0') NULL,
    [AntiScratch]      CHAR (1)        DEFAULT ('0') NULL,
    [ContactLenseType] CHAR (1)        DEFAULT ('0') NULL,
    [Frames]           CHAR (1)        DEFAULT ('0') NULL,
    [ipd]              VARCHAR (15)    NULL,
    [color_ipd]        VARCHAR (15)    NULL,
    [comment_ipd]      VARCHAR (25)    NULL,
    [NoOfPairs]        INT             NULL,
    [CostLense]        NUMERIC (18, 2) NULL,
    [CostFrame]        NUMERIC (18, 2) NULL,
    [remarks]          NTEXT           NULL,
    [UserID]           VARCHAR (15)    NULL,
    [Create_Date]      DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]        VARCHAR (20)    DEFAULT (host_name()) NULL
);

