CREATE TABLE [dbo].[PMRPatientTreatment] (
    [Trans_Key]        BIGINT          NOT NULL,
    [TransNBR]         BIGINT          NOT NULL,
    [Series]           VARCHAR (2)     NOT NULL,
    [RegistrationNo]   NUMERIC (10)    NOT NULL,
    [DoctorID]         VARCHAR (15)    NULL,
    [InsuranceID]      VARCHAR (15)    NULL,
    [InsuranceGroupID] VARCHAR (15)    NULL,
    [RowNBR]           INT             NOT NULL,
    [Item_Code]        VARCHAR (15)    NULL,
    [DepartmentID]     VARCHAR (15)    NULL,
    [Qty]              NUMERIC (5)     NULL,
    [Unit]             CHAR (1)        NULL,
    [SalePrice]        NUMERIC (10, 2) NULL,
    [DiscountPer]      NUMERIC (10, 2) NULL,
    [DiscountAmt]      NUMERIC (10, 2) NULL,
    [DeductibleAmt]    NUMERIC (10, 2) NULL,
    [CostPrice]        NUMERIC (10, 2) NULL,
    [BillAmt]          NUMERIC (10, 2) NULL,
    [Issue_Flag]       CHAR (1)        NULL,
    [Dsh_Key]          NUMERIC (10)    NULL,
    [Remark]           NTEXT           NULL,
    [UserID]           VARCHAR (15)    NULL,
    [Create_Date]      DATETIME        NULL,
    [MachineID]        VARCHAR (20)    NULL,
    [TreatmentRemark]  VARCHAR (100)   NULL
);

