CREATE TABLE [dbo].[PMRPatientGeneralInfo] (
    [Trans_Key]         BIGINT         NOT NULL,
    [TransNBR]          BIGINT         NOT NULL,
    [TransType]         VARCHAR (4)    NOT NULL,
    [TransDateEnglish]  VARCHAR (10)   NULL,
    [PatientType]       VARCHAR (15)   DEFAULT ('Insurance') NULL,
    [BillType]          CHAR (2)       DEFAULT ('CR') NULL,
    [Series]            VARCHAR (2)    DEFAULT ('CR') NULL,
    [RegistrationNo]    NUMERIC (10)   NOT NULL,
    [TokenNo]           NUMERIC (10)   DEFAULT (0) NULL,
    [InsuranceID]       VARCHAR (15)   NULL,
    [InsuranceGroupID]  VARCHAR (15)   NULL,
    [DoctorID]          VARCHAR (15)   NULL,
    [bp]                VARCHAR (10)   NULL,
    [Breathing]         VARCHAR (10)   NULL,
    [Height]            VARCHAR (10)   NULL,
    [Weight]            VARCHAR (10)   NULL,
    [Temprature]        VARCHAR (10)   NULL,
    [PulseRate]         VARCHAR (10)   NULL,
    [Respiratory]       VARCHAR (10)   NULL,
    [VisitNo]           NUMERIC (10)   DEFAULT (1) NULL,
    [VisitType]         VARCHAR (15)   NULL,
    [DurationOfIllness] NUMERIC (5)    DEFAULT (1) NULL,
    [DurationYMD]       CHAR (1)       DEFAULT ('D') NULL,
    [AdmissionType]     CHAR (1)       DEFAULT ('0') NULL,
    [FixedAlergies]     CHAR (1)       DEFAULT ('0') NULL,
    [DrugAlergies]      CHAR (1)       DEFAULT ('0') NULL,
    [OtherAlergies]     CHAR (1)       DEFAULT ('0') NULL,
    [ChiefComplaint]    VARCHAR (700)  NULL,
    [NoteAlergies]      NTEXT          NULL,
    [SignificantSign]   VARCHAR (500)  NULL,
    [OtherCondition]    VARCHAR (500)  NULL,
    [Diagnosis]         NTEXT          NULL,
    [DX_Code1]          VARCHAR (15)   NULL,
    [DX_Code2]          VARCHAR (15)   NULL,
    [DX_Code3]          VARCHAR (15)   NULL,
    [DX_Code4]          VARCHAR (15)   NULL,
    [MedicationNote]    NTEXT          NULL,
    [IllnessType]       NUMERIC (5)    DEFAULT (0) NULL,
    [Lmp]               NVARCHAR (100) NULL,
    [LmpDate]           VARCHAR (10)   NULL,
    [Cmf]               CHAR (1)       DEFAULT ('N') NULL,
    [CmfNote]           NTEXT          NULL,
    [Los]               NUMERIC (5)    DEFAULT (1) NULL,
    [Eda]               VARCHAR (10)   NULL,
    [DoctorRemark]      NTEXT          NULL,
    [UserID]            VARCHAR (15)   NULL,
    [Create_Date]       DATETIME       DEFAULT (getdate()) NULL,
    [MachineID]         VARCHAR (20)   DEFAULT (host_name()) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDX_PMRPatientGeneralInfo]
    ON [dbo].[PMRPatientGeneralInfo]([Trans_Key] ASC);

