CREATE TABLE [dbo].[PMRUCAFPrint] (
    [Trans_key]             BIGINT          NOT NULL,
    [AppearanceOrder]       INT             DEFAULT (1) NULL,
    [TransType]             VARCHAR (5)     NOT NULL,
    [TransDateEnglish]      VARCHAR (20)    NULL,
    [PatientType]           CHAR (10)       NULL,
    [BillType]              CHAR (2)        NULL,
    [Series]                VARCHAR (2)     NOT NULL,
    [RegistrationNo]        NUMERIC (10)    NOT NULL,
    [PatientName]           NVARCHAR (75)   NOT NULL,
    [Age]                   NUMERIC (3)     NULL,
    [Sex]                   CHAR (1)        NULL,
    [AgeYMD]                CHAR (1)        NULL,
    [ID_No]                 VARCHAR (20)    NULL,
    [TokenNo]               NUMERIC (10)    NULL,
    [InsuranceID]           VARCHAR (15)    NULL,
    [InsuranceGroupID]      VARCHAR (15)    NULL,
    [DoctorID]              VARCHAR (15)    NULL,
    [DoctorNameEnglish]     VARCHAR (50)    NULL,
    [DepartmentID]          VARCHAR (15)    NULL,
    [DepartmentNameEnglish] VARCHAR (50)    NULL,
    [bp]                    VARCHAR (10)    NULL,
    [Breathing]             VARCHAR (10)    NULL,
    [Temprature]            VARCHAR (10)    NULL,
    [PulseRate]             VARCHAR (10)    NULL,
    [Respiratory]           VARCHAR (10)    NULL,
    [VisitNo]               NUMERIC (10)    NULL,
    [VisitType]             VARCHAR (15)    NULL,
    [DurationOfIllness]     NUMERIC (5)     NULL,
    [DurationYMD]           VARCHAR (10)    DEFAULT ('D') NULL,
    [AdmissionType]         CHAR (1)        NULL,
    [FixedAlergies]         CHAR (1)        NULL,
    [DrugAlergies]          CHAR (1)        NULL,
    [OtherAlergies]         CHAR (1)        NULL,
    [ChiefComplaint]        NTEXT           NULL,
    [NoteAlergies]          NTEXT           NULL,
    [NoteSpl]               NTEXT           NULL,
    [NoteOther]             NTEXT           NULL,
    [SignificantSign]       NTEXT           NULL,
    [OtherCondition]        NTEXT           NULL,
    [Diagnosis]             NTEXT           NULL,
    [DX_Code1]              VARCHAR (15)    NULL,
    [DX_Code2]              VARCHAR (15)    NULL,
    [DX_Code3]              VARCHAR (15)    NULL,
    [DX_Code4]              VARCHAR (15)    NULL,
    [ICD_Type]              VARCHAR (2)     NULL,
    [MedicationNote]        NTEXT           NULL,
    [IllnessType]           NUMERIC (5)     NULL,
    [lmp]                   NVARCHAR (100)  NULL,
    [cmf]                   CHAR (1)        NULL,
    [cmfNote]               NTEXT           NULL,
    [los]                   NUMERIC (5)     NULL,
    [eda]                   VARCHAR (10)    NULL,
    [userID]                VARCHAR (10)    NULL,
    [MachineID]             VARCHAR (20)    NULL,
    [Create_Date]           VARCHAR (20)    NULL,
    [RowNBR]                INT             NULL,
    [item_code]             VARCHAR (15)    NULL,
    [qty]                   NUMERIC (5)     NULL,
    [unit]                  CHAR (1)        NULL,
    [SalePrice]             NUMERIC (10, 2) NULL,
    [DiscountPer]           NUMERIC (10, 2) NULL,
    [DiscountAmt]           NUMERIC (10, 2) NULL,
    [NetAmt]                NUMERIC (10, 2) NULL,
    [ItemNameEnglish]       VARCHAR (75)    NULL,
    [ItemNameArabic]        NVARCHAR (50)   NULL,
    [DosageEnglish]         NVARCHAR (20)   NULL,
    [DosageArabic]          NVARCHAR (20)   NULL,
    [Duration]              NVARCHAR (20)   NULL,
    [CountryIOTA]           VARCHAR (15)    NULL,
    [CountryNameEng]        VARCHAR (50)    NULL,
    [DocumentInfo1]         IMAGE           NULL,
    [DocumentInfo2]         IMAGE           NULL
);

