CREATE TABLE [dbo].[purchasedetails9] (
    [BranchID]       VARCHAR (15)    NOT NULL,
    [Group_key]      INT             NOT NULL,
    [SlNo]           DECIMAL (4)     NOT NULL,
    [Item_Code]      VARCHAR (15)    NOT NULL,
    [pack1]          DECIMAL (3)     NOT NULL,
    [pack2]          DECIMAL (3)     NOT NULL,
    [pack3]          DECIMAL (3)     NOT NULL,
    [Batch]          VARCHAR (15)    NULL,
    [Expiry]         VARCHAR (10)    NULL,
    [UserQty]        DECIMAL (12, 3) NULL,
    [BonusQty]       DECIMAL (12, 3) NULL,
    [Unit]           CHAR (10)       NULL,
    [TotalQty]       DECIMAL (12, 3) NULL,
    [QtyInBox]       DECIMAL (12, 3) NULL,
    [QtyInPcs]       DECIMAL (12, 3) NULL,
    [Amount]         DECIMAL (12, 2) NULL,
    [Discount]       DECIMAL (12, 3) NULL,
    [Discount2]      DECIMAL (12, 3) NULL,
    [PurchasePrice]  DECIMAL (12, 3) NULL,
    [CostPrice]      DECIMAL (12, 5) NULL,
    [SellingPrice]   DECIMAL (12, 2) NULL,
    [ProfitPer]      DECIMAL (12, 3) NULL,
    [ProfitAmt]      DECIMAL (12, 2) NULL,
    [PurchaseStatus] VARCHAR (5)     NULL,
    [VATPercent]     DECIMAL (5, 2)  NULL,
    [VATAmt]         DECIMAL (10, 2) NULL
);

