CREATE TABLE [dbo].[PurchaseDetails] (
    [BranchID]       VARCHAR (15)    NOT NULL,
    [Group_key]      INT             NOT NULL,
    [SlNo]           NUMERIC (4)     NOT NULL,
    [Item_Code]      VARCHAR (15)    NOT NULL,
    [pack1]          NUMERIC (3)     NOT NULL,
    [pack2]          NUMERIC (3)     NOT NULL,
    [pack3]          NUMERIC (3)     NOT NULL,
    [Batch]          VARCHAR (15)    NULL,
    [Expiry]         VARCHAR (10)    NULL,
    [UserQty]        NUMERIC (12, 3) DEFAULT (0) NULL,
    [BonusQty]       NUMERIC (12, 3) DEFAULT (0) NULL,
    [Unit]           CHAR (10)       DEFAULT ('Box') NULL,
    [TotalQty]       NUMERIC (12, 3) DEFAULT (0) NULL,
    [QtyInBox]       NUMERIC (12, 3) DEFAULT (0) NULL,
    [QtyInPcs]       NUMERIC (12, 3) DEFAULT (0) NULL,
    [Amount]         NUMERIC (12, 2) DEFAULT (0) NULL,
    [Discount]       NUMERIC (12, 3) DEFAULT (0) NULL,
    [Discount2]      NUMERIC (12, 3) DEFAULT (0) NULL,
    [PurchasePrice]  NUMERIC (12, 3) DEFAULT (0) NULL,
    [CostPrice]      NUMERIC (12, 5) DEFAULT (0) NULL,
    [SellingPrice]   NUMERIC (12, 2) DEFAULT (0) NULL,
    [ProfitPer]      NUMERIC (12, 3) NULL,
    [ProfitAmt]      NUMERIC (12, 2) NULL,
    [PurchaseStatus] VARCHAR (5)     DEFAULT ('PUR') NULL,
    [VATPercent]     NUMERIC (5, 2)  DEFAULT ((0)) NULL,
    [VATAmt]         NUMERIC (10, 2) DEFAULT ((0)) NULL
);

