CREATE TABLE [dbo].[stkposition] (
    [Primary_Key]  INT             IDENTITY (1, 1) NOT NULL,
    [BranchID]     VARCHAR (15)    NOT NULL,
    [SlNo]         NUMERIC (15)    NOT NULL,
    [StockDate]    VARCHAR (10)    NOT NULL,
    [warehouseid]  VARCHAR (5)     NOT NULL,
    [Item_Code]    VARCHAR (15)    NOT NULL,
    [Batch]        VARCHAR (15)    NOT NULL,
    [Expiry]       VARCHAR (10)    NULL,
    [CostPrice]    NUMERIC (12, 2) NULL,
    [SellingPrice] NUMERIC (12, 2) NULL,
    [QtyBox]       NUMERIC (10)    NULL,
    [QtyStrips]    NUMERIC (10)    NULL,
    [QtyPcs]       NUMERIC (10)    NULL,
    [QtyBadBox]    NUMERIC (12, 3) NULL,
    [QtyBadStrips] NUMERIC (12, 3) NULL,
    [QtyBadPcs]    NUMERIC (12, 3) NULL,
    [TQtyGood]     NUMERIC (12, 3) NULL,
    [TQtyBad]      NUMERIC (12, 3) NULL,
    [Stock_Type]   CHAR (1)        NULL,
    [PageNo]       NUMERIC (5)     NULL,
    [Loc_Row]      VARCHAR (10)    NULL,
    [Loc_Col]      VARCHAR (10)    NULL,
    [Remarks]      VARCHAR (300)   NULL,
    [UserID]       VARCHAR (30)    NULL,
    [Create_date]  DATETIME        NULL,
    [machineID]    VARCHAR (30)    NULL
);

