CREATE TABLE [dbo].[StockImport] (
    [BranchID]        VARCHAR (15)    NULL,
    [Primary_Key]     NUMERIC (15)    NOT NULL,
    [BranchFrom]      VARCHAR (15)    NOT NULL,
    [WareHouseFrom]   VARCHAR (15)    NOT NULL,
    [BranchTo]        VARCHAR (15)    NULL,
    [WareHouseTo]     VARCHAR (15)    NULL,
    [TransType]       VARCHAR (10)    NULL,
    [TransSeries]     VARCHAR (5)     NULL,
    [TransNo]         NUMERIC (15)    NOT NULL,
    [TransDate]       VARCHAR (10)    NULL,
    [ReqNo]           VARCHAR (10)    NULL,
    [ReqDate]         VARCHAR (20)    NULL,
    [AcCodeFrom]      VARCHAR (15)    NULL,
    [AcCodeTo]        VARCHAR (15)    NULL,
    [PostInAccounts]  CHAR (1)        DEFAULT ('N') NULL,
    [PostInStock]     CHAR (1)        DEFAULT ('N') NULL,
    [amount]          NUMERIC (15, 2) NULL,
    [remarks]         VARCHAR (300)   NULL,
    [BrID]            VARCHAR (15)    NULL,
    [Group_Key]       NUMERIC (15)    NOT NULL,
    [SlNo]            NUMERIC (3)     NOT NULL,
    [Item_Code]       VARCHAR (15)    NOT NULL,
    [ItemDescription] VARCHAR (50)    NULL,
    [Batch]           VARCHAR (15)    NULL,
    [Expiry]          VARCHAR (10)    NULL,
    [Qty]             NUMERIC (12, 3) NULL,
    [Bonus]           NUMERIC (12, 3) NULL,
    [Unit]            VARCHAR (10)    NULL,
    [Pack1]           NUMERIC (8)     NULL,
    [Pack2]           NUMERIC (8)     NULL,
    [Pack3]           NUMERIC (8)     NULL,
    [Price]           NUMERIC (12, 4) NULL,
    [CostPrice]       NUMERIC (12, 2) NULL,
    [SallingPrice]    NUMERIC (12, 2) NULL,
    [CostInUnit]      NUMERIC (12, 2) NULL,
    [ItemAmount]      NUMERIC (12, 2) NULL,
    [UserID]          VARCHAR (15)    DEFAULT ('Admin') NULL,
    [Create_Date]     DATETIME        DEFAULT (getdate()) NULL,
    [MachineID]       VARCHAR (20)    DEFAULT (host_name()) NULL
);

