CREATE TABLE [dbo].[UCAFPrint] (
    [Trans_Key]         BIGINT          NOT NULL,
    [TransDateEnglish]  VARCHAR (20)    NULL,
    [PatientType]       CHAR (1)        NULL,
    [BillType]          CHAR (1)        NULL,
    [Series]            VARCHAR (2)     NOT NULL,
    [RegistrationNo]    NUMERIC (10)    NOT NULL,
    [TokenNo]           NUMERIC (10)    NULL,
    [InsuranceID]       VARCHAR (10)    NULL,
    [InsurnaceGroupID]  VARCHAR (10)    NULL,
    [DoctorID]          VARCHAR (10)    NULL,
    [bp]                VARCHAR (10)    NULL,
    [Breathing]         VARCHAR (10)    NULL,
    [Temprature]        VARCHAR (10)    NULL,
    [PulseRate]         VARCHAR (10)    NULL,
    [Respiratory]       VARCHAR (10)    NULL,
    [VisitNo]           NUMERIC (10)    NULL,
    [VisitType]         VARCHAR (15)    NULL,
    [DurationofIllness] NUMERIC (5)     NULL,
    [AdmissionType]     CHAR (1)        DEFAULT ('0') NULL,
    [FixedAlergies]     CHAR (1)        DEFAULT ('0') NULL,
    [DrugAlergies]      CHAR (1)        DEFAULT ('0') NULL,
    [OtherAlergies]     CHAR (1)        DEFAULT ('0') NULL,
    [ChiefComplaint]    NTEXT           NULL,
    [NoteAlergies]      NTEXT           NULL,
    [SignificantSign]   NTEXT           NULL,
    [OtherCondition]    NTEXT           NULL,
    [Diagnosis]         NTEXT           NULL,
    [DX_Code1]          VARCHAR (15)    NULL,
    [DX_Code2]          VARCHAR (15)    NULL,
    [DX_Code3]          VARCHAR (15)    NULL,
    [DX_Code4]          VARCHAR (15)    NULL,
    [MedicationNote]    NTEXT           NULL,
    [IllnessType]       NUMERIC (5)     DEFAULT (0) NULL,
    [Lmp]               NVARCHAR (100)  NULL,
    [Cmf]               CHAR (1)        DEFAULT ('N') NULL,
    [CmfNote]           NTEXT           NULL,
    [Los]               NUMERIC (5)     DEFAULT (1) NULL,
    [Eda]               VARCHAR (10)    NULL,
    [RowNBR]            INT             NULL,
    [Item_Code]         VARCHAR (15)    NULL,
    [Qty]               NUMERIC (5)     NULL,
    [Unit]              CHAR (1)        NULL,
    [Price]             NUMERIC (10, 2) NULL,
    [DiscountPer]       NUMERIC (10, 2) NULL,
    [DiscountAmt]       NUMERIC (10, 2) NULL,
    [BillAmt]           NUMERIC (10, 2) NULL,
    [ItemNameEnglish]   VARCHAR (75)    NULL,
    [ItemnameArabic]    NVARCHAR (50)   NULL,
    [Duration]          NVARCHAR (20)   NULL,
    [Userid]            VARCHAR (15)    NULL,
    [Create_Date]       VARCHAR (20)    NULL,
    [MachineID]         VARCHAR (20)    NULL
);

