CREATE TABLE [dbo].[usersbank] (
    [BranchID]             VARCHAR (15)   NOT NULL,
    [UserID]               VARCHAR (15)   NOT NULL,
    [UserNameEnglish]      VARCHAR (50)   NOT NULL,
    [UserNameArabic]       NVARCHAR (50)  NULL,
    [passwordID]           NVARCHAR (300) NULL,
    [LanguageUsed]         CHAR (15)      NULL,
    [UserGroup]            VARCHAR (15)   NULL,
    [DepartmentID]         VARCHAR (15)   NULL,
    [Locked]               CHAR (1)       NULL,
    [NoOfInstance]         CHAR (1)       NULL,
    [CounterID]            VARCHAR (20)   NULL,
    [StrictCounterId]      CHAR (1)       NULL,
    [PhotoLocation]        VARCHAR (50)   NULL,
    [workstationID]        VARCHAR (30)   NULL,
    [no_of_login]          NUMERIC (5)    NULL,
    [msg_status]           CHAR (1)       NULL,
    [msg_from]             VARCHAR (5)    NULL,
    [Courtesy]             VARCHAR (5)    NULL,
    [AccessModule1]        INT            NULL,
    [AccessModule2]        INT            NULL,
    [AccessModule3]        INT            NULL,
    [AccessModule4]        INT            NULL,
    [AccessModule5]        INT            NULL,
    [AccessModule6]        INT            NULL,
    [AccessModule7]        INT            NULL,
    [AccessModule8]        INT            NULL,
    [AccessModule9]        INT            NULL,
    [AccessModule10]       INT            NULL,
    [AccessModule11]       INT            NULL,
    [AccessModule12]       INT            NULL,
    [RemoteAccessSettings] VARCHAR (50)   NULL,
    [NewPassword]          VARCHAR (500)  NULL,
    [Create_User]          VARCHAR (15)   NULL,
    [Create_date]          DATETIME       NULL,
    [machineid]            VARCHAR (20)   NULL,
    [Primary_Key]          INT            NULL,
    [DisplayLoginUsers]    CHAR (1)       NULL,
    [LoginNow]             CHAR (1)       NULL,
    [DisplayTotalSale]     CHAR (1)       NULL
);

