<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Wpf\AATM.Contracts\AATM.Contracts.csproj" />
    <ProjectReference Include="..\Configuration\AATM.CORE.Configuration\AATM.Core.Configuration.csproj" />
  </ItemGroup>

</Project>
